### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by pleckey** [floragunncom/search-guard#1]
Thank you so much for this - we were just about to embark on doing this ourselves when I stumbled across this repo.  If you need any help (even testing, documentation, etc.) then please feel free to contact me - my team and I will be happy to support your efforts.

:+1:

**Comment by floragunncom** [comment]
@pleckey any help (especially writing unit tests to increase test coverage, documentation and general feedback) is very welcome. Primary goal for the next month is to get the code more stable. New features (like SAML) are also on the roadmap, but a little bit later.
