### ISSUE TITLE
The complete code is Open Source -Binary Redistribution 

### ISSUE THREAD

**Issue by hirik** [floragunncom/search-guard#1]
Hi,

Is it possible to redistribute "SearchGuard" binaries with our product? if yes, Is there any limitation for that?. Also, I found that In maven, Binary license is mentioned as apache 2.0 license "https://mvnrepository.com/artifact/com.floragunn/search-guard-7/7.4.0-37.1.0-api"

**Comment by floragunn** [comment]
Please ask this kind of question here: https://search-guard.com/contacts/
