### ISSUE TITLE
How to configure sg_roles.yml in SG 2

### ISSUE THREAD

**Issue by woodkan** [floragunncom/search-guard#102]
Have any guide on configuring sg_roles.yml? There are 4 level for configuring the permssions for indices, who know what the 3nd level stand for?
******************************
sg_role_name: 
   indices: 
      '2nd level' :                       # indices name
            '3nd level':                 # what does it mean?
                 - 4th level             # permissions

**Comment by floragunncom** [comment]
types

**Comment by woodkan** [comment]
Thanks. I see.
