### ISSUE TITLE
Filter on field type

### ISSUE THREAD

**Issue by rbw0** [floragunncom/search-guard#107]
Hello,

Firstly - thanks for a great project.

We're currently running a single node ES cluster (ELK stack). It's a pretty much default setup with all logs ending up in the same index. Indices are created once per day (i.e. logstash-2016.03.16).

All events are created with a `type` field, which makes it easy creating and saving searches in the Kibana GUI (which interfaces with ES for querying).

Is it possible with Search Guard to limit what a user can see based on a certain field value (I.e. allow a user to see the record if field `type` equals a certain value)? Is this what flsfilter is? If possible, what would such an ACL configuration look like?

Thanks!

Robert

**Comment by floragunncom** [comment]
Its possible with Search Guard 2, with the upcoming document and field level security (DLS/FLS), see https://github.com/floragunncom/search-guard/wiki

If you need filter for only for ``_type``  you can achieve this also without DLS/FLS
