### ISSUE TITLE
Blacklist some of the fields.

### ISSUE THREAD

**Issue by vinayakakr** [floragunncom/search-guard#109]
Hello,

Is there any way we can hide some fields  for specific roles in SG 2.2? .

Here is the scenario, we have several fields, out of these there are few fields we don't want to display it to every one. is there any way to  set rule on those specific fields in search Guard 2.2?

**Comment by floragunncom** [comment]
Will be possible with Field level security: https://github.com/floragunncom/search-guard/wiki
(Not yet released but will come this month)
