### ISSUE TITLE
Cannot add or remove filter on index

### ISSUE THREAD

**Issue by julienbeclin** [floragunncom/search-guard#11]
Hello,

I have installed ES 1.5.2 on my Ubuntu server and have configured my elasticsearch.yml with ; network.host : localhost so that you can only query from localhost.
i have done the pre-installation step for searchguard:

curl -XPUT 'http://localhost:9200/searchguard/ac/ac' -d '{
    "acl": [
    {    
        "__Comment__": "By default no filters are executed and no filters are by-passed. In such a case an exception is thrown and access will be denied.",
        "filters_bypass": [],
        "filters_execute": []
     },
     {
           "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
           "roles": [
               "admin"
           ],
           "filters_bypass": ["*"],
           "filters_execute": []
     }
     ]
}'

And even added another one : 

"__Comment__": "For user admin all filters are bypassed (so none will be executed). This means unrestricted access.",
"users": ["admin"],
"filters_bypass": ["*"],
      "filters_execute": []
    }

I then installed searchguard plugin using:  bin/plugin -i com.floragunn/search-guard/0.5 and went back to elasticsearch.yml to enable my logins, passwords, roles, etc...

Issue: I cannot do any curl query to add a rule on a filter.
For example, if I try to do the first step of the example config :

 curl -u admin-XPUT 'http://localhost:9200/searchguard/ac/ac?pretty' -d '
{"acl": [
    {
           "__Comment__": "Default is to execute all filters",
           "filters_bypass": [],
           "filters_execute": ["*"]
    }
]}'

and enter my password :    Enter host password for user 'admin':

I get the following response : 

 {
  "error" : "RuntimeException[java.lang.RuntimeException: Only allowed from localhost (loopback)]; nested: RuntimeException[Only allowed from localhost (loopback)]; ",
  "status" : 500
}

Any idea what the issue is ? Thanks !

**Comment by cpesoft** [comment]
Hi,

try setting `searchguard.allow_all_from_loopback: true` in `elasticsearch.yml`.
That should do the trick. (It did at least for me)

**Comment by julienbeclin** [comment]
Ooops I had not seen this line !
Thanks for the answer it works now. But I don't really see how the whole concept works...

If I want to add a new rule, do I have to chose a different _id ? Because when I put 
curl -XPUT 'http://localhost:9200/searchguard/ac/ac?pretty' -d '
it does not create the rule (because I can't add to the mapping), but overwrites it.

Should I add my rule with a different _id (ac2 for example) ? Or should I overwrite the  whole mapping with the old+new one ?

Thanks

**Comment by floragunncom** [comment]
we are aware of this issue, will change in the next version and docs will be updated as well

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
