### ISSUE TITLE
[Request] Information about roles

### ISSUE THREAD

**Issue by carioka88** [floragunncom/search-guard#110]
Hello, 
I don't know if for other people is the same, but I find pretty confuse all the documentation about the roles and the ACL rules...how really it works.
I am following all the setup with the certificates that are provided.
When restarting elasticsearch it does not let me execute again sgadmin.sh, giving me an error about admin/get does not exist.
If I don't restart ES, I can check the searchguard index with the user kirk, but after restarting ES, I cannot.. Is it normal? How can I check it? Do we need to create an admin user?
I tried to create it, and add it in all possible roles...but it does not work for me...
All this configuration it is only needed in the master node?
There are 2 elasticsearch.yml files? one for ES itself and another for the SG2 configuration(inside sgconfig)??
Would it be possible to have more information about how to do all this configuration?
Thank you!

**Comment by floragunncom** [comment]
docs will come, stay tuned.

For know we recommend to look into the Vagrantfile for that https://github.com/floragunncom/search-guard/blob/2.2/Vagrantfile

**Comment by xploit42** [comment]
@carioka88 you need only one elasticsearch.yml. elasticsearch.yml.example in sgconfig just give you lines to add at the end of your /etc/elasticsearch/elasticsearch.yml file.

**Comment by carioka88** [comment]
I see.
Thanks!
