### ISSUE TITLE
Can not update searchguard settings in SG 2.2.1 ALPHA 3

### ISSUE THREAD

**Issue by woodkan** [floragunncom/search-guard#112]
I am testing SG 2.2.1 ALPHA 3 with ES 2.2.1. As I have only 3 ES nodes, so I want to change the searchguard' replicas to 2, but it failed. 

<pre>
[root@HP-MGR-VSANTEST150 tmp]# curl -u admin:admin -XGET http://10.30.29.150:9200/searchguard/_settings?pretty                                  {
  "searchguard" : {
    "settings" : {
      "index" : {
        "creation_date" : "1459330684229",
        "number_of_shards" : "1",
        "number_of_replicas" : "3",
        "uuid" : "F_YsVliURii1WnRn_NxmfQ",
        "version" : {
          "created" : "2020199"
        }
      }
    }
  }
}
[root@HP-MGR-VSANTEST150 tmp]# curl -u admin:admin -XPUT http://10.30.29.150:9200/searchguard/_settings?pretty -d '{"index": { "number_of_replicas": 2 }}'
{
  "error" : {
    "root_cause" : [ {
      "type" : "security_exception",
      "reason" : "no permissions for indices:admin/settings/update"
    } ],
    "type" : "security_exception",
    "reason" : "no permissions for indices:admin/settings/update"
  },
  "status" : 403
}
</pre>

<pre>
below is the previliges for admin in sg_roles.yml
======================================
sg_admin:
  cluster:
    - CLUSTER_ALL
  indices:
    '*':
      '*':
        - ALL
=====================================
</pre>

**Comment by floragunncom** [comment]
Maybe this is related to https://github.com/floragunncom/search-guard/issues/108

Can you pls. also format future post with &lt;pre&gt; tags, otherwise its hard to read. I've done this for your above post. Regarding the issue pls. share also the rest of your configuration so that we can see if the user has the <pre>sg_admin</pre> role

**Comment by woodkan** [comment]
```
in sg_internal_users.yml 
===================================================================
admin:
  hash: $2a$12$Jc.I.9D..tY/P8ED8hx48edt3mtBm/4pMxh24YDNUDHqYIZG4b1HO
  roles:
    - admin
===================================================================

in  sg_roles_mapping.yml 
====================================================================
sg_admin:
  users:
    - admin
=======================================================================

no more configuration for admin
```

**Comment by woodkan** [comment]
Today, I tried to upload one templates to ES, but failed with below errors:
```
[root@tmp-centos7 template]# curl -XPUT 'http://192.168.7.115:9200/_template/cfbill?pretty' -d @/etc/logstash/template/cfbill.template.json -u admin
Enter host password for user 'admin':
{
  "error" : {
    "root_cause" : [ {
      "type" : "security_exception",
      "reason" : "no permissions for indices:admin/template/put"
    } ],
    "type" : "security_exception",
    "reason" : "no permissions for indices:admin/template/put"
  },
  "status" : 403
}
````
Even if I added indices rights for admin in sg_roles.yml, it was the same 
```
sg_admin:
  cluster:
    - CLUSTER_ALL
    - indices:admin/template/get
    - indices:admin/template/put
    - indices:*
  indices:
    '*':
      '*':
        - ALL
```

**Comment by floragunncom** [comment]
seem like a dup of #108

**Comment by floragunncom** [comment]
issue still valid with Search Guard 2 Beta 1? https://github.com/floragunncom/search-guard

**Comment by floragunncom** [comment]
```"no permissions for indices:admin/settings/update"``` is intentional because you can not simply change the settings of the searchguard index (cause its a special index and there specially protected).

To do so you have to use a command like 
```
curl -Ss \
--insecure \
-E ch.pem \
--key kirk.key.pem \
--tlsv1.2 \
-XPUT http://10.30.29.150:9200/searchguard/_settings?pretty -d '{"index": { "number_of_replicas": 2 }}'
```
where kirk.key.pem and ch.pem are the key/certificate for the admin user which is configured in elasticsearch.yml
```
searchguard.authcz.admin_dn:
  - "CN=kirk,OU=client,O=client,l=tEst, C=De"
```

```"no permissions for indices:admin/template/put"```is fixed with https://github.com/floragunncom/search-guard/commit/53527f88ab925ad33a2668d9e1dafed14fcb35cc
