### ISSUE TITLE
Config hot reloading not working

### ISSUE THREAD

**Issue by paulheijman** [floragunncom/search-guard#113]
Hi,

I have SG2 2.2.1.0-alpha3 working on a 3 node cluster (ES 2.2.1).
The problem I have is that the 'Config hot reloading' is not working:

```shell
# before changing config (correct information)

pheadmin@es:~/Dev/Elastic/lab-ssl/elasticsearch $ curl -sk "https://es-01.cm.local:9200/_searchguard/authinfo" -u pheadmin:secret |json_pp
{
   "user" : "User [name=pheadmin, roles=[cmadmin]]",
   "peer_certificates" : "0",
   "principal" : null,
   "remote_address" : "127.0.0.1:54744",
   "sg_roles" : [
      "sg_public",
      "sg_admin"
   ]
}

# add starfleet role in sg_internal_users.yml
# run sgadmin.sh (no errors)

pheadmin@es:~/Dev/Elastic/lab-ssl/elasticsearch $ curl -sk "https://es-01.cm.local:9200/_searchguard/authinfo" -u pheadmin:secret |json_pp
{
   "sg_roles" : [
      "sg_public",
      "sg_admin"
   ],
   "remote_address" : "127.0.0.1:54839",
   "peer_certificates" : "0",
   "principal" : null,
   "user" : "User [name=pheadmin, roles=[cmadmin]]"
}

# missing role starfleet
# restart node es-01

pheadmin@es:~/Dev/Elastic/lab-ssl/elasticsearch $ curl -sk "https://es-01.cm.local:9200/_searchguard/authinfo" -u pheadmin:secret |json_pp
{
   "sg_roles" : [
      "sg_public",
      "sg_role_starfleet_library",
      "sg_role_starfleet",
      "sg_admin"
   ],
   "user" : "User [name=pheadmin, roles=[starfleet, cmadmin]]",
   "principal" : null,
   "peer_certificates" : "0",
   "remote_address" : "127.0.0.1:60921"
}

# now starfleet role is showing
# try different node (es-02)

pheadmin@es:~/Dev/Elastic/lab-ssl/elasticsearch $ curl -sk "https://es-02.cm.local:9201/_searchguard/authinfo" -u pheadmin:secret |json_pp
{
   "peer_certificates" : "0",
   "user" : "User [name=pheadmin, roles=[cmadmin]]",
   "principal" : null,
   "remote_address" : "127.0.0.1:60958",
   "sg_roles" : [
      "sg_public",
      "sg_admin"
   ]
}

# missing role starfleet
```

Is there some caching flush or reload command?

Thanks in advance!

**Comment by floragunncom** [comment]
Normally you do not need a manual flush/reload. But spreading the new config within the cluster happens asynchronously you maybe have to wait a few seconds. How long did you wait after running sgadmin.sh?

**Comment by paulheijman** [comment]
A few minutes on the first host. Up to half an hour on another host...

**Comment by floragunncom** [comment]
ok, will investigate this

**Comment by paulheijman** [comment]
Thanks!

**Comment by floragunncom** [comment]
can you post logfiles on trace level (or send them by mail)? at least in unittests i can not reproduce it.

**Comment by floragunncom** [comment]
i also can not reproduce it in the vagrant environment, see  https://gist.github.com/floragunncom/dd055afc299c8f5f30ddb0dbfc6c9836

To test yourself:
<pre>
clone and checkout https://github.com/floragunncom/search-guard/tree/issue113
vagrant up
</pre>

**Comment by paulheijman** [comment]
Here is the log file from one node:

At [2016-03-31 14:27:45,648] I did a 'https://es-01.clubmessage.local:9200/_searchguard/authinfo'
I then added a new group to my user in sg_internal_users.yml
At around [2016-03-31 14:28:41,910] I did the sgadmin to upload the config
At [2016-03-31 14:29:16,677] I did another 'https://es-01.clubmessage.local:9200/_searchguard/authinfo'

It looks like ‘com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction’ is run only once at startup...

**Comment by paulheijman** [comment]
The Vagrant environment is working fine. I think it was something about cluster health which prevented the update.
Thank you for your help!
