### ISSUE TITLE
search-guard 2 lead to kibana settings page blank since _source

### ISSUE THREAD

**Issue by liebazi7** [floragunncom/search-guard#115]
When i installed search guard 2 in ES 2.2, configure kibana.yml with user, pass and ca, the setting page can't load normal via http://ip:5601. I started kibana with verbose option, found there is a 404 response from GET /elasticsearch/.kibana/_mapping/*/field/_source=_'@timestamp' request.(I think the the long value in '' is timestamp)
Next, I request https://elasticip:9200/.kibana/_mapping/*/field/_source, it returns {} as 404 status code.
https://elasticip:9200/.kibana/_mapping/* returns config type of .kibana 
But after remove search-guard-2 plugin, it would be ok.
Search Guard 2 would disable _source feature ? But when i updated mapping of config type of .kibana with "_source": {"enable": true}, it also didn't work.
I tried version 2.2.0 and 2.2.1 of search guard, the problem occurred both.
I've no idea now. Any body can help me? Thanks:)

**Comment by liebazi7** [comment]
I'm sure it's a privilege problem now although the debug log not record any privilege exception. When I set the user that access to kibana( to elasticsearch) mapping role with privilege: indices: - ALL. It works. Currently, it's not a bad solution. But I don't know which is the key privileges as decision point.  
    I think it's search guard inner privileges transform to cause no exception log. 
    Maybe some one can read it's source code to confirm it.

**Comment by floragunncom** [comment]
can you post (or mail) the log anyhow?

**Comment by floragunncom** [comment]
issue still valid with Search Guard 2 Beta 1? https://github.com/floragunncom/search-guard

**Comment by aya-soft** [comment]
Yes, issue is still here

**Comment by aya-soft** [comment]
Request GET /.kibana/_mapping/*/field/_source returns empty object {}
instead of this right object:

{
   ".kibana": {
      "mappings": {
         "index-pattern": {
            "_source": {
               "full_name": "_source",
               "mapping": {}
            }
         },
         "visualization": {
            "_source": {
               "full_name": "_source",
               "mapping": {}
            }
         },
         "search": {
            "_source": {
               "full_name": "_source",
               "mapping": {}
            }
         },
         "config": {
            "_source": {
               "full_name": "_source",
               "mapping": {}
            }
         },
         "dashboard": {
            "_source": {
               "full_name": "_source",
               "mapping": {}
            }
         }
      }
   }
}

**Comment by floragunncom** [comment]
Are you sure that kibana use does have the ``sg_kibana4_server``role or at least the ``indices:admin/mappings/fields/get`` permission?

If you run ES on debug level (for searchguard) you should a log like this: https://gist.github.com/floragunncom/317b79309ead63d651d6

**Comment by aya-soft** [comment]
we have this settings, more then needed, i think:
  cluster:
    - cluster:monitor/nodes/info
    - cluster:monitor/health
    - cluster:monitor/state
    - cluster:monitor/nodes/stats
  indices:
    '*':
      '*':
        - indices:monitor/stats
        - indices:admin/delete
        - indices:admin/create
        - indices:admin/get
        - indices:admin/put
        - indices:admin/exists
        - indices:admin/mapping/get
        - indices:admin/mapping/put
        - indices:admin/mappings/fields/get
        - indices:admin/mappings/fields/put
        - indices:admin/refresh
        - indices:admin/validate/query
        - indices:data/read/search
        - indices:data/read/msearch
        - indices:data/read/field_stats
        - indices:data/read/get
        - indices:data/read/mget
        - indices:data/write/delete
        - indices:data/write/index
        - indices:data/write/update
        - indices:data/read/*

**Comment by floragunncom** [comment]
I think without DEBUG logs its searching the needle in the haystack

**Comment by aya-soft** [comment]
Lines with 'requested' grabed from whole log file
[e2.txt](https://github.com/floragunncom/search-guard/files/215351/e2.txt)

**Comment by floragunncom** [comment]
would be better to grep ``PrivilegesEvaluator``

**Comment by aya-soft** [comment]
Works at the moment with this two lines in place:
. . .
        - indices:admin/mappings/fields*
        - indices:data/read/mget*
. . .

**Comment by aya-soft** [comment]
Last one for covering this permission:  indices:data/read/mget[shards]
Can anyone clarify first?
Because indices:admin/mappings/fields/get not works!

**Comment by aya-soft** [comment]
Lines with 'PrivilegesEvaluator' grabb
[e1.txt](https://github.com/floragunncom/search-guard/files/215451/e1.txt)
ed from whole log file

**Comment by floragunncom** [comment]
check with user ``kibanaro`` and password: kibanaro:
