### ISSUE TITLE
Snapshot API with Searchguard enabled is not working

### ISSUE THREAD

**Issue by XDestination** [floragunncom/search-guard#116]
When I try to create a snapshot I get the following error:
`{
  "error" : "ForbiddenException[Attempt from null to _all indices for cluster:admin/snapshot/create and User [name=USERNAME, roles=[]]]",
  "status" : 403
}`

The ACL for the user USERNAME looks like this:
`{
      "users": [
        "USERNAME"
      ],
      "filters_bypass": [
        "*"
      ],
      "filters_execute": []
    }`

Any ideas on how to fix this?

**Comment by XDestination** [comment]
I'm running ES in version 1.7.2 and the searchguard plugin in version 1.7.3.0

**Comment by floragunncom** [comment]
Will not fix this for Search Guard 1 but for Search Guard 2.

**Comment by floragunncom** [comment]
Fixed for SG 2. Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!

**Comment by floragunncom** [comment]
see https://github.com/floragunncom/search-guard/wiki/Snapshot-Restore
