### ISSUE TITLE
Failed to install search-guard incompatible with ES 2.2 

### ISSUE THREAD

**Issue by kalwar** [floragunncom/search-guard#117]
-> Installing com.floragunn/search-guard-2/2.2.0...
Trying https://download.elastic.co/com.floragunn/search-guard-2/search-guard-2-2.2.0.zip ...
Trying https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-2/2.2.0/search-guard-2-2.2.0.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-2/2.2.0/search-guard-2-2.2.0.zip ...
Trying https://github.com/com.floragunn/search-guard-2/archive/2.2.0.zip ...
Trying https://github.com/com.floragunn/search-guard-2/archive/master.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

Using ES: 2.2
"version" : {
    "number" : "2.2.0"
 }

**Comment by floragunncom** [comment]
We are currently in beta status, there is no final release yet. The most recent beta is for elasticsearch 2.3.1 only

<pre>
sudo bin/plugin install com.floragunn/search-guard-ssl/2.3.1.8.1
sudo bin/plugin install com.floragunn/search-guard-2/2.3.1.0-beta1
</pre>
