### ISSUE TITLE
Cannot connect to .kibana when searchguard is enabled and searchguard.allow_all_from_loopback: false

### ISSUE THREAD

**Issue by julienbeclin** [floragunncom/search-guard#12]
Hello !

I am using using Search Guard for Elasticsearch and Kibana on my Ubuntu Server. Currenty, I access Kibana from an external web browser using credentials, and use Nginx as a reverse proxy to acces Elasticsearch in local ( ~/config/kibana.yml, I've put  host:"localhost").
This conf was working fine, and since I've installed SearchGuard plugin, I cannot access Kibana using the credentials that I wrote in elasticsearch.yml (I've followed the Pre-Installation steps).
However I can return results for ".kibana" index using "_search" API for admin users, which means that searchguard works well !
When I disable SearchGuard, everything works fine.

Error on Nginx server : 

Courier Fetch: Cannot read property 'timed_out' of undefined
TypeError: Cannot read property 'timed_out' of undefined
    at http://"ESserverIPaddress"/index.js?_b=6004:42972:17
    at Function.Promise.try (http://"ESserverIPaddress"/index.js?_b=6004:46233:26)
    at http://"ESserverIPaddress"/index.js?_b=6004:46211:27
    at Array.map (native)
    at Function.Promise.map (http://"ESserverIPaddress"/index.js?_b=6004:46210:30)
    at callResponseHandlers (http://"ESserverIPaddress"/index.js?_b=6004:42965:22)
    at http://"ESserverIPaddress"/index.js?_b=6004:43083:16
    at wrappedCallback (http://"ESserverIPaddress"/index.js?_b=6004:20888:81)
    at wrappedCallback (http://"ESserverIPaddress"/index.js?_b=6004:20888:81)
    at http://"ESserverIPaddress"/index.js?_b=6004:20974:26

Error on localhost web-browser : 

Courier Fetch: resp is undefined
TypeError: resp is undefined
callResponseHandlers/<@http://localhost:5601/index.js?_b=6004:42972:1
Promise.try@http://localhost:5601/index.js?_b=6004:46233:23
Promise.map/<@http://localhost:5601/index.js?_b=6004:46211:16
Promise.map@http://localhost:5601/index.js?_b=6004:46210:26
callResponseHandlers@http://localhost:5601/index.js?_b=6004:42965:1
fetchWithStrategy/<@http://localhost:5601/index.js?_b=6004:43083:16
qFactory/defer/deferred.promise.then/wrappedCallback@http://localhost:5601/index.js?_b=6004:20888:31
qFactory/defer/deferred.promise.then/wrappedCallback@http://localhost:5601/index.js?_b=6004:20888:31
qFactory/ref/<.then/<@http://localhost:5601/index.js?_b=6004:20974:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:5601/index.js?_b=6004:22017:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:5601/index.js?_b=6004:21829:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:5601/index.js?_b=6004:22121:13
done@http://localhost:5601/index.js?_b=6004:17656:34
completeRequest@http://localhost:5601/index.js?_b=6004:17870:7
createHttpBackend/</xhr.onreadystatechange@http://localhost:5601/index.js?_b=6004:17809:1

Error when I run kibana locally : 

{"@timestamp":"2015-06-22T15:31:50.437Z","level":"error","message":"Authentication Exception","node_env":"production","error":{"message":"Authentication Exception","name":"Error","stack":"Error: Authentication Exception\n  at respond (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:235:15)\n  at checkRespForFailure (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:203:7)\n  at HttpConnector.<anonymous> (/opt/kibana/src/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)\n  at IncomingMessage.bound (/opt/kibana/src/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickCallback (node.js:442:13)\n"}}

Thanks for helping !

**Comment by julienbeclin** [comment]
Turned out I my configuration was wrong, but I don't really know why ! Could we have some more example config please ?

I had this error log in my elasticsearch.log : 

[2015-06-23 11:00:28,709][INFO ][com.floragunn.searchguard.rest.DefaultRestFilter] Authenticated user is User [name=username, roles=[admin]]
[2015-06-23 11:00:28,712][WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] Cannot determine types for indices:admin/exists (class org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequest) due to type[s]() method not found
[2015-06-23 11:00:28,718][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to com.floragunn.searchguard.tokeneval.MalformedConfigurationException: More than one default configuration found for action indices:admin/exists
com.floragunn.searchguard.tokeneval.MalformedConfigurationException: More than one default configuration found

Here is my previous conf : 

curl -XPUT 'http://localhost:9200/searchguard/ac/ac' -d '
{
	"acl": [
		{
		"__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
		"filters_bypass": [],
		"filters_execute": []
		},
		
		{
		"__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
		"roles": ["admin"],
		"filters_bypass": ["*"],
		"filters_execute": []
		},
		
		{
		  "__Comment__": "Default is to execute all filters",
		  "filters_bypass": [],
		  "filters_execute": ["*"]
		},
		
		{
		  "__Comment__": "Any authenticated user can do anything on the '.kibana' index - no filter will be executed",
		  "indices": [".kibana"],
		  "filters_bypass": ["*"],
		  "filters_execute": []
		}
	]
}'

To make it work I put the default conf you gave in the Pre-installation paragraph.

**Comment by floragunncom** [comment]
can you pls. post your config files and ac rules?

**Comment by julienbeclin** [comment]
Hello

Here is my searchguard conf : 

# Enable or disable the complete Searchguard plugin functionality
searchguard.enabled: true

# Path where to write/read the searchguard master key file
searchguard.key_path: /etc/searchguard/

# When using DLS or FLS and a get or mget is performed then rewrite it as search request
searchguard.rewrite_get_as_search: true

#############################################################################################
# Authentication backend                                                                    #
#                                                                                           #
#############################################################################################
# Validates the username and credentials
searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend

#############################################################################################
# Authorization backend (authorizer)                                                        #
#                                                                                           #
#############################################################################################
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator

#############################################################################################
# HTTP authentication method                                                                #
#                                                                                           #
#############################################################################################
# Define HTTP authentication method. In future we will here have more like NTLM, SPNEGO/Kerberos and Digest.
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator

# Settings based authentication (define users and password directly here in the settings. Note: this is per node)
searchguard.authentication.settingsdb.user.admin: passwordadmin
searchguard.authentication.settingsdb.user.user1: passworduser1

# Settings based authorization (define users and their roles directly here in the settings. Note: this is per node)
searchguard.authentication.authorization.settingsdb.roles.admin: ["admin"]

# Configure the actionrequestfilter to allow or forbid action 
searchguard.actionrequestfilter.names: ["readonly"]
searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*", "indices:admin*", "indices:data/write*"]


My rules are the default ones : 

{
"acl": [
{
"__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
"filters_bypass": [],
"filters_execute": []
},

{
"__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
"roles": ["admin"],
"filters_bypass": ["*"],
"filters_execute": []
}]}
    } ]
  }

What is weird is that this config is working on another VM with same parameters, but this bug occurs in the VM only when searchguard is enabled. Strange

**Comment by floragunncom** [comment]
<code>searchguard.dlsfilter.names: ["dashboard","index-pattern"]</code> defines a filter "index-pattern"
<code>searchguard.dlsfilter.index_pattern: ...</code> "index_pattern" filter is not defined
index_pattern vs. index-pattern ??

**Comment by julienbeclin** [comment]
Yeah must be it here, I try to define a dls filter with the wrong name...
But I don't get all the error messages

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
