### ISSUE TITLE
Search Guard 2 not allow REINDEX

### ISSUE THREAD

**Issue by aya-soft** [floragunncom/search-guard#122]
We have this permission list:

sg_superadmin:
  cluster:
    - cluster*
    - indices*
    - indices:data/write/reindex
  indices:
    '*':
      '*':
        - indices*
        - indices:data/write/reindex

BUT this request not works:

POST /_reindex
{
   "source": {
      "index": "test"
   },
   "dest": {
      "index": "test_v2"
   }
}

Error message: no permission for indices:data/write/reindex

**Comment by floragunncom** [comment]
pls format and indent the message above. To find out whats probably going wrong pls. enable debug logging and perform an reindex request an post the logs. They should look like https://gist.github.com/floragunncom/317b79309ead63d651d6

For which SG version do you get this behaviour (if not beta1 then pls try this)

**Comment by floragunncom** [comment]
could not reproduce, for me it works

**Comment by floragunncom** [comment]
no feedback.
pls check with the upcoming beta2 version. If the issue still occurs pls reopen or file a new one
