### ISSUE TITLE
ClassCastException when running sgadmin.sh script

### ISSUE THREAD

**Issue by mkhelif** [floragunncom/search-guard#124]
Hello,

I have been trying to setup SG v2.3.1.0-beta1.
When I run sgadmin.sh script, I receive the following error:
`java.lang.ClassCastException: [B cannot be cast to java.lang.String`
`        at com.floragunn.searchguard.transport.SearchGuardTransportService.addAdditionalContextValues(SearchGuardTransportService.java:143)`

This seems to happen when using DER encoded name (value is stored as byte array).

Cheers,
Marwan

**Comment by floragunncom** [comment]
good catch, thx.

Can you describe how you generated the certificate causing this exception?

**Comment by mkhelif** [comment]
We have a root CA (certified by third party CA) and an intermediate CA (certified by the root CA).
The certificate is generated by the intermediate CA, then I imported the full certificate chain in P12 keystore, then converted it to JKS keystore.

It seems the problem occurs when I import the full chain (-chain while openssl pkc12). If I don't import the full chain, the client (sgadmin or any other Java tool) complain that it cannot validate the full certificate chain (which makes sense).

But regarding the certificates themselves, I couldn't find anything specific.

Hope it helps.

**Comment by floragunncom** [comment]
this is fixed, pls check with the upcoming beta2 version. If the issue still occurs pls reopen or file a new one

**Comment by mkhelif** [comment]
Problem is fixed in beta2.
Thank you!
