### ISSUE TITLE
Kibana & SG

### ISSUE THREAD

**Issue by carioka88** [floragunncom/search-guard#125]
Hello!
After installing SG2, I am trying to set up Kibana. But I am having some troubles.
Right now I am using the certificates that you provide.
My configuration is almost the same that you provide, but with less users..
For Kibana I have as in your demo: sg_kibana4 and sg_kibana4_server, but I can't connect to ES, receiving this error:
 `plugin:elasticsearch 	Unable to connect to Elasticsearch at https://localhost:9200. 
`
`"message":"Unable to revive connection: https://localhost:9200/"
`
I have include in the kibana.yml:
   elasticsearch.url: "https://localhost:9200"
   elasticsearch.ssl.ca: "/ca/signing-ca.pem"

But I know I am missing something in the configuration...
Do I need to create a kibana user too?

Thanks in advance!

**Comment by floragunncom** [comment]
sounds more like a genal connection problem: can you open ``https://localhost:9200/`` in a browser or via  ``curl -k  https://localhost:9200`` ?

**Comment by carioka88** [comment]
I can get the info via
`curl -Ss --insecure https://localhost:9200/_cluster/health?pretty -u name:password`
and also from the browser I can access to `https://localhost:9200/_plugin/head/`

**Comment by floragunncom** [comment]
in kibana.yml make sure that you also set
```
elasticsearch.url: "https://localhost:9200"
elasticsearch.username: "kibanaserver"
elasticsearch.password: "******"
```

Seems that you missed creating a user for kibana (needs full access to .kibana)

If this still wont work consider adding
```
#elasticsearch.ssl.ca: "/ca/signing-ca.pem"
elasticsearch.ssl.verify: false
```

**Comment by carioka88** [comment]
It works making `elasticsearch.ssl.verify: false` and adding the user!
Thank you!

**Comment by floragunncom** [comment]
``elasticsearch.ssl.verify: false`` is just a workaround.

Can you try ``elasticsearch.ssl.ca: "/ca/root-ca.pem"``
If this also cause troubles try ``elasticsearch.ssl.ca: "/ca/chain-ca.pem"``

**Comment by carioka88** [comment]
With `elasticsearch.ssl.ca: "/ca/root-ca.pem"`
I get:
`{"type":"log","@timestamp":"2016-05-02T15:59:58+00:00","tags":["error","elasticsearch"],"pid":17806,"message":"Request error, retrying -- Hostname/IP doesn't match certificate's altnames: \"Host: localhost. is not in the cert's altnames: DNS:node-search.example.com, IP Address:127.0.0.1, Registered ID:1.2.3.4.5.5\"`

And with `{elasticsearch.ssl.ca: "/ca/chain-ca.pem" `
I get: 
` "type":"log","@timestamp":"2016-05-02T15:35:41+00:00","tags":["error","elasticsearch"],"pid":17389,"message":"Request error, retrying -- self signed certificate in certificate chain"}`

**Comment by floragunncom** [comment]
Thats ok and expected. So either you go with ``elasticsearch.ssl.verify: false`` (not a good choice for production systems) or with ``elasticsearch.ssl.ca: "/ca/root-ca.pem"`` and add the correct hostname to the node certificate [here](https://github.com/floragunncom/search-guard-ssl/blob/master/example-pki-scripts/gen_node_cert.sh#L29) and [here](https://github.com/floragunncom/search-guard-ssl/blob/master/example-pki-scripts/gen_node_cert.sh#L41)

**Comment by carioka88** [comment]
true!
Now the hostname is matching with the node name. I still had "example.com", and it was not matching completely with my actual node name... even if it was quite enough for the rest to work ok.
I changed it and Kibana works perfectly.
Thanks a lot!
