### ISSUE TITLE
what the roles in  sg_roles_mapping.yml and  the backendroles  in sg_internal_users.yml mean

### ISSUE THREAD

**Issue by PKFresher** [floragunncom/search-guard#126]
I'm confused  with   the roles  in sg_internal_user   it's mean indices ?

kirk:
  hash: $2a$12$xZOcnwYPYQ3zIadnlQIJ0eNhX1ngwMkTN.oMwkKxoGvDVPn4/6XtO
  #password is: kirk
  roles:
    - captains
    - starfleet

What is the role of the  backendroles in sg_roles_mapping  

sg_role_vulcans:
  backendroles:
    - vulcangov
  users:
    - kirk

did  the roles in sg_internal_user   and    the  backendroles in sg_roles_mapping    have
 any relationship?

**Comment by floragunncom** [comment]
roles in sg_internal_user are roles (not indices) the user have, for example "starfleet". These are called "backendroles" cause these are roles the user have in a specific backend (internal, ldap, etc). The roles are only related to sg_roles_mapping and not to  sg_roles

These roles are mapped to sgroles in sg_roles_mapping (you can also map directly users)

The mapped roles (=sgroles, for example sg_role_vulcans) are related to sg_roles which defines the permissions for a particular sgrole

**Comment by floragunncom** [comment]
this is not an issue, pls ask questions (which are not issues or bugs) here https://groups.google.com/forum/#!forum/search-guard

**Comment by PKFresher** [comment]
yeah, thanks for your replay. i will  map directly users.

if roles in sg_internal_user  are just used to show  user have and not authenticate ?
