### ISSUE TITLE
Enhancement: add support for Node Client

### ISSUE THREAD

**Issue by faxm0dem** [floragunncom/search-guard#128]
[SG Non-Server Node Clients](https://github.com/floragunncom/search-guard/wiki/Terminology#sg-non-server-node-client-sgnsnc) are currently unsupported.

We're using one of those in the form of a [syslog-ng destination driver](https://github.com/balabit/syslog-ng/tree/master/modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch) for two main reasons:

* Efficiency: the node client is much faster than HTTP and reasonably faster than transport because the client is more aware of the shard locations
* Security: the node client is safer w/ respect to message loss compared to transport mode (according to the [documentation](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/destination-elasticsearch-interaction.html)
* Orchestration: it's much easier to automate node client integration with other systems than transport or http clients, because they can be listed using the nodes API e.g. `GET /_cat/nodes`

For these reasons we'd like to see SG support node client.

**Comment by floragunncom** [comment]
@faxm0dem does this work for you now with the latest version?

**Comment by faxm0dem** [comment]
thanks a lot for this we didn't test yet but we definitely will ASAP!

**Comment by floragunncom** [comment]
I assume it works, if not pls. reopen or file a new issue

**Comment by faxm0dem** [comment]
I tried using sg 2.4.0.6. Unfortunately I couldn't make it work.
See [related issue on syslog-ng tracker](https://github.com/balabit/syslog-ng/issues/1221) for details.

Thanks!
