### ISSUE TITLE
Can't install with ES 2.3.3

### ISSUE THREAD

**Issue by liviudm** [floragunncom/search-guard#131]
Hi,

I'm trying to install Search Guard with Elasticsearch 2.3.3, but I get back that it's not supported. Since 2.3.3 is mostly a bug fix release, I guess search guard should work just fine with it and the same should be true for any minor release. Here's is the install log:

`$ sudo bin/plugin install com.floragunn/search-guard-ssl/2.3.2.9
-> Installing com.floragunn/search-guard-ssl/2.3.2.9...
Trying https://download.elastic.co/com.floragunn/search-guard-ssl/search-guard-ssl-2.3.2.9.zip ...
Trying https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-ssl/2.3.2.9/search-guard-ssl-2.3.2.9.zip ...
Downloading ............................................................................................DONE
Verifying https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-ssl/2.3.2.9/search-guard-ssl-2.3.2.9.zip checksums if available ...
Downloading .DONE
ERROR: Plugin [search-guard-ssl] is incompatible with Elasticsearch [2.3.3]. Was designed for version [2.3.2]`

`$ sudo bin/plugin install com.floragunn/search-guard-2/2.3.2.0-beta2
-> Installing com.floragunn/search-guard-2/2.3.2.0-beta2...
Trying https://download.elastic.co/com.floragunn/search-guard-2/search-guard-2-2.3.2.0-beta2.zip ...
Trying https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-2/2.3.2.0-beta2/search-guard-2-2.3.2.0-beta2.zip ...
Downloading .........DONE
Verifying https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-2/2.3.2.0-beta2/search-guard-2-2.3.2.0-beta2.zip checksums if available ...
Downloading .DONE
ERROR: Plugin [search-guard-2] is incompatible with Elasticsearch [2.3.3]. Was designed for version [2.3.2]
`

**Comment by floragunncom** [comment]
Elasticsearch plugin infrastructure require a separate plugin build per version. SG compatible with ES 2.3.3 will be released today. Pls. ask such kind of question in the google group, github issues are reserved for bugs and feature requests.

What you can try ON YOUR OWN RISK: Unzip the plugin, change plugin-descriptor.properties to match your ES version and re-zip.
