### ISSUE TITLE
Log changes made to the security configuration

### ISSUE THREAD

**Issue by floragunncom** [floragunncom/search-guard#132]
Whenever the searchguard index is updated log the changes. Can be done by registering a ConfigChangeListener which does this.

**Comment by jochenkressin** [comment]
I think this belongs more to the audit log module. While I second the feature request, I propose to move it over to the audit log module and schedule it for SG6.

**Comment by floragunncom** [comment]
this will be part of the upcoming compliance edition
https://floragunn.com/elasticsearch-compliance-preview/
