### ISSUE TITLE
What is mean of the search guard entry？

### ISSUE THREAD

**Issue by LazyerHong** [floragunncom/search-guard#140]
Who can tell me about the mean of this entry?
What is the mean about the "cn","ou", "dc" ????

searchguard.authcz.admin_dn:
  - cn=admin,ou=Test,ou=ou,dc=company,dc=com

**Comment by floragunncom** [comment]
Pls. ask such kind of questions in the google group https://groups.google.com/forum/#!forum/search-guard . Github issues are reserved for bugs and feature requests. Thanks.
