### ISSUE TITLE
Allow regex for username

### ISSUE THREAD

**Issue by djtecha** [floragunncom/search-guard#143]
It would be pretty nice if I could use a regex for username matching so I could allow a domain like *@test.com as a fallback if a stricter match is not found. Otherwise, I just allow * Maybe something like this in the internal users file:

test_user1:
  username: djtecha@test.com
  
test_catchall:
  username: '*@test.com'

**Comment by floragunncom** [comment]
Do you want to submit a PR for this?

**Comment by djtecha** [comment]
Hmm nvm, I found a work around to just use the sg_role_mapping with a regex.
