### ISSUE TITLE
SearchGuard not connecting with Elasticsearch

### ISSUE THREAD

**Issue by kavipreetha** [floragunncom/search-guard#146]
I use elasticssearch 2.3.3 
and installed following as plugin in ES
search-guard-ssl - 2.3.3.13
search-guard-2 - 2.3.3.1

1. Created jks file using search-guard-ssl and copied to elasticsearch/config path

2. elasticsearch.yml added entried related to search-guard-ssl 
searchguard.ssl.transport.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.transport.keystore_password: guidanz123
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: guidanz123
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.http.keystore_password: guidanz123
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: guidanz123

3. elasticsearch.yml added the entry of search-guard-2 plugin
searchguard.authcz.admin_dn:
  - "DC=com, DC=10.9.14.8, O=Guidanz Com Inc., OU=Guidanz Com Inc. Root CA, CN=Guidanz Com Inc. Root CA"

4. Opened another terminal and ran the following command,
plugins/search-guard-2/tools/sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -h 10.9.14.8 -p 9300 -ks plugins/search-guard-2/sgconfig/node-guidanz-keystore.jks  -kspass guidanz123 -ts plugins/search-guard-2/sgconfig/truststore.jks -tspass guidanz123  -nrhn
Got the following error,
Connect to 10.9.14.8:9300
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.9.14.8}{10.9.14.8:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transpotore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: guidanz123
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.http.keystore_password: guidanz123
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: guidanz123

searchguard.audit.type: internal_elasticsearch

Kindly suggest to proceed further.rt.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:848)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:868)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:201)

5. And in elelasticsearch got the following error,

[2016-06-24 11:56:38,625][ERROR][com.floragunn.searchguard.transport.SearchGuardTransportService] No user found in this LivenessRequest for action cluster:monitor/nodes/liveness and transport type netty. If you see this error related when you use sgadmin make sure you connect with a client (and not with a node) certificate.

Below is full configuration of my elasticsearch.yml
cluster.name: my-searchgaurd-application
network.host: 10.9.14.8
http.port: 9500
searchguard.authcz.admin_dn:
  - "DC=com, DC=10.9.14.8, O=Guidanz Com Inc., OU=Guidanz Com Inc. Root CA, CN=Guidanz Com Inc. Root CA"
searchguard.ssl.transport.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.transport.keystore_password: guidanz123
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: guidanz123
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.http.keystore_password: guidanz123
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: guidanz123
searchguard.audit.type: internal_elasticsearch

Kindly suggest to proceed further.

**Comment by floragunncom** [comment]
```plugins/search-guard-2/tools/sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -h 10.9.14.8 -p 9300 -ks plugins/search-guard-2/sgconfig/XXXXX.jks -kspass guidanz123 -ts plugins/search-guard-2/sgconfig/truststore.jks -tspass guidanz123 -nrhn```

For ```XXXXX``` use the client certificate generated with https://github.com/floragunncom/search-guard-ssl/blob/master/example-pki-scripts/gen_client_node_cert.sh and use the DN of this certificate with ```searchguard.authcz.admin_dn```

**Comment by floragunncom** [comment]
You can also have a look into our Vagrant demo for this https://github.com/floragunncom/search-guard-ssl/blob/master/Vagrantfile

**Comment by kavipreetha** [comment]
I will try Vagrant demo. But can you tell what is wrong with the above procedure??
Regarding Vagrant demo it seems to be script file. Can you tell me the steps to set it up.

**Comment by kavipreetha** [comment]
I have specified the DN as told
searchguard.authcz.admin_dn:
  - "C=DE, L=TEST, O=Test, OU=SSL, CN=node-guidanz.example.com"

**Comment by floragunncom** [comment]
DN direction is wrong, try 
<pre>"CN=node-guidanz.example.com,OU=SSL,O=Test,L=TEST,C=DE"</pre>

**Comment by floragunncom** [comment]
To use the vagrant script install [vagrant](https://www.vagrantup.com) and then type <pre>vagrant up</pre> (in the directory where the ```Vagrantfile``` is)

**Comment by kavipreetha** [comment]
I tried specifying the DN with the following format,
searchguard.authcz.admin_dn:
    - "CN=node-guidanz.example.com,OU=SSL,O=Test,L=TEST,C=DE"

Still getting the same error.
Kindly suggest me to proceed further.

**Comment by floragunncom** [comment]
Maybe you want to try the preconfigured Search Guard Bundle https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle to get it up and running

**Comment by floragunncom** [comment]
Will close this because its not an issue. Please ask questions like this here: https://groups.google.com/forum/#!forum/search-guard
