### ISSUE TITLE
Bundle in quickstart docs is unavailable

### ISSUE THREAD

**Issue by gkhasel1** [floragunncom/search-guard#149]
Hey, great plugin! The link to download the search guard bundle in this doc https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle can not be found. I get the following output:

```
Application Aa30JUUJZQ4i5UPcU5BUHz is unavailable
```

the link is https://cdn.filestackcontent.com/Hrdru8DRVO2HGvZkwOoQ.

**Comment by jochenkressin** [comment]
We moved the bundle from filestack to our own download location, this should be stable now:

http://downloads.floragunn.com/elasticsearch-4DD5ED74-7B2A-4662-8048-425634E6A694.tar.gz

I also updated the respective Wiki page:

https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle

Thanks for letting us know!
