### ISSUE TITLE
SearchGuard and Logstash Document

### ISSUE THREAD

**Issue by nguyenmv2** [floragunncom/search-guard#151]
Could you please setup a simple documentation for logstash integration ? 
I was able to setup kibana with search guard but I could not setup logstash
Thank you

**Comment by floragunncom** [comment]
We are working on that. Maybe [this example](https://github.com/floragunncom/search-guard/wiki/Configure-logstash) can help you until the documentation is finished.

**Comment by jochenkressin** [comment]
We just added the logstash configuration chapter:

https://github.com/floragunncom/search-guard-docs/blob/master/logstash.md

Please let us know if anything is missing or unclear!

**Comment by nguyenmv2** [comment]
Thank you for the documentation

**Comment by DVikas4193** [comment]
Hi ,
What I am seeing sometimes it shows  Invalid keystore format when try to run logstash ,according to the documentation.I am using 6.2.2 there exist root.pem not truststore.jks,So I gave the path of root.pem and I got the above error and I am not able to solve it. Could you please provide the troubleshooting documents for logstash as u did very nicely for tsl,ssl ,elasticsearch etc.
