### ISSUE TITLE
sgadmin.sh requires truststore and keystore to have file extention .jks to be parsed as JKS type

### ISSUE THREAD

**Issue by dopey** [floragunncom/search-guard#152]
https://github.com/floragunncom/search-guard/blob/d844f41371eead76cee4c222cf6fee488049fa2f/src/main/java/com/floragunn/searchguard/tools/SearchGuardAdmin.java#L188

The code will parse truststore and keystore inputs as JKS type only if the file extension is .jks. I could not find mention of this behavior in the documentation.

It would be great if either:
1) This behavior were documented in the usage of the script
2) It was possible to provide the storetype on the cmdline, similar to how its done in the elasticsearch.yml

**Comment by ewolinetz** [comment]
I came across this today as well. +1 to option 2

**Comment by floragunncom** [comment]
We will implement this, thanks for reporting.
