### ISSUE TITLE
support DNS server name in cert (instead of only IPs)

### ISSUE THREAD

**Issue by dopey** [floragunncom/search-guard#153]
search-guard isn't working for me unless the IP address of each node is included as a SAN in the crt file. I have DNS entries set up for all my hosts of the form elasticsearch[01-03].my-company.com and I am able to use these hostnames for zen discovery. It would be great if search-guard could respect my seed names because then I could have a SAN entry in my crt like 'DNS: *.my-company.com' and it wouldn't be necessary to regenerate the keystore/truststore pair every time a node is added to the cluster.

I don't believe that the previous versions of search-guard did hostname verification by default. It may be that I can turn this behavior off in the search-guard config options, just not sure how.

**Comment by floragunncom** [comment]
Can you pls look into the logfiles and search for a logentry (on DEBUG level) which looks like ``Hostname of peer is XXX with hostnameVerificationResovleHostName: XXX``. That would be very helpful to dig into this issue.

Seems this issue is related: https://github.com/floragunncom/search-guard-ssl/issues/22

In general you can disable hostname verification (or at least hostname resolution) with 
```
#searchguard.ssl.transport.truststore_password: changeit
# Enforce hostname verification (default: true)
searchguard.ssl.transport.enforce_hostname_verification: false
# If hostname verification is enabled specify if hostname should be resolved (default: true)
searchguard.ssl.transport.resolve_hostname: false
```

**Comment by dopey** [comment]
Grabbed some log lines from one of my hosts:

    [2016-06-29 22:27:07,096][DEBUG][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport$ClientSSLHandler] Hostname of peer is nextkibana02.es.my-company.com with hostnameVerificationResovleHostName: true
    [2016-06-29 22:27:07,097][DEBUG][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport$ClientSSLHandler] Hostname of peer is nextkibana03.es.my-company.com with hostnameVerificationResovleHostName: true
    [2016-06-29 22:27:08,051][DEBUG][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport$ClientSSLHandler] Hostname of peer is 1.1.1.3 with hostnameVerificationResovleHostName: true

These lines are all right near one another (can probably tell from the timestamps). The ipaddress `1.1.1.3` is the same as host `nextkibana03.es.my-company.com`. But my seeds are only the dns hostnames, not the ip addresses.

**Comment by floragunncom** [comment]
Are you really sure that 1.1.1.3 can be resolved to nextkibana03.es.my-company.com? From the logs it looks like 1.1.1.3 is not resolveable.

Can you share the network.* settings in elasticsearch.yml for all nodes?

**Comment by dopey** [comment]
So, I actually changed the ip address there, since I'm used to doing that when posting online. In reality its a private address and the dns does resolve.

    >$ ping nextkibana03-ops.es.my-company.com
    PING nextkibana03-ops.es.my-company.com (1.1.1.3) 56(84) bytes of data.
    64 bytes from 192.168.5.3: icmp_seq=1 ttl=64 time=0.401 ms
    64 bytes from 192.168.5.3: icmp_seq=2 ttl=64 time=0.348 ms
    64 bytes from 192.168.5.3: icmp_seq=3 ttl=64 time=0.437 ms

Here is the network section for one of my nodes:

    # ---------------------------------- Network ----------------------------------- 
    #
    # Set the bind address to a specific IP (IPv4 or IPv6):
    #
    network.host: 1.1.1.3
    #
    # Set a custom host and port for HTTP:
    #
    http.host: 127.0.0.1
    http.port: 9200
    #
    # For more information, see the documentation at:
    # <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>

So maybe I need to change the `network.host` to be the dns server name instead of the IP?

**Comment by floragunncom** [comment]
What is ``192.168.5.3``?

```
PING nextkibana03-ops.es.my-company.com (1.1.1.3) 56(84) bytes of data.
64 bytes from 192.168.5.3 <<<<---------- ??
```
Can you pls execute ``nslookup 192.168.5.3`` and ``1.1.1.3`` and post the results.

Try settings ``network.publish_host: nextkibana03-ops.es.my-company.com``, maybe this helps. But for me it looks its somehow related to hostname resolution.

**Comment by dopey** [comment]
heh, so I apologize for being confusing here. `1.1.1.3` was just my attempt to mask the ip address, which doesn't matter anyway since its a private network IP.

I'll try setting the `network.publish_host`.

**Comment by floragunncom** [comment]
does it work now?

**Comment by dopey** [comment]
So I think it does have to do with the network.host. I now have:

```
network.host: nextkibana01-ops.nextes.my-company.com
```

and my cert has: 
```
#5: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: staging-elasticsearch-server
  DNSName: *.nextes.my-company.com
  OIDName: 1.2.3.4.5.5
]```

but the error I get now is: 
```
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching nextkibana03-ops.nextes.my-company.com found.
```

So im thinking that searchguard may not support certs w/ wildcard SAN's. For the time being I will try turning off the hostname validation.

**Comment by floragunncom** [comment]
Will dig into this, thanks for reporting

**Comment by dopey** [comment]
It does work when I turn off hostname validation.

**Comment by floragunncom** [comment]
Does is also work with hostname verification turned on but hostname resolution turned off?

<pre>
searchguard.ssl.transport.enforce_hostname_verification: true
searchguard.ssl.transport.resolve_hostname: false
</pre>

**Comment by dopey** [comment]
It does not work with hostname verification turned on and resolution turned off. I get the same java security cert error. At the moment I can only get it to work by either explicitly adding each server name to the cert (w/out wildcard) or by turning off hostname verification.

**Comment by floragunncom** [comment]
@dopey @ewolinetz any news here?

**Comment by dopey** [comment]
@floragunncom no longer with that team but when I left 3 months ago we were still turning off hostname verification in order for this to work.

**Comment by floragunncom** [comment]
I did some tests with hostname verification (and resolution) turned on in combination with wildcard certificates. No problems. #157 seems to be solved too.

If you (or anyone else) still having problems with wildcard certificates and hostname verification pls. file a new issue and reference this one.
