### ISSUE TITLE
Elasticsearch can only accept one user once, because of the elasticsearch.yml settings

### ISSUE THREAD

**Issue by yangfeiran** [floragunncom/search-guard#154]
I installed the search-guard, as the instruction. Then, generate certifications for two users, one is admin, one is kirk.
After I put the two keystore.jks and one truststore.jks in the keys folder, I config the elasticsearch.yml as below:
```
 searchguard.ssl.transport.keystore_filepath: /usr/share/elasticsearch/config/keys/admin-keystore.jks
 searchguard.ssl.transport.truststore_filepath: /usr/share/elasticsearch/config/keys/truststore.jks
 security.manager.enabled: false
 searchguard.authcz.admin_dn:
   - "CN=admin, OU=client, O=client, L=Test, C=DE"
```

I build a java client for the elasticsearch. When I use the admin-keystore.jks for the client to connect the elasticsearch, it works fine. However, when it comes with kirk-keystore.jks, it fails to authorize the user.

Then I change the elasticsearch.yml as below:
```
 searchguard.ssl.transport.keystore_filepath: /usr/share/elasticsearch/config/keys/kirk-keystore.jks
 searchguard.ssl.transport.truststore_filepath: /usr/share/elasticsearch/config/keys/truststore.jks
 security.manager.enabled: false
 searchguard.authcz.admin_dn:
   - "CN=kirk, OU=client, O=client, L=Test, C=DE"
```
The only user that can connect the elasticsearch becomes kirk.

The goal I made is that, I can use different keystore.jks for different client, and different client can all connect the elasticsearch. The only difference is that different user has different permissions, to visit different indices or types or different operations, as defined in sg_roles_mapping.yml or sg_internal_users.yml.

Is that problem cuased by my configuration or search-guard function disability? I browsed all docs in https://github.com/floragunncom/search-guard-docs, but still can't find the answer.

**Comment by floragunncom** [comment]
You wrote "However, when it comes with kirk-keystore.jks, it fails to authorize the user." - Please. post logfiles (on DEBUG level) for this case and also your sg_config.yml.

**Comment by yangfeiran** [comment]
@floragunncom 
Thanks for your reply, here is my sg_config.yml:
`# This is the main configuration file where the authentication and authorization
# backends as well as the http authenticators and other settings will be defined.
#
# The authentication works like that:
# 
# If there are no authenticators (authc) defined a implicit one will be created.
# This will authenticate against the internal user database and use HTTP Basic.
#
# If more than one is configured the first one which succeeds wins. If all fail then the request will be unauthenticated
# and a respective exception is thrown and/or the HTTP status is set to 401.
# 
# After authentication authorization (authz) will be applied. There can be zero or more authorizers which collect
# the roles from a given backend for the authenticated user.
#
# For HTTP is possible to allow anonymous authentication. If that is allowed then the http authenticators try to
# find user credentials in the HTTP request and if such where found then the user gets regularly authenticated.
# If none can be found the user will be authenticated as an "anonymous" user. This user has always the username "sg_anonymous"
# and one role named "sg_anonymous_backendrole". If you enable anonymous authentication for all http authenticators will not challenge.
# 
#
# Notice: If you define more than one authenticator make sure to put non-challenging authenticators like "proxy" or "clientcert"
# at the beginning and the challenging one at the end. If you configure more than one challenging authenticator you have to deal with
# the "challenge" flag. Because its not possible to challenge a client with two different authentication methods (for example
# Kerberos and Basic) only one can have challenge: true. All others need to have challenge: false and that means
# they look into the request and if they found no credentials they will not challenge. You can cope with this situation
# with pre-authentication. That is submitting credentials for non-challenging authenticators within the first request
# (Thats especially easy for Basic authentication). 
# Default value of the challenge flag is true.
#
# 
#
# HTTP
#   basic (challenging)
#   proxy (not challenging, needs xff)
#   kerberos (challenging) NOT FREE FOR COMMERCIAL
#   clientcert (not challenging, needs https)

# Authc
#   internal
#   noop
#   ldap  NOT FREE FOR COMMERCIAL USE

# Authz
#   ldap  NOT FREE FOR COMMERCIAL USE
#   noop

searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        #internalProxies: '.*' # trust all internal proxies, regex pattern
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
        #trustedProxies: '.*' # trust all external proxies, regex pattern
        ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
        ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
        ###### and here https://tools.ietf.org/html/rfc7239
        ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
    authc:
      kerberos_auth_domain: 
        enabled: false
        order: 4
        http_authenticator:
          type: kerberos # NOT FREE FOR COMMERCIAL USE
          challenge: true
          config:
            # If true a lot of kerberos/security related debugging output will be logged to standard out
            krb_debug: false
            # Acceptor (Server) Principal name, must be present in acceptor_keytab_path file
            acceptor_principal: 'HTTP/localhost'
            # If true then the realm will be stripped from the user name
            strip_realm_from_principal: true
        authentication_backend:
          type: noop
      basic_internal_auth_domain: 
        enabled: true
        order: 2
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      proxy_auth_domain:
        enabled: false
        order: 1
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
      clientcert_auth_domain:
        enabled: false
        order: 0
        http_authenticator:
          type: clientcert
          challenge: false
        authentication_backend:
          type: noop
      ldap:
        enabled: false
        order: 3
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          # LDAP authentication backend (authenticate users against a LDAP or Active Directory)
          type: ldap # NOT FREE FOR COMMERCIAL USE
          config:
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: true
            hosts:
              - localhost:8389
            bind_dn: null
            password: null
            userbase: 'ou=people,dc=example,dc=com'
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username 
            usersearch: '(uid={0})'
            # Use this attribute from the user as username (if not set then DN is used)
            username_attribute: null
    authz:    
      roles_from_myldap:
        enabled: false
        authorization_backend:
          # LDAP authorization backend (gather roles from a LDAP or Active Directory, you have to configure the above LDAP authentication backend settings too)
          type: ldap # NOT FREE FOR COMMERCIAL USE
          config:
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: true
            hosts:
              - localhost:8389
            bind_dn: null
            password: null
            rolebase: 'ou=groups,dc=example,dc=com'
            # Filter to search for roles (currently in the whole subtree beneath rolebase)
            # {0} is substituted with the DN of the user
            # {1} is substituted with the username 
            # {2} is substituted with an attribute value from user's directory entry, of the authenticated user. Use userroleattribute to specify the name of the attribute            
            rolesearch: '(uniqueMember={0})'
            # Specify the name of the attribute which value should be substituted with {2} above
            userroleattribute: null
            # Roles as an attribute of the user entry
            userrolename: memberOf
            # The attribute in a role entry containing the name of that role
            rolename: cn
            # Resolve nested roles transitive (roles which are members of other roles and so on ...)
            resolve_nested_roles: true
            
            userbase: 'ou=people,dc=example,dc=com'
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username 
            usersearch: '(uid={0})'
            
      roles_from_another_ldap:
        enabled: false
        authorization_backend:
          type: ldap # NOT FREE FOR COMMERCIAL USE
          #config goes here ...`
Actually, I didn't change anything in that.

logfiles:
RemoteTransportException[[node-80][172.16.50.81:7300][cluster:monitor/nodes/liveness]]; nested: ElasticsearchSecurityException[Cannot authenticate User [name=CN=kirk,OU=client,O=client,L=Test,C=DE, roles=[]]];
Caused by: ElasticsearchSecurityException[Cannot authenticate User [name=CN=kirk,OU=client,O=client,L=Test,C=DE, roles=[]]]
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:268)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:128)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:245)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:62)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:50)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{172.16.50.81}{172.16.50.81:7300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at esclient.main(esclient.java:40)

In addition, the error is the same, even though I added `searchguard.authcz.impersonation_dn.0:
   - "CN=kirk, OU=client, O=client, L=Test, C=DE"` after I read this page:https://github.com/floragunncom/search-guard/issues/129

**Comment by floragunncom** [comment]
Add something like this in sg_internal_users.yml

```
'CN=kirk,OU=client,O=client,L=Test,C=DE':
  #transport login only
  hash: '_impersonation_only_'
  roles:
    - vulcan
    - starfleet
```

**Comment by yangfeiran** [comment]
@floragunncom 
I am sorry for replying so lately. Thank you for your kindly reply.

The way I fix the problem is like this:
First, change the elasticsearch.yml like below:
 ```
searchguard.ssl.transport.keystore_filepath: /usr/share/elasticsearch/config/keys/admin-keystore.jks
 searchguard.ssl.transport.truststore_filepath: /usr/share/elasticsearch/config/keys/truststore.jks
 security.manager.enabled: false
 searchguard.authcz.admin_dn:
   - "CN=admin, OU=client, O=client, L=Test, C=DE"
 searchguard.authcz.impersonation_dn:
  "CN=kirk,OU=client,O=client,L=Test,C=DE":
     - 'admin'
```
and second, the setting in the client is set as below:
```
.put("searchguard.ssl.transport.keystore_filepath", "kirk-keystore.jks")
.put("searchguard.ssl.transport.truststore_filepath", "truststore.jks")
.put("searchguard.ssl.transport.enforce_hostname_verification", false)
.put("request.headers.sg_impersonate_as", "admin")
```

So, the user 'kirk' is impersonated as user 'admin', then 'kirk' can be authorized and has the pemission to get data from elasticsearch.

However, this kind of solution brings out a new problem, which is elasticsearch should be restarted every time I add a new user to the search guard. This is a server problem when elasticsearch is available for people to use. Isn't it?

**Comment by yangfeiran** [comment]
`#<sg_role_name>:
#  cluster:
#    - '<permission>'
#  indices:
#    '<indexname or alias>':
#      '<type>':  
#        - '<permission>'
#      _dls_: '<querydsl query>'
#      _fls_:
#        - '<field>'
#        - '<field>'

# When a user make a request to elasticsearch then the following roles will be evaluated to see if the user has
# permissions for the request. A request is always associated with an action and is executed against and index (or alias)
# and a type. If a request is executed against all indices (or all types) then the asterix ('*') is needed.
# Every role a user has will be examined if it allows the action against an index (or type). At least one role must match
# for the request to be successful. If no role match then the request will be denied. Currently a match must happen within
# one single role - that means that permissions can not span multiple roles. 

# For <permission>, <indexname or alias> and <type> simple wildcards are possible. 
# A asterix (*) will match any character sequence (or an empty sequence)
# A question mark (?) will match any single character (but NOT empty character)
# Example: '*my*index' will match 'my_first_index' as well as 'myindex' but not 'myindex1'
# Example: '?kibana' will match '.kibana' but not 'kibana'
# Note: You cannot have a dot (.) in the <permission>, <indexname or alias> or <type> name/wildcard

# For <permission>, <indexname or alias> and <type> are also regular expressions possible. 
# You have to pre- and apend a '/' to use regex instead of simple wildcards
# '/<java regex>/'
# Example: '/\S*/' will match any non whitespace characters
# Note: You cannot have a dot (.) in the <permission>, <indexname or alias> or <type> regex
# Use \S instead
# See https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html


# DLS (Document level security) NOT FREE FOR COMMERCIAL
# Install https://github.com/floragunncom/search-guard-module-dlsfls
# Per Index you can define a DLS query
# If more than one DLS query match they will be OR'ed

# FLS (Field level security) NOT FREE FOR COMMERCIAL
# Per Index you can define a FLS fields
# If more than one FLS config match the field will be appended
# Install https://github.com/floragunncom/search-guard-module-dlsfls


# Allows everything
# but not changes to searchguard config/index
sg_all_access:
  cluster:
    - '*'
  indices:
    '*':
      '*':
        - '*'
        
sg_role_starfleet:
  indices:
    sf:
       ships:  
         - READ
       public:  
         - 'indices:*'
       students:  
         - READ
       alumni:  
         - READ
    'pub*':
       '*':  
         - READ

sg_role_chinacloud:
  cluster:
    - '*'
  indices:
    '*':
      '*':
        - ALL

sg_role_starfleet_captains:
  indices:
    sf:
       '*':  
         - CRUD
    pub*:
       '*':  
         - CRUD 
  cluster:
    - 'cluster:monitor*'
  

sg_readonly_and_monitor:
  cluster:
    - CLUSTER_MONITOR
  indices:
    '*':
      '*':
        - ALL

sg_readall:
  indices:
    '*':
      '*':
        - READ

sg_readonly_dlsfls:
  indices:
    '/\S*/':
      '*':
        - READ    
      _dls_: '{"term" : {"_type" : "legends"}}'
      _fls_:
        - 'aaa'
        - 'bbb'

sg_transport_client:
  cluster:
      - cluster:monitor/nodes/liveness
      - cluster:monitor/state

sg_kibana4:
  cluster: 
      - cluster:monitor/nodes/info
      - cluster:monitor/health
  indices:
    '*':
      '*':
        - READ
        - indices:admin/mappings/fields/get*
        - indices:admin/validate/query*
        - indices:admin/get*
    '?kibana':
      '*':
        - indices:admin/exists*
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*

sg_kibana4_server:
  cluster:
      - cluster:monitor/nodes/info
      - cluster:monitor/health
  indices:
    '?kibana':
      '*':
        - ALL

sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    'logstash-*':
      '*':
        - CRUD
        - CREATE_INDEX
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX
`

**Comment by yangfeiran** [comment]
@floragunncom 
I tried your method to add `'CN=test,OU=client,O=client,L=Test,C=DE':
  #transport login only
   hash: $2a$12$9utr9oAmqSw0zMenB3Vt0.gWSM7A1R2cKjm7V3ff/4maV/6Lfmj1i
   `into the sg_internal_users.yml. And gave it a role in the sg_roles_mapping.yml. Reload the changes. And changed the client like this:
		```
.put("searchguard.ssl.transport.keystore_filepath", "test-keystore.jks");
.put("searchguard.ssl.transport.truststore_filepath", "truststore.jks");
.put("searchguard.ssl.transport.enforce_hostname_verification", false);
.put("request.headers.sg_impersonate_as", "CN=test,OU=client,O=client,L=Test,C=DE");
```

**Comment by yangfeiran** [comment]
@floragunncom 
Your kindly answer solved my problem, with a little bit modification. It should be added as below:
```
CN=kirk,OU=client,O=client,L=Test,C=DE:
  #transport login only
  hash: '_impersonation_only_'
```
You see, without the " ' " .
