### ISSUE TITLE
Search Guard Failed To Connect using Public Wildcard SSL

### ISSUE THREAD

**Issue by skyfx64** [floragunncom/search-guard#157]
Hello I'm trying to implement search Guard using Public Wildcard SSL certificate but always get this error message when execute sgadmin.

ES : 2.3.3
SG : 2.3.3.2
SG SSL : 2.3.3.13
OS : CenTos 6.5

star-test.jks = server public wildcard certificate

**Command :**
plugins/search-guard-2/tools/sgadmin.sh    -h es0.test.com -p 9300   -cd plugins/search-guard-2/sgconfig/    -ks plugins/search-guard-2/sgconfig/star-test.jks    -ts plugins/search-guard-2/sgconfig/star-test.jks     -kspass p@ssw0rd    -tspass p@ssw0rd    -nhnv

**Error Message :**
Connect to es0.test.com:9300
ERR: Cannot connect to elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.64.20.50}{es0.test.com/10.64.20.50:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:848)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:868)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:252)
        at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:71)

**Open SSL :**
**Command :** openssl s_client -connect es0.test.com:9300
**Output :**
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES128-SHA256
    Session-ID:
    Session-ID-ctx:
    Master-Key: 757A47D180D3BE2978FA1D88DC08CAE0B993C31058A5DF5B764853B8A27A76C36E8C81DC852AE75254EA77403DD2BE79
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1467347418
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

**Elastic Configuration :**
cluster.name: IEG-Analytic-Dev
node.name: IEG-Corp-Search-Dev
bootstrap.mlockall: true
network.host: es0.test.com

http.compression: true

http.cors.enabled : true
http.cors.allow-origin : "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length

script.engine.groovy.inline.aggs: on
script.engine.groovy.inline.update: on

searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: star-test.jks
searchguard.ssl.http.keystore_password: p@ssw0rd
searchguard.ssl.http.truststore_filepath: star-test.jks
searchguard.ssl.http.truststore_password: p@ssw0rd
searchguard.ssl.http.clientauth_mode: NONE

searchguard.ssl.transport.keystore_filepath: star-test.jks
searchguard.ssl.transport.keystore_password: p@ssw0rd
searchguard.ssl.transport.truststore_filepath: star-test.jks
searchguard.ssl.transport.truststore_password: p@ssw0rd
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.enable_openssl_if_available: true
searchguard.ssl.http.enable_openssl_if_available: true

security.manager.enabled: false
searchguard.authcz.admin_dn:
- "CN=*.test.com,OU=Department,O=Test,L=Test,C=ID"

Could you help me to check why still give that error, just for information i don't have any client certificate for my wildcard SSL.

thanks'

**Comment by iboware** [comment]
It may have something to do with [this issue](https://github.com/floragunncom/search-guard-ssl/issues/22) I created before. Using a public wildcard certificate for ssl.transport won't work very well as I have experienced before. Your DNS records and server names must be well configured to be able do it. it is better to create a self signed one using the scripts provided [here](https://github.com/floragunncom/search-guard-ssl-docs/blob/master/quickstart.md). In the end it is only for internal communication. On the other hand a wildcard public SSL Certificate works well with the ssl.http. Of course this is my opinion and experience. I hope it helps.

**Comment by floragunncom** [comment]
Can this issue be closed?

**Comment by floragunncom** [comment]
maybe related to https://github.com/floragunncom/search-guard/issues/153

**Comment by dopey** [comment]
I had a similar issue, same error message I believe. For me it ended up being the cluster name. Once I used the `-icl` option to ignore the cluster name, or the `-cn` option to specify the cluster name, I was able to successfully run the sgadmin tool.

**Comment by floragunncom** [comment]
@skyfx64 did the comments from @iboware and @dopey helped you out?

**Comment by floragunncom** [comment]
ping

**Comment by floragunncom** [comment]
no feedback, will close this issue. Think we track it in https://github.com/floragunncom/search-guard/issues/153

**Comment by skyfx64** [comment]
Hello,

Please close this thread, because we have certificate issue. After buy a new one everything okay.

Thanks

Sent from my iPhone

On Dec 11, 2016, at 10:15 PM, floragunn GmbH <notifications@github.com> wrote:

Closed #157.

**Comment by floragunncom** [comment]
@skyfx64 thx for you feedback, glad to hear that its working
