### ISSUE TITLE
Puppet Module for Search Guard

### ISSUE THREAD

**Issue by nguyenmv2** [floragunncom/search-guard#161]
This is not an issue. I just want to know if the search-guard team has a puppet module. ElasticSearch has an official puppet module, and so does Shield. 

Thank you

**Comment by floragunncom** [comment]
Thanks for you question. No, we do not have a Puppet module at the moment. Since there is not much request for it, this is not a top priority on our todo list either. But of course we highly appreciate any contributions from the community.

**Comment by tremblerz** [comment]
+1

**Comment by hyf101070** [comment]
+1

**Comment by zer0nimbus** [comment]
+1
