### ISSUE TITLE
Cannot run elasticsearch after installing search-guard plugin

### ISSUE THREAD

**Issue by LinhTruongVan** [floragunncom/search-guard#18]
Hi @floragunncom ,
I'm facing with an issue. My elasticsearch cannot run after installing search-guard plugin. I got an elasticsearch exeption : "You're trying to run elasticsearch as root or window Administrator and thats forbidden". I don't know how to solve its. Could you help me?

**Comment by floragunncom** [comment]
see https://groups.google.com/forum/#!searchin/search-guard/root/search-guard/yAIrnlwNLsQ/8vouo5wMtAIJ

**Comment by LinhTruongVan** [comment]
OK. I solved it. Thanks for your help :+1:
