### ISSUE TITLE
Tests are too slow

### ISSUE THREAD

**Issue by Gordiychuk** [floragunncom/search-guard#185]
Tests from com.floragunn.searchguard.SGTests works to slow. On my machine 17 tests from SGTests get 5 minutes. As result tests not available run often when prepare PR with TDD methodology. 

What do you thinks about test refactoring, and increase startup time?

**Comment by floragunncom** [comment]
Good idea, wanna submit a PR for this?

**Comment by Gordiychuk** [comment]
Yes

**Comment by floragunncom** [comment]
Great, happy to merge
