### ISSUE TITLE
Commits to master bypassing a PR

### ISSUE THREAD

**Issue by Gordiychuk** [floragunncom/search-guard#189]
Please, not commit to master branch bypassing PR, because it can lead to not valid master branch and also skip all code quality tests and potential code review.

**Comment by floragunncom** [comment]
This is currently not possible. But we will do the work resolving PR merge conflict. Please stay tuned regrading your pending merge request - we work on it and they are scheduled for the next upcoming release (planned for end of this month)

**Comment by Gordiychuk** [comment]
The problem with not a merge conflict. The problem with code quality. You can not guarantee quality of your code without code review, tests and so on. All of this points not work if you commit to master branch by passing a PR.
