### ISSUE TITLE
No access to kibana when adding bypass on .kibana:index-pattern

### ISSUE THREAD

**Issue by julienbeclin** [floragunncom/search-guard#19]
Hi I have an issue when I add a bypass on inde:type. Any idea ?

Config :

```json
# Enable or disable the complete Searchguard plugin functionality
searchguard.enabled: true

# Path where to write/read the searchguard master key file
searchguard.key_path: /etc/searchguard/

# When using DLS or FLS and a get or mget is performed then rewrite it as search request
searchguard.rewrite_get_as_search: true

searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend

searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator

searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator

searchguard.authentication.settingsdb.user.admin: admin
searchguard.authentication.settingsdb.user.user1: user1pwd
searchguard.authentication.settingsdb.user.user2: user2pwd

searchguard.authentication.authorization.settingsdb.roles.admin: ["admin"]

# Configure the actionrequestfilter to allow or forbid action
searchguard.actionrequestfilter.names: ["readonly","kibanaaccess"]
searchguard.actionrequestfilter.readonly.allowed_actions: [ "indices/data/read/*","*monitor*", "indices:admin*"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*","indices:data/write*"]
```

```json
ACL rules :

{"acl": [
    {
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": [],
      "filters_execute": ["*"]
    },
    {
      "__Comment__": "This means that every requestor (regardless of the requestors hostname and username) which has the admin role can do anything",
      "roles": [
        "admin"
      ],
      "filters_bypass": ["*"],
      "filters_execute": []
    },
    {
      "__Comment__": "This means that for the user user1 on index .kibana and type index-pattern, all is bypassed",
      "users": ["user1"],
      "indices": [".kibana:index_patten"],
      "filters_bypass": ["*"],
      "filters_execute": []
    }
]}'
```
user1 cannot access kibana with this error :

![error_kibana](https://cloud.githubusercontent.com/assets/12039154/8377775/73f961b0-1c14-11e5-96c7-f119016d7b9c.png)

But only with this ACL rules :

``` json

{"acl": [
    {
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": [],
      "filters_execute": ["*"]
    },
    {
      "__Comment__": "This means that every requestor (regardless of the requestors hostname and username) which has the admin role can do anything",
      "roles": [
        "admin"
      ],
      "filters_bypass": ["*"],
      "filters_execute": []
    }
]}'
```

user1 can access to kibana and every index.

**Comment by floragunncom** [comment]
What do want achieve with this: <code>"indices": [".kibana:index_patten"]</code>?
It means: user1 may access the index ".kibana" and the type "index_pattern" without restrictions.

But all other types in the .kibana index are restricted.

**Comment by julienbeclin** [comment]
That is exactly what I am trying to achieve.
When you use Kibana with Elasticsearch, ES generates automatically a Kibana index (named by default```.kibana```). In this index, new documents are automatically created depending on what you create and save in Kibana.
For instance : 
if you create a visualisation in Kibana, a new document with ```_index:.kibana``` and ```_type:visualization``` is created and stored.
 Same for new dashboards and new index-patterns : 
```_index:.kibana```,```_type:dashboard``` is stored.
```_index:.kibana```,```_type:vindex-pattern``` is stored.

So what I am tring to achieve is to let user1 access kibana and all the docuements with typê index-pattern, but forbid him to access visualizations and dashboard for example.

**Comment by floragunncom** [comment]
<code>"indices": [".kibana:index_patten"]</code> != <code>"indices": [".kibana:index-patten"]</code>
(index_patten vs index-patten), maybe thats the problem?

**Comment by julienbeclin** [comment]
Damn, I have to check into that, it might be the issue (which would be stupid from me...)
I am currently working on something else so it might take some time try that again, but I will definitely tell you if this solves the issue or not.
Thanks for your time I'll get back to you

**Comment by jayeshdhamechai** [comment]
@julienbeclin 
Hi,
Were you able able to set up access control on kibana dashboards using search-guard?

**Comment by balubollam** [comment]
Replacing your default  settings
  {
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": ["*"],
      "filters_execute": []
    },


May solve the above issue

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
