### ISSUE TITLE
Authentication not being passed to kibana plugins

### ISSUE THREAD

**Issue by djtecha** [floragunncom/search-guard#191]
#Versions
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
elasticsearch-2.3.4
 search-guard-2-2.3.4.4
search-guard-ssl-2.3.4.14
kibana-4.5.3

Install the marvel plugin (or timelion), restart kibana then try to use the plugins using the drop down from kibana. This leads to a http basic auth window dropping down even though I am already logged in, and since I use SSO the authentication can not be completed and results in a 401 unauthorized.

> [2016-08-02 09:57:46,201][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Unexpected exception com.google.common.util.concurrent.UncheckedExecutionException: ElasticsearchSecurityException[test@gmail.com not found] 
> com.google.common.util.concurrent.UncheckedExecutionException: ElasticsearchSecurityException[daniel.kasen@redfin.com not found]
>     at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
>     at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
>     at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
>     at com.floragunn.searchguard.auth.BackendRegistry.authenticate(BackendRegistry.java:401)
>     at com.floragunn.searchguard.filter.SearchGuardRestFilter.process(SearchGuardRestFilter.java:56)
>     at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:263)
>     at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:176)
>     at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
>     at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
>     at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:449)
>     at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
>     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
>     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
>     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
>     at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
>     at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
>     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
>     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
>     at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
>     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
>     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
>     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
>     at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
>     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
>     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
>     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
>     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
>     at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
>     at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
>     at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
>     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
>     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
>     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
>     at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
>     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
>     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
>     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
>     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
>     at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
>     at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
>     at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
>     at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
>     at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
>     at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
>     at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)

sg_config:

searchguard:

  dynamic:
    http:
      xff:
        enabled: true
        trustedProxies: '._'
        internalProxies: '._'
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
    authc:
      authentication_domain_proxy:
        enabled: true
        order: 1
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
      authentication_domain_basic_internal:
        enabled: true
        order: 2
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern

**Comment by djtecha** [comment]
I have noticed that if I enable anonymous_auth_enabled: true and add that user to the correct permissions it is able to pass though directly to port 5601, so not going through my nginx frontend. Seems as if kibana is dropping the x-proxy-user when it passes to applications that are not kibana itself.

**Comment by djtecha** [comment]
Has anyone been able to get kibana plugins to work correctly using SG? Kind of been in a holding pattern for a while here and it'd be nice to know if I'm messing up or this is just a limitation at this time.

**Comment by Andrew-Stubbs** [comment]
I have the same problem trying to use XFF / x-proxy-user with Kibana and Timelion

Using the browser logs, when I try and view a dashboard widget the iframe will attempt to POST to:
https://...:5601/api/timelion/run

Using cURL I can confirm that hitting this endpoint with my XFF header results in:

> {"statusCode":401,"error":"Unauthorized","message":"Unauthorized","attributes":{"realm":"Authorization Required","error":"Unauthorized"}}

But passing through an Authorization header returns the correct data.

From inspecting traffic, I believe Kibana is passing the XFF header to Timelion as it makes its request outlined above, but Timelion itself is then blocked later on, presumably when making a subsequent HTTP request, either back to Kibana or to Elasticsearch.

**Comment by floragunncom** [comment]
@djtecha if you like to beta test pls drop us a note/mail

**Comment by djtecha** [comment]
Yea, I can help out. Is there a zip I can grab or should I just compile from a specific tag?

**Comment by floragunncom** [comment]
We will come back to you shortly

**Comment by floragunncom** [comment]
We have now a version for Kibana 5.0.2 and 5.1.1 ready.

**Comment by djtecha** [comment]
hmm, any chance this will be backported to something that runs on ES 2.4.* ? Upgrading my clusters would be a lot of work to upgrade to the 5 series. Otherwise, I'll look into this overhaul beginning 2017. I understand if it's more work then it's worth to back-port though.

**Comment by floragunncom** [comment]
we are working on this

**Comment by jochenkressin** [comment]
In Kibana 5.0.2 and above HTTP Basic Authentication is broken. We've just released a Kibana plugin which adds login/logout functionality and makes Kibana compatible with Search Guard again. It's currently in alpha, but if you want to give it a try, you can find the code and the alpha releases here:

https://github.com/floragunncom/search-guard-kibana-plugin 

There's also a release for Kibana 4.6.0 which is compatible with ES 2.4.x. Any feedback is much appreciated!

**Comment by djtecha** [comment]
This lets me get to other plugins, but sort of blocks my SSO login method. Any advice on passing just the username to this login method? Because google does my authentication and then simply passes the username along to the application and this plugin appears to want the password again which just never exists on the server.

**Comment by jochenkressin** [comment]
Ok, understood. At the moment we only support Basic Auth headers, but we can probably extend it to support SSO / x-proxy-user as well.

Just to make sure I've understood the scenario correctly. You authenticate against an SSO solution, and then use proxy authentication on SG side, correct?

**Comment by djtecha** [comment]
That is correct. And thank you, it worked well when I continued to log in as the admin user. :)

**Comment by floragunncom** [comment]
Just an addition: If you just need SSO support, and do not need Basic Auth, you can also whitelist the required headers in kibana.yml, e.g.:

elasticsearch.requestHeadersWhitelist: [ 'Authorization', 'x-forwarded-for', 'x-proxy-user' ]

This however will not work together with the Basic Auth plugin.

**Comment by djtecha** [comment]
So I was forced to upgrade to ES 5.2.1 and everything that goes with that. Now I have an odd problem. I can get kibana with the SG plugin working but I have to completely disable the authentication_domain_basic_internal method, which breaks things like LS and general admin things. Any ideas on what I'm doing wrong here?

searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        trustedProxies: '.*'
        internalProxies: '.*'
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
    authc:
      authentication_domain_proxy:
        enabled: true
        order: 2
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
      authentication_domain_basic_internal:
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern

I see my name being passed through in the kibana logs but I still get a pop up box (basic auth).

**Comment by floragunncom** [comment]
What happens if you switch the order (proxy first, then basic)?

**Comment by djtecha** [comment]
Ok, I got this working using the SG kibana plugin. For those still fighting with this here is how I was able to get this set up.

nginx part passing the user:
```    rewrite ^/kibana4/(.*) /$1 break;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:5601;
    proxy_set_header x-proxy-user $ngo_user;
    proxy_set_header Authorization $ngo_auth;
```

This proxy's to the kibana webui which uses the SG kibana plugin:

```
searchguard.cookie.password: "RANDOMSTRING"
searchguard.basicauth.enabled: false
elasticsearch.requestHeadersWhitelist: ["x-proxy-user", "authorization", "x-forwarded-for", "x-forwarded-server"]
```

make sure you are passing the x-proxy-user and check the kibana logs to confirm that your username is making it this far.

example line:

{"type":"response","@timestamp":"2017-03-01T18:06:01Z","tags":[],"pid":157911,"method":"post","statusCode":200,"req":{"url":"/elasticsearch/_msearch","method":"post","headers":{"host":"logs.redf.in","x-real-ip":"10.11.0.1","x-scheme":"http","x-forwarded-for":"10.11.0.1","x-proxy-user":"djtecha","connection":"close","content-length":"749","accept":"application/json, text/plain, */*","origin":"https://test.com","kbn-version":"5.2.1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36","content-type":"application/x-ldjson","referer":"https://test.com/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.8"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://test.com/app/kibana"},"res":{"statusCode":200,"responseTime":3954,"contentLength":9},"message":"POST /elasticsearch/_msearch 200 3954ms - 9.0B"}

Next set up the sg_config.yml in the following way:

```
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        trustedProxies: '.*'
        internalProxies: '.*'
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
    authc:
      authentication_domain_proxy:
        enabled: true
        order: 0
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
      authentication_domain_basic_internal:
        enabled: true
        order: 2
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
```

Might want to modify the proxies settings for a more secure setting. But that's about it. Just set up the roles and role mappings to how you need them, but kibana should be using your x-proxy-user all the way though. The basic auth in the es_config.yml is for backend stuff like ES, direct curl access, logstash and all those things.

**Comment by floragunncom** [comment]
Thats great. So is the original issue ("Authentication not being passed to kibana plugins") also resolved now?

**Comment by djtecha** [comment]
Hard to say as the only plugins I used where timelion and marvel. and timelion is included and I can't get xpack working on ES5 yet. We can close this issue for now if you'd like and I can re-open in I run into it with future plugins. Thanks for the help.

**Comment by floragunncom** [comment]
When timelion is working than other plugins should also work, so lets close this (long standing) issue.

If you or anyone else experience problems with other Kibana plugins pls. open a new issue and reference this one.
