### ISSUE TITLE
Adding internal users

### ISSUE THREAD

**Issue by girishgoudapatil** [floragunncom/search-guard#193]
Hi,

Is there a way to write users directly to elaticsearch instead of updating sg_internal_users.yml and reloading via sgadmin tool?

Regards,
Girish

**Comment by floragunncom** [comment]
not yet. Why do you need this? sgadmin is scriptable.

**Comment by girishgoudapatil** [comment]
I have hundreds of users and each having its own role with specific dsl query , as of now we need to rewrite the config files everytime there is a new user or user leaves the system.

**Comment by floragunncom** [comment]
So you want to have a kind of (REST) api for this? 

Is your system already in production or are you in an evaluation/testing phase?

**Comment by girishgoudapatil** [comment]
A rest API would be perfect.

The system is already in production but we are adding the authentication/authorization to the reports, so we are evaluating searchguard

**Comment by floragunncom** [comment]
We put his on our feature list. 

Pls. keep in mind that you need a commercial license for the DLS module if you want to use it in production.

**Comment by girishgoudapatil** [comment]
Re. licence - We are aware of the commercial license.

Is there way to bypass sgadmin till we have the API's ?

**Comment by floragunncom** [comment]
no, you cannot bypass it by now, sorry

**Comment by floragunncom** [comment]
We started to work on this ...

**Comment by floragunncom** [comment]
Hi - we just released the first version of the management API. This is an early beta release, so you might find some bugs or issues. Would be great if you could try it out and help us by reporting any bugs or missing features.

Github repository:
https://github.com/floragunncom/search-guard-rest-api

Documentation:
https://github.com/floragunncom/search-guard-docs/blob/master/managementapi.md

Snapshot, compatible with ES 2.4.x and Search Guard 2.4.x.7:
https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/dlic-search-guard-rest-api/2.4-1-SNAPSHOT/dlic-search-guard-rest-api-2.4-1-20161008.211208-1.jar

**Comment by girishgoudapatil** [comment]
thanks much, I will give it a go

**Comment by floragunncom** [comment]
released yesterday, see https://github.com/floragunncom/search-guard-rest-api
