### ISSUE TITLE
The default index of kibana problem

### ISSUE THREAD

**Issue by LazyerHong** [floragunncom/search-guard#195]
In the kibana setting, i have two index  nginx-223-\* and apache-tomcat-223-_. And the nginx-223-_ index is set as the default index.
Then, I have installed the search guard successfully, but there are some questions when using this plugins.

When i login the kibana as the nginxuser, i can only see the index of  nginx-223-_. The kibana show the index nginx-223-_ which is the default index.

But when i login the kibana as the user apacheuser which can only see the index of apache-tomcat-223-_,   i can not login the kibana. Because the kibana always show the default index nginx-223-_ so that the apacheuser can not access. The kibana show the errors which always not show the apach-tomcat-223-*.

So, the default index have affect on the use of search guard. Who can tell me how to solve the problem?

**Comment by LazyerHong** [comment]
Nobody？ I think it is a important function when we access the kibana.

**Comment by floragunncom** [comment]
Will look into this, thx for reporting.

**Comment by floragunncom** [comment]
We started working on that

**Comment by floragunncom** [comment]
This will be solved as part of the upcoming Search Guard multiuser/multitenancy feature. The release is planned in February 2017.

**Comment by floragunncom** [comment]
Our new Kibana multi tenancy module for ES/KI 5.2.2 has arrived as first beta! https://groups.google.com/forum/?hl=en#!topic/search-guard/XuJkRCaHUIQ
