### ISSUE TITLE
Audit logging - log each request to another cluster

### ISSUE THREAD

**Issue by megastef** [floragunncom/search-guard#2]
Hi, first off thanks for providing Search Guard. 

1) Does your audit logging support logging of each request? 
Please see this discussion about the audit trail feature shield: 
https://discuss.elastic.co/t/elasticsearch-request-logging/1786

2) In addtion I would like to ask how to configure audit logging to send audit logs to another Elasticsearch cluster. In our specific case the 'other' cluster would be [Logsene](http://www.sematext.com/logsene/).

**Comment by floragunncom** [comment]
Sorry, both cases are not supported yet. We will put this on the roadmap (contributions welcome).

**Comment by otisg** [comment]
Another +1 for sending audit to another cluster (think: offsite), like to Logsene for example.

**Comment by floragunncom** [comment]
@otisg maybe you are willing to contribute to such a functionality?

**Comment by floragunncom** [comment]
This will come July 2016 with the second feature release after GA

**Comment by floragunncom** [comment]
Its finally here https://github.com/floragunncom/search-guard-module-auditlog
