### ISSUE TITLE
plugins/search-guard-2/tools/sgadmin.sh:Seems there is no elasticsearch running on localhost:9200 - Will exit

### ISSUE THREAD

**Issue by yiyezhiqiu331** [floragunncom/search-guard#200]
when  i excute  : plugins/search-guard-2/tools/sgadmin.sh   -p 9200  -cd plugins/search-guard-2/sgconfig/ -ks plugins/search-guard-2/sgconfig/kirk-keystore.jks -ts plugins/search-guard-2/sgconfig/truststore.jks 

i get this:
 plugins/search-guard-2/tools/sgadmin.sh   -p 9200  -cd plugins/search-guard-2/sgconfig/ -ks plugins/search-guard-2/sgconfig/kirk-keystore.jks -ts plugins/search-guard-2/sgconfig/truststore.jks

**Comment by floragunncom** [comment]
This is a very confusing description and very likely not a bug. Can you pls. ask this question again with more details attached here: https://groups.google.com/forum/#!forum/search-guard Please also include what you tried so far and which version of Search Guard and which Java/Operation System vendor and version you are using.
