### ISSUE TITLE
FAIL: Expected 5 config types for node but got only []

### ISSUE THREAD

**Issue by bujarmetaj2016** [floragunncom/search-guard#203]
Hi 
please I need help with this one

I am having a problem running sgadmin.sh 
1. elasticsearch 2.3.5
2. search-guard-2 2.3.5.5
3. search-guard-ssl 2.3.5.15 

elasticsearch:
 searchguard.authcz.admin_dn:
        - CN=sgadmin

      searchguard.ssl.transport.http.enforce_clientauth: false
      searchguard.ssl.transport.enabled: true
      searchguard.ssl.transport.keystore_filepath: localhost-keystore.jks
      searchguard.ssl.transport.keystore_password: August2016
      searchguard.ssl.transport.truststore_filepath: truststore.jks
      searchguard.ssl.transport.truststore_password: August2016
      searchguard.ssl.transport.enforce_hostname_verification: true
      searchguard.ssl.transport.resolve_hostname: true
      searchguard.ssl.http.enabled: true
      searchguard.ssl.http.keystore_filepath: localhost-keystore.jks
      searchguard.ssl.http.keystore_password: August2016
      searchguard.ssl.http.truststore_filepath: truststore.jks
      searchguard.ssl.http.truststore_password: August2016
      searchguard.ssl.transport.enable_openssl_if_available: true
      searchguard.ssl.http.enable_openssl_if_available: true

Will connect to localhost:9300 ... done
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: elasticsearch
Clusterstate: YELLOW
Number of nodes: 1
Number of data nodes: 1
searchguard index does not exists, attempt to create it ... done
Populate config from /usr/share/elasticsearch/plugins/search-guard-2/sgconfig
Will update 'config' with plugins/search-guard-2/sgconfig/sg_config.yml
   SUCC: Configuration for 'config' created or updated
Will update 'roles' with plugins/search-guard-2/sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'rolesmapping' with plugins/search-guard-2/sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'internalusers' with plugins/search-guard-2/sgconfig/sg_internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update 'actiongroups' with plugins/search-guard-2/sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated

FAIL: Expected 5 config types for node 4EdmSODQRJ-mBc_eWrRF-g but got only []
Done with failures

Thank you 
B

**Comment by floragunncom** [comment]
Can you pls provide the following infos:

* Operating system vendor and version
* Do you run elasticsearch within a cloud environment (aws, ...)
* Java version and vendor
* Complete elasticsearch logfiles (every node) on DEBUG level (from elasticsearch start until sgadmin is finished/fails)

Seems to be a duplicate or at least related to https://github.com/floragunncom/search-guard/issues/182

**Comment by bujarmetaj2016** [comment]
Hi, 
Thank you for your fast reply and for your help.

OS X El Capitan 10.11.4
bento/centos-6.7
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)
[elasticsearch.log.zip](https://github.com/floragunncom/search-guard/files/436516/elasticsearch.log.zip)

Thanks
B

**Comment by bujarmetaj2016** [comment]
Hi,
Thanks for fast reply and for your help!

OS X El Capitan 10.11.4
bento/centos-6.7
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)

Thanks
B

**Comment by floragunncom** [comment]
Seems we found the issue but we cannot reproduce the issue locally so we kindly ask you if you can test https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-2/2.3.5.6-SNAPSHOT/search-guard-2-2.3.5.6-20160826.200736-47.zip and report back if the problem persists or is gone. It was likely a nasty threading issue. Thanks in advance.

**Comment by floragunncom** [comment]
Fixed (in master).
