### ISSUE TITLE
Custom settings for searchguard index

### ISSUE THREAD

**Issue by ericofusco** [floragunncom/search-guard#204]
I'm wondering if it's possible to define settings for searchguard index that's created by the plugin. I'd like to explicitly define the number of replicas based on my business requirements. 

I had 1 node running when I first installed SG, then I added one replica and shutdown my master for testing and I noticed my cluster with red status because searchguard index didn't have any replicas. I believe it should have a setting for that.

Thanks in advance.

**Comment by ewolinetz** [comment]
#176 
#197

**Comment by floragunncom** [comment]
Replica adjustment is already possible with sgadmin and you should have always as many replicas as datanodes-1 for the searchguard index.

**Comment by floragunncom** [comment]
Incidentally, we published a blog post about this just yesterday: https://floragunn.com/search-guard-index-replica-shards/

**Comment by ericofusco** [comment]
Thank you. It worked as expected.
