### ISSUE TITLE
Setting an Authorization header in transport client requests

### ISSUE THREAD

**Issue by mostrilla** [floragunncom/search-guard#207]
Hello,
we have a Java application that exposes a REST API and connects to ElasticSearch through a TransportClient; the REST API supports HTTP Basic authentication.

When connecting to a Shield cluster, we can use a client certificate with minimal privileges to authenticate the transport client and pass through the HTTP Authorization header to impersonate the user that made a request to the REST API.

How can we do the same in SearchGuard? We can't impersonate any user without validating the credentials, and we can't validate the credentials on the Elasticsearch HTTP interface as it is not always available.

**Comment by floragunncom** [comment]
When connecting via transport client you can add a "sg_impersonate_as" header. You do not need a password here but you need to allow the impersonation in the elasticsearch.yml file (wildcards supported).

See here how it works:
* https://github.com/floragunncom/search-guard/blob/master/src/test/java/com/floragunn/searchguard/SGTests.java#L869

* https://github.com/floragunncom/search-guard/issues/53#issuecomment-217019746

Does this fit your needs? If not pls. tell us whats missing.

**Comment by mostrilla** [comment]
In our test environment we are storing users in SearchGuard, so when our HTTP API receives a request with an `Authorization` header we would need SearchGuard to process it; basically we are trying to use SearchGuard both to restrict Elasticsearch access and as an authentication backend.

We could validate the credentials by making a an HTTPS request to `_searchguard/authinfo` containing the `Authorization` header received by our API, then impersonate the user in the transport client if the request is successful, but that requires:

- a client certificate that can impersonate multiple users, which we would prefer to avoid
- enabling HTTP on Elasticsearch, which we would like to be optional

We know that it's kind of an hack to pass the `Authorization` header on the transport channel to override the client certificate identity, as implemented by Shield, but it is useful in cases like ours where multiple users share a common transport client.

**Comment by floragunncom** [comment]
Can your check if this build works for you: https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-2/2.4.0.6klokh-SNAPSHOT/search-guard-2-2.4.0.6klokh-20160918.175633-1.zip

``.putHeader("Authorization", "basic "+encodeBasicHeader("username", "password"))``

with 

<pre>
public static String encodeBasicHeader(final String username, final String password) {
        return new String(DatatypeConverter.printBase64Binary((username + ":" + Objects.requireNonNull(password)).getBytes(StandardCharsets.UTF_8)));
    }
</pre>

**Comment by mostrilla** [comment]
Hi,
I tried your build and it works fine 👍
