### ISSUE TITLE
Error whith _upgrade API

### ISSUE THREAD

**Issue by f0r3st** [floragunncom/search-guard#208]
Hello,

When trying to upgrade indices after an upgrade of ES, I received the following error:
{"error":{"root_cause":[{"type":"exception","reason":"unauthenticated request internal:indices/admin/upgrade for user User [name=_sg_internal, roles=[]]"}],"
type":"exception","reason":"unauthenticated request internal:indices/admin/upgrade for user User [name=_sg_internal, roles=[]]"},"status":500}

Upgrade command:
curl -u user:password -XPOST "http://server:9200/*/_upgrade" --verbose

It seems that the internal user account is not allowed to execute upgrade command.

**Comment by floragunncom** [comment]
thx, good catch
