### ISSUE TITLE
It seems host authentication can not work together with the other authentication method!

### ISSUE THREAD

**Issue by woodkan** [floragunncom/search-guard#214]
ES Version: 2.4.0
Search Guard SSL : 2.4.0.16
search Guard 2     : 2.4.0.6

I tested the host authentication method, it seems that it can not work together with the other method!

I configure the SG with internal users first, and it works well. then I tried to enable host authentication with the lower order, then the host authentication take affective, I can access ES form the host , but the internal users can not access ES now. below is the error messages: 

> [root@tk-mgr-elk224

 sgconfig]# curl -u admin:admin http://192.168.7.220:9200/_cat/health?pretty
{
  "error" : {
    "root_cause" : [ {
      "type" : "security_exception",
      "reason" : "no permissions for cluster:monitor/health"
    } ],
    "type" : "security_exception",
    "reason" : "no permissions for cluster:monitor/health"
  },
  "status" : 403
}

After i disable host authentication, all work well agagin. 

below is my configuration for host authentication:

>  authc:
>       basic_internal_auth_domain:
>         enabled: true
>         order: 2
>         http_authenticator:
>           type: basic
>           challenge: true
>         authentication_backend:
>           type: intern
>       host_auth_domain:
>         enabled: true
>         order: 1
>         http_authenticator:
>           type: host
>           challenge: false
>         authentication_backend:
>           type: noop

**Comment by floragunncom** [comment]
Can you please post your sg_roles_mapping.yml file?

**Comment by woodkan** [comment]
below is my sg_roles_mapping.yml

> 
# In this file users, backendroles and hosts can be mapped to search guard roles.
# What a role is allowed to do you specify in sg_roles.yml

sg_role_starfleet:
  backendroles:
    - starfleet
    - captains
    - defectors
    - 'cn=ldaprole,ou=groups,dc=example,dc=com'
  hosts:
    - "*.starfleetintranet.com"
  users:
    - worf

sg_role_starfleet_captains:
  backendroles:
    - captains

sg_role_klingons1:
  backendroles:
    - klingon
  hosts:
    - "*.klingongov.kli"
  users:
    - worf

sg_logstash:
  users:
    - logstash
    
sg_kibana4_server:
  users:
    - kibanaserver
    
sg_kibana4:
  users:
    - kibanaro

sg_all_access:
  hosts:
    - 192.168.7.220
  users:
    - admin
    - adm
    - jianwu

sg_network:
  users:
    - test1

sg_sysadm:
  users:
    - test2
    
#sg_public:
#  users:
#    - '*'
    
sg_readall:
  users:
    - readall
    - riker
    - troid
    
sg_readonly_dlsfls:
  users:
    - dlsflsuser
    
sg_kibana4_testindex:
  users:
    - test

**Comment by woodkan** [comment]
Below is my sg_roles_mapping.yml

> 
sg_role_starfleet:
  backendroles:
    - starfleet
    - captains
    - defectors
    - 'cn=ldaprole,ou=groups,dc=example,dc=com'
  hosts:
    - "*.starfleetintranet.com"
  users:
    - worf
sg_role_starfleet_captains:
  backendroles:
    - captains
sg_role_klingons1:
  backendroles:
    - klingon
  hosts:
    - "*.klingongov.kli"
  users:
    - worf
sg_logstash:
  users:
    - logstash  
sg_kibana4_server:
  users:
    - kibanaserver
sg_kibana4:
  users:
    - kibanaro
sg_all_access:
  hosts:
    - 192.168.7.220
  users:
    - admin
    - adm
    - jianwu
sg_network:
  users:
    - test1
sg_sysadm:
  users:
    - test2  
sg_public:
  users:
    - '*'
sg_readall:
  users:
    - readall
    - riker
    - troid
sg_readonly_dlsfls:
  users:
    - dlsflsuser
sg_kibana4_testindex:
  users:
    - test

**Comment by floragunncom** [comment]
if you configure something like
<pre>
sg_all_access:
  hosts:
     - 192.168.7.220
</pre>
you do not need the 

<pre>
http_authenticator:
  type: host
</pre>

I guess we need to make this more clear in the documentation how the host authentication is supposed to work and when ``http_authenticator: type: host`` is really needed.

**Comment by woodkan** [comment]
I did not understand clearly.  I enable host authentication, and remove `http_authenticator: type: host". Then the internal authentication can work, but I can not access ES from 192.168.7.220

**Comment by floragunncom** [comment]
we will deprecate `http_authenticator: type: host` cause its not really needed.
Something like

<pre>
sg_role1:
  hosts:
     - 192.168.7.220
     - *.example.com
  users:
     - myuser
  backendroles:
     - myrole 
</pre>

will grant `sg_role1` for all users who are 'myuser' or have the backendrole 'myrole' or for all other users/roles if the request is originally coming from the ip 192.168.7.220 (or from any host in the domain example.com)

**Comment by floragunncom** [comment]
@woodkan will close this issue. If you still have problems pls. open a new issue and reference this one.
