### ISSUE TITLE
logstash can't connect to ES.

### ISSUE THREAD

**Issue by SkyBridge007** [floragunncom/search-guard#215]
version:   Search Guard Bundle builds on Elasticsearch 2.4.0.
logstash: 2.4.0

logstash.conf
```
output{
    elasticsearch{
        hosts => ["10.73.44.100:9200"]
	password => logstash
	ssl => true
	ssl_certificate_verification => true
	truststore => "/apps/searchguardbundle/searchguard-client/plugins/search-guard-2/sgconfig/truststore.jks"
	truststore_password => changeit
	user => logstash
        index => "logstash-%{+YYYY.MM.dd}"
        document_type => "document"
        workers => 1
        flush_size => 20000
        idle_flush_time => 10
        template_overwrite => true
    }
    stdout{
       codec=>rubydebug
     }
}
```

logstash start error log:

`
Pipeline aborted due to error {:exception=>"Java::JavaIo::IOException", :backtrace=>["sun.security.provider.JavaKeyStore.engineLoad(sun/security/provider/JavaKeyStore.java:772)", "sun.security.provider.JavaKeyStore$JKS.engineLoad(sun/security/provider/JavaKeyStore.java:55)", "java.security.KeyStore.load(java/security/KeyStore.java:1445)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)", "RUBY.get_store(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:667)", "org.jruby.RubyKernel.tap(org/jruby/RubyKernel.java:1858)", "RUBY.get_store(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:665)", "RUBY.setup_trust_store(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:609)", "RUBY.ssl_socket_factory_from_options(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:602)", "RUBY.pool_builder(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:394)", "RUBY.pool(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:402)", "RUBY.initialize(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:208)", "RUBY.build_client(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:58)", "RUBY.initialize(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:49)", "RUBY.initialize(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/client.rb:118)", "RUBY.new(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport.rb:26)", "RUBY.build_client(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:129)", "RUBY.initialize(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20)", "RUBY.build(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:44)", "RUBY.build_client(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch.rb:134)", "RUBY.register(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:14)", "RUBY.register(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/output_delegator.rb:75)", "RUBY.start_workers(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)", "RUBY.start_workers(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181)", "RUBY.run(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136)", "RUBY.start_pipeline(/Users/wuhu/apps/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491)", "java.lang.Thread.run(java/lang/Thread.java:745)"], :level=>:error}
`

**Comment by floragunncom** [comment]
seems the truststore password is incorrect, see http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/security/provider/JavaKeyStore.java/#772

If you are using the bundle look into the elasticsearch.yml file for the correct password

**Comment by floragunncom** [comment]
does this fixed your issue?

**Comment by floragunncom** [comment]
no feedback, assume issue is solved. If not pls. reopen or file another issue.
