### ISSUE TITLE
Bad SHA-256 checksum for Search Guard Bundle tar.gz

### ISSUE THREAD

**Issue by nicolas-moteau** [floragunncom/search-guard#216]
On page https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle ,
the SHA-256 checksum of https://floragunn.com/downloads/elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz is incorrect :
SHA-256 checksum: b64e4c77972c131a0d461bcc5b1fb68795556235451385dd09d5f4d292b4db38

I got
```
$ sha256sum elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz
c3d5904f8341a2c5bd07474f64304d9aec135342f30a25eaa9f69789505df623  elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz
```

**Comment by floragunncom** [comment]
I just tried to reproduce:

- went to https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle 
- downloaded https://floragunn.com/downloads/elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz
- checksummed

$sha256sum elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz 
b64e4c77972c131a0d461bcc5b1fb68795556235451385dd09d5f4d292b4db38  elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz

Are you sure the tgz was downloaded correctly?

**Comment by nicolas-moteau** [comment]
Well... I only have the problem when downloading the file with my browser...
```
wget https://floragunn.com/downloads/elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz
$ sha256sum elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz 
b64e4c77972c131a0d461bcc5b1fb68795556235451385dd09d5f4d292b4db38  elasticsearch-76EDC0BB-9A7E-40BE-96B6-67872AB3D965.tar.gz
```
Strange behavior, but definitively not an issue on your side. I close the issue.
Thanks.
