### ISSUE TITLE
Search Guard says Open SSL is not available, even though it is

### ISSUE THREAD

**Issue by cfoutstd** [floragunncom/search-guard#219]
SG v2.4.0.7
CentOS 7

I see the following log

`[2016-10-13 16:01:03,921][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL`

Even though I see

```
[root@ip-10-22-x-x elasticsearch]# which openssl
/bin/openssl
[root@ip-10-22-x-x elasticsearch]# rpm -qa | grep openssl
openssl-libs-1.0.1e-51.el7_2.7.x86_64
openssl-1.0.1e-51.el7_2.7.x86_64

```

**Comment by floragunncom** [comment]
Pls read the [documentation](https://github.com/floragunncom/search-guard-ssl-docs/blob/master/openssl.md) and/or ask questions here https://groups.google.com/forum/#!forum/search-guard

github issues are reserved for bugs and feature requests

**Comment by cfoutstd** [comment]
This was meant to be a bug report.

**Comment by bobymicroby** [comment]
We have the same issue on CentOS 7.2.
```
which openssl
/usr/bin/openssl
```

```
rpm -qa | grep openssl
openssl-libs-1.0.1e-51.el7_2.7.x86_64
openssl-1.0.1e-51.el7_2.7.x86_64
```

**Comment by floragunncom** [comment]
@cfoutstd @bobymicroby did you install the netty tcnative dynamic or statically linked library as described here: https://github.com/floragunncom/search-guard-ssl-docs/blob/master/openssl.md ?

**Comment by cfoutstd** [comment]
Steps in the link you posted fixed this for me. Thanks!

**Comment by bobymicroby** [comment]
And using Fedora tentative did it for me
