### ISSUE TITLE
Searchguard plugin and Elasticsearch Client such as: NEST, Elasticsearch.angular,js

### ISSUE THREAD

**Issue by LinhTruongVan** [floragunncom/search-guard#22]
Hey everybody,
I'm facing with some troubles. When i access to elasticsearch index, i'm using syntax following:
http://username:password@localhost:9200/myindex/_search
But, i don't know how to access elasticsearch with elasticsearch client such as: Nest, elasticsearch.angular.js.
And can't i use some syntax:  http://localhost:9200/myindex/_search@username:password or something like that to work with RESTful API ?.

Best regards,
TVL

**Comment by floragunncom** [comment]
If the desired client supports somehow HTTP Basic authentication it should work. If not then you can't use this client. Pls. consult the respective client documentation. Maybe this helps you: https://www.elastic.co/guide/en/shield/current/_http_rest_clients.html
