### ISSUE TITLE
No permissions for indices:data/read/search

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#220]
Hello,

My configuration is the following:
JDK 1.8
SearchGuard 2.4.1.7
ElasticSearch 2.4.1
Kibana 4.6
Number of nodes: 1 (this is test server).

I am trying to restrict the access for different roles to different index names. For examples, the role A will have access only to indices logstash-syslog\* while the role B only to indices logstash-audit*, etc.

Below is the configuration:

sg_role_roleb:
  indices:
    '_':
      '_':
        - indices:data/read/field_stats
        - indices:data/read/msearch
    'logstash-syslog_':
      '_':
        - '_'
    '?kibana':
      '_':
        - READ
        - "indices:_"
        - indices:admin/exists_
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/mappings/fields*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/read/field_stats*
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*

I use internal user authorization. The user that belongs to the defined role is successfully authenticated via Kibana, Kibana correctly displays logs from the file which was defined by for this role. However, Kibana displays "No permissions for indices:data/read/search" error.

Log file contains the following message:
[2016-10-17 22:11:24,771][INFO ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] No perm match for indices:data/read/search and [sg_role_roleb]

Am I doing something wrong? Would you please help me with this problem?

Thank you,
Armenak

**Comment by floragunncom** [comment]
why not just adding ``indices:data/read/search`` to ``sg_role_roleb``

**Comment by armenak** [comment]
Because in this case the second index will be accessible via Kibana. I tested this scenario.

Perhaps I was not to clear yesterday. Here is the scenario (simplified). There are two roles: RoleA and RoleB. And there are two indices: IndexA and IndexB. I want to give access to IndexA only for RoleA and access to IndexB only to RoleB.

If I add indices:data/read/search to sg_role_roleb such as below
'':
'':
- indices:data/read/field_stats
- indices:data/read/msearch
- indices:data/read/search

then users will be able to see the documents from both indices.

**Comment by floragunncom** [comment]
pls post you complete sg_roles.yml and sg_roles_mapping.yml

**Comment by armenak** [comment]
sg_roles_mapping.yml
---
sg_role_starfleet:
  backendroles:
    - starfleet
    - captains
    - defectors
    - 'cn=ldaprole,ou=groups,dc=example,dc=com'
  hosts:
    - "*.starfleetintranet.com"
  users:
    - worf

sg_role_captains:
  backendroles:
    - captains

sg_role_lms:
  backendroles:
    - lms

sg_role_nmc:
  backendroles:
    - nmc

sg_role_as:
  backendroles:
    - as

sg_role_klingons1:
  backendroles:
    - klingon
  hosts:
    - "*.klingongov.kli"
  users:
    - worf

sg_logstash:
  users:
    - logstash

sg_kibana4_server:
  users:
    - kibanaserver

sg_kibana4:
  users:
    - kibanaro

sg_all_access:
  users:
    - admin
    - adm

#sg_public:
#  users:
#    - '*'

sg_readall:
  users:
    - readall
    - riker
    - troid

sg_readonly_dlsfls:
  users:
    - dlsflsuser

sg_kibana4_testindex:
  users:
    - test

#sg_own_index:
#  users:
#    - '*'


sg_roles.yml
---
# Allows everything
# but not changes to searchguard config/index
sg_all_access:
  cluster:
    - '*'
  indices:
    '*':
      '*':
        - '*'

sg_role_lms:
  indices:
    'logstash-*':
      '*':
         - '*'
      _dls_: '{"term" : {"_type" : "audit"}}'
      _fls_:
        - '@timestamp'
        - 'path'
        - 'type'
    '?kibana':
      '*':
        - READ
        - indices:admin/exists*
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/mappings/fields*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/read/field_stats*
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*

sg_role_nmc:
  indices:
    'logstash-*':
      '*':
         - '*'
      _dls_: '{"term" : {"_type" : "syslog"}}'
    '?kibana':
      '*':
        - READ
        - indices:admin/exists*
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/mappings/fields*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/read/field_stats*
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*

sg_role_as:
  indices:
    'logstash-syslog*':
      '*':
        - READ
        - indices:admin/mappings/fields/get*
        - indices:admin/validate/query
        - indices:admin/get
    '?kibana':
      '*':
        - indices:admin/exists*
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/read/msearch
        - indices:data/read/field_stats
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*
        - indices:admin/mappings/fields/get*

sg_readonly_and_monitor:
  cluster:
    - CLUSTER_MONITOR
  indices:
    '*':
      '*':
        - ALL

sg_readall:
  indices:
    '*':
      '*':
        - READ
sg_readonly_dlsfls:
  indices:
    '/\S*/':
      '*':
        - READ
      _dls_: '{"term" : {"_type" : "legends"}}'
      _fls_:
        - 'aaa'
        - 'bbb'

sg_transport_client:
  cluster:
      - cluster:monitor/nodes/liveness
      - cluster:monitor/state

sg_kibana4:
  indices:
    '*':
      '*':
        - READ
        - indices:admin/mappings/fields/get*
        - indices:admin/validate/query*
        - indices:admin/get*
    '?kibana':
      '*':
        - indices:admin/exists*
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*

sg_kibana4_testindex:
  indices:
    'test*':
      '*':
        - READ
        - indices:admin/mappings/fields/get*
        - indices:admin/validate/query*
        - indices:admin/get*
    '?kibana':
      '*':
        - indices:admin/exists*
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*

sg_kibana4_server:
  cluster:
      - cluster:monitor/nodes/info
      - cluster:monitor/health
  indices:
    '?kibana':
      '*':
        - "indices:*"

sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    'logstash-*':
      '*':
        - CRUD
        - CREATE_INDEX
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX

# Allows each user to access own named index
sg_own_index:
  indices:
    '${user_name}':
      '*':
        - ALL

**Comment by armenak** [comment]
Please find attached. Basically the problem with the role sg_role_as. According to test scenario, I'd like members of this group see the documents only from indices ogstash-syslog*. Kibana does show the correct set of document, but displays "No permissions for indices:data/read/search" error.

[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/543519/sg_roles.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/543520/sg_roles_mapping.yml.txt)

**Comment by phamthanhnhan14** [comment]
Did you fix it bro?
Please update this issue with your solutions.
Thanks,

**Comment by armenak** [comment]
Any update on this issue?

**Comment by floragunncom** [comment]
So looking on you config the role ``sg_role_as`` include the ``indices:data/read/search`` permission for all ``logstash-syslog*`` indices. Can you post your complete logfile?

If a user is really a member of role  ``sg_role_as`` you should not get an exception for ``indices:data/read/search``. But Kibana does normally issue a msearch request which makes it a little more tricky. We also work on something in the moment that maybe be related: https://github.com/floragunncom/search-guard/commit/da712ac7c427bb26aba653c7389305fb359b667f

**Comment by armenak** [comment]
The complete logfile is too large. I extracted relevant log entries. The user name I use for testing is "armenak" and the role name is "as". Please see the log entries below. I think the problem is in "No wildcard match found for ..."  messages, but I can't figure out why. Want to repeat, that the data wise, Kibana returns correct result, but there is a annoying message which appears in Kibana complaining about "No permissions for indices:data/read/search" .


[elasticsearch.txt](https://github.com/floragunncom/search-guard/files/579668/elasticsearch.txt)

**Comment by armenak** [comment]
Any update regarding this issue?

**Comment by floragunncom** [comment]
We're on in ... (little bit busy because of ES 5 release)

**Comment by floragunncom** [comment]
Catching now up on this (sorry for the delay).

There is no `No perm match for indices:data/read/search` message in the logfile you posted here: https://github.com/floragunncom/search-guard/issues/220#issuecomment-259301289

**Comment by armenak** [comment]
I started using ES5 and SG5. Should I open another issue?

**Comment by floragunncom** [comment]
do you have the same issue also for SG5? then yes please

**Comment by floragunncom** [comment]
can we close this?

**Comment by armenak** [comment]
Yes, please.
