### ISSUE TITLE
Kibana problem  

### ISSUE THREAD

**Issue by 478682649** [floragunncom/search-guard#224]
Hi  all, 
  I use search guard to protect elasticsearch,my index like this : 
http-3-2015-10-20,
http-2-2015-10-20,
http-1-2015-10-20,
So,I write sg_roles :

 12 administrators:
 13   indices:
 14     '*':                   
 15       '*':
 16         - KIBANA_USER      
 17     '?kibana':
 18       '*':
 19         - KIBANA_SERVER
 20 
 21 developers:
 22   indices:
 23     '*-3-*':
 24       '*':
 25         - KIBANA_USER
 26         - indices:data/read/search      
 27     '?kibana':
 28       '*':
 29         - KIBANA_SERVER

When I use the developer's user to login, but kibana will report  I need add "indices:data/read/field_stats" for developer?  why ?
And I want also kown ,what's user  should I write the in kibana ,to conntect the elasticsearch?

**Comment by floragunncom** [comment]
Please use github only for reporting bugs, and use our Google Group for asking installation and configuration questions: https://groups.google.com/forum/#!forum/search-guard
