### ISSUE TITLE
How Search Guard Security Plugin Works ?

### ISSUE THREAD

**Issue by LinhTruongVan** [floragunncom/search-guard#23]
Hi @floragunncom ,

In my opinon, Search Guard Security Plugin is too interesting. I'm very curious about how Search Guard Security Plugin process the request, how it process the token of user,why user only need to login once, how to logout,..... In your github, i saw a short description with title "How its works", but i want to get more information about its.
Could you explain me in detail  how Search Guard Security Plugin  works ? 
Thanks you so much :)

**Comment by floragunncom** [comment]
this is not an issue, pls. ask this kind of questions on the mailing list https://groups.google.com/forum/#!forum/search-guard , thanks
