### ISSUE TITLE
search-guard-5 not on maven repository

### ISSUE THREAD

**Issue by ericofusco** [floragunncom/search-guard#230]
ElasticSearch 5.0.0
Search Guard 5.0.0-8

When I try to run elasticsearch-plugin install I get the following error.

Full command: /usr/share/elasticsearch/bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.0.0-8

Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/floragunn/search-guard-5/5.0.0-8/search-guard-5-5.0.0-8.zip

I checked repository and floragunn doesn't exist under com folder.

**Comment by floragunncom** [comment]
Because it's not released yet :-) Expect it by end of this week.

**Comment by ericofusco** [comment]
Thanks @floragunncom, looking forward to it.
