### ISSUE TITLE
no permissions for indices:admin/mappings/get 

### ISSUE THREAD

**Issue by asantoso** [floragunncom/search-guard#233]
no permissions for indices:admin/mappings/get even though using admin/admin as user.

**Comment by jochenkressin** [comment]
Please follow our guidelines when issuing a bug report, you provided far too few information in order for us to say anything about it:

**Comment by jochenkressin** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place only for reporting bugs or feature requests.
If you report a bug please include always the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
