### ISSUE TITLE
 The roles are not picking though the user is been assigned to role

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#235]
Hello SearchGuard,

My environment is:
Java 1.8
RedHat 7
ElasticSearch 5
SearchGuard 5

With SG2 I was able to successfully configure authorization, but I can't do the same with SG5. Since the documentation stays that the same configuration files can be used for SG5 I copied configuration files after I installed SG5.

The error I am getting is:

[RolesChecked [sg_kibana4_server]]
[2016-11-20T14:45:19,418][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=kibanaserver, roles=[]] [IndexType [index=_all, type=*]] [Action [cluster:monitor/main]] [RolesChecked [sg_kibana4_server]]

Configuration files are attached.

Please help. We plan to use SG5 in production and this issue prevents us from going live. We have a commercial license and would like to use LDAP in future, but I'd like to test SG5 with internal user database.

Regards,
Armenak

[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/602402/sg_roles.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/602403/sg_config.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/602404/sg_roles_mapping.yml.txt)

**Comment by armenak** [comment]
Update on this issue. I was able to make Kibana work by using default "kibanaserver" password, rather than the one I generated using hash.sh script. I am able to login using admin/admin.

Now the challenge to make logstash work. Below is my logstash configuration:
output {
    elasticsearch {
       hosts => ["host_name"]
       user => logstash
       password => logstash
       index => "logstash-%{type}-%{+YYYY.MM.dd}"
       #ssl => true
       #ssl_certificate_verification => true
       #truststore => "/path/to/elasticsearch-2.3.3/config/truststore.jks"
       #truststore_password => changeit
    }
}

I am seeing the following error in logstash logs: 
[ERROR][logstash.outputs.elasticsearch] Got a bad response code from server, but this code is not considered retryable. Request will be dropped {:code=>403}

In ElasticSearch I see the following error:
[INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=logstash, roles=[]] [IndexType [index=logstash-audit-2016.11.21, type=audit]] [Action [indices:data/write/bulk]] [RolesChecked [sg_logstash, sg_own_index, sg_public]]

The only was I was able to make LogStash work is by assigning logstash user to the group sg_all_access.

The configuration files the same as attached above. I just modified sg_logstash role as follow:
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    'logstash-*':
      '*':
        - indices:data/write/bulk
        - indices:data/write/bulks
        - indices:data/write/delete
        - indices:data/write/update
        - indices:data/read/search
        - indices:data/read/scroll
        - CRUD
        - CREATE_INDEX
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX

I am new to ES5 and was surprised that index names are created using random characters (or hash values?). I should have indexes such as logstash-audit-* or logstash-syslog-*. However, I see the following names:
3Hfq0641RKGCSCHGcnur-Q  
Bghul_MkT5upn6qx5bRCWw  
Ejms7ZIKRkSKNyawM0beQQ  
hqgz5UKxTn2tzLAUfZV7lg  
nzV_woNSTUmaA0OBTImJBw  
_thpvwxPS0i-nSRy0tURFw

Is it possible that the issue with ES index names cause the problem?

**Comment by halleys** [comment]
Hi,

I also faced a similar issue. I am using ES 2.4.0 + corresponding version of SearchGuard & SearchGaurd-SSL and it is working fine. 
Now I am testing ES5 + SearchGaurd 5:5.0.0-8. For the test I used same SearchGaurd configurations.
When I started Kibana, I encountered a permission error.
So I simplified configurations and conducted some tests. 
This is a sg_roles.yml and my 'admin' user belongs to the 'all_access':
```yaml

all_access:
  cluster:
    - CLUSTER_ALL
  indices:
    '*':
      '*':
        - "indices:*"
    '?kibana':
      '*':
        - "indices:*"

```

I updated SG index with SG admin tool and when refreshing my Kibana page, I found this error in the ES logs:
```
[2016-11-22T12:50:41,179][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=admin, roles=[]] [IndexType [index=.kibana, type=index-pattern]] [Action [indices:data/read/mget]] [RolesChecked [all_access]]
[2016-11-22T12:51:43,500][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=admin, roles=[]] [IndexType [index=.kibana, type=index-pattern]] [Action [indices:data/read/mget]] [RolesChecked [all_access]]

```

Please advice me if there is any issue in my configuration or SearchGaurd. 

Youngmi

**Comment by armenak** [comment]
Any update regarding this issue?

**Comment by floragunncom** [comment]
Can you please try to add the following privileges to the cluster section:

  cluster:
      - indices:data/read/mget*      
      - indices:data/read/msearch* 

And let us know if this helped?

**Comment by halleys** [comment]
@floragunncom 

It woks for me! thank you for advice.

**Comment by floragunncom** [comment]
we updated the default config https://github.com/floragunncom/search-guard/commit/744a729a30538073b425a6e8975bb78688c24e4a

**Comment by armenak** [comment]
Kibana issue was resolved. Thanks. 

However, I am facing the problem with LogStash. It was working with 2.4 perfectly fine. 

The configuration on SG side was attached in my previous comment. Copying my LogStash configuration:

output {
    elasticsearch {
       hosts => ["<host_name>"]
       user => logstash
       password => logstash
       index => "logstash-%{type}-%{+YYYY.MM.dd}"
       #ssl => true
       #ssl_certificate_verification => true
       #truststore => "/path/to/elasticsearch-2.3.3/config/truststore.jks"
       #truststore_password => changeit
    }
}

**Comment by floragunncom** [comment]
can you try adding `- "indices:data/write/bulk*"` to cluster privileges of `sg_logstash`?

**Comment by armenak** [comment]
I've tried it, but still does not work.

Here is my sg_logstash role:
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    'logstash-*':
      '*':
        - CRUD
        - CREATE_INDEX
        - indices:data/write/bulk*
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX



And here are the messages I am getting:

[2016-12-01T20:52:55,722][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=logstash, roles=[]] [IndexType [index=logstash-syslog-2016.12.02, type=syslog], IndexType [index=logstash-syslog-2016.12.02, type=audit], IndexType [index=logstash-audit-2016.12.02, type=syslog], IndexType [index=logstash-audit-2016.12.02, type=audit]] [Action [indices:data/write/bulk]] [RolesChecked [sg_logstash, sg_own_index, sg_public]]

[2016-12-01T20:52:56,437][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=logstash, roles=[]] [IndexType [index=logstash-audit-2016.12.02, type=audit]] [Action [indices:data/write/bulk]] [RolesChecked [sg_logstash, sg_own_index, sg_public]]

**Comment by floragunncom** [comment]
what i meant was

<pre>
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
    - indices:data/write/bulk* # < ---- need to be here for SG5
  indices:
    'logstash-*':
      '*':
        - CRUD
        - CREATE_INDEX
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX
</pre>

"can you try adding indices:data/write/bulk* to **cluster privileges** of sg_logstash?"

**Comment by armenak** [comment]
Thank you, this is working now with the change you suggested. It would be great to modify default configuration.

Now, back to end-user authorization. I am using standard configuration files and configured one role "sg_role_as" with one user "armenak". Configuration changes are below.
sg_role.yml

sg_roles_as:
  indices:
    '*':
      '*':
        - READ
        - indices:admin/mappings/fields/get*
        - indices:data/read/msearch
        - indices:data/read/mget
        - indices:admin/validate/query
        - indices:admin/get
    '?kibana':
      '*':
        - indices:admin/exists*
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/read/msearch
        - indices:data/read/field_stats
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*
        - indices:admin/mappings/fields/get*

sg_roles_mapping.yml
sg_role_as:
  users:
    - armenak

I am getting the following error:
[INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=armenak, roles=[]] [IndexType [index=.kibana, type=index-pattern]] [Action [indices:data/read/mget]] [RolesChecked [sg_own_index, sg_public, sg_role_as]]

**Comment by armenak** [comment]
Any update on this issue?

**Comment by armenak** [comment]
Any update on this issue?

**Comment by floragunncom** [comment]
same story, try adding `indices:data/read/mget` to cluster privileges.

All composite actions like bulk, mget, msearch etc need to be granted on cluster level since SG 5.

**Comment by floragunncom** [comment]
does this work? can this issue be closed?

**Comment by armenak** [comment]
Please do not close this issue yet. I will test issue #252 tomorrow. If it works, than this issue also can be closed.

**Comment by armenak** [comment]
Issue #252 is still not working.

**Comment by floragunncom** [comment]
ping

**Comment by armenak** [comment]
Sorry for the delay. Please give me one more day.

**Comment by armenak** [comment]
This issue depends whether #252 will be resolved. As soon as #252 is resolved, I will be able to this this one.

**Comment by floragunncom** [comment]
@armenak can we close this issue?

**Comment by armenak** [comment]
Not yet.

**Comment by armenak** [comment]
you can close this issue. thank you.

**Comment by floragunncom** [comment]
you are also allowed to close it :-)
