### ISSUE TITLE
SearchGuard index name

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#236]
In SG2, the index name where SG stored its configuration was "searchguard". In SG5 the name is created using random characters. The option "-i" in SGAdmin, which suppose to create custom index name is not working. Is this behavior intentional? I think it would be great to give more freedom in choosing SearchGuard index name.

**Comment by floragunncom** [comment]
No, this is not intentional, thanks for reporting, we'll investigate.

**Comment by armenak** [comment]
Any update on this issue?

**Comment by floragunncom** [comment]
Cannot reproduce. Can you provide your elasticsearch.yml as well as the command line statements you executed? Elasticsearch logfile might also be useful to investigate this a bit deeper.

**Comment by armenak** [comment]
I've installed ES 5.0.2 from scratch and started sending logs using LogStash. Same symptoms. Index names are: "_hgol5W2T76PD8G5xU-u5Q" (Kibana) and "lbVivZmKQuy3bjatdKQSIw".

elasticsearch.yml is attached.

[elasticsearch.yml.txt](https://github.com/floragunncom/search-guard/files/633070/elasticsearch.yml.txt)

**Comment by floragunncom** [comment]
There is no searchguard configuration contained in this elasticsearch.yml

**Comment by armenak** [comment]
Yes, I have installed ES from scratch and still see this issue. Any ideas
what could cause ES to "hash" index names?

**Comment by floragunncom** [comment]
can you provide a screenshot or something like this where we can see the "hashed" index names?

**Comment by armenak** [comment]
Snapshot is attached.
![screen shot 2016-12-10 at 10 01 45 pm](https://cloud.githubusercontent.com/assets/3421052/21078454/733a77c8-bf24-11e6-9997-7e540a941502.png)

**Comment by floragunncom** [comment]
Now i get it. But the folder name on the file system has nothing to do with the logical index name. This changed in Elasticsearch 5 and has nothing to do with Search Guard.

Look into <hashid>/_state/state* files (binary), there you should see the real index name

**Comment by armenak** [comment]
Thank you.
