### ISSUE TITLE
[Search Guard 5]  Subparagraph to "Dynamic configuration"

### ISSUE THREAD

**Issue by Basek** [floragunncom/search-guard#237]
Add, please, subparagraph to "Dynamic configuration" on quick start page that for apply the configuration need run from cmd

plugins\search-guard-5\tools\sgadmin.bat -ks plugins\search-guard-5\sgconfig\keystore.jks -kspass "keystore_password" -nhnv -ts plugins\search-guard-5\sgconfig\truststore.jks -cd plugins\search-guard-5\sgconfig\ -tspass "truststore_password"

and it is necessary to has a JAVA_HOME environment variable or set it by next cmd command (use set without parameters to look all of them)

set JAVA_HOME=C:\Program Files\Java\jre_installed_version

**Comment by floragunncom** [comment]
You can do this on your own. Just submit a pull request on the https://github.com/floragunncom/search-guard-docs project. 
We are happy to merge it.
