### ISSUE TITLE
search-guard installation fails in ES 2.4.1

### ISSUE THREAD

**Issue by neuronring** [floragunncom/search-guard#239]
I have downloaded the version 2.4.1.8 of searchguard .
`sudo bin/plugin install -b com.floragunn/search-guard-2/2.4.1.8`

and it fails to install saying 

> -> Installing from file:/app/v2.4.1.8.zip...
Trying file:/app/v2.4.1.8.zip ...
Downloading ..DONE
Verifying file:/app/v2.4.1.8.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by jochenkressin** [comment]
No need to download, you install Search Guard directly from Maven Central. From this:

-> Installing from file:/app/v2.4.1.8.zip...
Trying file:/app/v2.4.1.8.zip ...

I'm seeing that you try to install a zip file from a local directory. This is also possible, but you need the release zip file from Maven, not the sources from GitHub.

Anyways, this command:

sudo bin/plugin install -b com.floragunn/search-guard-2/2.4.1.8

fetches SG directly from Maven, and you should see an output like this:

sudo bin/plugin install -b com.floragunn/search-guard-2/2.4.1.8
Password:
-> Installing com.floragunn/search-guard-2/2.4.1.8...
Trying https://download.elastic.co/com.floragunn/search-guard-2/search-guard-2-2.4.1.8.zip ...
Trying https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-2/2.4.1.8/search-guard-2-2.4.1.8.zip ...
Downloading ..........DONE
Verifying https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-2/2.4.1.8/search-guard-2-2.4.1.8.zip checksums if available ...
Downloading .DONE
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission shutdownHooks
* javax.security.auth.AuthPermission doAs
* javax.security.auth.AuthPermission modifyPrivateCredentials
* javax.security.auth.kerberos.ServicePermission * accept
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Installed search-guard-2 into /Users/jkressin/Development/elasticsearch-2.4.1/plugins/search-guard-2

**Comment by jochenkressin** [comment]
See also the installation instructions in the documentation:

https://github.com/floragunncom/search-guard-docs/blob/master/installation.md
