### ISSUE TITLE
searchguard.authentication.settingsdb.digest does not work

### ISSUE THREAD

**Issue by sanori** [floragunncom/search-guard#24]
I have sha1sum the plain text password and added it as follows:
searchguard.authentication.settingsdb.digest: SHA1
searchguard.authentication.settingsdb._username_: _sha1hashed_password_
But it makes com.floragunn.searchguard.authentication.AuthException.

It seems that ```searchguard/authentication/backend/simple/SettingsBasedAuthenticationBackend.java```
should make digest for password (user input), not pass (hashed password in configuration).

**Comment by jbladen** [comment]
Did this fix not make it into the 1.7 branch? I have this issue with 1.7.3.
