### ISSUE TITLE
Support sg_impersonate_as header in REST requests

### ISSUE THREAD

**Issue by fabiocorneti** [floragunncom/search-guard#242]
HI,
would you consider supporting the `sg_impersonate_as` header in REST requests authenticated by a client certificate?
Our use case would be to impersonate specific users in a backend that does not have access to the transport port.

I did a rough test at https://github.com/fabiocorneti/search-guard/commit/07fdbb3890c871488251716d8d92d66852fac9a8 :

```
$ curl -k --cert ./config/localhost.pfx:password -H "sg_impersonate_as: iuser" https://localhost:9235/_searchguard/authinfo?pretty
{
  "user" : "User [name=iuser, roles=[]]",
  "remote_address" : "[::1]:49932",
  "sg_roles" : [ "iuser" ],
  "principal" : "CN=localhost",
  "peer_certificates" : "1"
}
```

**Comment by floragunncom** [comment]
thx, will look into this

**Comment by floragunncom** [comment]
For transport layer impersonation we require that the impersonated exists (that means that he must be known with the impersonated username in at least one of the configured authentication backends.  
Authorization will also be processed for the impersonated user to collect roles).

For rest layer impersonation this would make sense IMHO (for improved security as well as for to be consistent with transport layer authentication).

@fabiocorneti  Can you share your thoughts about this?

**Comment by fabiocorneti** [comment]
I agree with that requirement, when I did my quick test I just checked if the `impersonate` could work with Rest requests, looking better at the code I see that `authenticate` also retrieves the roles so impersonation should happen before that.

**Comment by floragunncom** [comment]
@fabiocorneti looks this good for you?: https://github.com/floragunncom/search-guard/commit/8ca333cc4c60149245409614c8f14f80d607a13a

**Comment by floragunncom** [comment]
ping

**Comment by floragunncom** [comment]
this comes with SG6

**Comment by floragunncom** [comment]
Done, see https://groups.google.com/forum/#!topic/search-guard/OdbGNIpkbzA
