### ISSUE TITLE
Redundant condition or mistake?

### ISSUE THREAD

**Issue by breml** [floragunncom/search-guard#248]
While reading the code, I found the following line in https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/configuration/PrivilegesEvaluator.java#L422

```
if (_requestedResolvedIndexTypes.isEmpty() && _requestedResolvedIndexTypes.isEmpty()) {
```

Either the condition is redundant and one part can be removed, or while implementing this condition, something got messed up and one part of the condition is currently missing.

**Comment by breml** [comment]
The relevant section has been changed in commit https://github.com/floragunncom/search-guard/commit/27676a2d9ef8a6d0b0facdbe35edc85a6786405b#diff-f415759448f2fef656c2b13769ce6b60.

The conditions was:
```
if (_requestedResolvedAliasesIndices.isEmpty() && _requestedResolvedTypes.isEmpty()) {
```

**Comment by floragunncom** [comment]
@breml good catch, thx
