### ISSUE TITLE
Search Guard Bundle: sgadmin not preconfigured anymore

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard#258]
In the 2.x series of the Search Guard Bundle, we shipped sgadmin.sh preconfigured with keystore, truststore, passwords etc. so you just needed to execute "./sgadmin.sh" (see also docs).

In the 5.x series, the command line options are missing, so you need to specify all parameters manually.

**Comment by floragunncom** [comment]
Not reproducible

<pre>
elasticsearch-5.0.0-sg5-40a219fb-7105-4283-b3bf-086d02b65720 cd searchguard-client
➜  searchguard-client ll
total 48
-rw-r--r--@  1 temp  staff    11K 26 Okt 06:35 LICENSE.txt
-rw-r--r--@  1 temp  staff   150B 26 Okt 06:35 NOTICE.txt
drwxr-xr-x@  5 temp  staff   170B 26 Okt 06:40 config
drwxr-xr-x@ 36 temp  staff   1,2K 26 Okt 06:40 lib
drwxr-xr-x@  3 temp  staff   102B 14 Nov 20:19 plugins
-rw-r--r--@  1 temp  staff   253B 14 Nov 20:19 sgadmin.bat
-rwxr-xr-x@  1 temp  staff   252B 14 Nov 20:19 sgadmin.sh
➜  searchguard-client ./sgadmin.sh
Search Guard Admin v5
Will connect to localhost:9300 ... done
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: elasticsearch
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
searchguard index does not exists, attempt to create it ... done (with 0 replicas, auto expand replicas is off)
Populate config from /Users/temp/Downloads/elasticsearch-5.0.0-sg5-40a219fb-7105-4283-b3bf-086d02b65720/searchguard-client/plugins/search-guard-5/sgconfig
Will update 'config' with plugins/search-guard-5/sgconfig/sg_config.yml
   SUCC: Configuration for 'config' created or updated
Will update 'roles' with plugins/search-guard-5/sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'rolesmapping' with plugins/search-guard-5/sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'internalusers' with plugins/search-guard-5/sgconfig/sg_internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update 'actiongroups' with plugins/search-guard-5/sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Done with success
</pre>

**Comment by jochenkressin** [comment]
Sorry, my fault, confused releases
