### ISSUE TITLE
"?pretty=true" does not work

### ISSUE THREAD

**Issue by kiblik** [floragunncom/search-guard#259]
When I change
```curl "http://XXX:YYY@ZZZ:9200/_searchguard/authinfo"```
to
```curl "http://XXX:YYY@ZZZ:9200/_searchguard/authinfo?pretty=true"```
text stay in one line. But in other queries (e.g. `curl "http://XXX:YYY@ZZZ:9200/_cluster/health?pretty=true"`), responses look _pretty_

ES 5.1.1
SG 5.1.1-10 from [https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-5/5.1.1-10-SNAPSHOT/search-guard-5-5.1.1-10-20161218.194423-1.zip](https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-5/5.1.1-10-SNAPSHOT/search-guard-5-5.1.1-10-20161218.194423-1.zip)

**Comment by floragunncom** [comment]
fixed
