### ISSUE TITLE
Can't connect to 9300

### ISSUE THREAD

**Issue by gelinger777** [floragunncom/search-guard#265]
Sgadmin.sh says it cannot connect to 9300. When even I specify -p 9200 it fails to connect and apply configs. What to do?

**Comment by floragunncom** [comment]
Pls read the [documentation](https://github.com/floragunncom/search-guard-docs) and/or ask questions here https://groups.google.com/forum/#!forum/search-guard

Github issues are reserved for bugs and feature requests

**Comment by gelinger777** [comment]
Your documentation when it comes to version 5.1.1 is very confusing and the group is silent.
https://groups.google.com/forum/#!topic/search-guard/k_4PJxQJ0-U here i have asked, nobody answered. Is that very hard to say how to overcome the issue?  cannot connect to 9300...
