### ISSUE TITLE
allow certificate mapping to fields like msUPN

### ISSUE THREAD

**Issue by laf-rge** [floragunncom/search-guard#270]
I have a setup with an active directory issued user certificate for users who access the cluster. I have a working configuration for both authc and authz using LDAP mapping the userPrincipleName as the login name. I can not however get the clientcert to use the user_mapping for msUPN. From looking at the code it appears that the user_mapping field does not support this.

**Comment by floragunncom** [comment]
If i have this right this might help you:

https://github.com/floragunncom/search-guard/commit/2febe4d74ad079c28b80c4e8fb8aee3781e5491a

Its already in master and will be part of the upcoming release (next few days)

**Comment by floragunncom** [comment]
ping

**Comment by floragunncom** [comment]
no feedback

**Comment by laf-rge** [comment]
I'm not sure what to put in the configuration to test this.
