### ISSUE TITLE
how can I tell my role and user when I use elasticsearch rest api

### ISSUE THREAD

**Issue by xycloud** [floragunncom/search-guard#273]
how can I tell my role and user when I use elasticsearch rest api

**Comment by floragunncom** [comment]
try:

/_searchguard/authinfo

This will return a JSON string containing the username, the backendroles and the mapped Search Guard roles.

Please use the Search Guard Google group for asking questions, GitHub is for reporting bugs and issues.

https://groups.google.com/forum/#!forum/search-guard
