### ISSUE TITLE
elasticsearch releases 2.4.3->2.4.4 & 5.1.1->5.1.2

### ISSUE THREAD

**Issue by Khezen** [floragunncom/search-guard#276]
Please guys, 

Could you release new versions compatible with latest elasticsearch releases?

Awesome plugin by the way ;)

**Comment by floragunncom** [comment]
release is planned for tomorrow

**Comment by Khezen** [comment]
thanks, great support!

**Comment by rptete** [comment]
How long time left to release? How many hours?

**Comment by floragunncom** [comment]
released 3h ago https://twitter.com/searchguard/status/820892578472148992
If you need realtime announcements pls. follow us on twitter

Note: [Kibana plugin](https://github.com/floragunncom/search-guard-kibana-plugin) for 5.1.2 will be released shortly ()

**Comment by rptete** [comment]
and which KI plugin should I download for ELK-5?
