### ISSUE TITLE
suggest for sgadmin

### ISSUE THREAD

**Issue by xycloud** [floragunncom/search-guard#279]
suggest:
pls make sgadmin can play CRUD on only one role/user by cmdline

**Comment by floragunncom** [comment]
don't get what you mean, pls. elaborate more on this

**Comment by xycloud** [comment]
currently, if we wanna add one role and plus some permission on that role, we have to edit the three files: ```sg_internal_users.yml```, ```sg_roles.yml```, ```sg_roles_mapping.yml``` . can we just do that in one command line, like ```sgadmin --add-role xxx --add-permission xxx --add-user xxx```

**Comment by floragunncom** [comment]
We have our REST management api for that https://github.com/floragunncom/search-guard-rest-api/wiki

**Comment by xycloud** [comment]
seems its not free

**Comment by floragunncom** [comment]
thats true

But sgadmin is open source, you can add any feature you want yourself.

**Comment by floragunncom** [comment]
The idea behind Search Guard is to deliver basic security for free. For anything beyond this basics (kerberos, ldap, dls/fls), for enterprise readyness (auditlog) and for advanced comfort (like mngt. api) we will charge users if used in production. We think thats a fair approach with only winners.

**Comment by xycloud** [comment]
you are so right, users should pay if the use the enterprise plugins in production. but could there be a official ACL GUI? I saw that feature has been in progress, how about now

**Comment by floragunncom** [comment]
GUI is coming but no timeline/release date yet. And GUI will also be a commercial non-free component because it just makes the Search Guard more comfortable.

**Comment by xycloud** [comment]
ok,  I will pay if I am using it in production when it comes out
