### ISSUE TITLE
Access restrictons based on index names

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#281]
I have multiple ElasticSearch indices which have three different naming patterns:
1. logstash-*
2. logstash-syslog-*
3. logstash-audit-*
where "*" represents the date.

The following configuration gives me the expected result:
<pre>
sg_role_armenak:
  cluster:
    - cluster:monitor/main
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-syslog*':
      '*':
        - READ
        - SEARCH
        - indices:data/read/field_stats
      _dls_: '{"term" : {"_type" : "audit"}}'
    'logstash-audit*':
      '*':
        - READ
        - SEARCH
        - indices:data/read/field_stats
      _dls_: '{"term" : {"_type" : "audit"}}'
    'logstash-*':
      '*':
        - READ
        - SEARCH
        - indices:data/read/field_stats
      _dls_: '{"term" : {"_type" : "audit"}}'
    '?kibana':
      '*':
        - KIBANA_SERVER
</pre>

However, if I include only one index patter such as below, than I receive "Discover: [security_exception] no permissions for indices:data/read/field_stats" in Kibana.

<pre>
sg_role_armenak:
  cluster:
    - cluster:monitor/main
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-syslog*':
      '*':
        - READ
        - SEARCH
        - indices:data/read/field_stats
      _dls_: '{"term" : {"_type" : "audit"}}'
    '?kibana':
      '*':
        - KIBANA_SERVER
</pre>
Is this an expected behavior? On production, I plan to use multiple index patterns, based on the team's names, and it would be difficult to list all the patterns for each and every role.

**Comment by floragunncom** [comment]
whats wrong with just:

<pre>
sg_role_armenak:
  cluster:
    - cluster:monitor/main
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-*':
      '*':
        - READ
        - SEARCH
        - indices:data/read/field_stats
      _dls_: '{"term" : {"_type" : "audit"}}'
    '?kibana':
      '*':
        - KIBANA_SERVER
</pre>

**Comment by armenak** [comment]
Wrong is that there could be multiple different scenarios and different
patterns, not just "Logstash-*".

**Comment by floragunncom** [comment]
Can you work with multiple roles? Put one scenario/pattern into a own role and then assign these roles to your teams?

**Comment by armenak** [comment]
Let me clarify. There could be 20 teams. Each team will have their own roles. For example, HR, payroll, etc. The volume is so high that it will be unwise to have only one index per day and than restrict access only using DSL/FSL. I plan to have one index for each team (some teams may have >1 index) and than apply DSL.

Index naming convention is as follow: hr-<date>, payroll-syslog-<date>, payroll-audit-<date>.

If I have 20 index patterns and describe the restriction for each and every pattern in each and every role than it works. However, if I miss one index patter than it will throw an error which I posted in my initial message.

**Comment by armenak** [comment]
ping

**Comment by floragunncom** [comment]
Can we discuss this on a more concrete example? What i understood so far is that:

* You have around 20 teams (can you give some examples here how they are named?)
* You have 20 different indices (hr, payroll-syslog, payroll-audit, ...). Is it a coincidence that the number of index(patterns) and the number of teams are identical. Can you give other examples of index names?
* You index a lot of data and so you create one index per day. That mean your index name looks like `hr-2017-01-17` - Right?

I think you can get around your problem with something like:

<pre>
#give this role to every user which uses kibana
sg_role_kibana_basic:
  cluster:
    - cluster:monitor/main
    - CLUSTER_COMPOSITE_OPS
  indices:
    '*':
      '*':
        - indices:admin/mappings/fields/get*
        - indices:data/read/field_stats
    '?kibana':
      '*':
        - KIBANA_SERVER

sg_role_hr:
  indices:
    'hr-*':
      '*':
        - READ
        - SEARCH
      _dls_: '{"term" : {"_type" : "audit"}}'
      
sg_role_payroll:
  indices:
    'payroll-*':
      '*':
        - READ
        - SEARCH
      _dls_: '{"term" : {"_type" : "audit"}}'
</pre>

but i have not enough details to have a full understanding of your problem.

**Comment by armenak** [comment]
Proposed configuration does not work. In Kibana, I receive "Discover: no permissions for indices:data/read/search" exception. I think the problem is that when I login as a user who can see only audit logs, Kibana tries to access syslogs and cannot due to permissions defined in SearchGuard. However, instead of just showing audit logs, it displays the exception and shows nothing.

I tried to add indices:data/read/search to sg_role_kibana_basic role, but in this case any users can see all the data.

**Comment by armenak** [comment]
Here are the requested details. There is a Log Consolidation system. The goal is to collect log entries from many different teams in the organization. But for the sake of simplicity let's assume we have HR, Payroll, and Finance teams. Log entries from HR and Payroll teams will have their own index: hr-* and payroll-*. Finance team will have two indices: fin-audit-* and fin-syslog-*.

As I indicated above, the suggested solution does not work. I will submit elasticsearch log file and configuration files. Please have a look and let me know if I am doing something wrong.

Attaching log files.
[elasticsearch.log.txt](https://github.com/floragunncom/search-guard/files/728744/elasticsearch.log.txt)
[sg_action_groups.yml.txt](https://github.com/floragunncom/search-guard/files/728745/sg_action_groups.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/728747/sg_config.yml.txt)
[sg_internal_users.yml.txt](https://github.com/floragunncom/search-guard/files/728746/sg_internal_users.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/728748/sg_roles_mapping.yml.txt)
[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/728749/sg_roles.yml.txt)

**Comment by floragunncom** [comment]
I just tested your scenario and i it works well for me. How does your index patterns in Kibana look like? They should match the index patterns defined in Search Guard. If you query an index pattern which includes forbidden indices for your current user you get indeed a "Discover: no permissions for indices:data/read/search" - but this is desired in that case. It also works well for me in combination with DLS and FLS.

**Comment by armenak** [comment]
@floragunncom You are correct, the issue was caused by the index pattern in Kibana. 

It is just a bit confusing for me and will be confusing for users to see the error message. If there will be a possibility for users to have their own default Kibana index pattern, it would be great. 

I am still having issues with FLS, but this issue can be closed. Thank you for your help.

**Comment by floragunncom** [comment]
To make this more smooth we are working on multiuser/multitenant support for Search Guard and Kibana. Will be released next month.
