### ISSUE TITLE
agadmin

### ISSUE THREAD

**Issue by Passpes** [floragunncom/search-guard#284]
Configs from https://github.com/floragunncom/search-guard-docs/blob/master/kibana.md
what's the problem with this configuration ? 
tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/kirk-keystore.jks -kspass changeit -cd sgconfig/ -icl -nhnv -h 192.168.40.174
Search Guard Admin v5
Will connect to 192.168.40.174:9300 ... done
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: elasticsearch
Clusterstate: GREEN
Number of nodes: 2
Number of data nodes: 2
searchguard index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/search-guard-5/sgconfig
Will update 'config' with sgconfig/sg_config.yml
   FAIL: Configuration for 'config' failed because of com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
 in 'reader', line 68, column 9:
            enabled: true
            ^
expected <block end>, but found BlockMappingStart
 in 'reader', line 73, column 10:
             authentication_backend:
             ^

 at [Source: java.io.FileReader@2cfbeac4; line: 73, column: 10]
Will update 'roles' with sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'rolesmapping' with sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'internalusers' with sgconfig/sg_internal_users.yml
   FAIL: Configuration for 'internalusers' failed because of ElasticsearchParseException[duplicate settings key [kibanaserver.hash] found at line number [1], column number [692], previous value [$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H.], current value [$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H.]]
Will update 'actiongroups' with sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
FAIL: Expected 2 nodes to return response, but got only 1
Timeout (java.util.concurrent.TimeoutException: Timeout after 30SECONDS while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups](index=searchguard))
Done with failures

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by floragunncom** [comment]
your yml is invalid, try to validate them with http://www.yamllint.com or http://yaml-online-parser.appspot.com
