### ISSUE TITLE
sgadmin.sh exposes password in processtable

### ISSUE THREAD

**Issue by faxm0dem** [floragunncom/search-guard#285]
* Search Guard and Elasticsearch version: 2.4.2
* JVM version and operating system version: Centos7 openjdk8
* Number of nodes in your cluster: 9
* Description of the bug

Running `sgadmin.sh` requires passing secrets as command line parameters.
This is insecure as the secrets are exposed to the processtable (unless SELinux or similar is running).
A possible workaround is to use the Management API.

One way to address this would be to allow passing the secrets as environment variables.

**Comment by floragunncom** [comment]
Good catch, we're also looking at HashiCorp vault.

**Comment by faxm0dem** [comment]
If you agree with the ENV idea, I'll implement it asap

**Comment by floragunncom** [comment]
I agree and would love to see a PR (we need you to ask to sign our CLA before we can merge it)

**Comment by floragunncom** [comment]
@faxm0dem any PR planned, we start preparing our next release and i would like to include this feature.

**Comment by faxm0dem** [comment]
Would tomorrow be okay?

**Comment by floragunncom** [comment]
sure, great

**Comment by faxm0dem** [comment]
Sorry for the stupid question, but how do I run `sgadmin.sh` after compiling searchguard, without having to install it?
I tried the following (my maven skills are NaN):

```
mvn exec:java -Dexec.mainClass="com.floragunn.searchguard.tools.SearchGuardAdmin"
```

**Comment by floragunncom** [comment]
I would start it within the IDE (Eclipse, IntelliJ, ...)

**Comment by faxm0dem** [comment]
Hmmm same error in IDE:

    Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException

**Comment by floragunncom** [comment]
fixed with v11, released today
