### ISSUE TITLE
Problem configuring Monitoring (Marvel) with SearchGuard

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#286]
Hello,

I've installed X-Pack on both Kibana and ElasticSearch and, according to instructions, disabled all x-pack modules except monitoring. 

In elasticsearch.yml I added the following:
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false

xpack.monitoring.exporters:
  my_remote:
    type: http
    host: [ "http://event-apptst01.as.it.ubc.ca:9200" ]
    auth:
      username: kibanaserver
      password: kibanaserver
    connection:
      timeout: 6s
      read_timeout: 60s

and the following to kibana.yml:
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false

xpack.monitoring.elasticsearch.url: "http://event-apptst01.as.it.ubc.ca:9200"

After restarting both Kibana and ElasticSearch I receive permission errors in Kibana (please see the attachment).

Am I missing something in the configuration? Where should I add missing permission definitions?
![kibana](https://cloud.githubusercontent.com/assets/3421052/22495135/8802662e-e7f2-11e6-9a8e-9b4f07b6068a.png)

**Comment by floragunncom** [comment]
@armenak thats more likely a (role) configuration issue than a bug. I would like discuss such problem on the [google group list](https://groups.google.com/forum/#!forum/search-guard) so i close this. Pls. see also https://github.com/floragunncom/search-guard-ssl/issues/43 maybe @matejzero can share his working config. We do not officially support X-Pack so this is all on "best effort" base and may work (or not).

**Comment by matejzero** [comment]
@armenak check the url @floragunncom posted. I added my roles there.
