### ISSUE TITLE
Install plugin with proxy

### ISSUE THREAD

**Issue by rptete** [floragunncom/search-guard#287]
#230  with compatibility to ES-5.1.2 and SGadmin10:
wget http://repo1.maven.org/maven2/com/floragunn/search-guard-5/5.1.2-10/search-guard-5-5.1.2-10.zip
/usr/share/elasticsearch/bin/elasticsearch-plugin install file:///root/search-guard-5-5.1.2-10.zip
/usr/share/elasticsearch/bin/elasticsearch-plugin list

searchguard5-kibanaPlugin with compatibility to KI-5.1.2
wget https://github.com/floragunncom/search-guard-kibana-plugin/releases/download/v5.1.2-alpha/searchguard-kibana-alpha-5.1.2.zip
/usr/share/kibana/bin/kibana-plugin install file:///root/searchguard-kibana-alpha-5.1.2.zip
/usr/share/kibana/bin/kibana-plugin list

Thanks to Marc Escamilla

**Comment by floragunncom** [comment]
@rptete so whats the issue here?

**Comment by rptete** [comment]
any, sorry, close it, I posted this because the installation of plugins to the lastest version of ES-KI is very difficult only reading your docs.
I tried post it in search-guard-docs, but i cant

**Comment by floragunncom** [comment]
You can post it to the google group https://groups.google.com/forum/#!forum/search-guard and/or make a pull request for the https://github.com/floragunncom/search-guard-docs repo.
