### ISSUE TITLE
Connection to Pig using Elasticsearch Connector

### ISSUE THREAD

**Issue by YonoloX** [floragunncom/search-guard#29]
Hello,

How could we store and load data from Elasticsearch to Pig while security is implemented by search-guard, for the moment it throw an error of illegal get of data.

The connector used : https://www.elastic.co/guide/en/elasticsearch/hadoop/current/pig.html#_reading_data_from_elasticsearch_4

Thanks in advance.

**Comment by floragunncom** [comment]
pls. provide more details like stacktrace, error message, config files etc

**Comment by YonoloX** [comment]
The message error I was having is:  
Message: org.apache.pig.backend.executionengine.ExecException: ERROR 2118: [GET] on [_nodes/transport] failed; server[null] returned [401|Unauthorized:]

The configuration I was using is the same as introduced in the template of your documentation (yaml files, searchguard index...)

I was trying to write data from Pig (HDFS) into Elasticsearch, the connector used for that is a jar file :
REGISTER elasticsearch-hadoop-pig-2.1.0.jar;

Without searchguard plugin I can write data like:
DEFINE EsStorage org.elasticsearch.hadoop.pig.EsStorage('es.nodes = localhost', 'es.http.timeout = 1m', 'es.index.auto.create = true',);
b = load 'my_file' using PigStorage(',') as (f1:chararray, f2:chararray, f3:chararray);
store b into 'myindex1/mytype' using EsStorage;

I've looked into shield documentation and I found that it is possible to use this connector to write/load from secured elasticsearch by adding security parameters to the connector ('es.net.http.auth.user = admin', 'es.net.http.auth.pass = secret'), and so : 
DEFINE EsStorage org.elasticsearch.hadoop.pig.EsStorage('es.nodes = dholak', 'es.http.timeout = 1m', 'es.index.auto.create = true', );

To use SSL I've only succeeded to do it this way according to the documentation provided on the connector project: 
DEFINE EsStorage org.elasticsearch.hadoop.pig.EsStorage('es.nodes = localhost', 'es.index.auto.create = true', 'es.net.http.auth.user = admin', 'es.net.http.auth.pass = secret', 'es.net.ssl = true', 'es.net.ssl.keystore.location = keystore.jks', 'es.net.ssl.keystore.pass = kspass', 'es.net.ssl.truststore.location = truststore.jks', 'es.net.ssl.truststore.pass = tspass');

I wonder if there is a way where less passwords are provided as parameters to make SSL connection possible.

Thanks for your feedback.

**Comment by floragunncom** [comment]
pls. post you elasticsearch.yml config file and the acl

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
