### ISSUE TITLE
Proxy auth generates xff messages when used with basic auth

### ISSUE THREAD

**Issue by dachenbach** [floragunncom/search-guard#292]
I have enabled proxy authentication in sg_config.yml for use with SSO, but I still have basic authentication enabled for role account access (e.g. logstash, kibana, etc.). With both enabled, this message repeats several times a second in the elasticsearch log:

`[2017-02-07T20:03:58,584][INFO ][c.f.s.a.BackendRegistry  ] ElasticsearchSecurityException[xff not done] extracting credentials from ElasticsearchSecurityException[xff not done]`

Presumably it's doing this every time a role account authenticates.

Here is my sg_config.yml:

```searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
        trustedProxies: '10\.185\.25(\d)?\.\d+'
    authc:
      basic_internal_auth_domain:
        enabled: true
        order: 2
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      proxy_auth_domain:
        enabled: true
        order: 1
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "X-Forwarded-User"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
```

Both authentication methods work aside from all the log messages.

**Comment by faxm0dem** [comment]
Same here. The situation has dramatically improved with search-guard-5 though, as there is only a single line left (without stack trace). But not sure this is related to SG, maybe just how ES5 handles default logging config.

**Comment by ale0xB** [comment]
+1
I have JWT enabled and Kibana works OK with basic Authentication, however all my logs are flooded with messages of this kind (repeats every ~5ms). 

`[2017-02-09T13:57:57,660][ERROR][c.f.d.a.h.j.HTTPJwtAuthenticator] Invalid or expired JWT token. io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0`

**Comment by shkrid** [comment]
+1
Any idea how to fix it?

**Comment by faxm0dem** [comment]
It's a tricky problem. Some people want to see those. Maybe it's possible to filter them out using log4j2 filters (assuming elastic 5)

**Comment by shkrid** [comment]
@faxm0dem Can you show me some example how to do it? I'm newbie in it. Thanks.

**Comment by shkrid** [comment]
@floragunncom I think it would be a most elegant solution.

**Comment by dachenbach** [comment]
That sounds like a good solution to me, too.

**Comment by shkrid** [comment]
@floragunncom Now I have a lot of such errors same as @ale0xB 
```[2017-02-13T04:43:12,909][ERROR][c.f.d.a.h.j.HTTPJwtAuthenticator] Invalid or expired JWT token. io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0
[2017-02-13T04:43:12,914][ERROR][c.f.d.a.h.j.HTTPJwtAuthenticator] Invalid or expired JWT token. io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0
[2017-02-13T04:43:12,917][ERROR][c.f.d.a.h.j.HTTPJwtAuthenticator] Invalid or expired JWT token. io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0
[2017-02-13T04:43:12,920][ERROR][c.f.d.a.h.j.HTTPJwtAuthenticator] Invalid or expired JWT token. io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0
```
What to do with it? DEBUG level too?

It's seems that kibana trigger such messages (very frequently)

**Comment by faxm0dem** [comment]
My opinion is that ideally the level should depend on the presence of other authentication requests. I realise though that this is probably not worth the effort.

**Comment by ale0xB** [comment]
I agree with @faxm0dem. In my case I don't want to see any of those messages), since I have another authentication method working in Kibana (Basic Auth).

Can I filter messages incoming from HTTPJwtAuthenticator only? That'd probably be enough for me.

**Comment by faxm0dem** [comment]
I'm using syslog-ng to do that kind of thing. But I'll investigate of it's possible using log4j2 only.

**Comment by floragunncom** [comment]
fixed with v11, released today (for jwt we need a release of the jwt module, expected soon)

**Comment by floragunncom** [comment]
will JWT this here: https://github.com/floragunncom/search-guard-authbackend-jwt/issues/3
