### ISSUE TITLE
Reindexing fails on version 5.2

### ISSUE THREAD

**Issue by dorony** [floragunncom/search-guard#295]
Elasticsearch version: 5.2.0
Searchguard version: 5.2-10
JVM version: 1.8.0_121
OS version: Ubuntu 14.04.5
Number of nodes: 8

Hi,
Under version 5.2, a simple reindexing request fails with the error:
`no permissions for indices:data/write/reindex
`
This is the request I was sending:
```
POST _reindex
{
  "source": {    
    "index": "my-index"
  },
  "dest": {
    "index": "my-index2"
  }
}
```
The user is permitted for all indices operations:
```
indices:
    '*':
      '*':
        - '*'
```
In the logs, I see this warning:
`[2017-02-13T06:54:53,231][WARN ][c.f.s.c.PrivilegesEvaluator] indices:data/write/reindex for '_all' indices is not allowed for a regular user`
I'm not sure why it mentions `_all` when I was specifying `my-index2`. 
Thanks.

**Comment by floragunncom** [comment]
Thanks, will fix it.

Did it work with 5.0.x or 5.1.x ?

**Comment by dorony** [comment]
It worked with 5.1.x for sure, I think 5.0.x as well

**Comment by floragunncom** [comment]
This will be fixed in v11, expected release date is this week.

**Comment by floragunncom** [comment]
fixed with v11, released today
