### ISSUE TITLE
ES 5.2.1 problem with searchguard 5.2

### ISSUE THREAD

**Issue by Passpes** [floragunncom/search-guard#297]
Hi,
It seems that the latest version of searchguard 5.2 can't be integrated with elasticsearch new update 5.2.1, any updates for searchguard ?

Ansible output:

bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.2", "delta": "0:00:02.747773", "end": "2017-01-20 14:35:48.069594", "failed": true, "rc": 1, "start": "2017-01-20 14:35:45.321821", "stderr": "Exception in thread \"main\" java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/floragunn/search-guard-5/5.2/search-guard-5-5.2.zip\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)\n\tat sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)\n\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)\n\tat org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:279)\n\tat org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:322)\n\tat org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:240)\n\tat org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:210)\n\tat org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)\n\tat org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)\n\tat org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)\n\tat org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)\n\tat org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)\n\tat org.elasticsearch.cli.Command.main(Command.java:88)\n\tat org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)\nCaused by: java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/floragunn/search-guard-5/5.2/search-guard-5-5.2.zip\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)\n\tat sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)\n\tat java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)\n\tat java.net.URLConnection.getContentLengthLong(URLConnection.java:501)\n\tat java.net.URLConnection.getContentLength(URLConnection.java:485)\n\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)\n\tat org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:278)\n\t... 10 more", "stdout": "-> Downloading com.floragunn:search-guard-5:5.2 from maven central", "stdout_lines": ["-> Downloading com.floragunn:search-guard-5:5.2 from maven central

**Comment by floragunncom** [comment]
Search Guard compatible with 5.2.1 not yet released. Pls. check currently supported versions here: https://github.com/floragunncom/search-guard/wiki before filing an issue.

A 5.2.1 compatible version is expected to be released tomorrow.
