### ISSUE TITLE
Kibana prompts me for username and password twice

### ISSUE THREAD

**Issue by feidududexigua** [floragunncom/search-guard#298]
ES version:5.2.0  REST layer no ssl
kibana version: 5.2.0
java version "1.8.0_45"
Number of nodes: 3

Hi,
I'v configured my kibana like this:

server.port: 5601
elasticsearch.url: "http://localhost:9200"
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"

and start it normally.

but when I open a browser, and access Kibana,it prompts me for username and password twice,one for “Authorization Required”,and another for “Search Guard".why this happend?

Thx.

**Comment by floragunncom** [comment]
you may want to install https://github.com/floragunncom/search-guard-kibana-plugin/releases

**Comment by feidududexigua** [comment]
It works,thanks a lot.

**Comment by Passpes** [comment]
No release for kibana 5.2.2 yet ?

**Comment by floragunncom** [comment]
done https://github.com/floragunncom/search-guard-kibana-plugin/releases/tag/v5.2.2-1

**Comment by vsevolodk** [comment]
@floragunncom can you please specify pull request link for this bug?

**Comment by floragunncom** [comment]
Please don't comment on closed issues. There's no PR, because the issue was on Kibana side, and we had to implement our own Kibana plugin to fix it. So, the fix is the Kibana plugin itself.
