### ISSUE TITLE
no permissions for indices:monitor/stats

### ISSUE THREAD

**Issue by Passpes** [floragunncom/search-guard#299]
Hi,

I'm trying to pull indices using https://192.168.40.168:9200/_cat/indices?v but I got the following error:
{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for indices:monitor/stats"}],"type":"security_exception","reason":"no permissions for indices:monitor/stats"},"status":403}

Should I configure some roles in Kibana or how can I get /_cat/indices?v working?

Thanks,

**Comment by floragunncom** [comment]
Again (you already posted this question to the google group):

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by Passpes** [comment]
Yeah but seems that there's no feedback in google grp :/

**Comment by floragunncom** [comment]
in google group you get support from the community - so its up to them to answer you. If you need guaranteed support with SLA's you may want to consider to buy commercial support here: https://floragunn.com/searchguard/searchguard-license-support/
