### ISSUE TITLE
Default configuration failing

### ISSUE THREAD

**Issue by slundberg** [floragunncom/search-guard#30]
Using the default ACL from the curl command in the ReadMe under "Setup ACL rules", and using the config 

```yml
searchguard.authentication.settingsdb.user.admin: pass
searchguard.authentication.authorization.settingsdb.roles.admin: ["admin"]
```

does not allow admin search access in 1.5.2:

```bash
curl -u admin:pass 'http://localhost:9200/_search?pretty'
```

gives

```json
{
  "error" : "RuntimeException[java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/search and User [name=admin, roles=[admin]]]; nested: RuntimeException[Attempt from null to _all indices for indices:data/read/search and User [name=admin, roles=[admin]]]; ",
  "status" : 500
}
```

I saw a similar note in the Google groups. Is there something basic missing here? If so it would be good to include in the ReadMe. Thanks!

**Comment by slundberg** [comment]
Looks like
```
curl -u admin:pass 'http://localhost:9200/_search?pretty'
```
is to blame since
```
curl -u admin:pass 'http://localhost:9200/logstash-2015.07.07/_search?pretty'
````
works as expected.

**Comment by floragunncom** [comment]
can you pls. post you acl and complete .yml configuration?

**Comment by slundberg** [comment]
Sorry for the long delay, I didn't need to search `_all` so this has been on the back burner.

`cat elasticsearch.yml | grep -v '^#' | grep -v '^$'` gives:

```
searchguard.enabled: true
searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator
searchguard.authentication.settingsdb.user.admin: XXXXXXXXXX
searchguard.authentication.authorization.settingsdb.roles.admin: ["root"]
searchguard.restactionfilter.names: ["readonly"]
searchguard.restactionfilter.readonly.allowed_actions: ["*"]
searchguard.restactionfilter.readonly.forbidden_actions: []
``` 

The ACL's are:

```json
{"_index":"searchguard","_type":"ac","_id":"ac","_version":4,"found":true,"_source":{
    "acl": [
    {    
        "indices": [
               "*", "_all", "ALL"
        ],
        "filters_bypass": ["*"],
        "filters_execute": []
     }
     ]
}}
```

**Comment by rahulmodi1** [comment]
I am getting the same issue. My ACL's are:

PUT /searchguard/ac/ac
{
    "acl": [
    {    
        "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
        "filters_bypass": [],
        "filters_execute": []
     },
     {
           "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
           "roles": [
               "admin"
           ],
           "filters_bypass": ["*"],
           "filters_execute": []
     }
     ]
}

and elasticsearch.yml is:

searchguard.enabled: true
searchguard.rewrite_get_as_search: true
searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator
searchguard.authentication.settingsdb.user.rahul: rahul
searchguard.authentication.settingsdb.user.michaeljackson: neverland
searchguard.authentication.authorization.settingsdb.roles.rahul: ["role1","role2","role3","admin","root"]
searchguard.authentication.authorization.settingsdb.roles.michaeljackson: ["kingofpop","superstar"]
searchguard.actionrequestfilter.names: ["readonly"]
searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*", "indices:admin*", "indices:data/write*"]

Any help will be much appreciated. Thanks

**Comment by triumph281** [comment]
searchguard ，the ACL index cannot be search . it cause such exception,you can search like this:
http://localhost:9200/logstash\*/_search ,any way, use index name like "logstash\*" and eliminate "searchguard"

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
