### ISSUE TITLE
How do I integrate Elasticsearch with the Searchguard plugin into my SpringMVC project?

### ISSUE THREAD

**Issue by Holyangelmom** [floragunncom/search-guard#300]
Now my springmvc project requires the use of elasticsearch to achieve full-text search, and the need to install searchguard plug-ins to ensure data security, but how to install searchguard plug-in elasticsearch inherited to the web project? please give me some ideas.
Any help will be much appreciated!

**Comment by floragunncom** [comment]
Hello - we'd like to ask you to post this question to our Google Group, so also other users can benefit from the answer:

https://groups.google.com/forum/#!forum/search-guard

Github issues are for reporting bugs only. Please re-post on Google Groups, and add some more details, especially:

- Are you running Elasticsearch in-process in your web app, or standalone?
- Do you use a Transport Client, or the REST interface to communicate with ES?
- Which version of ES/SG are you using?

Thanks!

**Comment by Holyangelmom** [comment]
OK ! Thx
