### ISSUE TITLE
 Whether it is supported es5.0.1?

### ISSUE THREAD

**Issue by hexian55** [floragunncom/search-guard#301]
Search Guard Bundle 5.0.2-10

The most recent version of this bundle can be downloaded here:

https://floragunn.com/downloads/elasticsearch-5.0.2-10-06DA3957-0462-4D3E-835F-DC41831F4B40.tar.gz

SHA-256 checksum: 3fd8913f4a330d509b7d4da121a3fee9653dfc33981b6a2ef4cf4d92833dc610

This bundle builds on

Elasticsearch 5.0.2
Search Guard 5.0.2-10

 it is supported es5.0.1?？

**Comment by floragunncom** [comment]
The bundle is an always up-to date kind of "show case" or quickstart. But you can install Search Guard yourself, supported versions are here: https://github.com/floragunncom/search-guard/wiki

**Comment by hexian55** [comment]
thank you for your answer,I see
