### ISSUE TITLE
Get all search-guard users

### ISSUE THREAD

**Issue by gubr123** [floragunncom/search-guard#304]
Hi

Using v5.2.1

Is there a way I can retrieve all search guard users without using the rest API?
same question for adding/deleting a user without using the rest API?

Thanks

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
