### ISSUE TITLE
Rewriting request to only allowed subset of indices

### ISSUE THREAD

**Issue by shkrid** [floragunncom/search-guard#305]
https://readonlyrest.com/documentation#toc-2-3-1-indices-rule
If a read request asks for a some indices they have permissions for and some indices that they do NOT have permission for, the request is rewritten to involve only the subset of indices they have permission for.
This is behaviour is very useful in Kibana: different users can see the same dashboards with data from only their own indices.

Is it possible to do with SearchGuard?

**Comment by floragunncom** [comment]
This will be a part of the upcoming Kibana Multitenancy Module: https://github.com/floragunncom/search-guard-module-kibana-multitenancy - Expect first beta next week

**Comment by floragunncom** [comment]
Beta 1 released, pls install Search Guard v11 and Elasticsearch 5.2.x and [the module](https://github.com/floragunncom/search-guard-module-kibana-multitenancy/wiki) then follow the instructions here https://github.com/floragunncom/search-guard-docs/blob/master/multitenancy.md (Index rewrite). 

Set in sg_config.yml (and run sgadmin)
```
searchguard.dynamic.kibana.multitenancy_enabled: false
searchguard.dynamic.kibana.do_not_fail_on_forbidden: true
```

**Comment by floragunncom** [comment]
no feedback

Note: beta 2 released today https://github.com/floragunncom/search-guard-module-kibana-multitenancy/wiki
