### ISSUE TITLE
could not make search-guard works with elasticsearch head 

### ISSUE THREAD

**Issue by robertchen** [floragunncom/search-guard#306]
Search Guard and Elasticsearch version
Both are 5.1.1
JVM version and operating system version
JDK 1.8, AWS linux
Number of nodes in your cluster
3

the Key, certficates are generated by the example.sh,  the elasticsearch head tried to talk with https which is not work. Even just curl with username and password not working:

[root@ip-10-8-8-246 elasticsearch-head]# curl https://admin:admin@10.8.8.246:9200/
curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
...

the elasticsearch configuration is: 
[root@ip-10-8-8-246 elasticsearch-head]# cat /etc/elasticsearch/elasticsearch.yml
cluster.name: ELK-TUHAO
path.data: /data
node.name: usg-elk-a
network.host: 10.8.8.246
action.destructive_requires_name: true
bootstrap.memory_lock: true
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.unicast.hosts: ['10.8.8.246', '10.8.8.209', '10.8.8.248']

searchguard.ssl.transport.keystore_filepath: usg-elk-a-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false
#searchguard.ssl.transport.http.enforce_clientauth: false

searchguard.authcz.admin_dn:
  - CN=kirk, OU=client, O=client, L=Test, C=DE

#enable REST API with https:
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: usg-elk-a-keystore.jks
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: changeit

![elasticsearch head not working](https://cloud.githubusercontent.com/assets/1059160/23413389/88405550-fda6-11e6-8d9d-0fd06814f9d2.PNG)

**Comment by floragunncom** [comment]
do you think this is a bug?

**Comment by buxiangzhuce** [comment]
do you mean that we can not connect to head after installing search guard？thank you for reply   @floragunncom

**Comment by robertchen** [comment]
Yes, head not able to connect to the cluster.

**Comment by floragunncom** [comment]
Does `curl -k https://admin:admin@10.8.8.246:9200/`work?
Regarding `head` plugin: Pls look into the JS developer console of your browser to get details why the connection is fails and make sure you have enabled CORS support and you can open `https://admin:admin@10.8.8.246:9200` directly in the browser.

Regarding CORS pls read the head docs: https://github.com/mobz/elasticsearch-head and if its still not working i suggest you open a head issue.

**Comment by floragunncom** [comment]
ping

**Comment by robertchen** [comment]
thanks,  curl -k works:

[root@ip-10-8-8-246 ec2-user]# curl -k https://admin:admin@10.8.8.246:9200/
{
  "name" : "usg-elk-a",
  "cluster_name" : "ELK-TUHAO",
  "cluster_uuid" : "P5VnvOw-T7eN2G5YC2Dyfw",
  "version" : {
    "number" : "5.1.1",
    "build_hash" : "5395e21",
    "build_date" : "2016-12-06T12:36:15.409Z",
    "build_snapshot" : false,
    "lucene_version" : "6.3.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by xiaoyuxiaoyu** [comment]
Hi robertchen:
     Have you  connected to the cluste by elasticsearch-head?

**Comment by robertchen** [comment]
yes, should be ok.

**Comment by xiaoyuxiaoyu** [comment]
Can you tell me how to connect with elasticsearch-head when we use search-guard ? Thank you anyway

**Comment by desp0916** [comment]
@xiaoyuxiaoyu 

1. Before connecting ES with Elasticsearch-head, you need to browse to either ES node (https://es-node01:9200/) and let your browser accept the self-signed certificate while it warns you of the unsecured/untrusted connection.
2. Then browse to Elasticsearch-head: http://es-head:9100/?base_uri=https://es-node01:9200&auth_user=admin&auth_password=admin_password
3. Finally, press the "Connect" button in Elasticsearch-head and the cluster health info will appear.
