### ISSUE TITLE
Why visit kibana need to log in twice?

### ISSUE THREAD

**Issue by agenge** [floragunncom/search-guard#308]
My Elasticsearch 5.2 uses the search guard 5.2 plugin. 
After installing kibana 5.2, visit http://192.168.56.101:5601, asked to log in twice.

First ask: 
**Authorization Required**

type username and passwd, And then again asked to enter the user name and password.
the second time:
**search guard**

Why?  kibana.yml:
```
elasticsearch.url: 'https://192.168.56.101:9200'
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
elasticsearch.ssl.verify: false
```

**Comment by floragunncom** [comment]
https://github.com/floragunncom/search-guard/issues/298
