### ISSUE TITLE
X-Pack search profiler and SearchGuard

### ISSUE THREAD

**Issue by dorony** [floragunncom/search-guard#312]
Elasticsearch version: 5.2.1
Searchguard version: 5.2.1-11
JVM version: 1.8.0_121
OS version: Ubuntu 14.04.5
Number of nodes: 8

Hi,
While the instructions [here](https://github.com/floragunncom/search-guard-docs/blob/master/kibana.md#kibana-5) work for the dev-tools Console (Sense), the [search profiler](https://www.elastic.co/guide/en/x-pack/current/profiler-getting-started.html) that comes with X-Pack and appears as another dev tool, doesn't work with SearchGuard. It displays an AuthenticationError when attempting to profile a query. Is there any way to make it work?

**Comment by floragunncom** [comment]
Sorry, but we do not and we can not support x-pack plugins. Please try here https://discuss.elastic.co or https://github.com/elastic/elasticsearch/issues

**Comment by dorony** [comment]
May I mention that the problem is with SearcGuard and not x-pack? You are saying that x-pack does not work with your product?
