### ISSUE TITLE
internal_users config in not loaded after running sgadmin.sh

### ISSUE THREAD

**Issue by yasvanth** [floragunncom/search-guard#314]
Hi @floragunncom 

I am EX cluster on 3 node cluster. When I made changes to sg_internal_users by removing user admin and executed new ./sgadmin.sh. When I login with admin:admin, Kibana lets me to access all the indices. 

I have updated the config on all the node and executed still the issue is same. I am running all latest version:
ES 5.2.2
SG 5 v11
kibana 5.2.2.
kibana-plugin SG 5.2.2-1

Thanks,

**Comment by floragunncom** [comment]
Have you verified that sgadmin was executed correctly? What is the output of sgadmin when you run it?

Did you just update the sg_internal_users config (with option -f), or did you specify a config directory (with option -cd). Can you post your complete sgadmin call?

After you have updated the config, can you try to retrieve the current active config from your cluster (with option -r) and compare it with the contents of the file that you loaded?

You write "I have updated the config on all the node". What do you mean by that? You just need to execute sgadmin against one of the nodes in your cluster, no need to update any config files on each node directly.

**Comment by yasvanth** [comment]
Hi,
I have executed below command from .../plugins/search-guard-5/tools/
`./sgadmin.sh -ts ../sgconfig/truststore.jks -tspass 12345 -ks ../sgconfig/sgadmin.jks -kspass 123344 -cd ../sgconfig -icl -nhnv`

output is:
`Will update 'config' with ../sgconfig/sg_config.yml
   SUCC: Configuration for 'config' created or updated
Will update 'roles' with ../sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'rolesmapping' with ../sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'internalusers' with ../sgconfig/sg_internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update 'actiongroups' with ../sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Done with success'

**Comment by floragunncom** [comment]
Yes, that looks fine. Can you try to retrieve the current active config from your cluster (use sgadmin with option -r) and compare it with the contents of the file ../sgconfig/sg_internal_users.yml?

**Comment by yasvanth** [comment]
i get 
searchguard index already exists, so we do not need to create one.
Will retrieve 'config' into ../sgconfig/sg_config_2017-Mar-28_21-48-27.yml
   SUCC: Configuration for 'config' stored in ../sgconfig/sg_config_2017-Mar-28_21-48-27.yml
Will retrieve 'roles' into ../sgconfig/sg_roles_2017-Mar-28_21-48-27.yml
   SUCC: Configuration for 'roles' stored in ../sgconfig/sg_roles_2017-Mar-28_21-48-27.yml
Will retrieve 'rolesmapping' into ../sgconfig/sg_roles_mapping_2017-Mar-28_21-48-27.yml
   SUCC: Configuration for 'rolesmapping' stored in ../sgconfig/sg_roles_mapping_2017-Mar-28_21-48-27                                                                   .yml
Will retrieve 'internalusers' into ../sgconfig/sg_internal_users_2017-Mar-28_21-48-27.yml
   SUCC: Configuration for 'internalusers' stored in ../sgconfig/sg_internal_users_2017-Mar-28_21-48-                                                                   27.yml
Will retrieve 'actiongroups' into ../sgconfig/sg_action_groups_2017-Mar-28_21-48-27.yml
   SUCC: Configuration for 'actiongroups' stored in ../sgconfig/sg_action_groups_2017-Mar-28_21-48-27                                                                   .yml

**Comment by floragunncom** [comment]
Yes, this is a dump of the currently active Search Guard configuration in your cluster. Now please compare the contents of your original file ../sgconfig/sg_internal_users.yml (the one you uploaded), and ./sgconfig/sg_internal_users_2017-Mar-28_21-48- 27.yml. They should be identical. Can you please post the contents of the two files?

**Comment by yasvanth** [comment]
I have attached the file 


[sg_roles_2017-Mar-28_21-48-27.txt](https://github.com/floragunncom/search-guard/files/877109/sg_roles_2017-Mar-28_21-48-27.txt)
[sg_roles_mapping.txt](https://github.com/floragunncom/search-guard/files/877110/sg_roles_mapping.txt)
[sg_roles_mapping_2017-Mar-28_21-48-27.txt](https://github.com/floragunncom/search-guard/files/877113/sg_roles_mapping_2017-Mar-28_21-48-27.txt)
[sg_action_groups.txt](https://github.com/floragunncom/search-guard/files/877107/sg_action_groups.txt)
[sg_action_groups_2017-Mar-28_21-48-27.txt](https://github.com/floragunncom/search-guard/files/877108/sg_action_groups_2017-Mar-28_21-48-27.txt)
[sg_config.txt](https://github.com/floragunncom/search-guard/files/877111/sg_config.txt)
[sg_config_2017-Mar-28_21-48-27.txt](https://github.com/floragunncom/search-guard/files/877114/sg_config_2017-Mar-28_21-48-27.txt)
[sg_internal_users.txt](https://github.com/floragunncom/search-guard/files/877116/sg_internal_users.txt)
[sg_internal_users_2017-Mar-28_21-48-27.txt](https://github.com/floragunncom/search-guard/files/877115/sg_internal_users_2017-Mar-28_21-48-27.txt)
[sg_roles.txt](https://github.com/floragunncom/search-guard/files/877112/sg_roles.txt)

**Comment by floragunncom** [comment]
Files look fine for me. However, you have defined the internal/Basic Auth domain twice. While this should not be an issue, one of these two definitions is sufficient:

    authc:
      kibana_auth_domain:
        enabled: true
        order: 1
        http_authenticator:
          type: "basic"
          challenge: true
        authentication_backend:
          type: "internal"
      basic_internal_auth_domain:
        enabled: true
        order: 4
        http_authenticator:
          type: "basic"
          challenge: true
        authentication_backend:
          type: "internal"

Next, does the effect only occur when accessing ES with Kibana? Can you please try to access your ES cluster directly via REST? You should see a Basic Auth dialogue, try using admin/admin there. 

If login succeeds (which it should not), try to access this endpoint in a browser:

https://<es host>:<es port>/_searchguard/authinfo

This returns some more information about the currently logged in used.

**Comment by yasvanth** [comment]
the output when i tried using curl 
{
  "user" : "User [name=idptest, roles=[]]",
  "user_name" : "idptest",
  "user_requested_tenant" : null,
  "remote_address" : "[::1]:49952",
  "sg_roles" : [
    "sg_user1"
  ],
  "sg_tenants" : {
    "idptest" : true
  },
  "principal" : null,
  "peer_certificates" : "0"
}


And This was the output from web client

{"user":"User [name=idptest, roles=[]]","user_name":"idptest","user_requested_tenant":null,"remote_address":"[::1]:50000","sg_roles":["sg_user1"],"sg_tenants":{"idptest":true},"principal":null,"peer_certificates":"0"}

**Comment by floragunncom** [comment]
Now I'm confused. You wrote initally:

"When I made changes to sg_internal_users by removing user admin and executed new ./sgadmin.sh. When I login with admin:admin, Kibana lets me to access all the indices."

But the output above shows that you have logged in with a user called "idptest"?

**Comment by yasvanth** [comment]
oh ya sorry I forgot to mention. I have tried with admin:admin the output was not authorised.
So I tried with idp test works fine as required. When I access admin:admin from kibana it lets me in.

**Comment by floragunncom** [comment]
ok - maybe it's a cookie problem then. Can you try to remove the searchguard_authentication cookie first, and then try admin/admin in Kibana again. Because if you cannot access ES directly with admin/admin, then you also cannot do that in Kibana, we use the same endpoint _searchguard/authinfo when checking the credentials. Thx!

**Comment by floragunncom** [comment]
Are you sure that the configuration files you sent yesterday are correct? According to the output of the authinfo endpoint, you are logged in with a user idptest:

"user_name" : "idptest"

Which has the role sg_user1:

"sg_roles" : [
"sg_user1"
]

But I cannot find any role sg_user1 in the roles or roles mapping files.

Also, in the roles mapping, you map user idptest to the role sg_idptest:

sg_idptest:
  users:
    - idptest

But there is no such role in the roles.yml file.

**Comment by yasvanth** [comment]
Should erase brower cookies or to set searchgurad_authentication cookie to false

**Comment by floragunncom** [comment]
Erase the browser cookie please

**Comment by yasvanth** [comment]
I have made config changes today to create two user.

**Comment by yasvanth** [comment]
I have cleared the cookies and tried to login using admin:admin  kibana lets me in. I have tried in firefox and chrome Including private browsing .

**Comment by floragunncom** [comment]
Ok, this is very weird then, we have not heard from such a behavior before. Can you please send me your current configuration, including the two new users, again? I'm trying to reproduce the behavior locally then.

**Comment by yasvanth** [comment]
[sg_internal_users.txt](https://github.com/floragunncom/search-guard/files/879665/sg_internal_users.txt)
[sg_roles.txt](https://github.com/floragunncom/search-guard/files/879667/sg_roles.txt)
[sg_roles_mapping.txt](https://github.com/floragunncom/search-guard/files/879666/sg_roles_mapping.txt)
[sg_config.txt](https://github.com/floragunncom/search-guard/files/879664/sg_config.txt)

**Comment by floragunncom** [comment]
Can you also send the actiongroups please?

Another thing, can you:

1. Stop your node
2. Delete logfiles and enable trace mode (see below)
3. Start the node again
4. Use Kibana to log in with admin/admin
5. Send me the elasticsearch log file

You enable trace mode by adding these two lines in config/log4j.properties:

logger.fg.name = com.floragunn
logger.fg.level = trace

Thanks!

**Comment by yasvanth** [comment]
ALL:
  - "indices:*"
MANAGE:
  - "indices:monitor/*"
  - "indices:admin/*"
CREATE_INDEX:
  - "indices:admin/create"
  - "indices:admin/mapping/put"
MANAGE_ALIASES:
  - "indices:admin/aliases*"
MONITOR:
  - "indices:monitor/*"
DATA_ACCESS:
  - "indices:data/*"
  - "indices:admin/mapping/put"
WRITE:
  - "indices:data/write*"
  - "indices:admin/mapping/put"
READ:
  - "indices:data/read*"
DELETE:
  - "indices:data/write/delete*"
CRUD:
  - READ
  - WRITE
SEARCH:
  - "indices:data/read/search*"
  - "indices:data/read/msearch*"
  - SUGGEST
SUGGEST:
  - "indices:data/read/suggest*"
INDEX:
  - "indices:data/write/index*"
  - "indices:data/write/update*"
  - "indices:admin/mapping/put"
  # no bulk index
GET:
  - "indices:data/read/get*"
  - "indices:data/read/mget*"

# CLUSTER
CLUSTER_ALL:
  - cluster:*
CLUSTER_MONITOR:
  - cluster:monitor/*
CLUSTER_COMPOSITE_OPS_RO:
  - "indices:data/read/mget"
  - "indices:data/read/msearch"
  - "indices:data/read/mtv"
  - "indices:data/read/coordinate-msearch*"
  - "indices:admin/aliases/exists*"
  - "indices:admin/aliases/get*"
CLUSTER_COMPOSITE_OPS:
  - "indices:data/write/bulk"
  - "indices:admin/aliases*"
  - CLUSTER_COMPOSITE_OPS_RO

**Comment by yasvanth** [comment]
I have attahced the log file after enabling trace and tried to login with admin:admin from kibana 


[test_cluster.txt](https://github.com/floragunncom/search-guard/files/879737/test_cluster.txt)

**Comment by floragunncom** [comment]
Hm ... I do not see any access to this node from Kibana, just the startup sequence of Elasticsearch. Are you sure this is the complete logfile? There should be some entries from a class called PrivilegesEvaluator in there. Can you check that Kibana is atually using the node you send me the lgofile from?

**Comment by yasvanth** [comment]
Hi,
There is no class entries I have even attached kiban.yml and es.yml

[kibana.txt](https://github.com/floragunncom/search-guard/files/879863/kibana.txt)
[elasticsearch.txt](https://github.com/floragunncom/search-guard/files/879864/elasticsearch.txt)

**Comment by floragunncom** [comment]
Hm. With the kibana.yml you sent Kibana won't start, because the host is not set correctly:

elasticsearch.url: "<https://elastic node:9200>"

**Comment by yasvanth** [comment]
I removed the host name while uploading.

**Comment by yasvanth** [comment]
I have removed the host name while uploading the .yml to git

**Comment by yasvanth** [comment]
elasticsearch.url: "https://<ip_address>:9200"

**Comment by yasvanth** [comment]
Hi, 

When I use below config in kibana.yml and tried logging-in again with admin:admin, testac, and idptest. I got an error.

`console.proxyConfig:`
 ` - match:`
      `protocol: "https"`
    `ssl:`
      `verify: false`

The error is 

> An error occurred while checking your credentials, make sure your have a running Elasticsearch cluster secured by Search Guard running.

If I remove the config I can access the index even from admin:admin


Thanks,

 Yash

**Comment by yasvanth** [comment]
Hi I have changed the reinstalled kibana, now it works as to be, but In kibana I get an empty page.
Here are the elasticsearch log, I think about the permissions.

[test_cluster copy.txt](https://github.com/floragunncom/search-guard/files/881568/test_cluster.copy.txt)

**Comment by yasvanth** [comment]
sorted by reinstalling kibana,
I opened new issue on permission. 
Thanks,
Yash
