### ISSUE TITLE
support for 5.3.0

### ISSUE THREAD

**Issue by Khezen** [floragunncom/search-guard#315]
feature request: support for 5.3.0

**Comment by floragunncom** [comment]
working on that ...

Would be great if you can help with some tests?

**Comment by floragunncom** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-5/5.3.0-11-SNAPSHOT/search-guard-5-5.3.0-11-20170329.222527-2.zip

**Comment by floragunncom** [comment]
is it working for you?

**Comment by Khezen** [comment]
Hi,

Thank you for sharing this. I haven't tested yet. I amgoing to publish it under a new tag(khezen/elasticsearch:searchguard-testing) as soon as elasticsearch release 5.3 tag on the dockerhub.

I'll keep you posted.

**Comment by Khezen** [comment]
It took a little bit more time as [previous official docker image](https://github.com/docker-library/elasticsearch)  is deprecated in favour of elasticsearch/elasticsearch:[version] which is built with X-Pack. So I had to work harder than expeted. 

I just published elasticsearch 5.3.0 including your SNAPSHOT to (khezen/elasticsearch:searchguard-testing)[https://hub.docker.com/r/khezen/elasticsearch].

I am going to test it soon but you can already use it for on your own. 

It would be great if you could publish a SNAPSHOT to your [maven repo](https://mvnrepository.com/artifact/com.floragunn/search-guard-5)   so I can keep searchguard-testing tag up to date with your current development with no effort.

**Comment by floragunncom** [comment]
released
