### ISSUE TITLE
No permissions for indices:data/read/search with version 5

### ISSUE THREAD

**Issue by yasvanth** [floragunncom/search-guard#316]
Hi,
I am having the same issue same like [https://github.com/floragunncom/search-guard/issues/220#issuecomment-266231401](url) 

> [2017-03-30T15:23:52,879][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=idptest, roles=[]] [IndexType [index=idp_test, type=*], IndexType [index=idp_test-2017.03.27, type=*], IndexType [index=searchguard, type=*], IndexType [index=.kibana, type=*], IndexType [index=testidp, type=*]] [Action [indices:monitor/stats]] [RolesChecked [sg_own_index, sg_user_idp]]

> index is "idp_test-2017.03.01"
So I declared the index as idp_test-* 
I even tried with idp_test*

sg_roles.yml 

sg_user_idp:
  cluster:
      - '*'
  indices:
    'idp_test-*':
      '*':
        - READ
        - indices:monitor/stats
        - indices:admin/mappings/fields/get*
        - indices:admin/validate/query
        - indices:admin/get
    '?kibana':
      '*':
        - indices:admin/exists*
        - indices:admin/mapping/put*
        - indices:admin/mappings/fields/get*
        - indices:admin/refresh*
        - indices:admin/validate/query*
        - indices:data/read/get*
        - indices:data/read/mget*
        - indices:data/read/search*
        - indices:data/read/msearch
        - indices:data/read/field_stats
        - indices:data/write/delete*
        - indices:data/write/index*
        - indices:data/write/update*
        - indices:admin/mappings/fields/get*

Thanks,
Yash

**Comment by floragunncom** [comment]
Please format you post, your config looks strange. Whats your SG and ES version and your Query?

If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by yasvanth** [comment]
Hi,
I am using ES 5.2, Sg 5.2.2-11 and kibana 5.2 . 
Java 1.8, 3 node cluster, 

I have two users testidp(index= testidp) and idptesp(index=idpt_test-*). these users needs to access their own index. when I access using curl I get an issue  

> error 403 Security exception.
In log file I can see error as 
> [2017-03-30T15:23:52,879][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=idptest, roles=[]] [IndexType [index=idp_test, type=], IndexType [index=idp_test-2017.03.27, type=], IndexType [index=searchguard, type=], IndexType [index=.kibana, type=], IndexType [index=testidp, type=*]] [Action [indices:monitor/stats]] [RolesChecked [sg_own_index, sg_user_idp]]


The issue and requirements are same.
[https://github.com/floragunncom/search-guard/issues/220#issuecomment-266231401](url)


Thanks,
Yash

**Comment by floragunncom** [comment]
The link does not work

**Comment by yasvanth** [comment]
The previous issue #220

**Comment by yasvanth** [comment]
@floragunncom ping. 
I have two index: userIndex1-<date> which should be access by user1 and userIndex2-<date> which should be accessible by user2.

Version:
JVM 1.8
ES: 5.2.2
kibana: 5.2.2
SG 5.2.2 v11
3 node cluster 

My config are: 
sg_roles.yml
`sg_role_user1:`
`     cluster:`
`       - CLUSTER_COMPOSITE_OPS`
`     indices:`
`       'userIndex1-*':`
`              '*':`
`                - ALL`
`       '?kibana':`
`           '*':`
`                 - ALL`       

`sg_role_user2:`
`     cluster:`
`       - CLUSTER_COMPOSITE_OPS`
`     indices:`
`       'userIndex2-*':`
`              '*':`
`                - ALL`
`       '?kibana':`
`           '*':`
`                 - ALL` 


sg_roles_maping.yml

`sg_roles_user1:`
`      users:`
`           - user1`
`sg_roles_user2:`
`       users:`
`           - user2`

when I login to kibana with user1 I can access to userIndex1-<date> but if I login with user2 
I get 
> No permission for indices:data/search 

In elasticsearch log 
> No Perm for User [name=used, roles=[]] [IndexType [index=_all, type=*]] [Action [indices:data/read/search]] [RolesChecked [sg_own_index, sg_role_user1]]

**Comment by floragunncom** [comment]
Pls. format your post to make the config readable

**Comment by yasvanth** [comment]
Is that fine?

**Comment by floragunncom** [comment]
no, try adding &lt;pre&gt; &lt;/pre&gt; around your code, see also https://guides.github.com/features/mastering-markdown

**Comment by yasvanth** [comment]
Thanks @floragunncom

**Comment by floragunncom** [comment]
As asked above: Whats your query?

**Comment by yasvanth** [comment]
When  create a separate roles for each user the first roles is executed. If  user1 logs-in and have permission the index userindex1. but when I try to login as second user permission error and cant view the index.

If it try to create user based on index name ( using sg_own_index) then works as expected.

**Comment by floragunncom** [comment]
No feedback, assume solved

**Comment by waveter** [comment]
I am still having the same problem

**Comment by floragunncom** [comment]
@waveter pls open a **new issue and provide** 

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* Steps to reproduce
* Your elasticsearch.yml and all sg_*.yml config files

Pls also note that we do not longer support elasticsearch versions which are older than 5.6.8 according to our end of life policy
