### ISSUE TITLE
indices:data/read/scroll/clear is ignored in sg_roles.yml

### ISSUE THREAD

**Issue by lemig** [floragunncom/search-guard#319]
Hello,

Here is the environment and description of the issue.

* Search Guard and Elasticsearch version
SG 2.4.4.11 - ES 2.4.4
KIBI EE 4.6.4

* JVM version and operating system version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
Windows 7 Enterprise

* Number of nodes in your cluster
1

* Description of the bug
My permission in the [sg_roles.yml](https://gist.github.com/lemig/42a22f46520f68fa05f28cad953aa242) for kibiadmin to  indices:data/read/scroll/clear is ignored.
I keep getting:
[2017-03-31 11:30:35,377][INFO ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] No perm match for User [name=kibiadmin, roles=[]] [IndexType [index=_all, type=*]] [Action [indices:data/read/scroll/clear]] [RolesChecked [kibiadmin]]

Any hint?

Miguel

**Comment by floragunncom** [comment]
add `"indices:data/read/scroll*"` to cluster level permissions:

<pre>
kibiadmin:
  cluster:
    - KIBI_CLUSTER
    - cluster:admin/plugin/siren/license/put
    - "indices:data/read/scroll*"
  indices:
    '*':
      '*':
        - KIBI_READONLY
        - indices:data/read/scroll/clear
        - indices:data/write/index
        - indices:data/write/read
        - indices:data/write/delete
        - indices:data/write/update
    'watcher':
      '*':
        - KIBI_READWRITE
    '?kibi':
      '*':
        - KIBI_READWRITE
</pre>

**Comment by floragunncom** [comment]
does this work?

**Comment by lemig** [comment]
Oups. Just tested.
Problem solved!
Thanks.
