### ISSUE TITLE
Permissions issue with indices:data/write/bulk[s]

### ISSUE THREAD

**Issue by lancemind** [floragunncom/search-guard#320]

**Comment by lancemind** [comment]
Moved to google groups

**Comment by floragunncom** [comment]
Google groups link: https://groups.google.com/forum/#!topic/search-guard/9O5TgdkDlrc

Elasticsearch does have a breaking change in 5.3 regarding how index is handled, see also https://github.com/elastic/elasticsearch/pull/22812
and https://groups.google.com/d/msg/search-guard/pgwf1VsUL2s/jYfL7dFnAgAJ
