### ISSUE TITLE
put together all plugins on same website

### ISSUE THREAD

**Issue by rptete** [floragunncom/search-guard#323]
Why not put the kibana plugins in the following path:

**http://repo1.maven.org/maven2/com/floragunn/kibana/
     - all kibana plugins**

like:

http://repo1.maven.org/maven2/com/floragunn/search-guard-2/
     - all searchguard-2 plugins

http://repo1.maven.org/maven2/com/floragunn/search-guard-5/
     - all searchguard-5 plugins

http://repo1.maven.org/maven2/com/floragunn/dlic/
     - all searchguard dlics

it would be more ordered and it would be easier to take control of new versions, etc.

and this repositories??
https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-5/
i dont understand...

**Comment by floragunncom** [comment]
We will consider pushing the kibana plugin to maven central, thx for the suggestion.

Regarding `https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-5/`: This is the snapshot repo like described in https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version

**Comment by floragunncom** [comment]
Unfortunately maven central rules does not allow to publish a single zip (without things like source, javadoc, etc which does not fit into the JS world of kibana). 

We're evaluating other options like bintray but until evaluation is finished we continue with shipping releases via github.
