### ISSUE TITLE
Add HashiCorp Vault support

### ISSUE THREAD

**Issue by floragunncom** [floragunncom/search-guard#325]
Add support for retrieving settings like SSL certificates or Keystore passwords from Vault.

**Comment by alejojo** [comment]
would it be possible to add also free-ipa certs support? I can create a new issue

https://www.freeipa.org/page/Certmonger
https://www.freeipa.org/page/PKI

**Comment by myoung34** [comment]
Is this still a viable feature request? Im doing this manually using the PKI backend and would love to rip some code out

**Comment by floragunncom** [comment]
no active work on this currently, assume within this year

**Comment by tamalsaha** [comment]
Is there any update on this issue?

**Comment by kgunnerud** [comment]
Any progress?

**Comment by floragunncom** [comment]
We will not implement this in the near future. Any contribution is very welcomed but it seems Vault is not (yet) common enough.
