### ISSUE TITLE
Issue with deleting index with wildcards

### ISSUE THREAD

**Issue by d-ng** [floragunncom/search-guard#332]
Search Guard Version 5.2.2 
Elasticsearch Version 5.2.2
JVM 1.8.0_121
OS Windows Server 2016

User have sgamin_all_access:

<pre>
sg_all_access:
  cluster:
  - "*"
  indices:
    '*':
      '*':
      - "*"
</pre>

When I tried to delete indices using wildcards, etc. https://hostname:9200/test*:
- if there are matching indices, the operation goes through
- if there are no matching indices, search guard throws the error:
Type: security_exception
Reason: "no permissions for indices:admin/delete"

This is very misleading. On the other hand, if you look at behavior in Elasticsearch without search guard, the delete operation goes through whether there are matching indices or not.

**Comment by floragunncom** [comment]
We consider this for the next release, thy for reporting
