### ISSUE TITLE
Cache not flushed when updating single configuration files

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard#334]
* Search Guard and Elasticsearch version
  * SG and ES 5.3.2
* JVM version and operating system version
  * Mac El Capitan, Oracke JDK 1.8.0_31
* Number of nodes in your cluster
  * 3

If you execute sgadmin with the -cd flag, then the internal caches seem to be flushed. However, if you just update a single config files, caches are not flushed.

To Reproduce:
* Add a user to the internal user database, e.g. via the REST management API
* Upload a sg_internal_users.yml file that does not contain the added user

Expected result:
* Cache was flushed, log in with added user not possible

Actual result:
* Cache was not flushed, log in with added user still possible

**Comment by brainless81** [comment]
!
