### ISSUE TITLE
No permittedAliasesIndex 'admin' found for 'indices:data/read/search'

### ISSUE THREAD

**Issue by yuexiuqi** [floragunncom/search-guard#338]
if the index has multi filtered alias ,then i can't access my data with 'admin' && sg_access_all role. 

some log info:
More than one filtered alias found for same index.This is currently not supported
No perm match for user [name=admin,roles=[]]
No permissions for indices:data/read/search

what config should i do to make it work?
thanks !

**Comment by floragunncom** [comment]
Duplicate of https://github.com/floragunncom/search-guard/issues/190
