### ISSUE TITLE
Improve error message on key- and truststore location

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard#339]
Some users are confused/don't know about the requirement to put the key- and truststore files (or PEM certs for that matter) in the config folder of ES.

While ES does not allow placing these outside the config directory, we should improve the error message we log, to make the root cause more obvious.

**Comment by floragunncom** [comment]
This is an issue for the SSL plugin, lets track it there (https://github.com/floragunncom/search-guard-ssl/issues/58)
