### ISSUE TITLE
 Keystore was tampered with, or password was incorrect

### ISSUE THREAD

**Issue by kumar1993** [floragunncom/search-guard#340]
I have generated the keystore files and the truststore files using the example script in the search-guard-ssl repository, but when i run search guard with these files as the keystore and truststore files, i am getting  Keystore was tampered with, or password was incorrect.

Below is the configuration: 
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_filepath: node-0-keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-0-keystore.jks
searchguard.ssl.http.truststore_filepath: truststore.jks

searchguard.ssl.transport.keystore_password: key@123
searchguard.ssl.transport.truststore_password: trust@123
searchguard.ssl.http.keystore_password: key@123
searchguard.ssl.http.truststore_password: trust@123

**Comment by jochenkressin** [comment]
Does not seem like a bug. Have you used the example scripts unchanged? The default password for the generated key- and trustores is "changeit"

**Comment by kumar1993** [comment]
I have changed the default password, you can see them in the properties

**Comment by floragunncom** [comment]
This is very likely not a bug so i'd like to discuss this in the google groups list to give other users a chance to help you: https://groups.google.com/forum/#!forum/search-guard

<hr>
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
