### ISSUE TITLE
Logout for SSO

### ISSUE THREAD

**Issue by yasvanth** [floragunncom/search-guard#342]
* Search Guard = 5 v11 and Elasticsearch = 5.2   
* JVM version 1.8 , operating system version Ubuntu 16.04
* Number of nodes in your cluster = 2 nodes 

Hi,

I have my ES setup  behind proxy SSO (using apache and  shibboleth sp) . Authentication is working fine as required. When I try to logout browser throws an error shown below:
![screen shot 2017-05-10 at 13 39 36](https://cloud.githubusercontent.com/assets/13409183/25899046/39caab88-3586-11e7-8e8d-f355446848df.png)

Is there any way where I can set redirect to an page which show "Close the browser to exit the application" 

Thanks
Yash

**Comment by floragunncom** [comment]
Can you post your kibana.yml - Normally you should not see any "Logout Button"

**Comment by yasvanth** [comment]
Hi,
I have attached my kibana.yml file. As you mentioned that I shouldn't see logout button but Logout button is available.

[kibana.txt](https://github.com/floragunncom/search-guard/files/1040977/kibana.txt)

**Comment by jochenkressin** [comment]
Ok, this is a bug then, the logout button should not be available when basic auth is set to false, since it does not make sense in this case

**Comment by yasvanth** [comment]
Will it because I use proxy order 0 and basic auth as 2. If i remove basic auth Kibana requires authentication 3 time. Each click I made is done by form- authentication.

**Comment by jochenkressin** [comment]
Fixed with v3 release of the Kibana Plugin.
