### ISSUE TITLE
Disable X-Pack Welcome screen

### ISSUE THREAD

**Issue by mat1010** [floragunncom/search-guard#345]
Hi,

I'm running the full ELK 5.4.0 stack with the kibana searchguard plugin `searchguard-kibana-5.4.0-2` and the elasticsearch searchguard plugin `com.floragunn:search-guard-5:5.4.0-12` on a `Centos 7.3.1611` with `java 1.8.0_121`. 

The cluster contains 1 master node on which also the kibana and logstash are located and 2 data/master nodes.

Searchguard restrictions and authentication is working perfectly fine. The issue I'm having is that the "X-Pack Welcome screen" is always being displayed even when disabled in kibana: [Screenshot](https://cloud.roterruler.de/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=624&a=true&file=x-pack-welcome-screen.JPG&t=KB7l2YXijUFyOuu&scalingup=0)

For me it looks like this is caused by the fact that querying settings within the kibana index for the value of `xPackMonitoring:showBanner` and `xPackMonitoring:allowReport` is not allowed while unauthenticated:
`Failed to load resource: the server responded with a status of 403 (Forbidden) /api/kibana/settings`

Is this a known issue / is this working correct for someone else who's running parts of x-pack in parallel with searchguard?

Thanks in advance.

**Comment by floragunncom** [comment]
We will look into this ...

**Comment by any1one** [comment]
I'm havign the same issue here, same setup.

**Comment by jochenkressin** [comment]
This likely affects all users who run X-Pack in parallel with Search Guard. Your analysis of the problem is correct, it's unauthenticated requests from the X-Pack plugin. We're working on a solution, but it might take some more time to find the best one.

**Comment by jochenkressin** [comment]
We've prepared a snapshot which will hopefully fix the issue with the welcome screen. However, if you're using multi tenancy as well, theres one caveat:

Since the settings for the welcome screen are stored in the global Kibana index, you need to opt-out for each tenant separately. We might improve this by copying the settings automatically, but this will require changes to the ES multitenancy module as well.

If you want to give the snapshot a try, please find it here:
https://cdn.filestackcontent.com/CvVSU9jLRUe7w4mqMZ9w

**Comment by mat1010** [comment]
First of all: Thank you verfy much for the quick support!

> However, if you're using multi tenancy as well, theres one caveat:

That's not an issue for me since we're not using the multi tenancy feature yet. We are not even planning todo so in the future.

Unfortunately I'm not able to get the snapshot working. Here's what I did:

* Create a backup of the existing searchguard-kibana plugin
* Replace `/usr/share/kibana/plugins/searchguard` with `kibana/searchguard-kibana` from the zip file
* set ownerships on `/usr/share/kibana/plugins/searchguard` to kibana:kibana
* restart kibana

Once the restart did complete successfully - the welcome message on the login screen is gone!

But somehow logging in is not working anymore - no matter which user I take. The message `An error occurred while checking your credentials, make sure your have a running Elasticsearch cluster secured by Search Guard running.` is being displayed once login has been clicked.

Following URL is being reported with a 404 while logging in:
`https://kibana.bahag.com/searchguard/api/v1/auth/login 404 (Not Found)`

And there's also the 403 for the xpack api call:
`https://kibana.bahag.com/api/xpack/v1/info 403 (Forbidden)`

Rolling back to the original version brings everything back to the initial behaviour with a working login. 

One more additional side note - when changing the following line in the `index.js` of the snapshot version 
```
-            APP_ROOT = '';
+            APP_ROOT = '/searchguard';
```
I get back to the initial state **WITH** the welcome message and a **WORKING** login without rolling back the whole plugin. 

Do I need to change something else beside replacing the kibana-searchguard-plugin?

Thx in advance,
mat1010

**Comment by jochenkressin** [comment]
Hi!

yes, the point of this snapshot release is to change the URL structure and remove the "searchguard" part. The X-Pack plugins contain some hardcoded paths, especially "/login" and "/logout", which our plugin needs to resemble. Otherwise, the Welcome Screen ist displayed on the login screen (where we don't have any authorized user) instead of Kibana (where we are past the login screen and have an authenticated user).

So, if you change the APP_ROOT back to "searchguard", you will see the old behavior again. The snapshot works here locally and on our integration systems, so could you please first check if it works if you start with a fresh browser, i.e. no cookies and an empty local and session storage?

Thanks!

**Comment by floragunncom** [comment]
@mat1010 ping - does it work for you with an "empty" browse, i.e. no cookies or local/session storage?

**Comment by mat1010** [comment]
Sorry for the missing reply. I tested it with a completly fresh browser and had some of my co-workers testing it - also running fresh / private sessions. Same issue on all systems and browsers. I hadn't replied yet since I wanted to doublecheck our apache reverseproxy settings so that they do not have any negative impact. I will report back once I was able to verify that.

**Comment by jochenkressin** [comment]
Ok, thanks and no problem. We will have another look at this tomorrow, the message:

An error occurred while checking your credentials, make sure your have a running Elasticsearch cluster secured by Search Guard running.

Means that the call from the plugin to /_searchguard/authinfo to authenticate the user has failed or this endpoint is not reachable on ES. Please have a look at your proxy settings, and we will also double-check the plugin code tomorrow. Like I said, it works here, so I'm positive we can find the missing bit quickly. Thanks for your input and tests!

**Comment by zqc0512** [comment]
I have the problem also.  ES 5.4.2  search-guard is 5.4.2-14   the kibana is searchguard-kibana-5.4.2-3.zip
i only have change the APP_ROOT to ''; 
the x-pack welcome pages not see , but can't log in to kibana
with out "An error occurred while checking your credentials, make sure your have a running Elasticsearch cluster secured by Search Guard running.";
thanks 
@jochenkressin

**Comment by floragunncom** [comment]
@zqc0512 Changing only the APP_ROOT in index.js is not enough, please diff the 5.4.0 branch against the 5.4.0-monitoring branch to see all changes.

**Comment by zqc0512** [comment]
@floragunncom  i use search-guard 5.4.2.3 can use u give 5.4.0?
can use this:https://cdn.filestackcontent.com/CvVSU9jLRUe7w4mqMZ9w  ?
thanks.

**Comment by zqc0512** [comment]
@floragunncom 
can tell me where change about it ?
thanks.

**Comment by floragunncom** [comment]
http://floragunncom.github.io/search-guard-docs/kibana.html
"First download the Search Guard Kibana plugin matching your Kibana version from github"

No, the versions need to match, that's a limitation by Kibana.

For the changes, just make a diff the between 5.4.0 branch against the 5.4.0-monitoring. The code is completely public.

**Comment by mat1010** [comment]
@jochenkressin @floragunncom 

I have it working now.
Here are the proper steps for a successfull upgrade:

* Remove the current kibana-searchguard plugin
* Restart kibana to have all caches rebuild *WITHOUT* the searchguard plugin
* Once the restart completed without the searchguard plugin, place the *new* version of the plugin into `/usr/share/kibana/plugins/searchguard` and do another restart. Now the plugin should work like expected.

Thanks a ton for the great work! Looking foward to see this in the stable release.

**Comment by jochenkressin** [comment]
Oh, great that you got it working, and thanks very much for your input. Bloody caching again ;) We'll  document this once v4 of the plugin with the X-Pack support is out.

**Comment by zqc0512** [comment]
@jochenkressin @floragunncom 
i use search-guard-kibana 5.4.2   when the V4 plugin can out put to use ?
thanks.

**Comment by floragunncom** [comment]
@zqc0512 Try this snapshot for 5.4.2: https://cdn.filestackcontent.com/8iA0PPUXQtOtdMyqkIun

In order to avoid caching problems, please follow @mat1010 advise above.
