### ISSUE TITLE
Can't restore backup

### ISSUE THREAD

**Issue by sfroment** [floragunncom/search-guard#348]
Hello,

I'm  trying to restore my db but I always get: ```{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for cluster:admin/snapshot/restore"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for cluster:admin/snapshot/restore"
  },
  "status" : 403
}```

So I searched in the doc and find this https://github.com/floragunncom/search-guard-docs/blob/master/snapshots.md.
Even my creating a new roles in sg_roles.yml and applied it, it doesn't change anything.
On the server side: ```2017-5-31 17:22:18[2017-05-31T15:22:18,904][WARN ][c.f.s.c.PrivilegesEvaluator] cluster:admin/snapshot/restore is not allowed for a regular user
```
I think I'm missing a point there...

search guard version 5.2.2

**Comment by floragunncom** [comment]
See https://github.com/floragunncom/search-guard-docs/blob/master/snapshots.md

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
