### ISSUE TITLE
kibana Unable to revive connection elasticsearch

### ISSUE THREAD

**Issue by andryzhu** [floragunncom/search-guard#350]
Hi,
elasticsearch 5.3.0 has  installed Search Guard 5 and Kibana 5.3.2 has installed Search Guard 5
My certificates use the TLS generator service

es cluster node 1 elasticsearch.yml configed:
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: 192.168.1.122-keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.keystore_password: "da4816291ba"
searchguard.ssl.transport.truststore_password: "3e2a441a72f"
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: 192.168.1.122-keystore.jks
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.keystore_password: "da4816291ba"
searchguard.ssl.http.truststore_password: "3e2a441a72f"
searchguard.ssl.http.clientauth_mode: OPTIONAL
searchguard.authcz.admin_dn:
  - CN=sgadmin

es cluster node 2 elasticsearch.yml configured:
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: 192.168.1.121-keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.keystore_password: "da4816291ba"
searchguard.ssl.transport.truststore_password: "3e2a441a72f"
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: 192.168.1.122-keystore.jks
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.keystore_password: "da4816291ba"
searchguard.ssl.http.truststore_password: "3e2a441a72f"
searchguard.ssl.http.clientauth_mode: OPTIONAL
searchguard.authcz.admin_dn:
  - CN=sgadmin

kibana's kibana.yml configured:
elasticsearch.url: "https://192.168.1.122:9200"
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
elasticsearch.ssl.verificationMode: none
elasticsearch.ssl.verify: true
searchguard.basicauth.enabled: true
searchguard.cookie.secure: false
searchguard.cookie.name: 'searchguard_authentication'
searchguard.cookie.password: 'searchguard_cookie_default_password'

after start es cluster all nodes and  kibana ,I see the following warn in kibana log:
{"type":"log","@timestamp":"2017-06-02T06:51:11Z","tags":["warning","elasticsearch","admin"],"pid":33426,"message":"No living connections"}
{"type":"log","@timestamp":"2017-06-02T06:51:14Z","tags":["warning","elasticsearch","admin"],"pid":33426,"message":"Unable to revive connection: https://192.168.1.122:9200/"}
{"type":"log","@timestamp":"2017-06-02T06:51:14Z","tags":["warning","elasticsearch","admin"],"pid":33426,"message":"No living connections"}
{"type":"log","@timestamp":"2017-06-02T06:51:17Z","tags":["warning","elasticsearch","admin"],"pid":33426,"message":"Unable to revive connection: https://192.168.1.122:9200/"}
{"type":"log","@timestamp":"2017-06-02T06:51:17Z","tags":["warning","elasticsearch","admin"],"pid":33426,"message":"No living connections"}

how can i do ?

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
