### ISSUE TITLE
Global tenant selected as default even if disabled in config

### ISSUE THREAD

**Issue by faxm0dem** [floragunncom/search-guard#351]
When disabling the Global tenant using `searchguard.multitenancy.tenants.enable_global: false`, it is still the default tenant which gets selected on a clean browser start (empty cookies I guess).
The consequences are one of the following:

1. if the `.kibana` index exists, the users are hitting a tenant they cannot select in the list. This is very confusing.
2. if the index doens't exist, they are greeted by a "red cluster" welcome page

**Comment by jochenkressin** [comment]
Thanks, we will include a fix for this in the next Plugin version, which will be released with SG13. Expected release date is in approx. 2 weeks.

**Comment by jochenkressin** [comment]
Fixed with v3 release of the Kibana Plugin.
