### ISSUE TITLE
how to configure search guard plugin

### ISSUE THREAD

**Issue by karampuri** [floragunncom/search-guard#354]
Hi,

I installed search guard-5 plugin as following link
https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle
i installed perfectly but how to configure it i don't know.
please assist me.

**Comment by jochenkressin** [comment]
Please don't ask question here, GitHub is for reporting bugs only. For questions, refer to our Google Group:

https://groups.google.com/forum/#!forum/search-guard

For configuration instructions, please refer to our documentation:

http://floragunncom.github.io/search-guard-docs/
