### ISSUE TITLE
Searchguard 5 & Kibana: Authentification Logout Redirect Problem

### ISSUE THREAD

**Issue by qnguyen050216** [floragunncom/search-guard#355]
Hello,

I have a problem with Searchguard5 (nginx & LDAP/AD Authen)

- For the first connexion/authentification or when I change Tab Browser: on my Kibana Site I got URL:
https:/mysite/searchguard/login?nextUrl=%2F#?_g=() 
==> Then I can see the Kibana Dashboard when I logged in.
- But for the next connexions/authentification or when I stay on the same Tab Browser when logged out: On my Kibana site I got this URL: https:/mysite/searchguard/login#?_g=()
==> Then I will be redirect to another site (not Kibana Site) when I logged in.

- Furthermore, I made some changes in JS file (apps/login/login_controller.js) to have the correct redirect but my changes were not applied on the Kibana site??? No changes on JS files were applied on Kibana.

Could you please help me. I took a lot of time to understand this issue?

Thanks in advance!

**Comment by floragunncom** [comment]
Pls provide

* Search Guard, Kibana and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* sg_config.yml
* kibana.yml

**Comment by floragunncom** [comment]
no feedback, assume solved
