### ISSUE TITLE
Access cluster health when SG Not yet initialized.

### ISSUE THREAD

**Issue by apenen** [floragunncom/search-guard#356]
Hi.

It's possible to access the cluster health when searchguard index is corrupt?
I can't see if elasticsearch is syncing or not.

**Comment by floragunncom** [comment]
Use the --diagnose option of sgadmin but please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
