### ISSUE TITLE
No dot (.) in the regex (Define roles and their associated permissions)

### ISSUE THREAD

**Issue by breml** [floragunncom/search-guard#358]
The documentation states in [Define roles and their associated permissions](https://github.com/floragunncom/search-guard-docs/blob/master/configuration.md#define-roles-and-their-associated-permissions), that it is not allowed to us the dot (.) in the regex.

Today I stumbled over this limitation and I have the following suggestions:
* The best solution of course would be to remove this limitation, because it is awkward to offer regex but at the same time limit it in such way
* Explain in the documentation, what the reason for this limitation is.
* Add examples, how this could be completely replaced (workaround)
  * `.` == `(\S|\s)` and `.*` == `(\S|\s)*`
  * `[.]`, `[\.]` or `\.` == `\x2E`

This would have helped me today.

**Comment by floragunncom** [comment]
thx, will add this to the docs and example files

**Comment by floragunncom** [comment]
Can you please try if dots are working (regardless of the documented limitation) if you are on ES >= 5.0.0

**Comment by breml** [comment]
I did try dots first, and it did not work, but I did not dig into the details, after I saw the comment in the documentation.
