### ISSUE TITLE
when a machine have many node how can run sgadmin_demo.sh

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#359]
@ewolinetz 
WARNING: JAVA_HOME not set, will use /bin/java
Search Guard Admin v5
Will connect to **localhost:9300 ... done**

### LICENSE NOTICE Search Guard ###
how can change the port of sgadmin_demo.sh connect....
thanks.

**Comment by zqc0512** [comment]
@bitmelt 
i need **connect to 9301 not 9300** 
how can change it ?
thanks.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
