### ISSUE TITLE
Can't use open ssl

### ISSUE THREAD

**Issue by jimiyi** [floragunncom/search-guard#361]
I put  netty-tcnative-openssl-1.0.2-dynamic-2.0.1.Final-fedora-linux-x86_64.jar into plugins/shard-guard-5, my openssl version is 1.0.2l, but when I start elastic search, the log report:
[2017-07-10T10:58:53,788][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-linux-x86_64, netty-tcnative-linux-x86_64-fedora, netty-tcnative]

**Comment by floragunncom** [comment]
Did you install Apache Portable Runtime (apr)?

Look here for details: https://github.com/floragunncom/search-guard-docs/blob/master/tls_openssl.md

<hr/>

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
