### ISSUE TITLE
how to connect 9300 when search-guard is enabled

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#363]
whe search-guard is enabled ,how can spark connect to 9300(transport.port),
spark use 9300 write data to es, now is auth ,how to configre it.
thanks.
@floragunncom

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by zqc0512** [comment]
I can't connect to 9300 , spark client  how to set , the network can't connect to google group,thanks.
can give me a doc .
thanks.
@floragunncom
