### ISSUE TITLE
install_demo_configuration creates config in an incorrect location

### ISSUE THREAD

**Issue by jaksmid** [floragunncom/search-guard#370]
Hello, I am using docker to try out search guard. I am deriving my image from elasticsearch:5 image.
However, when I run `install_demo_configuration.sh` as per the documentation, further steps in the doc do not work.

I noticed is that the script figures out the location of the config incorrectly.
So if add the following to my docker build after the `install_demo_configuration.sh`, everything works fine.

```
RUN cat /etc/elasticsearch/elasticsearch.yml > config/elasticsearch.yml
RUN mv -v /etc/elasticsearch/* /usr/share/elasticsearch/config/
```

It would be great to fix the script or at least put a warning into the documentation.
Regards,
Jakub

**Comment by floragunncom** [comment]
What is your ES and SG Version? What is the installation layout in the elasticsearch:5 image (the installer currently support tar.gz/deb/rpm). 

Do you get an error message when executing `install_demo_configuration.sh`? If yes pls. post it. If no what are the further steps which did not succeed? Pls. share also your Dockerfile so that we can easily try to reproduce this.

Regarding a fix or a doc warning note: Why not submit a PR for it?

**Comment by jaksmid** [comment]
Hello,

I am happy to create a PR but at the moment I am not really sure what is the best fix.

My docker is as follows:

My Dockerfile is as follows:

```
FROM elasticsearch:5

RUN apt-get update
RUN apt-get -y install sudo

RUN sudo bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.5.0-14
RUN chmod 777 plugins/search-guard-5/tools/install_demo_configuration.sh
RUN echo y | sudo plugins/search-guard-5/tools/install_demo_configuration.sh
RUN cat /etc/elasticsearch/elasticsearch.yml > config/elasticsearch.yml
RUN mv -v /etc/elasticsearch/* /usr/share/elasticsearch/config/
RUN sed -i 's\/etc/elasticsearch/\/usr/share/elasticsearch/config/\g' sgadmin_demo.sh
RUN chmod 777 sgadmin_demo.sh
RUN sed -i 's\searchguard.ssl.http.enabled: true\searchguard.ssl.http.enabled: false\g' config/elasticsearch.yml
```

After the start of the server, I run `docker exec ubuntu_elasticsearch_1 /usr/share/elasticsearch/sgadmin_demo.sh`, which works.

if I uncomment moving the configs and fixing up the location in sg_admin_demo.sh I get some errors along the way.

Let me know if I can help.
J.

**Comment by jaksmid** [comment]
This was for a long time official docker image so I suppose that there may be others that run into this.

**Comment by floragunncom** [comment]
So they can use your workaround which seems working very well

**Comment by jaksmid** [comment]
Ok, appreciate your help

**Comment by floragunncom** [comment]
see https://github.com/floragunncom/search-guard/issues/385
