### ISSUE TITLE
View full user permissions, just like _searchguard/authinfo

### ISSUE THREAD

**Issue by bw498c** [floragunncom/search-guard#371]
It would be really handy for debugging/testing if there was an endpoint to view a users full permissions. Similar to _searchguard/authinfo, but with permissions included.

**Comment by floragunncom** [comment]
Can you give an example how such an endpoint (and its response) should look like for you?

**Comment by bw498c** [comment]
Sure. Generally, I am looking for something that not just enumerates the roles, but details the permissions for each role. I expect the response to be similar to how roles are defined in `sg_roles`, except action groups are expanded.

What originally prompted this request was that I was trying to setup my user with the right permissions for kibana, but I kept getting permission errors. I found out that the permissions defined in the active `sg_roles` were not what I expected. I was expecting it to be a much newer version of `sg_roles`, when it was actually much older. I was unable to tell that the roles were different from the regular output for `_searchguard/authinfo` as it only listed roles.

The request and response might look like this (Note, it expands nested action groups):
```
GET _searchguard/authinfo?v

{
  "user": "User [name=some_user, roles=[]]",
  "user_name": "some_user",
  "user_requested_tenant": null,
  "remote_address": "xxx.xxx.xxx.xxx:xxxxx",
  "sg_roles": [
    ...,
    {
      "kibana_writer": {
        "cluster": [
          {
            "CLUSTER_COMPOSITE_OPS_RO": [
              "indices:data/read/mget",
              "indices:data/read/msearch",
              "indices:data/read/mtv",
              "indices:data/read/coordinate-msearch*",
              "indices:admin/aliases/exists*",
              "indices:admin/aliases/get*"
            ]
          },
          {
            "CLUSTER_COMPOSITE_OPS": [
              "indices:data/write/bulk",
              "indices:admin/aliases*",
              {
                "CLUSTER_COMPOSITE_OPS_RO": [
                  "indices:data/read/mget",
                  "indices:data/read/msearch",
                  "indices:data/read/mtv",
                  "indices:data/read/coordinate-msearch*",
                  "indices:admin/aliases/exists*",
                  "indices:admin/aliases/get*"
                }
              ]
            ]
          }
        ],
        "indices": {
          "?kibana": {
            "*": [
              {
                "CRUD": [
                  {
                    "READ": [
                      "indices:data/read*",
                      "indices:admin/mappings/fields/get*"
                    ]
                  },
                  {
                    "WRITE": [
                      "indices:data/write*",
                      "indices:admin/mapping/put"
                    ]
                  }
                ]
              },
              "indices:admin/refresh"
            ]
          },
          "*": {
            "*": [
              "indices:admin/mappings/fields/get*",
              "indices:data/read/field_stats*"
            ]
          }
        }
      }
    }
  ],
  "sg_tenants": {
    "admin": false
  },
  "principal": null,
  "peer_certificates": "0"
}
```

**Comment by floragunncom** [comment]
ok, so its basically print out the sg roles the user currently is a member of?

**Comment by bw498c** [comment]
Yes, basically print out their roles, and the permissions given to those roles

**Comment by floragunncom** [comment]
We're discussing this currently. Concerns were raised that this can disclose security relevant informations. So not sure if this gets implemented.

**Comment by bw498c** [comment]
Perhaps it can be enabled with a debugging flag? But disabled otherwise.

**Comment by floragunncom** [comment]
We will not implement this for now. One can check the current effective configuration with the sgadmin -r flag or via the new Kibana SG UI.
