### ISSUE TITLE
The real license of search-guard

### ISSUE THREAD

**Issue by lovezy** [floragunncom/search-guard#373]
@floragunncom Our Project needs import search-guard，but the license is confused，so which is the real license of search-guard，Apache License 2.0 or others？
Looking forward to your reply，Best regards！

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

As to your question, Search Guard is dual-licensed and you can read all about the license model on our homepage:

https://floragunn.com/searchguard-license-support/

And on this overview PDF:

https://floragunn.com/wp-content/uploads/2016/11/Search-Guard-Licensing.pdf
