### ISSUE TITLE
can give me a example how to add a user only read or search the doc ie *20170823*

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#378]
i need add a user in kibana only read or search the dos link   20170830*
he only can read the 20170830* the indexs,can't read the other 
how can configure it with search-guard
thanks.

**Comment by zqc0512** [comment]
i slove it.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
