### ISSUE TITLE
sg_roles_mapping error

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#380]
i add a role mapping about the hosts only connect 
but all the hosts can login kibana
configure file as:

sg_zqc_system_log_index:
  users:
    - zqc
    - zqc1
  hosts:
    - 11.0.44.103

search guard 5.4.2.4

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
