### ISSUE TITLE
elasticsearch start error 

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#381]
when start es
it output 
**[ERROR][c.f.s.a.BackendRegistry  ] Not yet initialized (you may need to run sgadmin)**
it can't connect to elasticsearch

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

As the error message states, you need to initialize Search Guard with sgadmin:

http://floragunncom.github.io/search-guard-docs/sgadmin.html
