### ISSUE TITLE
with this i can't open goolge, i ask a question  if transport.type: netty3 the search-guard is support?

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#382]
with this i can't open goolge, i ask a question  if transport.type: netty3 http.type: netty3 the search-guard is can support?
sorry.
the elasticsearch 5.4.3 have a bug about in big data env.
https://github.com/elastic/elasticsearch/issues/26293

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by zqc0512** [comment]
i can't open goolge 
sorry..
@floragunncom
