### ISSUE TITLE
Accept Red cluster does not work in ves5.1.1-15

### ISSUE THREAD

**Issue by mitech11** [floragunncom/search-guard#384]
Ran sgadmin with -arc option, but this version was unable to parse the flag. Got below error:

Search Guard Admin v5
ERR: Parsing failed.  Reason: Unrecognized option: -arc
usage: sgadmin.sh [-cd <directory>] [-cn <clustername>] [-dci] [-dg]
       [-dra] [-ec <cipers>] [-ep <protocols>] [-era] [-esa] [-f <file>]
       [-ff] [-h <host>] [-i <indexname>] [-icl] -ks <file> [-ksalias
       <alias>] [-kspass <password>] [-kst <type>] [-nhnv] [-nrhn] [-p
       <port>] [-r] [-rl] [-sniff] [-t <file-type>] -ts <file> [-tsalias
       <alias>] [-tspass <password>] [-tst <type>] [-us <number of
       replicas>]

The changelog suggests that this flag is supported since v14. 

Debugging:
Checked the code in the branches. Branch 5.1.1 has -arc option in com.floragunn.searchguard.tools.SearchGuardAdmin.java while branch es-5.1.1 branch is missing this option.

**Comment by floragunncom** [comment]
Right, we need to improve the docs and possibly versioning here. According to our EOL policy, v14 was not available for 5.1.1. v15, however, was a security release and was thus released for all versions. Will introduce a better semantic versioning.

**Comment by mitech11** [comment]
Sorry, just to clarify, will -arc flag be included for Elasticsearch v5.1.1?

**Comment by floragunncom** [comment]
no, you need to upgrade to 5.3.3 or later. Pls. refer to our EOL Policy https://github.com/floragunncom/search-guard-docs/blob/master/eol.md
