### ISSUE TITLE
Hashicorp Vault PKI:  Search Guard not initialized (SG11) for indices:admin/exists

### ISSUE THREAD

**Issue by ademaria** [floragunncom/search-guard#386]
Hello,

I am having problems configuring searchguard for an evaluation on my minikube/kubernetes backed elasticsearch 5.5.2.

I am using Hashicorp Vault to generate certificate, which I appreciate it being different that the demo setup you suggest.

The TLS connections between the hosts seems to setup OK, so I believe the certificates are properly configured and that part of the system seems to be working ok.

However, when I try to run the sgadmin.sh, I get the following error:

`ElasticsearchSecurityException[Search Guard not initialized (SG11) for indices:admin/exists. See https://github.com/floragunncom/search-guard-docs/blob/master/sgadmin.md]`

For this test run I am using the certificate from one of the nodes. I understanding that this is not advised in production or on your setup, but given that the certificate is generated by Vault, any other CN would also have the same certificate type.

[client.txt](https://github.com/floragunncom/search-guard/files/1288201/client.txt)
[master.txt](https://github.com/floragunncom/search-guard/files/1288200/master.txt)
[node.txt](https://github.com/floragunncom/search-guard/files/1288202/node.txt)
[sgadmin.txt](https://github.com/floragunncom/search-guard/files/1288203/sgadmin.txt)
[sgadmin_diag_trace_2017-Sep-08_14-34-31.txt](https://github.com/floragunncom/search-guard/files/1288224/sgadmin_diag_trace_2017-Sep-08_14-34-31.txt)
[certs.zip](https://github.com/floragunncom/search-guard/files/1288235/certs.zip)

password: 3hTd7CAkZCyFJzL4
p.s. don't worry about password showed as they are test passwords.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
