### ISSUE TITLE
Missing index returns 403 error instead of 404.

### ISSUE THREAD

**Issue by bhawdeadlydan** [floragunncom/search-guard#387]
When _abc_ index is present in elastic search and on firing a search query for _abc*_.
It gives back correct values with 200 status code.

On searching for _abc*_ on elastic search with no abc starting indices in elastic search, it gives the following error.

Exception in thread "main" java.lang.AssertionError: assertion failed: ElasticSearch returned failure error code 403: 
 {"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for indices:admin/get"}],"type":"security_exception","reason":"no permissions for indices:admin/get"},"status":403

This is not the expected response.

**Comment by floragunncom** [comment]
do you have permissions for an index `abc*`?

**Comment by bhawdeadlydan** [comment]
**sg_roles.yml**
sg_user01_role:
  cluster:
  - CLUSTER_MONITOR
  - CLUSTER_SCROLL
  - WRITE_BULK
  indices:
    abc*:
      "*":
      - INDICES_ALL

**sg_roles_mapping.yml**
sg_user01_role:
  users:
  - user01

**sg_action_groups.yml**
CLUSTER_MONITOR:
  - cluster:monitor*
CLUSTER_SCROLL:
 - "indices:data/read/scroll"
INDICES_ALL:
 - "*"
WRITE_BULK:
 - "indices:data/write/bulk*"


_user01_ has the permissions mentioned above for the index _abc*_

**Comment by floragunncom** [comment]
This should be fixed in SG 16 together with https://github.com/floragunncom/search-guard/issues/374.

Can you verify whether it works with SG 16?

**Comment by floragunncom** [comment]
assume solved
