### ISSUE TITLE
support for 5.6 ?

### ISSUE THREAD

**Issue by luvpreetsingh** [floragunncom/search-guard#389]
Is there support for elasticsearch and kibana version 5.6 available?

**Comment by floragunncom** [comment]
As explained here: https://groups.google.com/forum/#!forum/search-guard

"Please note: When a new Elasticsearch version is out, it usually takes us only a couple of days to release a matching Search Guard version. 
Don't ask for new versions here, we're releasing them as fast as we can."

**Comment by luvpreetsingh** [comment]
So, means it is not out yet. 

I accidentally upgraded it, so please tell me How much more time ?

**Comment by floragunncom** [comment]
Probably on Monday (but without any guarantees)

Pls. always check https://github.com/floragunncom/search-guard/wiki
