### ISSUE TITLE
Hiding class loading exceptions.

### ISSUE THREAD

**Issue by jkamenik** [floragunncom/search-guard#391]
https://github.com/floragunncom/search-guard/blob/85daf94fae48519ce0b2633440759bbb747eb66e/src/main/java/com/floragunn/searchguard/auth/BackendRegistry.java#L224

The following line hides the actual exception from output.

**Comment by floragunncom** [comment]
we will fix this, thx for reporting

**Comment by floragunncom** [comment]
Fixed with SG 17
