### ISSUE TITLE
Connection reset on long URI

### ISSUE THREAD

**Issue by KirkF** [floragunncom/search-guard#394]
Running Elasticsearch 5.5.3 and Searchguard 16. Was testing using Curator to automate snapshots when it started failing after reaching a certain number of indexes. The request looks like 
<pre>
*   Trying 10.251.26.68...
* TCP_NODELAY set
* Connected to 10.251.26.68 (10.251.26.68) port 9200 (#0)
* Server auth using Basic with user 'admin'
> GET /.kibana,.monitoring-es-6-2017.09.20,.monitoring-es-6-2017.09.21,.monitoring-es-6-2017.09.22,.monitoring-es-6-2017.09.23,.monitoring-es-6-2017.09.24,.monitoring-es-6-2017.09.25,.triggered_watches,.watcher-history-3-2017.09.20,.watcher-history-3-2017.09.21,.watcher-history-3-2017.09.22,.watcher-history-3-2017.09.23,.watcher-history-3-2017.09.24,.watcher-history-3-2017.09.25,.watches,cloudtrail-2017.09.20,cloudtrail-2017.09.21,cloudtrail-2017.09.22,cloudtrail-2017.09.23,cloudtrail-2017.09.24,cloudtrail-2017.09.25,filebeat-2017.09.21,filebeat-2017.09.22,filebeat-2017.09.23,filebeat-2017.09.24,filebeat-2017.09.25,searchguard/_stats/store,docs HTTP/1.1
> Host: 10.251.26.68:9200
> Authorization: Basic XXXXXXX==
> User-Agent: curl/7.51.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer`
</pre>
This does not happen on a cluster with searchguard not installed. I turned on debug and found the following:

`[2017-09-27T18:21:27,911][DEBUG][c.f.s.a.BackendRegistry  ] Try to extract auth creds from http basic 
[2017-09-27T18:21:27,911][DEBUG][c.f.s.a.BackendRegistry  ] User 'admin' is in cache? true (cache size: 3)
[2017-09-27T18:21:27,911][DEBUG][c.f.s.a.BackendRegistry  ] User 'User [name=admin, roles=[]]' is authenticated
[2017-09-27T18:21:27,911][DEBUG][c.f.s.a.BackendRegistry  ] sg_tenant 'null'
[2017-09-27T18:21:28,021][DEBUG][c.f.s.h.SearchGuardNonSslHttpServerTransport] [TMMbQTQ] caught exception while handling client http traffic, closing connection [id: 0x76a90d05, L:/172.17.0.2:9200 - R:/10.251.24.158:58968]
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:?]
        at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
`

Thanks

**Comment by floragunncom** [comment]
Maybe you run in an issue where `http.max_content_length` is exceeded. So i assume not the length of the uri is the problem, maybe its the response? See https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html how to increase limits and check defaults.

I try to reproduce it but no luck so far

**Comment by floragunncom** [comment]
Pls try to add  `-vv --trace-ascii dump.txt` flag to your curl command and post the contents of dump.txt and the console output. Do you use HTTPS or plain HTTP?

**Comment by KirkF** [comment]
HTTP. I will try your suggestions

**Comment by floragunncom** [comment]
The strange thing here that both sides (client/curl and the server/elasticsearch) both report "Connection reset by peer". Normally you see this only on one side. Can you maybe narrow down the issue by testing for how many indices it works and wether its always reproducible and wether its maybe curl related (so pls try wget or HTTPie or a browser). If nothings helps try inspecting the TCP stream with wireshark or tcpdump.

**Comment by KirkF** [comment]
It's not curl related, I just used curl to demonstrate. I found the problem using Curator. There is a number below which it works which I found by trial and error but haven't counted. I find it hard to believe the response could be over 100mb when the request is for statistical metadata.

**Comment by KirkF** [comment]
results from modified curl command, console output:
curl: (56) Recv failure: Connection reset by peer

dump.txt:
== Info:   Trying 10.251.26.68...
== Info: TCP_NODELAY set
== Info: Connected to 10.251.26.68 (10.251.26.68) port 9200 (#0)
== Info: Server auth using Basic with user 'admin'
=> Send header, 753 bytes (0x2f1)
0000: GET /.kibana,.monitoring-es-6-2017.09.20,.monitoring-es-6-2017.0
0040: 9.21,.monitoring-es-6-2017.09.22,.monitoring-es-6-2017.09.23,.mo
0080: nitoring-es-6-2017.09.24,.monitoring-es-6-2017.09.25,.triggered_
00c0: watches,.watcher-history-3-2017.09.20,.watcher-history-3-2017.09
0100: .21,.watcher-history-3-2017.09.22,.watcher-history-3-2017.09.23,
0140: .watcher-history-3-2017.09.24,.watcher-history-3-2017.09.25,.wat
0180: ches,cloudtrail-2017.09.20,cloudtrail-2017.09.21,cloudtrail-2017
01c0: .09.22,cloudtrail-2017.09.23,cloudtrail-2017.09.24,cloudtrail-20
0200: 17.09.25,filebeat-2017.09.21,filebeat-2017.09.22,filebeat-2017.0
0240: 9.23,filebeat-2017.09.24,searchguard/_stats/store,docs HTTP/1.1
0281: Host: 10.251.26.68:9200
029a: Authorization: Basic XXXXXXX==
02c9: User-Agent: curl/7.51.0
02e2: Accept: */*
02ef: 
== Info: Recv failure: Connection reset by peer
== Info: Curl_http_done: called premature == 1
== Info: Closing connection 0

**Comment by KirkF** [comment]
The number of indices at or below which it starts working is 18

**Comment by floragunncom** [comment]
And without SG its really working?

**Comment by KirkF** [comment]
I tested on a different cluster based on the same image without SG installed and the API works how I would expect and I am able to make snapshots using curator.

**Comment by floragunncom** [comment]
We are not able to reproduce this

**Comment by floragunncom** [comment]
* Added to integration test suites
* Tested on 3-node cluster with 5.5.3-16
* Created 50 indices with name myindexwithasuperlongindexnamepurelyfortesting_x
* Added 20 documents per index
*https://.../myindexwithasuperlongindexnamepurelyfortesting_1,[...],myindexwithasuperlongindexnamepurelyfortesting_50/_stats/store,docs
* Result: HTTP 200, "_shards" : { "total" : 500, "successful" : 500, "failed" : 0} ...

Is there anything else we need to consider to reproduce this issue? How many documents do you have per index? How big are your indices?

**Comment by KirkF** [comment]
I've done more testing to try to narrow the conditions under which I am seeing the failure. As far as I can tell it's not a particular index, it's not the number of indices, but it is the length of the path portion of the URI. 

For these purposes the 'store,docs' part doesn't matter. The _stats/ part does matter. The magic number seems to be 512. If there are more than 512 characters in the path of the URI the request breaks in the manner I've shown. If there are 512 or fewer characters it works as expected. 

If there is not a secondary portion to the API (i.e. just a plain GET on the indices) it works with any number. If I add _stats I'm restricted to 512 characters. If I use _settings it breaks in the same way. So for example if I have a list of indices and call _stats and it works but is very close to 512, then call _settings instead which puts it over 512 it will break.

I tested with different permutations of indices to get close, but to be exact I can actually request a nonexistent index and it will correctly return a 404 if it's <= 512 and just drop if it's > 512. Or even leaving off or adding the trailing / will make the difference

== Info:   Trying 10.251.26.68...
== Info: TCP_NODELAY set
== Info: Connected to 10.251.26.68 (10.251.26.68) port 9200 (#0)
== Info: Server auth using Basic with user 'admin'
=> Send header, 640 bytes (0x280)
0000: GET /.watcher-history-3-2017.09.25,.watcher-history-3-2017.09.26
0040: ,.watcher-history-3-2017.09.27,.watcher-history-3-2017.09.28,.wa
0080: tcher-history-3-2017.09.29,cloudtrail-2017.09.20,cloudtrail-2017
00c0: .09.21,cloudtrail-2017.09.22,cloudtrail-2017.09.23,cloudtrail-20
0100: 17.09.24,cloudtrail-2017.09.25,cloudtrail-2017.09.28,cloudtrail-
0140: 2017.09.29,filebeat-2017.09.21,filebeat-2017.09.22,filebeat-2017
0180: .09.23,filebeat-2017.09.24,filebeat-2017.09.25,filebeat-2017.09.
01c0: 26,filebeat-2017.09.27,filebeat-2017.09.28,.watches,.kibana12/_s
0200: tats/ HTTP/1.1
0210: Host: 10.251.26.68:9200
0229: Authorization: Basic XXXXXX==
0258: User-Agent: curl/7.51.0
0271: Accept: */*
027e: 
== Info: Recv failure: Connection reset by peer
== Info: Curl_http_done: called premature == 1
== Info: Closing connection 0

== Info:   Trying 10.251.26.68...
== Info: TCP_NODELAY set
== Info: Connected to 10.251.26.68 (10.251.26.68) port 9200 (#0)
== Info: Server auth using Basic with user 'admin'
=> Send header, 639 bytes (0x27f)
0000: GET /.watcher-history-3-2017.09.25,.watcher-history-3-2017.09.26
0040: ,.watcher-history-3-2017.09.27,.watcher-history-3-2017.09.28,.wa
0080: tcher-history-3-2017.09.29,cloudtrail-2017.09.20,cloudtrail-2017
00c0: .09.21,cloudtrail-2017.09.22,cloudtrail-2017.09.23,cloudtrail-20
0100: 17.09.24,cloudtrail-2017.09.25,cloudtrail-2017.09.28,cloudtrail-
0140: 2017.09.29,filebeat-2017.09.21,filebeat-2017.09.22,filebeat-2017
0180: .09.23,filebeat-2017.09.24,filebeat-2017.09.25,filebeat-2017.09.
01c0: 26,filebeat-2017.09.27,filebeat-2017.09.28,.watches,.kibana12/_s
0200: tats HTTP/1.1
020f: Host: 10.251.26.68:9200
0228: Authorization: Basic XXXXXX==
0257: User-Agent: curl/7.51.0
0270: Accept: */*
027d: 
<= Recv header, 24 bytes (0x18)
0000: HTTP/1.1 404 Not Found
<= Recv header, 47 bytes (0x2f)
0000: content-type: application/json; charset=UTF-8
<= Recv header, 21 bytes (0x15)
0000: content-length: 359
<= Recv header, 2 bytes (0x2)
0000: 
<= Recv data, 359 bytes (0x167)
0000: {"error":{"root_cause":[{"type":"index_not_found_exception","rea
0040: son":"no such index","resource.type":"index_or_alias","resource.
0080: id":".kibana12","index_uuid":"_na_","index":".kibana12"}],"type"
00c0: :"index_not_found_exception","reason":"no such index","resource.
0100: type":"index_or_alias","resource.id":".kibana12","index_uuid":"_
0140: na_","index":".kibana12"},"status":404}
== Info: Curl_http_done: called premature == 0
== Info: Connection #0 to host 10.251.26.68 left intact

I will keep testing, probably trying different versions of ES to see if that makes a difference. Thank you.

**Comment by floragunncom** [comment]
Pls make sure that this is really SG related by uninstalling SG on the failing cluster and see if it still happens.

**Comment by KirkF** [comment]
After doing a snapshot and restore I was able to replicate it on a cluster after removing SG, so it looks like an ES problem, must be something to do with our indices. Thanks for your help.

**Comment by floragunncom** [comment]
I recommend to open an issue in the elastic repo or their discuss forum and link back to this issue
