### ISSUE TITLE
After installing this plugin，es nodes cann't find each other

### ISSUE THREAD

**Issue by gnuhpc** [floragunncom/search-guard#4]
Pls help me out~ Thanks!

**Comment by floragunncom** [comment]
pls provide more details and post your configuration file(s)

**Comment by gnuhpc** [comment]
I have fixed it. BTW, does this plugin support kibana3 and kopf plugin?

**Comment by floragunncom** [comment]
kibana 3 is untested (kibana 4 should work), "kopf" should also work.

**Comment by gnuhpc** [comment]
how to config kibana4 for this plugin? Thanks!

**Comment by gnuhpc** [comment]
I configed the username and password in kibana.yml ,but I got error in invalidkey exception

**Comment by floragunncom** [comment]
again, pls provide the logfiles and your configuration and open another issue for that please

**Comment by floragunncom** [comment]
we will provide a guide, how to setup and configure search guard with kibana, soon
