### ISSUE TITLE
Problem with credentials if use alias in sg_roles.yml

### ISSUE THREAD

**Issue by spiritmonger** [floragunncom/search-guard#403]
Elasticsearch: 5.4.1 (one node)
Search Guard: 5.4.1-14
java version "1.8.0_65"

i have problem, not working alias configured in sg_roles.

for example, structure configured in elasticsearch, template for XXX-typeX-<date> ==> alias XXX-system
<pre>
alias: dev-system
indexes: 
  dev-type1-&lt;date&gt;
  dev-type2-&lt;date&gt;
</pre>

<pre>
alias prod-system
indexes: 
  prod-type1-&lt;date&gt;
  prod-type2-&lt;date&gt;
</pre>

then in sg_roles defined different group:

<pre>
-- for superadmin --

sg_system:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '?kibana-*':
      '*':
        - READ
    '*-system':
      '*':
        - READ

-- for devadmin --
sg_system_dev:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '?kibana-*':
      '*':
        - READ
    'dev-system':
      '*':
        - READ
</pre>
then if i try use this roles, i saw in log, when i haven't permission to dev-type1-<date>, ....

how is possible use right alias in sg_roles config?

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by floragunncom** [comment]
Will look into that now ...

**Comment by floragunncom** [comment]
see https://docs.search-guard.com/latest/snapshot-restore
