### ISSUE TITLE
Execute ./sgadmin_demo.sh cause error

### ISSUE THREAD

**Issue by ytzlax** [floragunncom/search-guard#406]
* Search Guard and Elasticsearch version : es:5.4.0 search guard: 5-5.4.0-15
* JVM version: java.version: jdk1.8.0_111
* Operating system version: win 7
* Number of nodes in your cluster: 1
* Description of the bug:
I did the quick start steps, install elasticsearch, install search gourd, execute ./install_demo_configuration.sh, start elasticserch ,
when I execute sgadmin_demo.sh file I get the next error:
Error: Could not find or load main class com.floragunn.searchguard.tools.SearchG
uardAdmin

**Comment by floragunncom** [comment]
install_demo_configuration.sh is not supposed to be run on windows. Try https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle to get it up and running.

**Comment by JohnMcAvinue** [comment]
That link says nothing about windows. Can search guard be using on a windows box? I see nothing in the documentation about it.

**Comment by jochenkressin** [comment]
https://docs.search-guard.com/latest/installation-windows

**Comment by JohnMcAvinue** [comment]
Thanks but the demo certificates download link is leading to a 404
