### ISSUE TITLE
Demo Configuration not works on Docker, Certificate Unknown

### ISSUE THREAD

**Issue by funkydorian** [floragunncom/search-guard#407]
* Version 5.6
* Java 1.8.0
* Docker

I am modifying docker-elk repo in order to include search-guard into it.

I had the same issue with [385](https://github.com/floragunncom/search-guard/issues/385) but overcome it with Dockerfile modifications.

I modified the repo according to the SearchGuard according to the [QuickStart](http://floragunncom.github.io/search-guard-docs/quickstart.html) but i stuck with the Certificate unknown issue.

elasticsearch_1  | [2017-11-07T20:00:31,578][ERROR][c.f.s.h.SearchGuardHttpServerTransport] [iX5WeYA] SSL Problem Received fatal alert: certificate_unknown
elasticsearch_1  | javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
elasticsearch_1  | 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:?]
elasticsearch_1  | 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:?]
elasticsearch_1  | 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:?]
elasticsearch_1  | 	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:?]
elasticsearch_1  | 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:?]
elasticsearch_1  | 	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:?]
elasticsearch_1  | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:?]
elasticsearch_1  | 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_141]

Here is the modified [repository](https://github.com/funkydorian/docker-elk-searchguard)

* Steps to reproduce
* docker-compose up
* docker exec  -it<elasticsearchID> ./sgadmin_demo.sh

I added the following under jvm.options under ElasticSearch Dockerfile but seems does not work either.

ENV ES_JAVA_OPTS="-Djavax.net.ssl.keyStore=/usr/share/elasticsearch/config/keystore.jks -Djavax.net.ssl.keyStorePassword=changeit -Djavax.net.ssl.trustStore=/usr/share/elasticsearch/config/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit"

**Comment by floragunncom** [comment]
here is a fixed version https://github.com/floragunncom/search-guard/blob/5.6.0/tools/install_demo_configuration.sh

**Comment by floragunncom** [comment]
no response, assume solved
