### ISSUE TITLE
Reload config with sgadmin does not load changed  user password (internal users)

### ISSUE THREAD

**Issue by ajaybhatnagar** [floragunncom/search-guard#409]
* Search Guard and Elasticsearch version
com.floragunn:search-guard-5:5.6.3-16,  tools es-5.6.3.zip
ES 5.6.3
* JVM version and operating system version
JVM 1.8.0_152-b16, OS Ubuntu 4.4.0-97-generic
* Number of nodes in your cluster
3

* Description of the bug
Cluster configured successfully and user access works fine with initial configuration loaded at startup. Thereafter I am trying to change only password for a user (internal users only) and reload the config . Config reloads with no errors but password not updated. Old password is still valid and new password  is unauthorized.

* Steps to reproduce
create internal users, assign roles and permissions. create index, load data. verify access to the documents using the user credentials.

Change the password hash in sg_internal_users. Reload the the config with sgadmin. Try accessing the document with old and new password. Old password will still allow access and new password will not.
------------
Data Index data loading:
curl -k -XPUT 'https://user1:user1pass@localhost:9200/user1index/tweet/1?pretty' -H 'Content-Type: application/json' -d'
{
    "user" : "kimchy1",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch1"
}';
curl -k -XPUT 'https://user1:user1pass@localhost:9200/user1index/tweet/2?pretty' -H 'Content-Type: application/json' -d'
{
    "user" : "kimchy2",
    "post_date" : "2010-11-15T14:12:12",
    "message" : "trying out Elasticsearch2"
}';
curl -k -XPUT 'https://user1:user1pass@localhost:9200/user1index/tweet/3?pretty' -H 'Content-Type: application/json' -d'
{
    "user" : "kimchy3",
    "post_date" : "2011-11-15T14:12:12",
    "message" : "trying out Elasticsearch3"
}'
--------------------------
Query Resuts with user2:
 curl -k -XGET 'https://user2:user2pass@localhost:9200/user1index/tweet/2?pretty'
{
  "_index" : "user1index",
  "_type" : "tweet",
  "_id" : "2",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "user" : "kimchy2",
    "post_date" : "2010-11-15T14:12:12",
    "message" : "trying out Elasticsearch2"
  }
}
-----------------------------

Run reload sgconfig with following command (after changing user2 hash only in sg_internal_users.yml, replaced it with logstash user's hash)

/usr/local/elasticsearch/plugins/search-guard-5/tools# ./sgadmin.sh   -ts /es1/etc/elasticsearch/truststore.jks  -tspass changeit -ks /es1/etc/elasticsearch/sgadmin-keystore.jks -kspass changeit    -icl -rl
Search Guard Admin v5
Will connect to localhost:9300 ... done

### LICENSE NOTICE Search Guard ###

If you use one or more of the following features in production
make sure you have a valid Search Guard license
(See https://floragunn.com/searchguard-validate-license)

* Kibana Multitenancy
* LDAP authentication/authorization
* Active Directory authentication/authorization
* REST Management API
* JSON Web Token (JWT) authentication/authorization
* Kerberos authentication/authorization
* Document- and Fieldlevel Security (DLS/FLS)
* Auditlogging

In case of any doubt mail to <sales@floragunn.com>
###################################
Reload config on all nodes
----------------------------------------
 Query again for same document as above
 curl -k -XGET 'https://user2:logstash@localhost:9200/user1index/tweet/2?pretty'
Unauthorized

Try with old password for user2 document is retrieved:
 curl -k -XGET 'https://user2:user2pass@localhost:9200/user1index/tweet/2?pretty'
{
  "_index" : "user1index",
  "_type" : "tweet",
  "_id" : "2",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "user" : "kimchy2",
    "post_date" : "2010-11-15T14:12:12",
    "message" : "trying out Elasticsearch2"
  }
}
---------------------------------------------
CONFIG DETAILS BELOW

sg_internal_users.yml definition (selected users only)
Initial Settings:

logstash:
  hash: $2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2
  #password is: logstash
user2:
  hash: $2a$12$tGec2O/a9O4W9c60TYVXeuCD/OK/k8mGYzLL.xbSQjL7T0JZvxbTW
  #password is user2pass
  roles:
    - user2role
---------------------------------
Modified Internal Users Settings (changing password only to be same as logstash user's hash as above)

user2:
  hash:  $2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2
    roles:
    - user2role

--------------------

Roles Mapping:

sg_roles_mapping (selected contents only)

sg_role_user1role:
  hosts:
    - "*.test.net"
  users:
    - user1
sg_role_user2role:
  hosts:
    - "*.test.net"
  users:
    - user2
------------------------
 ROLES in sg_roles.yml (selected users only)
sg_role_user1role:
  cluster:
    - UNLIMITED
  indices:
    'user*':
       '*':
         - UNLIMITED
sg_role_user2role:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    'user*':
       '*':
         - READ
----------------

No changes in ACTION GROUPS (default files).

**Comment by floragunncom** [comment]
Can you please format your post properly?

**Comment by floragunncom** [comment]
no response
