### ISSUE TITLE
Support for proxy authentication with TLS client certificate

### ISSUE THREAD

**Issue by mikn** [floragunncom/search-guard#419]
We're setting up an ES cluster with Searchguard on top of Kubernetes and we would like a more secure way to authenticate an upstream proxy, such as client certificate. Could it be possible to allow setting something similar to `searchguard.nodes_dn` for the proxy?

**Comment by floragunncom** [comment]
This a is valueable idea, we put it in our backlog for SG6

**Comment by floragunncom** [comment]
Tracked here https://github.com/floragunncom/search-guard/issues/697
