### ISSUE TITLE
Mutual SSL REST authentication related inquiry

### ISSUE THREAD

**Issue by vyutpatti** [floragunncom/search-guard#42]
Hi,

I have enabled mutual SSL Rest setup on my ES node. I enabled HTTPSClientCertAuthenticator http authentication method. My question is: What authentication backend do I enable? 

Enabling the SettingsBasedAuthenticationBackend leads to error: 
{
  "error" : "AuthException[com.floragunn.searchguard.authentication.AuthException: No user (CNuser) or wrong password (digest: plain/none)]; nested: AuthException[No user (CNuser) or wrong password (digest: plain/none)]; ",
  "status" : 500
}

AlwaysSucceedAuthenticationBackend doesn't sound like a right approach. Please advice.

Here are a snippet of my settings in  elasticsearch yml:
#############################################################################################
# REST layer SSL                                                                            #
#                                                                                           #
#############################################################################################
# Enable or disable rest layer security (https)
searchguard.ssl.transport.http.enabled: true
# JKS or PKCS12
searchguard.ssl.transport.http.keystore_type: JKS
# Absolute path to the keystore file (this stores the server certificates)
searchguard.ssl.transport.http.keystore_filepath: (server jks)
# Keystore password
searchguard.ssl.transport.http.keystore_password: pwd
# Do the clients (typically the browser or the proxy) have to authenticate themself to the http server, default is false
searchguard.ssl.transport.http.enforce_clientauth: true
# JKS or PKCS12
searchguard.ssl.transport.http.truststore_type: JKS
# Absolute path to the truststore file (this stores the client certificates)
searchguard.ssl.transport.http.truststore_filepath: (client  jks)
# Truststore password
searchguard.ssl.transport.http.truststore_password: pwd

#############################################################################################
# HTTP authentication method                                                                #
#                                                                                           #
#############################################################################################
# SSL mutual authentication (works only if searchguard.ssl.transport.http.enabled is 'true' with client auth enabled)
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.clientcert.HTTPSClientCertAuthenticator

#####################################################
# HTTP SSL mutual authentication configuration
# Attribute of that attribute in the certificate dn which holds the username
searchguard.authentication.https.clientcert.attributename: cn
#####################################################

Thx in advance for the pointers.

**Comment by floragunncom** [comment]
AlwaysSucceedAuthenticationBackend is perfect because your client is already authenticated (the certificate is in your truststore so thats fine).

**Comment by vyutpatti** [comment]
Thx for your response Floragunncom.
