### ISSUE TITLE
sgadmin.sh killed in Docker

### ISSUE THREAD

**Issue by chersicm** [floragunncom/search-guard#421]
Hello,
I'm running Elasticsearch 5.4.0 [official Docker image](docker.elastic.co/elasticsearch/elasticsearch:5.4.0) with Search Guard 5:5.4.0-15.

JVM info:
java.version: 1.8.0_131
java.vm.name: OpenJDK 64-Bit Server VM

OS info:
os.name: Linux
os.arch: amd64
os.version: 4.4.0-101-generic

I've a cluster of three nodes, but I've been testing on a single node with the same result.

Building the image from the Dockerfile (find attached at the bottom), Search Guard installs successfully, with a warning:

-> Downloading com.floragunn:search-guard-5:5.4.0-15 from maven central
[=================================================] 100%?? 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission /proc/sys/net/core/somaxconn read
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessClassInPackage.sun.nio.ch
* java.lang.RuntimePermission accessClassInPackage.sun.security.x509
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission loadLibrary.*
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission shutdownHooks
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission getProperty.ssl.KeyManagerFactory.algorithm
* java.security.SecurityPermission setProperty.ocsp.enable
* java.util.PropertyPermission com.sun.security.enableCRLDP write
* java.util.PropertyPermission java.security.debug write
* java.util.PropertyPermission java.security.krb5.conf write
* java.util.PropertyPermission javax.security.auth.useSubjectCredsOnly write
* java.util.PropertyPermission sun.nio.ch.bugLevel write
* java.util.PropertyPermission sun.security.krb5.debug write
* java.util.PropertyPermission sun.security.spnego.debug write
* javax.security.auth.AuthPermission doAs
* javax.security.auth.AuthPermission modifyPrivateCredentials
* javax.security.auth.kerberos.ServicePermission * accept
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

But when loading the configs by running sgadmin.sh, the process and the container get killed (find error log attached).

Command I use to run sgadmin.sh:
`plugins/search-guard-5/tools/sgadmin.sh -cd config/ -ts config/truststore.jks -tspass $TS_PASS -ks config/sgadmin-keystore.jks -kspass $KS_PASS -nhnv -cn deeplog`

I generated truststore and keystore using the [example PKI scripts](https://github.com/floragunncom/search-guard-ssl/tree/5.5.0/example-pki-scripts).

Attachments: [files.zip](https://github.com/floragunncom/search-guard/files/1531189/files.zip)

**Comment by floragunncom** [comment]
Pls. have a look here, this is know to work: https://github.com/deviantony/docker-elk/tree/searchguard

**Comment by chersicm** [comment]
I know, that's where I got everything started.

**Comment by floragunncom** [comment]
can you provide a reproducer? in the files.zip there is bin/ missing

**Comment by chersicm** [comment]
ok, attachment updated.

**Comment by floragunncom** [comment]
With [files_works.zip](https://github.com/floragunncom/search-guard/files/1531221/files_works.zip)

and

<pre>
docker build .
docker run -p 9300:9300 -it CONTAINER_ID
docker exec 5af565a13416 /bin/bash -c 'bin/init_sg.sh'
</pre>

i cannot reproduce this issue

**Comment by floragunncom** [comment]
no response, cannot reproduce
