### ISSUE TITLE
Trying to HEAD _alias gives unexpected 400 response

### ISSUE THREAD

**Issue by ceeeekay** [floragunncom/search-guard#431]
* ES 5.6.3
* OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
* OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
* Ubuntu 16.04.3 LTS
* Number of nodes in your cluster: 1 (dev)
* Description of the bug

A GET request against _alias returns either 200 or 404, depending if the alias exists.

Attempting to use HEAD returns a 400 in both cases.

**GET**
```
$ curl -ks 'https://user:pass@server:9200/my_index/_alias?pretty'
HTTP/1.1 200 OK
{
  "my_index" : {
    "aliases" : {
      "my_alias" : { }
    }
  }
}
```
**HEAD**
```
$ curl -ks --head 'https://user:pass@server:9200/my_index/_alias'
HTTP/1.1 400 Bad Request
content-type: text/plain; charset=UTF-8
content-length: 117
```

**Comment by ceeeekay** [comment]
Tested with SG disabled, same result. 

Putting '_alias' before the URL returns the correct response to a HEAD request, although in order to make this work for the user in question we would need to apply 'indices:admin/aliases/get' at the cluster level, instead of the index level, which is a problem.

Are there any suggestions on how to get around this?

**Comment by floragunncom** [comment]
I the problem remains if you disable SG (or with uninstalled SG) than i think that ES is just not supporting the HEAD method for this REST call. Its unlikely that this is SG related.

**Comment by ceeeekay** [comment]
It definitely is ES producing the 400, now that I've tested some more.

Is there any other way I can structure the request so I don't have to give `indices:admin/aliases/get` permission at the cluster level?

**Comment by floragunncom** [comment]
Lets discuss this in the forum https://groups.google.com/forum/#!forum/search-guard

Will close this issue because it does not look like a SG bug
