### ISSUE TITLE
Wiki update for 5.6.5

### ISSUE THREAD

**Issue by rvolykh** [floragunncom/search-guard#433]
Hello, found a small mistake in wiki
https://github.com/floragunncom/search-guard/wiki#elasticsearch-5x

Please, update wiki with correct version:

Actual:

5.6.5 | 5.6.4-18 | YES
-- | -- | --

Expected:

5.6.5 | 5.6.5-18 | YES
-- | -- | --

**Comment by floragunncom** [comment]
fixed, thx
