### ISSUE TITLE
Support for activity-based permissions

### ISSUE THREAD

**Issue by lyonssp** [floragunncom/search-guard#435]
I am trying to provide fine-grained access to dynamically indexed data in my ES cluster.  The use-case is somewhat simple:

A company signs up for my platform, at which time I dynamically create an index specifically for that company and add any searchable data to the index.  When searching through my cluster for data about that company (banking data, employee data, etc.), I want to restrict access to the index.  

I already have a authentication/authorization server set up that I use to secure other uses of my system outside of ES, and would like to somehow use that service in ES.  I use activity-based permissions, that look something like this `company:read:{company id}`. What I want is to pass a token to ES that it will pass to my auth server to fetch use data and permissions for that token, and subsequently approve/reject the request.

Is anything like this supported in Search Guard right now?  All of what I have seen is role-based permissions, which only fits for me if I basically treat each of my activity-based permissions as a role, I would probably just go with some reverse proxy approach over Search Guard in that case.

Would appreciate any help and am happy to provide more details if I'm being too vague.  I'd love to make this technology work for my use-case, as I trust that it is much more secure than a simple reverse proxy.

**Comment by floragunncom** [comment]
Is this about Elasticsearch 5 or 6? With ES 6 (and SG 6) you can either implement your own authentication modules (see http://docs.search-guard.com/latest/custom-authentication-modules#custom-authentication-modules) or use a JWT token together with custom attributes (http://docs.search-guard.com/latest/roles-permissions#dynamic-index-names-user-attributes)

With ES 5 (and SG 5) i think you have to go with the activity-role mapping put you can adjust this mapping dynamically and programmatically using the REST management API (http://docs.search-guard.com/latest/rest-api-access-control#rest-management-api)

If nothing of the above fits you maybe want to clone the Search Guard repo and implement it yourself (and maybe, if you solution may be valuable for other too, contribute it back)

**Comment by lyonssp** [comment]
Thank you so much for the info!  I have some follow-ups after reading, if you'd be so kind as to shed a little more light.

Permissions to take actions (read, write, etc.) against an entity in my domain take on the form 
`entity:action:{entityId}`

My ideal solution would be to leverage some hooks within Search Guard to build a mapping `[Domain Permission] -> (Index, [Allowed Actions])` so that I can dynamically figure out at search time what actions a user can take against the index they are targeting.  

Something promising that I saw was the last line in the custom modules link you sent me was this line:
> Attributes can be used to further describe the user, and, more importantly, they can be used as variables in the Document Level Security query. This makes it possible to write dynamic DLS queries based on a user’s attributes.

Ultimately, what I'm getting at is this question: The same way that there is a programmatic hook into the document-level security query, is there a programmatic hook into index permissions that I can leverage?

I could use the concept in the quote above, putting all tenant data in a single index and handling security at the document level, but currently am handling permissions at the index-level and am looking to change the makeup of my cluster as little as possible.

**Comment by floragunncom** [comment]
You can also use the user attributes on index names, not only in dsl queries, if this helps.
Otherwise i guess you need to clone the repo and modify the source code.

I will close this issue because its a feature at least we will not implement because its a very special case. Happy to discuss further on this topic in the SG forum https://groups.google.com/forum/#!forum/search-guard Maybe there are also others with similar needs and solutions.
