### ISSUE TITLE
X-Pack Monitoring Documentation Outdated

### ISSUE THREAD

**Issue by numbnut** [floragunncom/search-guard#438]
Hi,
I'm using the docker image docker.elastic.co/elasticsearch/elasticsearch:6.1.1 in combination with searchguard ves-6.1.1-20.1. At the moment I'm using this setup only on my local dev machine.

I'm using X-Pack monitoring and think the [documentation](https://github.com/floragunncom/search-guard-docs/blob/master/x_pack_monitoring.md) is outdated or somehow unclear.
The docu says: "In addition to the sg_monitor role, the user should also be assigned to the sg_kibana role." I'm referring to the latest version of the [sg_roles.yml](https://github.com/floragunncom/search-guard/blob/d3d50453b3ea295396e642fe24a90cbfba71cf50/sgconfig/sg_roles.yml) file.

1. There is no "sg_kibana" role in the sg_roles.yml. There are only sg_kibana_server and sg_kibana_user.
2. The role sg_monitor is marked as deprecated but still mentioned in the documentation.
3. There is a new role sg_xp_monitor, which I don't use at the moment, because it didn't work.

I hope this is the right place to file documentation issues. Thanks for your great work!

**Comment by floragunncom** [comment]
The documentation has been moved: 

http://docs.search-guard.com/latest/index
http://docs.search-guard.com/latest/search-guard-xpack-monitoring

Seems we need to outdate the master branch on GitHub still, thanks for letting us know.

You need to assign the sg_kibana_user and the sg_xp_monitor to the role you want to use for monitoring. The sg_kibana_user role provides the minimum set or permissions to use Kibana, and sg_xp_monitor adds the monitoring permissions.

**Comment by numbnut** [comment]
Thanks for the reply!
