### ISSUE TITLE
Search-guard-6:6.1.1 java TransportClient Problem

### ISSUE THREAD

**Issue by walterjar** [floragunncom/search-guard#440]
I configured elasticsearch-6.1.1 with search-guard-6:6.1.1-20.1, and use Java client to connect elasticsearch.  It looked like the client is fetched, but I can not use it to operate indexes.  
The same code can be used to create index for elasticsearch-6.1.1  with no search-guard.

Anyone please help me, thinks.

Here is the envirement.

* Search Guard and Elasticsearch version
	search-guard-6:6.1.1-20.1 elasticsearch-6.1.1

* JVM version and operating system version
	java version "1.8.0_45" in Windows 7

* Number of nodes in your cluster
	1

* Description of the bug
	I can fetch the TransportClient in java, but can not use it to operate ES indexes.

The error message is:  

"Exception in thread "main" ElasticsearchSecurityException[No user found for indices:admin/create]"
or
"NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{VxsPRNsaQze4_lC_hlfveA}{localhost}{127.0.0.1:9300}]]"

Here is the java code and elasticsearch.yml.

// elasticsearch-6.1.1
Settings settings = Settings.builder()
	.put("path.home", ".")
	.put("cluster.name", "elasticsearch")
	.put("searchguard.ssl.transport.enabled", "true")
	.put("searchguard.ssl.transport.keystore_filepath", "D:\\elasticsearch-6.1.1\\config\\node-0-keystore.jks")
	.put("searchguard.ssl.transport.truststore_filepath", "D:\\elasticsearch-6.1.1\\config\\truststore.jks")
	.put(SSLConfigConstants.SEARCHGUARD_SSL_HTTP_TRUSTSTORE_PASSWORD, "changeit")
	.put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_KEYSTORE_PASSWORD, "changeit")
	.put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_KEYSTORE_PASSWORD, "changeit")
	.put( SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_TRUSTSTORE_PASSWORD, "changeit")
	.put("searchguard.ssl.transport.enforce_hostname_verification", "false")
	.put("client.transport.sniff", "true")
	.build();

Client  client = new PreBuiltTransportClient(settings, SearchGuardSSLPlugin.class)
	  .addTransportAddress(new TransportAddress(InetAddress.getByName("localhost"), 9300));  

System.out.println("client=" + client);

// Fetched the client
// client=org.elasticsearch.transport.client.PreBuiltTransportClient@1cbb3d3b

// The "prepareCreate" code is correct when there is no search-guard
client.admin().indices().prepareCreate("hello").execute().actionGet();  
new XContentFactory();
XContentBuilder builder=XContentFactory.jsonBuilder()  
	  .startObject()  
	  .startObject("person")
	  .startObject("properties")  
	  .startObject("title").field("type", "text").field("store", true).endObject() 
	  .endObject()  
	  .endObject()  
	  .endObject();  

// Failed to create index
// Exception in thread "main" ElasticsearchSecurityException[No user found for indices:admin/create]
//	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:186)
//	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
// or
//Exception in thread "main" ElasticsearchSecurityException[No user found for indices:admin/create]
//	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:186)
//	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)

client.close();  

/**
	## elasticsearch.yml
	## Created by example-pki-scripts from search-guard-6:6.1.1-20.1 ( Deleted the opeopenssl command)
	## bash sgadmin.sh -ts truststore.jks -tspass changeit -ks kirk-keystore.jks -kspass changeit -nhnv -icl -cd ../sgconfig/

	searchguard.ssl.transport.enabled: true
	searchguard.ssl.transport.keystore_filepath: node-0-keystore.jks
	searchguard.ssl.transport.keystore_password: changeit
	searchguard.ssl.transport.truststore_filepath: truststore.jks
	searchguard.ssl.transport.truststore_password: changeit
	searchguard.ssl.transport.enforce_hostname_verification: false
	searchguard.ssl.http.enabled: true
	searchguard.ssl.http.keystore_filepath: node-0-keystore.jks
	searchguard.ssl.http.keystore_password: changeit
	searchguard.ssl.http.truststore_filepath: truststore.jks
	searchguard.ssl.http.truststore_password: changeit

	searchguard.authcz.admin_dn:
	  - CN=kirk,OU=client,O=client,L=Test,C=DE
 */

youxia

2018-01-22

**Comment by floragunncom** [comment]
Look here:
https://floragunn.com/transport-client-authentication-authorization/
https://floragunn.com/searchguard-elasicsearch-transport-clients/
https://github.com/floragunncom/search-guard/blob/f318138c840e85b796572f8b2a13c1a92e3758d0/src/test/java/com/floragunn/searchguard/IntegrationTests.java#L310

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
