### ISSUE TITLE
sg_kibana_user role not working

### ISSUE THREAD

**Issue by francarl** [floragunncom/search-guard#448]
Elasticsearch version 6.1.0
Kibana version 6.1.0
Search Guard es-6.1.0

JVM: openjdk version "1.8.0_151"
Docker image: Linux version 4.9.60-linuxkit-aufs (root@4a42478ffb9a) (gcc version 6.3.0 (Alpine 6.3.0) )

* Steps to reproduce

1. Add new user to sg_internal_users.yml with role sg_kibana_user 
 
```
testuser:
  readonly: true
  hash: $2y$12$zpakL1HN4sDigiYHiG3FqOxBgj3dpoCncvN7BV048zIovrJ4d1bYG
  roles:
    - sg_kibana_user
```

2.  Reload configuration with 

> sgadmin.sh  -cd config/sg/  -ts config/sg/truststore.jks  -ks config/sg/kirk-keystore.jks -nhnv -icl 

3. Try to log on Kibana with testuser, login is successful but user can't do anything. 
This is the error on kibana log

```
{
  "type": "request",
  "@timestamp": "2018-02-04T14:30:27Z",
  "tags": [
    "error",
    "uncaught"
  ],
  "pid": 1,
  "message": "{ name: 'Error',\n  message: '[security_exception] no permissions for [indices:data/read/get] and User [name=testuser, roles=[sg_kibana_user], requestedTenant=null]',\n  stack: '[security_exception] no permissions for [indices:data/read/get] and User [name=testuser, roles=[sg_kibana_user], requestedTenant=null] :: {\"path\":\"_searchguard/api/permissionsinfo\",\"query\":{},\"statusCode\":403,\"response\":\"{\\\\\"error\\\\\":{\\\\\"root_cause\\\\\":[{\\\\\"type\\\\\":\\\\\"security_exception\\\\\",\\\\\"reason\\\\\":\\\\\"no permissions for [indices:data/read/get] and User [name=testuser, roles=[sg_kibana_user], requestedTenant=null]\\\\\"}],\\\\\"type\\\\\":\\\\\"security_exception\\\\\",\\\\\"reason\\\\\":\\\\\"no permissions for [indices:data/read/get] and User [name=testuser, roles=[sg_kibana_user], requestedTenant=null]\\\\\"},\\\\\"status\\\\\":403}\"}\\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)\\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)\\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\\n    at IncomingMessage.bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\\n    at emitNone (events.js:91:20)\\n    at IncomingMessage.emit (events.js:185:7)\\n    at endReadableNT (_stream_readable.js:974:12)\\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)' }"
}

```

Please help. Thank you.

**Comment by floragunncom** [comment]
This is very likely just a misconfiguration and not a bug. It looks like you missed somehow mapping the the roles in roles_mapping.yml or set searchguard.roles_mapping_resolution to BOTH

See http://docs.search-guard.com/latest/mapping-users-roles#mapping and http://docs.search-guard.com/latest/role-mapping-modes#expert-role-mapping-modes

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
