### ISSUE TITLE
 SG 6.2.2 trying to read jvm.options.dpkg-dist on startup 

### ISSUE THREAD

**Issue by ceeeekay** [floragunncom/search-guard#453]
* Search Guard and Elasticsearch version: 6.2.2
* JVM version: openjdk-8-jre-headless:amd64 8u151-b12-0ubuntu0.16.04.2
* Operating system version: Ubuntu 16.04.3 LTS
* Number of nodes in your cluster: 9
* Log: https://gist.github.com/ceeeekay/f57eefa1a437732c22055b0343398bf5

After an upgrade of ES to 6.2.2, we find we have a file named jvm.options.dpkg-dist, as our jvm.options file is modified and pushed with puppet.

On startup, SG is trying to read this file, and failing, causing elasticsearch to not start.

The read failure is due to the permissions on jvm.options.dpkg-dist being set root:elasticsearch 600 by dpkg.

SG should not be trying to read this file. We could fix this by having puppet set the permissions correctly on this file, but that seems unnecessary for a file we don't want to read anyway.

Thanks,
CK

**Comment by fbacchella** [comment]
That's not an enhancement, but a bug. I had ES failing to start because I was editing a file with vi and it created a .file.swp that prevent starting.

**Comment by fbacchella** [comment]
```
Exception in thread "main" java.lang.IllegalArgumentException: plugin [search-guard-6] is incompatible with version [6.2.2]; was designed for version [6.2.1]
```

With search-guard-6-6.x-HEAD-20180319.042837-1489. Did you build one for 6.2.2 ?

**Comment by floragunncom** [comment]
@fbacchella try this:
[search-guard-6-6.x-HEAD-SNAPSHOT.zip](https://github.com/floragunncom/search-guard/files/1824379/search-guard-6-6.x-HEAD-SNAPSHOT.zip)

**Comment by ceeeekay** [comment]
@floragunncom sorry I completely missed your update from 3 days ago. I'll test this tomorrow when I'm back at my desk. Thanks.

**Comment by fbacchella** [comment]
I have:
```
-rw-r----- 1 root root          16384 Mar 19 11:31 .log4j2.properties.swp
```

And ES is indeed running, I get no warning or error log. Perfect !

**Comment by ceeeekay** [comment]
@floragunncom Thanks, I can confirm this fixes the file permission error.

However, I'm getting the following messages in the logs every second, on every node running the snapshot:

`[2018-03-20T16:30:49,049][ERROR][c.f.s.s.t.DefaultPrincipalExtractor] retval: CN=<hostname>3,OU=dev,O=client,L=Wellington,C=NZ`

All nodes print this entry with the current master node as the hostname, and the master node prints it  for every other node in the cluster.

I have downgraded the plugin again and confirmed that this is not the case with the previous version.

Could you please take a look at this?

**Comment by fbacchella** [comment]
That's my fault. They added that logging to resolve my issue #454, it's just a test version.

**Comment by floragunncom** [comment]
Fixed with Search Guard v22: https://docs.search-guard.com/latest/changelog-6-x-22
