### ISSUE TITLE
HTTPProxyAuthenticator split on ','

### ISSUE THREAD

**Issue by fbacchella** [floragunncom/search-guard#456]
In the class [HTTPProxyAuthenticator](https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/http/HTTPProxyAuthenticator.java#L66) I see
```
backendRoles = ((String) request.header(rolesHeader)).split(",");
```

So if my roles send by my proxy contains the symbol `,` but are separated by a `;`, I can't change that. I think it should be added as a setting.

**Comment by floragunncom** [comment]
The HTTPProxyAuthenticator is deprecated, see https://docs.search-guard.com/latest/proxy-authentication , so i don't think we will implement this.

We are currently working on a replacement (and will incorporate your proposal into the new module).

**Comment by fbacchella** [comment]
For what version is that scheduler ? Version 7 ? The documentation just says it's deprecated but we don't know how or when it will be replaced.

**Comment by jochenkressin** [comment]
Current plans are to deprecate and replace it for v7.

**Comment by angocor** [comment]
Hello. Could you expand how the replacement will work?. We just found out about this feature and it is exactly what we need.

**Comment by jochenkressin** [comment]
There will be some configuration changes, and we will add more features to securing proxy communication with TLS. So it will not be a simple drop-in replacement but will require some manual adjustments. Apart from that, you can expect to have the same features set in 7.x.

**Comment by fbacchella** [comment]
I see it was fixed in 6-x-23_0, thanks a lot !
