### ISSUE TITLE
[solved] FreeIPA connect with LDAPauthorizator throws NullPointerException

### ISSUE THREAD

**Issue by gviewde** [floragunncom/search-guard#46]
I successfully connected search-guard with FreeIPA for **user based** authentication / authorization with following config:
```
searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.ldap.LDAPAuthenticationBackend
searchguard.authentication.authentication_backend.cache.enable: false

searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator

searchguard.authentication.ldap.host: ["ipa01.core.ab.local:389"]
searchguard.authentication.ldap.ldaps.ssl.enabled: false
searchguard.authentication.ldap.ldaps.starttls.enabled: false
searchguard.authentication.ldap.bind_dn: "uid=searchguard,cn=users,cn=accounts,dc=ab,dc=local"
searchguard.authentication.ldap.password: XXX
searchguard.authentication.ldap.userbase: "cn=users,cn=accounts,dc=ab,dc=local"
searchguard.authentication.ldap.usersearch: (uid={0})
searchguard.authentication.ldap.username_attribute: uid

searchguard.authentication.authorization.ldap.rolebase: "cn=groups,cn=accounts,dc=ab,dc=local"
searchguard.authentication.authorization.ldap.rolesearch: (member={0})
searchguard.authentication.authorization.ldap.userroleattribute: cn
searchguard.authentication.authorization.ldap.userrolename: memberOf
searchguard.authentication.authorization.ldap.resolve_nested_roles: false
```

```
 {
 "__Comment__": "For user test all filters are bypassed (so none will be executed). This means unrestricted access to this index for this user.",
"users": [
"test"
],
"filters_bypass": ["*"],
"filters_execute": []
}
```

Now I would like to add **role based** authentication / authorization with following additional config:
```
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.ldap.LDAPAuthorizator
searchguard.authentication.authorizer.cache.enable: false
```
```
 {
 "__Comment__": "For admin role all filters are bypassed (so none will be executed) for all indices. This means unrestricted access at all for this role.",
 "roles": [
 "admins"
 ],
 "filters_bypass": ["*"],
 "filters_execute": []
 }
```

Unfortunately search-guard throws following NullPointerExeption:
`
java.lang.NullPointerException
        at com.floragunn.searchguard.authorization.ldap.LDAPAuthorizator.fillRoles(LDAPAuthorizator.java:285)
        at com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator.authenticate(HTTPBasicAuthenticator.java:83)
        at com.floragunn.searchguard.rest.AbstractACRestFilter.process(AbstractACRestFilter.java:178)
...
`

Any hint to solve this issue?

**Comment by floragunncom** [comment]
set
<pre># The attribute in a role entry containing the name of that role
searchguard.authentication.authorization.ldap.rolename: name
</pre> to the attribute which contains the name of the role

see also https://tomcat.apache.org/tomcat-8.0-doc/realm-howto.html#JNDIRealm

**Comment by gviewde** [comment]
I forgot to mention that this parameter is already defined with

`searchguard.authentication.authorization.ldap.rolename: cn`

Unfortunately the problem persists with this setting.

**Comment by gviewde** [comment]
'userrolename' needs to be defined as

`searchguard.authentication.authorization.ldap.userrolename: member`

**Comment by adamlwgriffiths** [comment]
If it's solved, then please close the issue.

**Comment by floragunncom** [comment]
Assume solved, pls reopen if not
