### ISSUE TITLE
.DS_Store files in .zip

### ISSUE THREAD

**Issue by fbacchella** [floragunncom/search-guard#460]
I downloaded https://repo1.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/6.2.2-10/search-guard-kibana-plugin-6.2.2-10.zip

And then checked it's content:
```
unzip -v search-guard-kibana-plugin-6.2.2-10.zip | grep .DS
    6148  Defl:N      417  93% 02-22-2018 20:44 e318af80  kibana/searchguard-kibana/lib/.DS_Store
    6148  Defl:N      357  94% 02-22-2018 20:44 546692b5  kibana/searchguard-kibana/public/.DS_Store
```

A good build system should never contains such kind of files.

**Comment by jochenkressin** [comment]
You are absolutely right and we will look into this. Thanks for reporting.

**Comment by floragunncom** [comment]
@jochenkressin i am wondering how this could happen? In clean.sh (which gets called in release.sh) this should be handled properly by `find . -name '.DS_Store' -type f -delete`

**Comment by jochenkressin** [comment]
Agreed, but we need to check.

**Comment by jochenkressin** [comment]
Confirmed as a bug.

**Comment by jochenkressin** [comment]
This was a problem with one specific Kibana Plugin version. Added checks and safeguards to prevent this from happening in the future.
