### ISSUE TITLE
Search Guard configuration GUI enabled when is not

### ISSUE THREAD

**Issue by fbacchella** [floragunncom/search-guard#461]
i'm using Search Guard community edition, and disabled entreprise in the elasticsearch.yaml:
```
searchguard.enterprise_modules_enabled: false
```

I installed then the kibana plugin and tried to access the configuration gui, as I saw in kibana's log:
```
log   [14:52:05.591] [info][status][plugin:searchguard@6.2.2] Status changed from yellow to yellow - Search Guard configuration GUI enabled
```

I think it should have said it's disabled, like other entreprise features:
```
log   [14:52:05.451] [info][status][plugin:searchguard@6.2.2] Status changed from yellow to yellow - Search Guard multitenancy disabled
log   [14:52:05.452] [info][status][plugin:searchguard@6.2.2] Status changed from yellow to yellow - Search Guard copy JWT params disabled
```

**Comment by jochenkressin** [comment]
That's not possible technically. During startup of Kibana the ES cluster is not reachable and thus we can't check if the REST API is available on ES or not. The message just states that the Kibana GUI part has been initialized successfully.

However, we will make the log message a bit more obvious, just need to think about the right wording here. Any suggestions?

**Comment by jochenkressin** [comment]
Will be added in the next release.

**Comment by jochenkressin** [comment]
Fixed with the release of Search Guard v22 / Kibana Plugin v11 : https://docs.search-guard.com/latest/changelog-6-x-22
