### ISSUE TITLE
sgadmin kill Elasticsearch&

### ISSUE THREAD

**Issue by nchanmala** [floragunncom/search-guard#464]
WARNING: JAVA_HOME not set, will use /bin/java
Search Guard Admin v6
Will connect to 11.0.16.44:9300 ... done
Connected as CN=kadmin,OU=client,O=client,L=Test,C=DE
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: ESPROD
Clusterstate: GREEN
Number of nodes: 14
Number of data nodes: 10
searchguard index already exists, so we do not need to create one.
Populate config from /ES_HOME/elasticsearch-6.1.2/plugins/search-guard-6/sgconfig
Will update 'sg/config' with ../sgconfig/sg_config.yml
   SUCC: Configuration for 'config' created or updated
Will update 'sg/roles' with ../sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'sg/rolesmapping' with ../sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'sg/internalusers' with ../sgconfig/sg_internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update 'sg/actiongroups' with ../sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Done with success
[1]+  Killed                  ./elasticsearch  (wd: /ES_HOME/elasticsearch-6.1.2/bin)

**Comment by floragunncom** [comment]
Is this reproducible? If yes please post whats in the logs of the killed ES node.

Pls provide also the following information:
* Elasticsearch and SG version
* Operating system details
* JVM version and vendor
* Installed tcnative + openssl version (if any)

**Comment by floragunncom** [comment]
no feedback, assume solved
