### ISSUE TITLE
request [13:03:08.115] [error][uncaught] { name: 'Error',   message: '[index_not_found_exception] no such index, with { resource.type="index_expression" & resource.id="_searchguard" & index_uuid="_na_" & index="_searchguard" }

### ISSUE THREAD

**Issue by sg-beginner** [floragunncom/search-guard#467]
When enterprise mode is disable I'm getting following error on Kibana for every user that logs in.

request [13:03:08.115] [error][uncaught] { name: 'Error',
  message: '[index_not_found_exception] no such index, with { resource.type="index_expression" & resource.id="_searchguard" & index_uuid="_na_" & index="_searchguard" }',
  stack: '[index_not_found_exception] no such index, with { resource.type="index_expression" & resource.id="_searchguard" & index_uuid="_na_" & index="_searchguard" } :: {"path":"/_searchguard/api/permissionsinfo","query":{},"statusCode":404,"response":"{\\"error\\":{\\"root_cause\\":[{\\"type\\":\\"index_not_found_exception\\",\\"reason\\":\\"no such index\\",\\"resource.type\\":\\"index_expression\\",\\"resource.id\\":\\"_searchguard\\",\\"index_uuid\\":\\"_na_\\",\\"index\\":\\"_searchguard\\"}],\\"type\\":\\"index_not_found_exception\\",\\"reason\\":\\"no such index\\",\\"resource.type\\":\\"index_expression\\",\\"resource.id\\":\\"_searchguard\\",\\"index_uuid\\":\\"_na_\\",\\"index\\":\\"_searchguard\\"},\\"status\\":404}"}\n    at respond (/opt/webm/servers/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:295:15)\n    at checkRespForFailure (/opt/webm/servers/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:254:7)\n    at HttpConnector.<anonymous> (/opt/webm/servers/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n    at IncomingMessage.bound (/opt/webm/servers/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)' }
 error  [13:03:08.066]  [index_not_found_exception] no such index, with { resource.type="index_expression" & resource.id="_searchguard" & index_uuid="_na_" & index="_searchguard" } :: {"path":"/_searchguard/api/permissionsinfo","query":{},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_expression\",\"resource.id\":\"_searchguard\",\"index_uuid\":\"_na_\",\"index\":\"_searchguard\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_expression\",\"resource.id\":\"_searchguard\",\"index_uuid\":\"_na_\",\"index\":\"_searchguard\"},\"status\":404}"}
    at respond (/opt/webm/servers/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:295:15)
    at checkRespForFailure (/opt/webm/servers/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:254:7)
    at HttpConnector.<anonymous> (/opt/webm/servers/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/opt/webm/servers/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Using RHEL  6.9

**Comment by NerdSec** [comment]
Hi,

As a new user trying out search-guard this is quite frustrating. I have been facing this same issue for the past 3 days, and i have tried to install this several number of times. The docs (https://docs.search-guard.com/latest/search-guard-installation.html) do not discuss this issue anywhere.

I have configured the TLS certificates using the TLS Offline tool and then proceeded to run the default sgconfig on the cluster. Then i disabled the Enterprise features, and I have a blank fields in all roles, users and mappings section in kibana. Is the Kibana GUI only available as an enterprise feature?

Regards,
N

**Comment by jochenkressin** [comment]
Sorry to hear that. Yes, the Configuration GUI is an enterprise feature. The respective page in the documentation is marked "Enterprise" (https://docs.search-guard.com/latest/configuration-gui). Can you please let me know where we should make this more explicit in your opinion, so we can improve the docs and prevent other users from running into the same issue? Thanks!

**Comment by NerdSec** [comment]
Thank you for clarifying that up. Now that you mention there is a label on every page of the docs. It seemed to have eluded for me for almost three days now. It would be a good idea to make it a little prominent, just a suggestion.

Also, you could add this in two places:

- **Docs**: It would be probably be a good idea to add it after this line. `The configuration GUI is part of the Search Guard Kibana plugin and installed by default.`

- **Feature Comparison**: Adding it here would also add value as it would emphasize the ease of use for the enterprise customers. `https://search-guard.com/product/#feature-comparison`

**Comment by NerdSec** [comment]
Also, the issue that 'sg-beginner' seems to be referring to along with me, should have been raised in the kibana plugin repo. A issue has been raised already (https://github.com/floragunncom/search-guard-kibana-plugin/issues/66).

I would like to point out that this happens when you set the enterprise modules to false in the demo cluster installation.

**Comment by jochenkressin** [comment]
Thanks for your valuable input! The issue you mentioned is already being worked on, we should be ready to release a new Kibana Plugin version including this and other fixes in the next week. We will update the docs alongside this release, so I will see to it that the changes you have proposed will make it in there as well. Leaving issue open until the new version has been released.

**Comment by jochenkressin** [comment]
Fixed with the release of Search Guard 22: https://docs.search-guard.com/latest/changelog-6-x-22. Documentation and website have been updated as well.
