### ISSUE TITLE
sgadmin opens 14 TCP sessions within 50 ms.

### ISSUE THREAD

**Issue by jalaja-git** [floragunncom/search-guard#468]
SG Version:search-guard-6-6.1.1-20.1
ES version:6.1.1
JVM version 1.8
Number of nodes :1 

**Problem**

I feel this is an issue. Please let me know otherwise.

sgadmin.sh opens like 14 TCP sessions within 50 milliseconds (Sends like 14 consecutive Hellos). 
Other than pushing the given below config ymls, is there anything else sg_admin does.?
sg_action_groups.yml  sg_config.yml  sg_internal_users.yml  sg_roles.yml  sg_roles_mapping.yml

https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/tools/SearchGuardAdmin.java#L435
Can you please point me to the code (line no 435 is I can see, not sure what that does internally) Is there a loop to open these sessions, so I can try modifying the code to have just one TCP session.

**Steps to reproduce:**
1. Start elastic and wait for it to listen on port 9200 and port 9300.
2. invoke sg_admin.sh which pushes the initial config. (you can run netstat -atn, output below to the number of TCP sessions opened within a very short time-span (55 ms)

thanks.
Jalaja

[]# netstat -atn | grep 9300 | grep TIME_WAIT
tcp6       0      0 10.0.0.1:52212          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52224          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52210          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52218          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52204          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52214          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52202          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52216          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52222          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52206          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52220          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52194          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52200          10.0.0.1:9300           TIME_WAIT
tcp6       0      0 10.0.0.1:52208          10.0.0.1:9300           TIME_WAIT

**Comment by floragunncom** [comment]
This is not Search Guard specific. sgadmin just acts as a transport client and connects to your ES cluster. If you do this without Search Guard installed you will also see many tcp connections. Pls ask your question here https://discuss.elastic.co therefore.

You might be also interested in these links:
* https://www.elastic.co/blog/found-elasticsearch-networking#connections-and-channels
* https://www.elastic.co/blog/found-interfacing-elasticsearch-picking-client
* https://discuss.elastic.co/t/transportclient-client-node-openning-too-many-tcp-connections/59217/5
* https://stackoverflow.com/questions/48668309/elastic-transportclient-too-many-tcp-connections?rq=1
