### ISSUE TITLE
use api can't show the status

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#470]
search-guard 5.6.8

use : http://ip:9200/_searchguard/api/user/admin?pretty
output: 

**No handler found for uri [/_searchguard/api/user/admin?pretty] and method [GET]**

**Comment by zqc0512** [comment]
update the jar file otuput

[2018-04-03T09:46:14,457][ERROR][c.f.s.d.r.a.UserApiAction]   **No ssl info found**

**Comment by floragunncom** [comment]
It seems you have not installed the REST module.

**Comment by floragunncom** [comment]
You find all information in the docs:
https://docs.search-guard.com/v5/search-guard-installation

Download the files from here (seems you downloaded the wrong files):
* https://github.com/floragunncom/search-guard-module-auditlog/wiki
* https://github.com/floragunncom/search-guard-rest-api/wiki

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
