### ISSUE TITLE
rest api output No ssl info found

### ISSUE THREAD

**Issue by zqc0512** [floragunncom/search-guard#474]
es 5.6.8
system: centos 7.3 x86_64
as now i down the right jar file like:

```
[root@xxx search-guard-5]# pwd
/opt/ES/es568/elasticsearch-5.6.8/plugins/search-guard-5
[root@f14cp-p1-soc34 search-guard-5]# ls
commons-cli-1.3.1.jar                                                         netty-codec-http-4.1.13.Final.jar  search-guard-5-5.6.8-19.jar
dlic-search-guard-module-auditlog-5.3-5-jar-with-dependencies.jar             netty-common-4.1.13.Final.jar      search-guard-ssl-5.6.8-23.jar
dlic-search-guard-module-kibana-multitenancy-5.4-4-jar-with-dependencies.jar  netty-handler-4.1.13.Final.jar     sgconfig
dlic-search-guard-rest-api-5.3-5-jar-with-dependencies.jar                    netty-resolver-4.1.13.Final.jar    tools
guava-19.0.jar                                                                netty-transport-4.1.13.Final.jar   transport-netty4-client-5.6.8.jar
netty-buffer-4.1.13.Final.jar                                                 plugin-descriptor.properties
netty-codec-4.1.13.Final.jar                                                  plugin-security.policy
[root@xxxx search-guard-5]# 
```
use curl and browser also output this error:

```
[2018-04-09T09:13:17,894][ERROR][c.f.s.d.r.a.UserApiAction] [xxx] No ssl info found
[2018-04-09T09:13:26,302][ERROR][c.f.s.d.r.a.UserApiAction] [xxx] No ssl info found
```
in elasticsearch.yml file also add
`searchguard.ssl.http.clientauth_mode: OPTIONAL`

the cmd is:

`[root@xxxxx example-pki-scripts]# curl -u xxx:xxx --insecure --cert node-1-signed.pem --key node-1.key.pem "http://xxx:9200/_searchguard/api/user/admin?pretty"`
output:
`No ssl info found
`
the browser is also:
![image](https://user-images.githubusercontent.com/25192261/38475082-e5540a8c-3bd7-11e8-92bd-7c18f3074945.png)

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
