### ISSUE TITLE
Error initializing search-guard 6.2.3 : Unexpected exception indices:data/write/bulk[s]

### ISSUE THREAD

**Issue by dizzler** [floragunncom/search-guard#477]
For Elasticsearch/search-guard version 6.2.3, I am unable to initialize search-guard due to (what appears to be) a permissions issue for the admin user/cert/DN. When writing the initial search-guard config to the "searchguard" index, all writes fail with error: 
ElasticsearchSecurityException[Unexpected exception indices:data/write/bulk[s]]

**Elasticsearch Version: 6.2.3
Search Guard Version: 6.2.3-22.0
Number of nodes: 4
Number of data nodes: 1
OS version: CentOS Linux release 7.4.1708 (Core)
Java version: OpenJDK Runtime Environment (build 1.8.0_161-b14)
[search-guard-6_cv_debug.output.txt](https://github.com/floragunncom/search-guard/files/1907903/search-guard-6_cv_debug.output.txt)
**

Here is the output from sgadmin.sh:

```
WARNING: JAVA_HOME not set, will use /bin/java
Search Guard Admin v6
Will connect to cvdev1-aw1-platform-services-01.node.cv-dev1-aws-west-1.consul:9300 ... done
Elasticsearch Version: 6.2.3
Search Guard Version: 6.2.3-22.0
Connected as CN=admin.elasticsearch-master.service.cv-dev1-aws-west-1.consul,OU=CSP-DB-Mgmt,O=Cloudvisory
Diagnostic trace written to: /usr/share/elasticsearch/plugins/search-guard-6/tools/sgadmin_diag_trace_2018-Apr-13_14-20-24.txt
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: elasticsearch-cluster-cvdev1aw1
Clusterstate: GREEN
Number of nodes: 4
Number of data nodes: 1
searchguard index does not exists, attempt to create it ... done (auto expand replicas is on)
Populate config from /etc/elasticsearch/search-guard/
Will update 'sg/config' with /etc/elasticsearch/search-guard/sg_config.yml
   FAIL: Configuration for 'config' failed because of ElasticsearchSecurityException[Unexpected exception indices:data/write/bulk[s]]
Will update 'sg/roles' with /etc/elasticsearch/search-guard/sg_roles.yml
   FAIL: Configuration for 'roles' failed because of ElasticsearchSecurityException[Unexpected exception indices:data/write/bulk[s]]
Will update 'sg/rolesmapping' with /etc/elasticsearch/search-guard/sg_roles_mapping.yml
   FAIL: Configuration for 'rolesmapping' failed because of ElasticsearchSecurityException[Unexpected exception indices:data/write/bulk[s]]
Will update 'sg/internalusers' with /etc/elasticsearch/search-guard/sg_internal_users.yml
   FAIL: Configuration for 'internalusers' failed because of ElasticsearchSecurityException[Unexpected exception indices:data/write/bulk[s]]
Will update 'sg/actiongroups' with /etc/elasticsearch/search-guard/sg_action_groups.yml
   FAIL: Configuration for 'actiongroups' failed because of ElasticsearchSecurityException[Unexpected exception indices:data/write/bulk[s]]
FAIL: Expected 4 nodes to return response, but got only 0
Done with failures
```

Additional diagnostic info/logs attached, including:

- the '--diagnose' output from sgadmin.sh, 
- the elasticsearch.yml config file,
- elasticsearch cluster log snippet
[search-guard-6_cv_debug.output.txt](https://github.com/floragunncom/search-guard/files/1907910/search-guard-6_cv_debug.output.txt)
[elasticsearch-cluster-cvdev1aw1.log](https://github.com/floragunncom/search-guard/files/1907911/elasticsearch-cluster-cvdev1aw1.log)

**Comment by floragunncom** [comment]
There must be something in the logs on ERROR level like 'Unexpected exception ...' which includes a stacktrace. Maybe its in one of the three other logfiles. Can you send over the missing logfiles from the other nodes?

**Comment by dizzler** [comment]
Here you go. Full log from startup until failure for all four nodes in the cluster. This is just a dev cluster until I get this working, so I recreated from scratch to generate these logs.

[elasticsearch-cluster-cvdev1aw1.logs.zip](https://github.com/floragunncom/search-guard/files/1909620/elasticsearch-cluster-cvdev1aw1.logs.zip)

**Comment by floragunncom** [comment]
Thats a tricky one it looks like. I cannot reproduce it right now.
Can you mail your certificates to us? How did you generate them?

Pls also add the following line to every log4j2.properties file:

<pre>
logger.searchguard.name = com.floragunn
logger.searchguard.level = all
logger.searchguardtrace.name = sg_action_trace
logger.searchguardtrace.level = all
</pre>

This generates a lot of debug/trace output. Pls post all of the logs.

**Comment by dizzler** [comment]
Here are the trace-level logs from all four nodes in the cluster:
[elasticsearch-cluster-cvdev1aw1.trace.logs.zip](https://github.com/floragunncom/search-guard/files/1917388/elasticsearch-cluster-cvdev1aw1.trace.logs.zip)

The certs are generated using Vault, then converted from PEM to PKCS12 format, then loaded into a newly created Java keystore. A similar process is used for creating the Java truststore. This is a hack for Java compatibility as Vault issues certs in a format that Java seems to hate, and this hack works for other Java apps that needed TLS auth/encryption for access to another database which shall not be named.

I can email the certs as they are generated during the deployment, and the deployment gets destroyed after dev testing. Email address?

**Comment by floragunncom** [comment]
Seems you have configured different admin_dn settings in your elasticsearch.yml files? Pls make sure that the   
searchguard.authcz.admin_dn setting is identical on all nodes in elasticsearch.yml. Normally you have just one admin dn but its also ok to have more than one. You seem to deal with two certs currently:

<pre>
CN=admin.elasticsearch-master.service.cv-dev1-aws-west-1.consul,OU=CSP-DB-Mgmt,O=Cloudvisory
CN=admin.elasticsearch-data.service.cv-dev1-aws-west-1.consul,OU=CSP-DB-Mgmt,O=Cloudvisory
</pre>

There is no need and no reason to have such like a "master" and a "data" admin cert.

**Comment by dizzler** [comment]
PEBCAK. Got it.

Using a single admin cert (as intended/required) fixes the problem. The certificate CN for that admin cert was intended to match a service FQDN in Consul, and I didn't realize I was setting that differently on the one data node. If I understand correctly, a misconfiguration caused the admin cert to be considered "admin" by the master Elasticsearch nodes, but not by the data node(s). Hence, the error only showed up once sgadmin.sh attempted to write data to the searchguard index.

Closing this bug report from my end.

**Comment by dizzler** [comment]
Thank you for the quick responses, btw.
