### ISSUE TITLE
Internal demo passwords still cached

### ISSUE THREAD

**Issue by stobias123** [floragunncom/search-guard#480]
Github is a place only for reporting bugs or feature requests.
If you report a bug please include always the following informations:

**SG / ES Version:** 
5.6.2

**JVM Version:**
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)

**Nodes in Cluster:** 
3

**Description of the bug:**
After changing the password in `sg_internal_users.yml` to a new hash, or even just a bogus string, I can still log into kibana with the demo user password.

Relevant config and logs
```
[root@data1 elasticsearch]# cat plugins/search-guard-5/sgconfig/sg_internal_users.yml
# This is the internal user database
# The hash value is a bcrypt hash and can be generated with plugin/tools/hash.sh
admin:
  hash: booooo
[root@data1 elasticsearch]#  ## Reloading config
[root@data1 elasticsearch]# /usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh -cert /usr/share/elasticsearch/config/certs/admin.pem -key /usr/share/elasticsearch/config/certs/admin.key -keypass certificatepassword -cacert /usr/share/elasticsearch/config/certs/root-ca.pem -icl -nhnv -rl

Search Guard Admin v5
Will connect to localhost:9300 ... done

### LICENSE NOTICE Search Guard ###
.....
Reload config on all nodes
[root@data1 elasticsearch]#
```
-->

**Comment by floragunncom** [comment]
`-rl` just reloads the config but if you made changes to the sg_*.yml files you need of course also "push" them:

<pre>sgadmin.sh -cert /usr/share/elasticsearch/config/certs/admin.pem -key /usr/share/elasticsearch/config/certs/admin.key -keypass certificatepassword -cacert /usr/share/elasticsearch/config/certs/root-ca.pem -icl -nhnv -cd /path/to/sgconfyml
</pre>

See also https://docs.search-guard.com/latest/sgadmin and https://docs.search-guard.com/latest/sgadmin-examples#sgadmin-examples
