### ISSUE TITLE
Building SearchGuard Locally

### ISSUE THREAD

**Issue by gsaxam** [floragunncom/search-guard#483]
I am trying to build searchguard locally on my machine, and upon running `mvn package` , I do not find the fat jar `.zip` file in the target directory anywhere. 

I am guessing that the the command `bin/elasticsearch-plugin install -b` need a searchguard zip package to install.

Can you please let me know how I can build it locally and install the version I built?

**Comment by floragunncom** [comment]
mvn package -Penterprise

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
