### ISSUE TITLE
roleMapSettings.getAsList(".hosts") is incorrectly handled.

### ISSUE THREAD

**Issue by jalaja-git** [floragunncom/search-guard#487]
Search Guard : Latest code base.

Older versions is doing it correctly - one is getAddress() if IP address is used, getHost() if domains are used. .
I want to open another issue of specifying wildcard '*' under hosts in rolesmapping.

https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/configuration/PrivilegesEvaluator.java#L1068

                if (caller != null &&  WildcardMatcher.matchAny(roleMapSettings.getAsList(".hosts"), caller.getAddress())) {
                    sgRoles.add(roleMap);
                    continue;
                }

                if (caller != null && WildcardMatcher.matchAny(roleMapSettings.getAsList(".hosts"), caller.getAddress())) {
                    sgRoles.add(roleMap);
                    continue;
                }

https://github.com/floragunncom/search-guard/blob/5.2.0/src/main/java/com/floragunn/searchguard/configuration/PrivilegesEvaluator.java#L895

            if (caller != null &&  WildcardMatcher.matchAny(roleMapSettings.getAsArray(".hosts"), caller.getAddress())) {
                sgRoles.add(roleMap);
                continue;
            }

            if (caller != null && WildcardMatcher.matchAny(roleMapSettings.getAsArray(".hosts"), caller.getHost())) {
                sgRoles.add(roleMap);
                continue;
            }

        }

Thanks,
Jalaja

**Comment by floragunncom** [comment]
What do you mean with `I want to open another issue of specifying wildcard '*' under hosts in rolesmapping.`?

**Comment by jalaja-git** [comment]
Thanks for the fix. Fix looks good to me.. it would be great if there we can document searchguard.dynamic.hosts_resolver_mode","ip-only". if there is already one, Please ignore.

Specifying * under hosts in rolesmapping, I want to discuss in another thread.  I will post it right away. 

Jalaja.
