### ISSUE TITLE
Sg admin gives - No nodes found

### ISSUE THREAD

**Issue by Sanjayaprasad** [floragunncom/search-guard#496]
Hi 

Elasticsearch 6.2.0
Searchguard is 6.2.2

we installed searchguard for elasticsearch and followed all process, but after executing elasticsearch, it is not starting elasticsearch, giving Not yet initialized [you may need to run sgadmin]
while running sgadmin it is giving NoNodesAvalaible exception error.
error: unable to check whether cluster is sane: none f the configured nodes are available.

Below is the sgadmin command which we are using : 

`sgadmin.sh -cd ..\sgconfig -key ..\..\..\config\kirk-key.pem -cert ..\..\..\config\kirk.pem -cacert ..\..\..\config\root-ca.pem -nhnv -icl`

Any early solution for this will be very helpful.
Thanks in advance:-)

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
