### ISSUE TITLE
Failed send ping to zen_unicast_IpAddress:Port 

### ISSUE THREAD

**Issue by KSSekhar** [floragunncom/search-guard#497]
Elastic Search cluster with 3 node configuration.I configured distributed of elastic search its working properly.After installing Search Guard in 3 node of ES.Inter Node communication failed send ping signal.

Search Guard version: 6
Elastic Search version : 6
JVm version : 1.8
Operating System : CentOS 7
Number of Nodes : 3
Bug: Inter node communicating not happending.

Node1 configuration with Log:
[ElasticSearchNode1.txt](https://github.com/floragunncom/search-guard/files/2019386/ElasticSearchNode1.txt)
[Subex.log](https://github.com/floragunncom/search-guard/files/2019389/Node1.log)

Node2 configuration With Log :
[ElasticSearchNode2.txt](https://github.com/floragunncom/search-guard/files/2019387/ElasticSearchNode2.txt)
[Subex.log](https://github.com/floragunncom/search-guard/files/2019391/Node2.log)

Node3 configuration With Log: 
[ElasticSearchNode3.txt](https://github.com/floragunncom/search-guard/files/2019388/ElasticSearchNode3.txt)

To generate Certificate used TLS Tool and below tlsconfig.yml file
[tlsconfig.txt](https://github.com/floragunncom/search-guard/files/2019397/tlsconfig.txt)
Command  : 
./sgtlstool.sh -c ../config/tlsconfig.yml -v true -overwrite true -ca -crt

I didn't changed  any thing in sgconfig Folder of Search Guard.

Please reply as soon as possible

**Comment by floragunncom** [comment]
Try to avoid blanks in all your dn's

`dn: CN=Sekhar.subexworld.org,C=in,L=Bangalore,O=Subex Ltd` instead of

`dn: CN=Sekhar.subexworld.org,C=in, L=Bangalore, O=Subex Ltd`

**Comment by KSSekhar** [comment]
Now dirstributed cluster of Elastic search configured and working properly.But Low Level Rest Client with Sniffer of Elastic Search API its not working.If comment Sniffer part of Elastic Search API its working properly.

Why Low level rest client with Sniffer not working ?

Please check source code of low level rest client.

**Comment by KSSekhar** [comment]
Sorry ,By mistake send without source code.

Please check source code low level rest client of elastic search java API
[javalowlevelrestapi.zip](https://github.com/floragunncom/search-guard/files/2021242/javalowlevelrestapi.zip)

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
