### ISSUE TITLE
Demo installer doesn't check for "xpack.security.enabled" before adding to config

### ISSUE THREAD

**Issue by hackery** [floragunncom/search-guard#499]
* ES 6.2.2 / SG 6.2.2-22.1
* JVM 1.8.0_161 on Windows 7 Pro SP1
* Single node cluster

Running the demo installer adds "xpack.security.enabled: false" without checking that the setting isn't already there (unlike several other additions). On startup, ES then fails immediately when parsing config, not accepting the duplicate.

Yes, I can "just delete it". However, it's inconvenient when I'm running through installation steps many times, and it's another step (and dependency) to add to automation.

**Comment by floragunncom** [comment]
Do you want prepare a PR for that?

**Comment by jochenkressin** [comment]
Added in Search Guard 22.3 which has just been released:

https://docs.search-guard.com/latest/changelog-searchguard-6-x-22_3
