### ISSUE TITLE
Allow disable of auto-expand and setting of replica count in single run

### ISSUE THREAD

**Issue by ewolinetz** [floragunncom/search-guard#500]
As part of calling `SearchGuardAdmin`, I would like to be able to initially create my SG index with a specified replica count and with replica auto-expand disabled without needing to rerun two more times.

We should be able to specify the replica count and have auto-expand disabled if required and not hardcode into the initial settings here:
https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/tools/SearchGuardAdmin.java#L619

**Comment by ewolinetz** [comment]
If possible, this should also be backported to the 5.x and 2.x releases as well.

**Comment by ewolinetz** [comment]
This is a request independent of that bugzilla. 

If a user wants to create their searchguard index without auto-expand and with a specific replica count they need to rerun the searchguard admin utility multiple times and I would like to be able to configure that all in a single run.

**Comment by floragunncom** [comment]
Ok, we can do this for ES >=5.6 but 2.x is EOL

**Comment by jochenkressin** [comment]
Added in Search Guard 22.3 which has just been released:

https://docs.search-guard.com/latest/changelog-searchguard-6-x-22_3

You can use the new "-er" switch. It accepts both the replica count or a pattern as described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html
