### ISSUE TITLE
6.2.1 Unable to set searchguard.basicauth.forbidden_usernames

### ISSUE THREAD

**Issue by tbennett6421** [floragunncom/search-guard#506]
Search Guard and Elasticsearch version
---
`elasticsearch --version`
Version: 6.2.1, Build: 7299dc3/2018-02-07T19:34:26.990113Z, JVM: 1.8.0_171

`elasticsearch-plugin list`
search-guard-6

`kibana --version`
6.2.1

`kibana-plugin list`
searchguard@6.2.1

JVM version and operating system version
---
`java -showversion`
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

` lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Number of nodes in your cluster
---
3 master-eligible node
2 data nodes
1 coordinating node

Description of the bug
---
We currently have a single coordinating node running kibana. When we set `searchguard.basicauth.forbidden_usernames: ["kibanaserver", "logstash"]` in `kibana.yml` and restart kibana we see the following occur

* kibana rapidly restarts, systemctl will show it run for about 2 seconds, die, then restart
* kibana spams the log file with the following message

{
    "type": "error",
    "@timestamp": "2018-06-12T13:47:41Z",
    "tags": [
        "fatal"
    ],
    "pid": 28223,
    "level": "fatal",
    "error": {
        "message": "child \"searchguard\" fails because [child \"basicauth\" fails because [\"forbidden_usernames\" is not allowed]]",
        "name": "ValidationError",
        "stack": "ValidationError: child \"searchguard\" fails because [child \"basicauth\" fails because [\"forbidden_usernames\" is not allowed]]\n    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)\n    at _validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)\n    at root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)\n    at Config._commit (/usr/share/kibana/src/server/config/config.js:119:35)\n    at Config.set (/usr/share/kibana/src/server/config/config.js:89:10)\n    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:62:10)\n    at /usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:22:12\n    at next (native)\n    at step (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:45:191)\n    at /usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:45:361"
    },
    "message": "child \"searchguard\" fails because [child \"basicauth\" fails because [\"forbidden_usernames\" is not allowed]]"
}

**Comment by tbennett6421** [comment]
Commenting `searchguard.basicauth.forbidden_usernames: ["kibanaserver", "logstash"]` in `kibana.yml` and restarting kibana fixes the issue

**Comment by floragunncom** [comment]
@tbennett6421 What is the version of the SG Kibana plugin? Make sure your running at least v11 (but we strongly recommend to update to latest v13 because of security fixes)

Pls. also post your complete kibana.yml

**Comment by tbennett6421** [comment]
I think we are running search-guard-kibana-plugin-6.2.1-10, is there a way I can double-check?

Posted `kibana.yml`
```
server.port: 5601
server.host: "127.0.0.1"
server.name: "SIEM-Prod"

elasticsearch.url: "https://siem-prod-cluster.fqdn.example.com:9200"
kibana.index: ".kibana"

elasticsearch.username: "kibanaserver"
elasticsearch.password: "<redacted>"
elasticsearch.ssl.verificationMode: none
elasticsearch.requestHeadersWhitelist: ["sg_tenant", "x-authenticated-user", "authorization", "x-forwarded-for", "x-forwarded-server", "x-forwarded-by", "x-proxy-user", "x-proxy-roles"]

logging.dest: /var/log/kibana/kibana.log
logging.silent: false
logging.quiet: false

searchguard.basicauth.enabled: true
searchguard.multitenancy.enabled: false
searchguard.cookie.name: "searchguard_authentication"
searchguard.cookie.secure: true
searchguard.cookie.password: "<redacted>"
searchguard.multitenancy.show_roles: true
searchguard.multitenancy.enable_filter: true
searchguard.multitenancy.tenants.enable_global: true
searchguard.multitenancy.tenants.enable_private: true
```

**Comment by mgustafsson1** [comment]
Could you please check that you have the following line in the SG Kibana plugin?
https://github.com/floragunncom/search-guard-kibana-plugin/blob/6.x/index.js#L38

That's where the configuration validation takes place, and it seems like the error message you see implies that the validation for forbidden_usernames goes wrong when starting Kibana.

If the line is there, you could try clearing the "optimize" folder in Kibana?

**Comment by tbennett6421** [comment]
yeah I looked any there is no forbidden_usernames in that file, Was that something added after 6.2.1-10?

**Comment by jochenkressin** [comment]
Yes, this was added in v11 of the plugin: https://docs.search-guard.com/6.x-20/changelog-6-x-22

**Comment by tbennett6421** [comment]
Thank you, I did not realize that this was a newer option, I've updated to 6.2.1-13 and after clearing the optimize cache it works fine.
