### ISSUE TITLE
User annot save dashboard in private tenant

### ISSUE THREAD

**Issue by iahmad-khan** [floragunncom/search-guard#507]
Hi,

By default , the user can see the global as read only and the private tenant as RW. 

But when I swtich to private tenant and try to save the dashboard , it says permission denied?

How can we configure a user to save his own dashboards and be able to read data from all other indices?

`Visualization Editor: no permissions for [indices:data/write/index] and User [name=webprod, roles=[readall], requestedTenant=null]: [security_exception] no permissions for [indices:data/write/index] and User [name=webprod, roles=[readall], …`

I have assigned him the readall role so that the user can read data from all indices. 
Do I need to assign the role special permissions to write to his own kibana index?

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
