### ISSUE TITLE
Invalid 'Authorization' header

### ISSUE THREAD

**Issue by surewecan** [floragunncom/search-guard#51]
We have configured search guard with AD authentication. It works, but for users with colon symbol auth doesn't work with the following WARN:

    [WARN ][com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator] Invalid 'Authorization' header, send 401 and 'WWW-Authenticate Basic'

The problem is in this part of https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/authentication/http/basic/HTTPBasicAuthenticator.java:

`if (decodedBasicHeaderParts.length != 2 || decodedBasicHeaderParts[1] == null)`

When password contains colon (":"), decoded phrase include more than 2 parts and auth attempt throws an exception.

**Comment by floragunncom** [comment]
confirmed as a bug. can you provide a pull request/patch to fix it?

**Comment by floragunncom** [comment]
We need also check properly for a blank password

**Comment by floragunncom** [comment]
Fixed for Search Guard 2. Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
