### ISSUE TITLE
Cannot install the searchguard with elasticsearch 6.3.0

### ISSUE THREAD

**Issue by iahmad-khan** [floragunncom/search-guard#510]
Error messege:

`ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.`

Which version works with elasticsearch 6.3.0 ?

Or there is no support for 6.3.0 yet?

**Comment by floragunncom** [comment]
Search Guard 6.3.0 has not been released yet.

**Comment by platzerg** [comment]
Hi,
when will the search-guard for ELK-Stack 6.3.0 be released?

THX

**Comment by floragunncom** [comment]
Search Guard for 6.3.0 released!
https://groups.google.com/d/msg/search-guard/OoBk8emtgLw/Qwt5gflkCAAJ
