### ISSUE TITLE
Can not create roles in everywhere

### ISSUE THREAD

**Issue by HitsuYaga** [floragunncom/search-guard#512]
Hi all, I have just setup ELK with Search Guard plugin. Everything is ok. But I can not create role through Kibana (using account admin, admin. Please help to check image attached) and file sg-roles.yml

# Roles for apache logs
sg_apache-read:
  readonly: true
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    'apache*':
      '*':
        - READ

I viewed any logs in my server but I can't found any problem.
Attach my screenshots of error:
![capture](https://user-images.githubusercontent.com/16111095/41858603-7cd4505a-78c4-11e8-9599-b87ba46a749a.JPG)

* Search Guard and Elasticsearch version: com.floragunn:search-guard-6:6.3.0-22.3 and ELK 6.3
* JVM version and operating system version: Java 1.8 and  Ubuntu 16.04
* Number of nodes in your cluster: 1 one per instance

**Comment by floragunncom** [comment]
Please do not cross-post. This question has been asked and answered here:

https://stackoverflow.com/questions/51026399/create-roles-in-search-guard
