### ISSUE TITLE
Created action group does not appear when editing/creating a search guard role's index permissions

### ISSUE THREAD

**Issue by havlan** [floragunncom/search-guard#518]
Hi. 
Searchguard: 6.2.4-31.2 (TRIAL)
Nodes: 4

I'm attempting to add an action group to a searchguard role with the gui in kibana as the admin.
To be more specific it's a read only group for .kibana index.

I add that group with four single permissions:
```
indices:data/read/get
indices:data/read/search
indices:data/read/mget*
indices:data/read/search*
```
I add that group, and try to edit a Search Guard role with index .kibana (doc_type: *) to use that action group but the action group does not appear when editing index permissions for .kibana for the user. Even after several minutes. 

I experienced this before, I created two different action groups, but only the first one created appeared in the Permissions: Action Groups tab. (They appear in the action group list)

Could it be a misconfiguration on my part? Or perhaps I'm missing something.

**Comment by floragunncom** [comment]
This might be a caching issue. Action Groups are fetched and cached for performance reasons, and deleted and re-fetched if something changes. Does the newly created action group appear if you log out and log in again?

**Comment by havlan** [comment]
It does! Should purge cache(from SG gui) have the same effect?
Thanks for responding.

**Comment by floragunncom** [comment]
No, this purges the cache on Elasticsearch, the action groups in the GUI are cached in your browser (session storage). It seems to be problem with purging this cache when action groups change. I'll label it as bug, thanks for reporting. Which version of the Kibana plugin are you using? The latest v13?

**Comment by havlan** [comment]
Yes I saw it being created on the ES side and it being listed in the action groups list.
At least it worked when logging in and out!
From the package.json
```json
"version":"6.2.4"
```

**Comment by floragunncom** [comment]
Fixed with Kibana Plugin v14
