### ISSUE TITLE
Able to search alias indice with only SEARCH privileges

### ISSUE THREAD

**Issue by matejzero** [floragunncom/search-guard#523]
As talked in [Google issue](https://groups.google.com/forum/#!topic/search-guard/v3lAHn5UV4s), it looks like I can access logs in alias only with `SEARCH` privilege.

I have an index `logs-dhcpd-*` and an alias on it called `test-infra`. I add `SEARCH` privileges to both and if I go directly to `logs-dhcpd-*` indice in Kibana, I get an error:
`Discover: [security_exception] no permissions for [indices:data/read/field_stats] and User [name= testuser, roles=[]]`

This is what I see on ES side:
```
[2018-07-17T13:14:47,462][INFO ][c.f.s.c.PrivilegesEvaluator] No index-level perm match for User [name= testuser, roles=[]] [IndexType [index=logs-dhcpd-2018.03, type=*], IndexType [index=logs-dhcpd-2017.12, type=*], IndexType [index=logs-dhcpd-2018.04, type=*], IndexType [index=logs-dhcpd-2018.05, type=*], IndexType [index=logs-dhcpd-2018.06, type=*], IndexType [index=logs-dhcpd-2018.07, type=*], IndexType [index=logs-dhcpd-2018.07-v1, type=*], IndexType [index=logs-dhcpd-2018.01, type=*], IndexType [index=logs-dhcpd-2018.02, type=*]] [Action [[indices:data/read/field_stats]]] [RolesChecked [sg_role_test]]
[2018-07-17T13:14:47,462][INFO ][c.f.s.c.PrivilegesEvaluator] No permissions for {sg_role_test=[IndexType [index=logs-dhcpd-2018.03, type=*], IndexType [index=logs-dhcpd-2017.12, type=*], IndexType [index=logs-dhcpd-2018.04, type=*], IndexType [index=logs-dhcpd-2018.05, type=*], IndexType [index=logs-dhcpd-2018.06, type=*], IndexType [index=logs-dhcpd-2018.07, type=*], IndexType [index=logs-dhcpd-2018.07-v1, type=*], IndexType [index=logs-dhcpd-2018.01, type=*], IndexType [index=logs-dhcpd-2018.02, type=*]]}
```

But if I go to `infra` alias, then I can see filtered (for some reason, it looks like it's still using a DLS filter which I removed) logs from `logs-dhpcd-*` indices.

#### Action groups
```
SEARCH:
  - "indices:data/read/search*"
  - "indices:data/read/msearch*"
  - SUGGEST

SUGGEST:
  - "indices:data/read/suggest*"
```

#### Internal users
```
# test user
testuser:
  hash: <passwordhash>
```

#### Roles:
```
sg_role_test:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    'universal':
      '*':
        - READ
    'test*':
      '*':
        - SEARCH
    'logs-dhcpd-*':
      '*':
        - SEARCH
    '?kibana*':
      '*':
        - INDICES_ALL
```

#### Roles mapping
```
sg_role_test:
  users:
    - testuser
```

**Comment by jochenkressin** [comment]
So the security exception you see in Kibana is about this action:

`indices:data/read/field_stats`

This is issued by Kibana, but the SEARCH action group does not contain the field_stats permissions. What is strange is that the behavior is different based on whether you use the index name or the alias. Will investigate. Which exact version are you using?

**Comment by jochenkressin** [comment]
Sorry, it's in the GG post: ES 5.6.6 with SG 5.6.6-18.

**Comment by matejzero** [comment]
Working on aliases and not on indice is what is bugging me:)

Thanks for having a look at the issue.

**Comment by matejzero** [comment]
Weird. I tried copying the code I posted in this issue again, but created a new role/user/mapping as testuser2 and remove all `dls` configuration from `sg_roles`  but I still get filtered results in `test-infra` indice.

But it looks like I get filtered indices even if I login as another user, even though this user has full unfiltered access to all indices.

I checked alias configuration, if I'm doing any alias filtering, but it doesn't seem so:
```
{
  "logs-dhcpd-2018.07-v1": {
    "aliases": {
      "test-infra": {

      }
    }
  }
}
```

If I retrieve configuration with `-r` switch, the configuration is the same as the one on the disk (i.e. no DLS filtering enabled).

It's bizzare. If I'll have time tomorrow, I will try this scenario on a fresh install to see if I can reproduce.

I can also enable debug logging and post the results in that might help.

**Comment by matejzero** [comment]
Hey there,

I'm sorry for stalling the issue. We were doing migration to ES6 and had some problems, so I was busy with that. I will check this bug out until the end of the week.

**Comment by matejzero** [comment]
Sorry for late reply, we had some problems with ES6 upgrade.

I tried this again and it's now working on ES 6.3.2 and latest SearchGuard. I don't have time to check this on ES5 anymore.

I did run on another problem, but I'll open a ticket for that.
