### ISSUE TITLE
An illegal reflective access operation has occurred - when using sgadmin.sh

### ISSUE THREAD

**Issue by camAtGitHub** [floragunncom/search-guard#525]
Elasticsearch Version: 6.3.0 (Elastic Docker container 6.3.0)
Search Guard Version: 6.3.0-22.3

I recently upgraded from ES 6.2.3 and had to apply an updated SG RBAC and I ran:
`./sgadmin.sh -h elkdev1 -cd ../sgconfig/ -icl -nhnv -cacert ../../../config/ssl/rootCA.pem -cert /tmp/elasticsearch/searchguard-admin-chain.pem -key /tmp/elasticsearch/searchguard-admin.key`

Which resulted in the WARNING below:

    WARNING: An illegal reflective access operation has occurred  
    WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/usr/share/elasticsearch/plugins/search-guard-6/netty-common-4.1.16.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)  
    WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil  
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations  
    WARNING: All illegal access operations will be denied in a future release

The RBAC still applied I just thought I'd bring the error to your attention.

**Comment by floragunncom** [comment]
Thanks, this is already known. The reason is that you are running Elasticsearch with Java 10, which is not officially supported. Java 9 and Java 10 are non LTS releases. Java 9 already reached EOL, and Java 10 will in September I think. So our next target version will be Java 11.

**Comment by ferdiga** [comment]
just  a hint "Syntax für Suche" - sorry this site is in german
https://decatec.de/home-server/volltextsuche-in-nextcloud-mit-ocr/
I think the syntax should be available in n info or help field.
especially adding a "+" in front of (the/all) search string(s) is not intuitive and different from google search etc.
