### ISSUE TITLE
Using Elasticsearch Java Clients with Search Guard

### ISSUE THREAD

**Issue by jackiekhuu-work** [floragunncom/search-guard#53]
Hi,

I want to use Elasticsearch Java native clients to get data from Elasticsearch.
Is there any way to use Elasticsearch java clients with Search Guard?
Is there any library like shield: https://www.elastic.co/guide/en/shield/current/_using_elasticsearch_java_clients_with_shield.html#_using_elasticsearch_java_clients_with_shield ?

**Comment by maximus2situation** [comment]
Hey @jackiekhuu-work ,
Did you find a way to do it? If it's the case please can you give me sample codes?

**Comment by paul58914080** [comment]
+1

**Comment by jackiekhuu-work** [comment]
@maximus2situation I can't. However, I tried this https://www.elastic.co/blog/playing-http-tricks-nginx, and It's working well.

**Comment by floragunncom** [comment]
closing #70 in favor of these

**Comment by floragunncom** [comment]
With elasticsearch 2 and Search Guard 2 it will work like that:
<pre>
Settings settings = Settings.settingsBuilder()
        .put("path.home", ".")
        .put("cluster.name", "myclustername")
        .put("searchguard.ssl.transport.enabled", true)
        .put("searchguard.ssl.transport.keystore_filepath", "spock-keystore.jks.jks"))
        .put("searchguard.ssl.transport.truststore_filepath", "truststore.jks")
        .put("searchguard.ssl.transport.enforce_hostname_verification", false)              
        .build();

try (TransportClient tc = TransportClient.builder().settings(settings).addPlugin(SearchGuardSSLPlugin.class).build()) {
            
            tc.addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress(nodeHost, nodePort)));
          //do something with tc
         tc.admin().cluster().nodesInfo(new NodesInfoRequest()).actionGet();
         //with impersonation (could also be specified globally) 
         tc.admin().cluster().nodesInfo(new NodesInfoRequest().putHeader("sg.impersonate.as", "worf")).actionGet();
}
</pre>

To specify global impersonation one can do that:

<pre>
.put("request.headers.sg.impersonate.as", "worf")   
</pre>

**Comment by sbmaggarwal** [comment]
Hello @floragunncom 

Is the `truststore.jks` and other `JKS` path is as per in the application itself or is the path relative to `config` folder only, just like what is done in `elasticsearch.yml` as suggested in [configuration steps](http://floragunncom.github.io/search-guard-docs/tls_configuration.html) ?
