### ISSUE TITLE
Add option to disable REST wrapper

### ISSUE THREAD

**Issue by jodawill** [floragunncom/search-guard#531]
We have a custom plugin that implements a REST wrapper, and we're about to upgrade from ES2 to ES6. We need search-guard for SSL, but we can't run it alongside our plugin in ES6 because both implement a REST wrapper. Could you add an option to disable the REST wrapper?

Thanks,

Josh

**Comment by floragunncom** [comment]
This is not something we will implement I'm afraid since it's really an edge case. If you want to disable the REST wrapper you will need to fork Search Guard.

**Comment by jwbennet** [comment]
I thought I might elaborate a bit on our use case.  We originally used the search-guard-ssl plugin to let us setup SSL for out cluster and we have our own plugin which implements a REST wrapper for handling authentication.  We're in the process of upgrading to Elasticsearch 6.3.x and found the following discussion:

https://groups.google.com/forum/#!searchin/search-guard/6.3.0$20plugin%7Csort:date/search-guard/G04Czw8Fhhc/2FI92G50CAAJ

In that it sounded like the `search-guard-ssl` plugin would eventually be going away so we thought we'd try using the free tier of the search guard plugin for providing SSL and continue using our own plugin for managing authentication.  This would be much easier for us if the search guard plugin allowed the REST wrapper to be disabled which would also make it work like XPack does.  Any thoughts on that?
