### ISSUE TITLE
Constant 401 After Installing Elasticsearch Plugin - Using Demo

### ISSUE THREAD

**Issue by tvollscw** [floragunncom/search-guard#533]
I've been trying to get a Search-Guard Demo Install up, following [the quick start guide](https://docs.search-guard.com/latest/demo-installer).

Currently running my entire Elastic Stack at v6.3.2
After installing the plugin for Elasticsearch, I am able to visit the website at https://localhost:9200/_searchguard/authinfo and log in to see the valid JSON string.
The issue happens whenever I try to use Kibana. I have not installed the Kibana Plugin yet (although I tried on another snapshot and it didn't work either), but I am seeing a constant 401 error come up in my syslog for kibana when trying to run it. When I try to visit the website through Kibana, it just constantly loads while the logs rack up the same 401 message. 

Example of my syslog:
`Aug  2 14:50:03 ELKD01 kibana[5797]: {"type":"response","@timestamp":"2018-08-02T19:50:03Z","tags":[],"pid":5797,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"connection":"upgrade","host":"logsd.securecomwireless.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://logsd.securecomwireless.com/","upgrade-insecure-requests":"1"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://logsd.securecomwireless.com/"},"res":{"statusCode":401,"responseTime":162,"contentLength":9},"message":"GET /app/kibana 401 162ms - 9.0B"}
Aug  2 14:50:03 ELKD01 kibana[5797]: {"type":"response","@timestamp":"2018-08-02T19:50:03Z","tags":[],"pid":5797,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"connection":"upgrade","host":"logsd.securecomwireless.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://logsd.securecomwireless.com/","upgrade-insecure-requests":"1"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://logsd.securecomwireless.com/"},"res":{"statusCode":401,"responseTime":9,"contentLength":9},"message":"GET /app/kibana 401 9ms - 9.0B"}
Aug  2 14:50:03 ELKD01 kibana[5797]: {"type":"response","@timestamp":"2018-08-02T19:50:03Z","tags":[],"pid":5797,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"connection":"upgrade","host":"logsd.securecomwireless.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://logsd.securecomwireless.com/","upgrade-insecure-requests":"1"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://logsd.securecomwireless.com/"},"res":{"statusCode":401,"responseTime":45,"contentLength":9},"message":"GET /app/kibana 401 45ms - 9.0B"}
Aug  2 14:50:03 ELKD01 kibana[5797]: {"type":"response","@timestamp":"2018-08-02T19:50:03Z","tags":[],"pid":5797,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"connection":"upgrade","host":"logsd.securecomwireless.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://logsd.securecomwireless.com/","upgrade-insecure-requests":"1"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://logsd.securecomwireless.com/"},"res":{"statusCode":401,"responseTime":9,"contentLength":9},"message":"GET /app/kibana 401 9ms - 9.0B"}
Aug  2 14:50:03 ELKD01 kibana[5797]: {"type":"response","@timestamp":"2018-08-02T19:50:03Z","tags":[],"pid":5797,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"connection":"upgrade","host":"logsd.securecomwireless.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://logsd.securecomwireless.com/","upgrade-insecure-requests":"1"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://logsd.securecomwireless.com/"},"res":{"statusCode":401,"responseTime":16,"contentLength":9},"message":"GET /app/kibana 401 16ms - 9.0B"}
Aug  2 14:50:03 ELKD01 kibana[5797]: {"type":"response","@timestamp":"2018-08-02T19:50:03Z","tags":[],"pid":5797,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"connection":"upgrade","host":"logsd.securecomwireless.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://logsd.securecomwireless.com/","upgrade-insecure-requests":"1"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://logsd.securecomwireless.com/"},"res":{"statusCode":401,"responseTime":7,"contentLength":9},"message":"GET /app/kibana 401 7ms - 9.0B"}
Aug  2 14:50:04 ELKD01 kibana[5797]: {"type":"response","@timestamp":"2018-08-02T19:50:04Z","tags":[],"pid":5797,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"connection":"upgrade","host":"logsd.securecomwireless.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://logsd.securecomwireless.com/","upgrade-insecure-requests":"1"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://logsd.securecomwireless.com/"},"res":{"statusCode":401,"responseTime":10,"contentLength":9},"message":"GET /app/kibana 401 10ms - 9.0B"}`

My Kibana.yml matches the contents of what is recommended within the Installation guide.
I have run both of the sgadmin_demo.sh & install_demo_configuration.sh scripts within the tools folder.

**Comment by floragunncom** [comment]
You write: "I have not installed the Kibana Plugin yet" and "My Kibana.yml matches the contents of what is recommended". I don't understand - did you install the plugin and follow the configuration documented here?

https://docs.search-guard.com/latest/kibana-plugin-installation

Also, please post your kibana.yml and your sg_config.yml.

**Comment by floragunncom** [comment]
@tvollscw friendly ping

**Comment by tvollscw** [comment]
Hey @floragunncom ,

I think the issue has been resolved.
The search guard files in /usr/share/kibana/optimize/ were owned by root.  Just Chown'd the owner to kibana and it seems to be working now.
