### ISSUE TITLE
official release/tag for 5.6.10-19.2

### ISSUE THREAD

**Issue by richm** [floragunncom/search-guard#536]
5.6.10-19.2 has been released to maven.org: http://search.maven.org/#artifactdetails%7Ccom.floragunn%7Csearch-guard-5%7C5.6.10-19.2%7Cjar

But there is no official release at https://github.com/floragunncom/search-guard/releases, nor is there a git tag for 5.6.10-19.2

When will there be an official release of 5.6.10-19.2?

**Comment by richm** [comment]
@jcantrill

**Comment by floragunncom** [comment]
@richm Sorry for the inconvenience, the tag for v5.6.10-19.2 has been pushed: https://github.com/floragunncom/search-guard/releases/tag/v5.6.10-19.2

**Comment by richm** [comment]
Thanks!
