### ISSUE TITLE
AccessDenied on property files with deploying searchguard stack with docker 

### ISSUE THREAD

**Issue by TehreemNisa** [floragunncom/search-guard#537]
Hi,
I am trying to deploy searchguard stack on Selinux hardened image. For all property files mapped from host machine to docker I get access denied error for dockers.

I did set Selinux to permissive mode and did setenforce 0.

Kindly can someone help me resolved this 

Below is the stack trace of compose script : 

`docker-compose up
Starting docker-elk_elasticsearch_1 ... done
Starting docker-elk_kibana_1        ... done
Starting docker-elk_logstash_1      ... done
Attaching to docker-elk_elasticsearch_1, docker-elk_kibana_1, docker-elk_logstash_1
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
kibana_1         | FATAL CLI ERROR Error: EACCES: permission denied, open '/usr/share/kibana/config/kibana.yml'
kibana_1         |     at Object.fs.openSync (fs.js:646:18)
kibana_1         |     at fs.readFileSync (fs.js:551:33)
kibana_1         |     at files.map.path (/usr/share/kibana/src/cli/serve/read_yaml_config.js:52:78)
kibana_1         |     at Array.map (<anonymous>)
kibana_1         |     at readYamlConfig (/usr/share/kibana/src/cli/serve/read_yaml_config.js:52:23)
kibana_1         |     at readServerSettings (/usr/share/kibana/src/cli/serve/serve.js:150:57)
kibana_1         |     at getCurrentSettings (/usr/share/kibana/src/cli/serve/serve.js:32:38)
kibana_1         |     at Command.<anonymous> (/usr/share/kibana/src/cli/serve/serve.js:33:22)
kibana_1         |     at Command.<anonymous> (/usr/share/kibana/src/cli/command.js:97:20)
kibana_1         |     at Command.listener (/usr/share/kibana/node_modules/commander/index.js:301:8)
elasticsearch_1  | Exception in thread "main" 2018-08-07 10:42:45,356 main ERROR No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
elasticsearch_1  | SettingsException[Failed to load settings from /usr/share/elasticsearch/config/elasticsearch.yml]; nested: AccessDeniedException[/usr/share/elasticsearch/config/elasticsearch.yml];
elasticsearch_1  |      at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:102)
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:95)
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86)
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.yml
elasticsearch_1  |      at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
elasticsearch_1  |      at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
elasticsearch_1  |      at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
elasticsearch_1  |      at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
elasticsearch_1  |      at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
elasticsearch_1  |      at java.base/java.nio.file.Files.newByteChannel(Files.java:415)
elasticsearch_1  |      at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
elasticsearch_1  |      at java.base/java.nio.file.Files.newInputStream(Files.java:154)
elasticsearch_1  |      at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1165)
elasticsearch_1  |      at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:100)
elasticsearch_1  |      ... 6 more
docker-elk_kibana_1 exited with code 1
docker-elk_elasticsearch_1 exited with code 1
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2018-08-07T10:43:08,630][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
logstash_1       | [2018-08-07T10:43:09,407][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.3.0"}
logstash_1       | [2018-08-07T10:43:09,495][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/usr/share/logstash/pipeline/*"}
logstash_1       | [2018-08-07T10:43:09,507][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
logstash_1       | [2018-08-07T10:43:09,904][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
docker-elk_logstash_1 exited with code 1
`

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
