### ISSUE TITLE
Minor issues with authentication-authorization documentation

### ISSUE THREAD

**Issue by austin987** [floragunncom/search-guard#538]
https://docs.search-guard.com/latest/authentication-authorization

I would've sent a PR, but afaict the docs aren't on github (right?)

Anywho, two things:
A) 'authorization' and 'authorisation' are used interchangably. The 's' version is used only 3 times, and the page name has 'z' version, so probably 'z' should be used throughout.
B) In the 'Authentication' section, some of the bullets are not indented. Specifically the descriptions for 'basic' and 'kerberos' are not indented. I was confused at how to specify HTTP authentication until I clicked on the HTTP page and saw the example. Once I realized that jwt/proxy/clientcert were indented, I realized it was a formatting confusion.

**Comment by floragunncom** [comment]
We'd love to get a PR for the docs :) They can be found here: 

[https://github.com/floragunncom/search-guard-docs](https://github.com/floragunncom/search-guard-docs)

You can find the main documentation in the __docs_ folder, they're in Markdown.

**Comment by austin987** [comment]
Lovely, thanks @floragunncom!

**Comment by floragunncom** [comment]
Merged PR, thanks for contributing
