### ISSUE TITLE
Error with Certificate - Search-Guard 6 Demo Issue

### ISSUE THREAD

**Issue by tvollscw** [floragunncom/search-guard#543]
I've recently installed an instance of Search-Guard 6 and have gotten it running on Elasticsearch 6.3.2.
Using JVM version 8 on Ubuntu 16.04. Only using one node.
My issue is that I'm not receiving any events from logstash. I know this to be because I haven't gotten Logstash authenticated yet with SearchGuard, so it's not able to properly connect to Elasticsearch in order to send over its parsed logs.

Here is the error i'm seeing in my `/var/log/syslog`:
```
Aug 15 12:57:10 ELKD01 logstash[4638]: [2018-08-15T12:57:10,324][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::ClientProtocolException] localhost:9200 failed to respond"}
Aug 15 12:57:11 ELKD01 logstash[4638]: [2018-08-15T12:57:11,365][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[https://logstash:xxxxxx@localhost:9200/], :added=>[https://logstash:xxxxxx@172.31.53.24:9200/]}}
Aug 15 12:57:11 ELKD01 logstash[4638]: [2018-08-15T12:57:11,370][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://logstash:xxxxxx@172.31.53.24:9200/, :path=>"/"}
Aug 15 12:57:11 ELKD01 logstash[4638]: [2018-08-15T12:57:11,422][WARN ][logstash.outputs.elasticsearch] Error while performing sniffing {:error_message=>"Host name '172.31.53.24' does not match the certificate subject provided by the peer (CN=node-0.example.com, OU=node, O=node, L=test, DC=de)", :class=>"Manticore::UnknownException", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:37:in `block in initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:79:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.0-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:74:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:291:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:245:in `block in healthcheck!'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:241:in `healthcheck!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:341:in `update_urls'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:157:in `sniff!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:146:in `block in start_sniffer'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:128:in `until_stopped'", "/usr/share/logstash/vendor/bundle/jrub
```

Alright, so I need to authenticate it. There was not any documentation on how to do this for the demo (or any available scripts to accomplish this from what I could find), [so I went to this web page](https://docs.search-guard.com/latest/logstash.html#using-logstash-with-search-guard), which dealt with authentication on logstash. 

Although the pages describes:

> Logstash requires you to set the trusted root CAs via the truststore or cacert parameter in the configuration. 

It proceeds to show how to set it up with a truststore, but not a cacert (which is what the demo is using). Trying to use the cacert as such, I was was continually getting the error above.

My Logstash.conf:

>  output {
>   elasticsearch {
>     user => logstash
>     password => logstash
>     ssl => true
>     ssl_certificate_verification => true
>     cacert => '/etc/logstash/root-ca.pem'
>     hosts => ["https://localhost:9200"]
>     sniffing => true
>     manage_template => false
>     index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
>     document_type => "%{[@metadata][type]}"
>    }
> }

I have tried changing hosts to `host => ["localhost:9200"]`, same error.
I have tried turning `ssl_certificate_verification` to false, and I verified the username and password, but still not getting any further. It would be nice if there was more of a follow-through with the demo, at least enough to pull in data with logstash. 

[I also saw this forum post](https://groups.google.com/d/topic/search-guard/LYIBUkGQBwM/discussion). It seems very straightforward of an issue, but no one specifically posted their config or how they got it to work, so I'm coming here, hoping for a quick response.. I'm trying to get this demo to work on an Elastic Stack install for the company that I work for. We will be interested in a quote for enterprise, but only if we can get the demo working.

**Comment by floragunncom** [comment]
This seems to be cross-posted and answered here: https://groups.google.com/forum/#!topic/search-guard/LYIBUkGQBwM/discussion

Closing as it does not seem to be an SG related bug. If you think this is an SG bug, please raise another issue.
