### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by rajeshwer** [floragunncom/search-guard#546]
bash-4.2# ./bin/elasticsearch-plugin install -b com.floragunn:search-guard-6:6.0.0-17.beta1
-> Downloading com.floragunn:search-guard-6:6.0.0-17.beta1 from maven central
[=================================================] 100%?? 
Warning: sha512 not found, falling back to sha1. This behavior is deprecated and will be removed in a future release. Please update the plugin to use a sha512 checksum.
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

Tried with different elastic versions 6.3.0 6.3.1 6.3.2 I have same issues

**Comment by floragunncom** [comment]
You need to install the SG version that matches your ES version exactly. 6.0.0-17.beta1 is a beta, not a regular release. Please refer to the docs for latest SG versions:

https://docs.search-guard.com/latest/search-guard-versions
