### ISSUE TITLE
username_atttibute supported for HTTP but not for Transport

### ISSUE THREAD

**Issue by jala-dx** [floragunncom/search-guard#547]
Hi -

HTTP honours username_attribute parameter and picks CN as the username attribute (see output below). Whereas in Transport, it always expect DN. Is this by design? Why is this inconsistent while HTTP accepts CN and DN, whereas accepts only DN?

Thanks.
Jalaja

When asking questions, please provide the following information:

* Search Guard and Elasticsearch version
SG - 6-6.1.1-20.1
ES - 6-1-1

* Search Guard configuration files

bash-4.2# cat sg_config.yml
<pre>
searchguard:
  dynamic:
    authc:
     clientcert_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn #optional, if omitted DN becomes username
          challenge: false
        authentication_backend:
          type: noop
</pre>

**Comment by floragunncom** [comment]
Good catch, i put it as a feature request to our backlog

**Comment by jala-dx** [comment]
Cool Thanks 👍

**Comment by jochenkressin** [comment]
Will label this as a bug since REST and transport should behave the same. Issue has been created, should be fixed in the next SG version.

**Comment by jochenkressin** [comment]
Scheduled for SG 24.

**Comment by floragunncom** [comment]
Will be released with SG 24 expected next week.
