### ISSUE TITLE
`SgRole#getAllResolvedPermittedIndices` does not support regular expression

### ISSUE THREAD

**Issue by occho** [floragunncom/search-guard#557]
`SgRole#getAllResolvedPermittedIndices` does not support regular expression.

At the line below, `permitted` can be a regular expression.
https://github.com/floragunncom/search-guard/blob/es-6.3.2_compliance/src/main/java/com/floragunn/searchguard/sgconf/ConfigModel.java#L378

However, `org.elasticsearch.cluster.metadata.IndexNameExpressionResolver#concreteIndexNames` does not support a regular expression.

So, `SgRole#getAllResolvedPermittedIndices` does not work as expected.

I observed this issue for the following code path: https://github.com/floragunncom/search-guard/blob/es-6.3.2_compliance/src/main/java/com/floragunn/searchguard/configuration/PrivilegesEvaluator.java#L471

# Versions

Elasticserch version: 6.3.2
SeachGuard ES plugin version: 6-6.3.2-compliance-2

**Comment by occho** [comment]
Workaround:
```
                   } else {
                       //System.out.println("wanted: all!");
                       //we want all indices so just return whats permitted
                       String[] allIndices = resolver.concreteIndexNames(cs.state(), IndicesOptions.lenientExpandOpen(), "*");
                       Set<String> wanted = new HashSet<>(Arrays.asList(allIndices));
                       WildcardMatcher.wildcardRetainInSet(wanted, permitted);
                       res.addAll(wanted);
                   }
```

**Comment by floragunncom** [comment]
Can you provide a config example where this becomes a "real" problem?

**Comment by occho** [comment]
## sg_roles.yml
```
# Read all, but no write permissions
sg_readall:  readonly: true
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:    
    '/\S*/':
      '*':
        - READ
```

`sg_readall.cluster.indices` is changed from `*` to regex pattern `/\S*/`.

## Test commands

Tested with `sg_roles.yml` that contains the above entry.

The following works. `buckets` in the response includes permitted indices.
```
curl https://localhost:9200/*/_search?pretty --insecure --user admin:admin -d '{"size":0,"aggs":{"indices":{"terms":{"field":"_index","size":10}}}}' -H 'Content-Type: application/json'
```

The following does not work. `buckets` in the response is empty.

```
curl https://localhost:9200/*/_search?pretty --insecure --user readall:readall -d '{"size":0,"aggs":{"indices":{"terms":{"field":"_index","size":10}}}}' -H 'Content-Type: application/json'
```

## Works for reproducing the issue

[search-guard-issues-557.tar.gz](https://github.com/floragunncom/search-guard/files/2407496/search-guard-issues-557.tar.gz)

**Comment by floragunncom** [comment]
confirmed as a bug - thx for reporting

**Comment by floragunncom** [comment]
Fixed in latest SG release.
