### ISSUE TITLE
sgadmin v5.0 and v5.1 do not support pem certificates

### ISSUE THREAD

**Issue by dcwebermn** [floragunncom/search-guard#559]
Used the TLS offline tool to generate certificates but when following the document and trying to run sgadmin using certificates we get an exception:  Unrecognized option: -cacert followed by a list of supported options - none of which include -cacert, - cert, or -key.....on keystore and truststore options.  So the documentation says pem certificates are supported by the tool doesn't support the documented options.

**Comment by floragunncom** [comment]
Both are EOL (End of Life) - https://docs.search-guard.com/latest/eol-policy#eol-dates
Pem support was added in 5.3.3-13
