### ISSUE TITLE
SAML Issue with JwsCompactConsumer

### ISSUE THREAD

**Issue by brokenthumbs** [floragunncom/search-guard#560]
Referencing an issue from https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKkvdzPnBfGZVjCnnXFVxdSNv
> We investigated this and it could be a bug in the SAML module in case the IdP URL contains a query string.

---

# Issue

### Background

I've enabled a Search Guard license and am seeing the following in the Elasticsearch logs. 

```
org.apache.cxf.rs.security.jose.jws.JwsCompactConsumer <init>
WARNING: Compact JWS does not have 3 parts
```

What could be causing that error? I'm trying to enable SAML logins to Elasticsearch. I'm receiving an error from Google:
`400. That’s an error. Invalid Request, invalid idpId in request URL, check if SSO URL is configured properly on SP side. That’s all we know.`

### Question
Is there anything that looks off to you that could potentially be a problem with my configuration?

The leading theory is that there is an issue when the IdP URL contains a query string, such as in the case of Google, where the IdP URL is https://accounts.google.com/o/saml2/idp?idpid=#####

# Extra Info

### IdP Browser

When visiting kibana.foo.io, I am redirected to https://accounts.google.com/o/saml2/idp?idpid=#####?SAMLRequest=nZJNbxoxEIb%2Fysr3%2FYKFTS...
There are two question marks in that URL, and replacing the second question mark with an ampersand yields
https://accounts.google.com/o/saml2/idp?idpid=#####&SAMLRequest=nZJNbxoxEIb%2Fysr3%2FYKFTS...

The first URL with two question marks creates a 400. The second URL with a question mark followed by an ampersand yields a correct logout.
Do you have any more information on if this could be fixed from the Search Guard side?

I noticed a similar post in Artifactory about SAML SSO with Google.
https://www.jfrog.com/jira/si/jira.issueviews:issue-html/RTFACT-10242/RTFACT-10242.html

### IdP CURL

I'm also noticing in the headers for a response to Elasticsearch. I'm receiving a 401 response, even while passing basic auth credentials. Is this related to my error with Google IdP?

```
curl --user admin:password "https://elasticsearch.foo.io:443" -v
* Rebuilt URL to: https://elasticsearch.foo.io:443/
*   Trying 123.456.789.0...
* TCP_NODELAY set
* Connected to elasticsearch.foo.io (123.456.789.0) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.foo.io
*  start date: Mar  7 00:00:00 2018 GMT
*  expire date: Apr  7 12:00:00 2019 GMT
*  subjectAltName: host "elasticsearch.foo.io" matched cert's "*.foo.io"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Server auth using Basic with user 'admin'
* Using Stream ID: 1 (easy handle 0x7fda03000800)
> GET / HTTP/2
> Host: elasticsearch.foo.io
> Authorization: Basic #####=
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 401
< date: Thu, 27 Sep 2018 21:26:17 GMT
< content-type: text/plain; charset=UTF-8
< content-length: 0
< www-authenticate: X-SG-IdP realm="Search Guard" location="https://accounts.google.com/o/saml2/idp?idpid=#####?SAMLRequest=nZJLb%2BMgFIX%2FisXezzp...." requestId="ONELOGIN_######-####-####-####-######"
<
* Connection #0 to host elasticsearch.foo.io left intact
```

### acs

acs returns as a 302 and yields the following data from SAMLResponse (translated from base64 encoded XML using https://www.base64decode.org/):

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://kibana.foo.io:443/searchguard/saml/acs" ID="_######" IssueInstant="2018-09-27T19:49:51.959Z" Version="2.0">
  <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://accounts.google.com/o/saml2?idpid=#####</saml2:Issuer>
  <saml2p:Status>
    <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
  </saml2p:Status>
  <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_#####" IssueInstant="2018-09-27T19:49:51.959Z" Version="2.0">
    <saml2:Issuer>https://accounts.google.com/o/saml2?idpid=#####</saml2:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
        <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
        <ds:Reference URI="#_#####">
          <ds:Transforms>
            <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
          </ds:Transforms>
          <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
          <ds:DigestValue>#####</ds:DigestValue>
        </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue>#####</ds:SignatureValue>
      <ds:KeyInfo>
        <ds:X509Data>
          <ds:X509SubjectName>ST=California,C=US,OU=Google For Work,CN=Google,L=Mountain View,O=Google Inc.</ds:X509SubjectName>
          <ds:X509Certificate>######</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </ds:Signature>
    <saml2:Subject>
      <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">####@foo.io</saml2:NameID>
      <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml2:SubjectConfirmationData NotOnOrAfter="2018-09-27T19:54:51.959Z" Recipient="https://kibana.foo.io:443/searchguard/saml/acs"/>
      </saml2:SubjectConfirmation>
    </saml2:Subject>
    <saml2:Conditions NotBefore="2018-09-27T19:44:51.959Z" NotOnOrAfter="2018-09-27T19:54:51.959Z">
      <saml2:AudienceRestriction>
        <saml2:Audience>https://kibana.foo.io:443/searchguard/saml/acs</saml2:Audience>
      </saml2:AudienceRestriction>
    </saml2:Conditions>
    <saml2:AttributeStatement>
      <saml2:Attribute Name="role">
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">readall</saml2:AttributeValue>
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">kibanauser</saml2:AttributeValue>
      </saml2:Attribute>
    </saml2:AttributeStatement>
    <saml2:AuthnStatement AuthnInstant="2018-09-27T19:11:25.000Z" SessionIndex="_#####">
      <saml2:AuthnContext>
        <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml2:AuthnContextClassRef>
      </saml2:AuthnContext>
    </saml2:AuthnStatement>
  </saml2:Assertion>
</saml2p:Response>
```

### Miscellaneous

* Search Guard and Elasticsearch version: 6.4.1
```
[2018-09-27T18:57:11,174][INFO ][c.f.s.c.IndexBaseConfigurationRepository] Search Guard License Type: FULL, valid
```

* Installed and used enterprise modules, if any: 
```
[2018-09-27T18:57:00,041][INFO ][c.f.s.SearchGuardPlugin ] 4 Search Guard modules loaded so far: [Module [type=REST_MANAGEMENT_API, implementing class=com.floragunn.searchguard.dlic.rest.api.SearchGuardRestApiActions], Module [type=AUDITLOG, implementing class=com.floragunn.searchguard.auditlog.impl.AuditLogImpl], Module [type=MULTITENANCY, implementing class=com.floragunn.searchguard.configuration.PrivilegesInterceptorImpl], Module [type=DLSFLS, implementing class=com.floragunn.searchguard.configuration.SearchGuardFlsDlsIndexSearcherWrapper]]
```

* JVM version and operating system version
```
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

$ cat /etc/*elease
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)
```

* Search Guard configuration files

elasticsearch.yml
```
searchguard.enterprise_modules_enabled: true
searchguard.compliance.history.internal_config_enabled: true
searchguard.compliance.history.external_config_enabled: true
searchguard.compliance.history.read.metadata_only: true
```

sg_config.yml
```
    authc:
      basic_internal_auth_domain:
        enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      saml_auth_domain_google:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: 'saml'
          challenge: true
          config:
            idp:
              metadata_file: GoogleIDPMetadata-foo.io.xml
              entity_id: https://accounts.google.com/o/saml2?idpid=###########
            sp:
              entity_id: __SP_ENTITY_ID__
            kibana_url: __KIBANA_URL__
            roles_key: role
            exchange_key: '__SAML_EXCHANGE_KEY__'
        authentication_backend:
          type: noop
```

**Comment by brokenthumbs** [comment]
Would it be a check here if the IdP URL contains a query string, and using `&` instead of `?` if the IdP URL already contains a query string?

https://github.com/floragunncom/search-guard-enterprise-modules/blob/e48d4f978171fa20cb3948b4ee8dfadb7a0d70f4/src/main/java/com/floragunn/dlic/auth/http/saml/HTTPSamlAuthenticator.java#L361

**Comment by floragunncom** [comment]
@nibix Can you please have a look here?

**Comment by nibix** [comment]
@brokenthumbs We have fixed the SAML support to properly handle IdPs using query strings in their endpoints. In order to make sure that this fixes the problems with your IdP, we can provide you a snapshot version. Would you be interested in receiving one for testing? If so, please tell us the version of ES in order to build a snapshot.

I cannot make much sense about the warning from JwsCompactConsumer, though. If the problem persists, we might have to look at the HTTP headers to get an idea what's about this JWT.

**Comment by brokenthumbs** [comment]
Hi @nibix,

Thanks for the update and the fix. Currently using ES version 6.4.1.

A snapshot would be great! I'll give it a try, and let you know if the problem persists with JwsCompactConsumer.

**Comment by brokenthumbs** [comment]
@nibix @floragunncom Has this fix been released yet?

**Comment by nibix** [comment]
@brokenthumbs A snapshot with the bugfix for ES 6.4.1 is now available at 

https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-6/6.4.1-23.2-SNAPSHOT/search-guard-6-6.4.1-23.2-20181014.110331-1.zip

Sorry for the long wait!

Please let me know if this fixes the problem for you.

**Comment by brokenthumbs** [comment]
Hi @nibix,

Thanks for the snapshot link! I installed the snapshot and tested out the SSO feature with Google SAML. 

1. Visiting Kibana from kibana.foo.io works fine! As long as my Google user has the `role` attribute of `kibanauser` and `readall`, I can visit kibana.foo.io and it automatically logs me in with my Google SAML App.

2. I'm having trouble visiting Kibana from the Google Apps panel. When visiting Kibana using https://accounts.google.com/o/saml2/initsso?idpid=######&spid=######&forceauthn=false, I receive a 200, which loads https://ssl.gstatic.com/accounts/o/#######-approval_page_css_ltr.css (200), and then https://kibana.foo.io/searchguard/saml/acs (302). The final page is https://kibana.foo.io/customerror?type=samlAuthError (200). 

I get the following SAMLResponse from https://kibana.staging.galileo.io/searchguard/saml/acs
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://kibana.foo.io:443/searchguard/saml/acs" ID="_abc123" IssueInstant="2018-10-16T20:02:10.657Z" Version="2.0">
  <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://accounts.google.com/o/saml2?idpid=#####</saml2:Issuer>
  <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:SignedInfo>
      <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
      <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
      <ds:Reference URI="#_abc123">
        <ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
        <ds:DigestValue>#####=</ds:DigestValue>
      </ds:Reference>
    </ds:SignedInfo>
    <ds:SignatureValue>######==</ds:SignatureValue>
    <ds:KeyInfo>
      <ds:X509Data>
        <ds:X509SubjectName>ST=California,C=US,OU=Google For Work,CN=Google,L=Mountain View,O=Google Inc.</ds:X509SubjectName>
        <ds:X509Certificate>######</ds:X509Certificate>
      </ds:X509Data>
    </ds:KeyInfo>
  </ds:Signature>
  <saml2p:Status>
    <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
   </saml2p:Status>
   <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_def456" IssueInstant="2018-10-16T20:02:10.657Z" Version="2.0">
    <saml2:Issuer>https://accounts.google.com/o/saml2?idpid=#####</saml2:Issuer>
    <saml2:Subject>
      <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">dchan@foo.io</saml2:NameID>
      <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml2:SubjectConfirmationData NotOnOrAfter="2018-10-16T20:07:10.657Z" Recipient="https://kibana.foo.io:443/searchguard/saml/acs"/>
      </saml2:SubjectConfirmation>
    </saml2:Subject>
    <saml2:Conditions NotBefore="2018-10-16T19:57:10.657Z" NotOnOrAfter="2018-10-16T20:07:10.657Z">
      <saml2:AudienceRestriction>
        <saml2:Audience>https://kibana.foo.io:443/searchguard/saml/acs</saml2:Audience>
      </saml2:AudienceRestriction>
    </saml2:Conditions>
    <saml2:AttributeStatement>
      <saml2:Attribute Name="role">
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">readall</saml2:AttributeValue>
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">kibanauser</saml2:AttributeValue>
      </saml2:Attribute>
    </saml2:AttributeStatement>
    <saml2:AuthnStatement AuthnInstant="2018-10-16T20:01:10.000Z" SessionIndex="_def456">
      <saml2:AuthnContext>
        <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml2:AuthnContextClassRef>
      </saml2:AuthnContext>
    </saml2:AuthnStatement>
  </saml2:Assertion>
</saml2p:Response>
```

Any ideas around what could be causing my error from issue 2? I can use Google SAML to SSO successfully into Kibana when browsing directly to kibana.foo.io, but I fail to use Google SAML to SSO when using the Google App link, https://accounts.google.com/o/saml2/initsso?idpid=#####&spid=#####&forceauthn=false

For reference, here is my Service Provider details from Google:
![image](https://user-images.githubusercontent.com/1063045/47045297-7b453980-d160-11e8-820c-bd11f810c570.png)

Hoping you might have an idea what could be going on 🤞

**Comment by brokenthumbs** [comment]
Some notes around the failure case:

---

I'm noticing that when logging in using kibana.foo.io, I see the following information in the SAMLResponse:
```
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://kibana.foo.io:443/searchguard/saml/acs" ID="_abc123" InResponseTo="ONELOGIN_123456-abcd-1234-efgh-12345678" IssueInstant="2018-10-16T20:59:32.089Z" Version="2.0">

...

      <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml2:SubjectConfirmationData InResponseTo="ONELOGIN_123456-abcd-1234-efgh-12345678" NotOnOrAfter="2018-10-16T21:04:32.089Z" Recipient="https://kibana.foo.io:443/searchguard/saml/acs"/>
      </saml2:SubjectConfirmation>
```

However, when using https://accounts.google.com/o/saml2/initsso?idpid=#####&spid=#####&forceauthn=false, I am missing `InResponseTo` with the `saml2p:Response` and `saml2:SubjectConfirmation`
```
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://kibanafoo.io:443/searchguard/saml/acs" ID="_abc123" IssueInstant="2018-10-16T20:58:56.088Z" Version="2.0">

...

      <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml2:SubjectConfirmationData NotOnOrAfter="2018-10-16T21:03:56.088Z" Recipient="https://kibana.foo.io:443/searchguard/saml/acs"/>
      </saml2:SubjectConfirmation>
```

Is it important to have `InResponseTo`? Not sure if this would really matter.

As far as I can see, that is the only difference in SAMLResponse data, except https://accounts.google.com/o/saml2/initsso?idpid=#####&spid=#####&forceauthn=false leads to https://kibana.foo.io/customerror?type=samlAuthError#?_g=()

Is there something else I could try to gather more information, to reveal why https://accounts.google.com/o/saml2/initsso?idpid=#####&spid=#####&forceauthn=false would not be working, but kibana.foo.io would be working?

Thanks again! 🙏

**Comment by nibix** [comment]
@brokenthumbs:

Thanks for the additional information. SAML is a quite complicated protocol (which is actually an understatement) and thus debugging can be quite tedious.

Visiting Kibana (the SP) from the Google Apps Panel (the IdP) comprises the so-called IdP initiated SSO use case - sometimes also called unsolicited response.

http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0-cd-02.html#5.1.4.IdP-Initiated%20SSO:%20%20POST%20Binding|outline
http://saml.xml.org/wiki/idp-initiated-single-sign-on-post-binding

The IdP initiated SSO can be actually recognized by the InResponseTo element missing from the SAMLResponse - just because there is no request which is responded to. In the case of SP initiated SSO, the InResponseTo must be validated (according to the SAML Standard), in order to avoid XSRF edge cases.

Until now, all SG SAML users we know actually used SP initiated SSO and not IdP initiated SSO, so there might be still problems with IdP initiated SSO.

Generally, for debugging SAML problems, the log output from the server is particularly interesting, because it will contain the most precise error messages. The output from the packages com.floragunn.dlic.auth.http.saml and com.onelogin.saml2.authn will be probably contain the most interesting pieces.

Temporarily, for testing, you might try to extend the SAML part of your Search Guard configuration by a new validator block like this: 

`saml_auth_domain_google:
        [...]
        http_authenticator:
          type: 'saml'
          challenge: true
          config:
            idp:
              metadata_file: GoogleIDPMetadata-foo.io.xml
              entity_id: https://accounts.google.com/o/saml2?idpid=###########
            sp:
              entity_id: __SP_ENTITY_ID__
            validator:
               strict: false
            [...]`

strict: false should be only used for testing purposes, as it disables quite a few of additional checks of the SAMLResponse, which are normally mandated by the SAML standard.

**Comment by brokenthumbs** [comment]
@nibix 

Thanks for the follow up, and explanation about IdP initiated SSO and SP initiated SSO. Complicated stuff!

---

Hmm...

I set validator: strict to false, and I enabled debug logs for com.floragunn.dlic.auth.http.saml and com.onelogin.saml2.authn, but am not seeing anything that looks related to my IdP initiated SSO.

I'm seeing only the following:
```
[2018-10-18T16:25:00,822][DEBUG][c.o.s.a.AuthnRequest ] AuthNRequest --> <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_abcdef-1234-1234-1234-abcdef" Version="2.0" IssueInstant="2018-10-18T16:25:00Z" ForceAuthn="true" Destination="https://accounts.google.com/o/saml2/idp?idpid=#####" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://kibana.foo.io:443/searchguard/saml/acs"><saml:Issuer>https://kibana.foo.io:443/searchguard/saml/acs</saml:Issuer><samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" AllowCreate="true" /></samlp:AuthnRequest>
```

I'm not entirely sure that the request is being logged, or making its way into the Elasticsearch logs, even with the log levels being set to debug.

---

The SP initiated SSO works for Google SAML at this point, though. Would it be okay to release the fix for Google SAML? This is with the understanding that only the SP initiated SSO works, and that the IdP initiated SSO from Google is not working as intended.

---

Thanks again for the responses. I appreciate the explanations on how the SAML setup works.

**Comment by nibix** [comment]
@brokenthumbs 

We'll release the fix with the next SG release. It's not entirely clear yet, when the release is going to happen - probably two to three weeks.

Regarding the IdP initiated issue: The log message is the AuthNMessage from Search Guard when it gets an unauthenticated request. Thus, the request from the IdP must have arrived before. How does the HTTP request from the IdP to Kibana look like? It should be sent to the endpoint https://kibana.foo.io:443/searchguard/saml/acs ...

**Comment by brokenthumbs** [comment]
Hmm, I'm not seeing anything on the Kibana logs. Has anybody else run into this particular IdP initiated issue, with other IdPs?

**Comment by nibix** [comment]
@brokenthumbs You should be able to see the HTTP requests between the IdP and Kibana inside the developer console of your browser. We need to ensure that the IdP redirects to the correct endpoint of Kibana.

Unfortunately, I am not aware of anyone else using SG with IdP initiated SSO.

Anyway, as this issue actually refers to another problem and is already closed, we might continue work in a seperate bug.

**Comment by brokenthumbs** [comment]
@nibix @floragunncom 

Is this fix released in the newest version? https://github.com/floragunncom/search-guard/releases/tag/v6.4.3-23.1

**Comment by jochenkressin** [comment]
Not in 23.1, it will come with 23.2 which will be out next week.

**Comment by brokenthumbs** [comment]
Thanks @jochenkressin !
