### ISSUE TITLE
Show The Name of Logged In User

### ISSUE THREAD

**Issue by Alsheh** [floragunncom/search-guard#563]
Adding the name of the logged in user near the Logout button would be great.

**Comment by floragunncom** [comment]
This is already in the making, will be released with v16 of the Kibana plugin.

**Comment by jochenkressin** [comment]
Feature is implemented, tracked under ITT-1576, ready to be released with v16.

**Comment by jochenkressin** [comment]
Kibana v16 has been released yesterday which fixes this issue.
