### ISSUE TITLE
Disable auto expand replicas of searchguard index

### ISSUE THREAD

**Issue by lanerjo** [floragunncom/search-guard#565]
Issue:
1. When using a Hot/Warm Architecture
2. Multiple instances of elasticsearch on same host machine
3. cluster.routing.allocation.same_shard.host:false (so no 2 replicas are not stored on the same host)
4. Searchguard index stays yellow

A similar issue can be found here:
https://github.com/elastic/elasticsearch/issues/29933

The resolution is to disable auto expand replicas and set the number of replicas to be num_hosts-1 at the highest.

**Comment by floragunncom** [comment]
We will add this to the docs

**Comment by floragunncom** [comment]
see https://github.com/floragunncom/search-guard-docs/pull/56

**Comment by floragunncom** [comment]
merged into the docs
