### ISSUE TITLE
SG doesn't work after i restart ES 

### ISSUE THREAD

**Issue by AnisHAIL** [floragunncom/search-guard#568]
Hi All,
ES version 5.3.2
SG version 5.3.2-15
OS: CentOS7
java version "1.8.0_131"
There are 1 node in the cluster
I have exactly the same problem as #178 (SG 2.3.3.3), and I should like to know if the corrective is available for SG 5.3.2-15

 thank you for your answer

**Comment by floragunncom** [comment]
ES 5.3.x and SG 5.3.x is EOL according to https://www.elastic.co/de/support/eol and https://docs.search-guard.com/latest/eol-policy#eol-dates. Pls update to to 5.6.12 or 6.4.2 and reopen the issue if its still there with recent versions.

**Comment by AnisHAIL** [comment]
Hi SeachGuard team,
As indicate in your anwer, we performed our tests (1 node in the cluster) with ElasticSearch  6.6.0 and SearchGuard 6:6.6.0-24,unfortunately we have the same issue (when Elasticsearch restarts I have to run the sgadmin tool again)
How can I fix this? 

I have atteched Elastic, SearchGuard files conf with logs
The es_sg_conf zip contains : 
 - elasticsearch.yml
-  sg_action_groups.yml
-  sg_config.yml
-  sg_internal_users.yml
-  sg_roles.yml
-  sg_roles_mapping.yml
- elastic.log
[es_sg_conf.zip](https://github.com/floragunncom/search-guard/files/3013445/es_sg_conf.zip)



thank you for the feedback
