### ISSUE TITLE
Search Guard for ES 6.5

### ISSUE THREAD

**Issue by xermus** [floragunncom/search-guard#583]
I am running Elasticsearch 6.5 and cannot install the mentioned plugin version to it (as it said it is only compatible with ES version 6.4).

When will you release the version for 6.5?

**Comment by floragunncom** [comment]
we are already working on this ... (and constantly answering such questions slows down work :-)

**Comment by floragunncom** [comment]
https://github.com/floragunncom/search-guard/issues/349#issuecomment-305715237
