### ISSUE TITLE
Unable to create connection between elastic search and kibana after enabling Search Guard Plugin in both

### ISSUE THREAD

**Issue by riteshsoni10** [floragunncom/search-guard#585]
**Search Guard Elasticsearch PLugin**
 https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-6/6.3.0-23.2/search-guard-6-6.3.0-23.2.zip
**Search Guard Kibana Plugin**
 http://central.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/6.3.0-13/search-guard-kibana-plugin-6.3.0-13.zip

Elastic Search: 6.3.0
Kibana: 6.3.0
JVM version: 1.8.0
Number of nodes: 1

NO error logs on eleastic search

Followed steps in PDF as it is:

https://docs.search-guard.com/resources/presentations/01_SG_Documents_installation.pdf

I have followed and installed it as demo for testing. But in my kibana error logs I am getting

{"type":"error","@timestamp":"2018-11-23T10:50:43Z","tags":["fatal"],"pid":6126,"level":"fatal","error":{"message":"child \"searchguard\" fails because [\"auth\" is not allowed]","name":"ValidationError","stack":"ValidationError: child \"searchguard\" fails because [\"auth\" is not allowed]\n    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)\n    at internals.Object._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)\n    at module.exports.internals.Any.root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)\n    at Config._commit (/usr/share/kibana/src/server/config/config.js:119:35)\n    at Config.set (/usr/share/kibana/src/server/config/config.js:89:10)\n    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:62:10)\n    at extendConfigService (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:26:10)\n    at <anonymous>"},"message":"child \"searchguard\" fails because [\"auth\" is not allowed]"}

elasticsearch.yml
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 0.0.0.0
http.port: 9200
######## Start Search Guard Demo Configuration ########
# WARNING: revise all the lines below before you go into production
searchguard.ssl.transport.pemcert_filepath: esnode.pem
searchguard.ssl.transport.pemkey_filepath: esnode-key.pem
searchguard.ssl.transport.pemtrustedcas_filepath: root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: esnode.pem
searchguard.ssl.http.pemkey_filepath: esnode-key.pem
searchguard.ssl.http.pemtrustedcas_filepath: root-ca.pem
searchguard.allow_unsafe_democertificates: true
searchguard.allow_default_init_sgindex: true
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de

searchguard.audit.type: internal_elasticsearch
searchguard.enable_snapshot_restore_privilege: true
searchguard.check_snapshot_restore_write_privileges: true
searchguard.restapi.roles_enabled: ["sg_all_access"]
cluster.routing.allocation.disk.threshold_enabled: false
cluster.name: Payworld-ELK
discovery.zen.minimum_master_nodes: 1
node.max_local_storage_nodes: 3
xpack.security.enabled: false
######## End Search Guard Demo Configuration ########
searchguard.enterprise_modules_enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.watcher.enabled: false
                                                           

Kibana.yml

server.port: 5601
server.host: 0.0.0.0
logging.dest: /var/log/kibana/kibana.log
elasticsearch.ssl.certificateAuthorities: [ "/etc/elasticsearch/root-ca.pem" ]
elasticsearch.ssl.verificationMode: none
xpack.security.enabled: false
searchguard.auth.type: "basic"
elasticsearch.url: "https://localhost:9200"
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.watcher.enabled: false
searchguard.cookie.secure: false

Output of below URL in browser with same username and password in kibana.yml gives
https://13.233.38.135:9200/_searchguard/authinfo?pretty

{
  "user" : "User [name=kibanaserver, roles=[], requestedTenant=null]",
  "user_name" : "kibanaserver",
  "user_requested_tenant" : null,
  "remote_address" : "125.63.93.130:49974",
  "backend_roles" : [ ],
  "custom_attribute_names" : [ ],
  "sg_roles" : [
    "sg_kibana_server",
    "sg_own_index"
  ],
  "sg_tenants" : {
    "kibanaserver" : true
  },
  "principal" : null,
  "peer_certificates" : "0",
  "sso_logout_url" : null
}

SG guard healt status also gives it is up...But kibana is unable to start

Thank You

**Comment by riteshsoni10** [comment]
@mgustafsson1 @Sicaine @n3gster @ewolinetz

**Comment by floragunncom** [comment]
Try 
http://central.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/6.3.0-16

**Comment by riteshsoni10** [comment]
I am reinstalling Search Guard kibana plugin....Give a moment
@floragunncom

**Comment by Sicaine** [comment]
@riteshsoni10 so why do you mention me?

**Comment by riteshsoni10** [comment]
@Sicaine....I had mentioned you earlier...

**Comment by Sicaine** [comment]
@riteshsoni10 and why did you mention me earlier?

**Comment by riteshsoni10** [comment]
@floragunncom Its taking almost more than 5 hrs at Optimising and caching bundles.

/usr/share/kibana/bin/kibana-plugin install http://central.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/6.3.0-16/search-guard-kibana-plugin-6.3.0-16.zip

Attempting to transfer from http://central.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/6.3.0-16/search-guard-kibana-plugin-6.3.0-16.zip
Transferring 2057977 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...


After this point it is not going forward or displaying any error..

**Comment by Sicaine** [comment]
@riteshsoni10 apparently the only reason why you mentioned me, is to be rude.

Don't mention people in some issue on your side if not necessary. I will unwatch your issue.

**Comment by riteshsoni10** [comment]
@Sicaine I had mentioned you because you had comitted to this repository previously. So I figured out that you might have an answer for my issue.

**Comment by riteshsoni10** [comment]
@Sicaine 
That was not my intention  to be rude. I apologise for mentioning you....

**Comment by jochenkressin** [comment]
https://groups.google.com/forum/#!topic/search-guard/4uNc8sYYMTQ

**Comment by jochenkressin** [comment]
The optimize process of Kibana is known to be flaky and also suffers from memory issues. Please refer to my post on the forum.

If the process does not return, most likely it ran out of memory in the very last step of the process. You can try to kill the process and start Kibana again. 

You can also try to set the memory for the node process with:

export NODE_OPTIONS="--max-old-space-size=8192"

Here's also a useful article about it:

http://blog.caustik.com/2012/04/11/escape-the-1-4gb-v8-heap-limit-in-node-js/

Will close the issue since there's nothing we can do, unfortunately.
