### ISSUE TITLE
Username key invalid in internausers api

### ISSUE THREAD

**Issue by pankajchandiitm** [floragunncom/search-guard#587]
As per documentation internalusers api should accept username as key in the body. But currently api throws invalid configuration.

**Comment by floragunncom** [comment]
Can you provide more details like ES/SG version, the request you sent (curl example), logoutput if any?

**Comment by pankajchandiitm** [comment]
ES version - 6.4.2
SG version - 6.4.2-23.2
Postman Request -
PUT https://localhost:9200/_searchguard/api/internalusers/pankaj12
{ 
    "password":"pankaj12",
    "roles":["sg_own_index","sg_kibana_user"],
    "username" : "pankaj11@gmail.com"
  }

Response - 
{
    "status": "error",
    "reason": "Invalid configuration",
    "invalid_keys": {
        "keys": "username"
    }
}


Logs - I don't see any log output on the console when this query is made specifically.

**Comment by floragunncom** [comment]
@jochenkressin is this planned for v24?

**Comment by floragunncom** [comment]
Scheduled for v24 expected next week
