### ISSUE TITLE
Kibana prompts me for username and password twice [ELK 6.5.1]

### ISSUE THREAD

**Issue by ltfi** [floragunncom/search-guard#589]
ELK Version 6.5.1 / Search Guard Version 23.0 comp with 6.5.1

When I open a browser, and access Kibana,it prompts me for username and password twice,one for “Authorization Required”,and another for “Search Guard".why this happend?

Thx.

**Comment by floragunncom** [comment]
The Kibana plugin is not yet compatible with Kibana Spaces, you need to turn them off for the moment:

[https://docs.search-guard.com/latest/upgrading-560](https://docs.search-guard.com/latest/upgrading-560)
