### ISSUE TITLE
Apache Zeppelin Integration Problem

### ISSUE THREAD

**Issue by ltfi** [floragunncom/search-guard#591]
I can't integrate the "Apache Zeppelin" tool with ELK because of the "ssl" requirement of Search Guard [Apache Zeppelin's interpreter doesn't work with ssl]. What should I do?

**Comment by jochenkressin** [comment]
TLS is only mandatory on the transport layer. On the REST layer, TLS is optional. So you can switch it off globally (not recommended), or just disable it on one node and point Zeppelin to this non-SSL node.

https://docs.search-guard.com/latest/configuring-tls#rest-layer-tls-1

Just set:

`searchguard.ssl.http.enabled: false`

in elasticsearch.yml

**Comment by ltfi** [comment]
Thanks for quick response.
