### ISSUE TITLE
try use transport error:No user found for cluster:monitor/nodes/info

### ISSUE THREAD

**Issue by silvia19941025** [floragunncom/search-guard#596]
now I can use es with https and kibana, but can not use es with transport client.Here is my elasticsearch log:

[2018-12-04T11:08:16,772][ERROR][c.f.s.f.SearchGuardFilter] **No user found for cluster:monitor/nodes/info from 175.6.6.227:13626 TRANSPORT via netty {Authorization=Basic** Q049c2lsdmlhLnp5c29mdC5jb20sIE9VPU9wcywgTz0iWnlzb2Z0IENvbSwgSW5jLiIsIERDPXp5c29mdCwgREM9Y29tOnsdfsfpbHZpYQ==, _sg_initial_action_class_header=NodesInfoRequest}

I guess maybe I lack some configuration about user.Here is my sg_config.yml

searchguard:
  dynamic:
      ......
    authc:
      ......
      transport_auth_domain:
        http_enabled: false
        transport_enabled: true
        order: 2
        http_authenticator:
        authentication_backend:
          type: internal
    authz:    
      ......
      internal_authorization:
        enabled: true
        authorization_backend:
          type: internal

lastly,here is my transprot request:

    	Settings settings = Settings.builder()
				.put("path.home", ".")
				.put("cluster.name", "demo")
				.put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_ENABLED, true)
				.put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_PEMCERT_FILEPATH,"../src/main/resources/ssl/node0.pem")
				.put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_PEMKEY_FILEPATH,"../src/main/resources/ssl/node0.key")
				.put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_PEMKEY_PASSWORD,"5suaaf8uT8")
				.put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_PEMTRUSTEDCAS_FILEPATH,"../src/main/resources/ssl/root-ca.pem")
    			.put("searchguard.ssl.transport.enforce_hostname_verification", false)
    			.put("client.transport.ignore_cluster_name", true)
    			.build();
	    	TransportClient client = new PreBuiltTransportClient(settings, SearchGuardSSLPlugin.class)
	    	.addTransportAddress(new TransportAddress(InetAddress.getByName("39.108.184.167"),9300));
	    	client.threadPool().getThreadContext().putHeader("Authorization", "Basic "+encodeBase64("CN=silvia.ff.com, OU=Ops, O=\"ff Com, Inc.\", DC=ff, DC=com:silvia"));
			client.admin().cluster().nodesInfo(new NodesInfoRequest()).actionGet();
	    	//搜索数据
			GetResponse response = client.prepareGet("user_hpq", "user_hpq", "1").execute().actionGet();

**Comment by floragunncom** [comment]
You need to replace "../src/main/resources/ssl/node0.pem" with an non-node (=client) certificate. 
Pls see
* https://docs.search-guard.com/latest/offline-tls-tool#node-and-client-certificates
* https://docs.search-guard.com/latest/elasticsearch-transport-clients-search-guard#using-transport-clients
* https://search-guard.com/transport-client-authentication-authorization/
* https://search-guard.com/tls-certificate-generator/
* https://search-guard.com/generating-certificates-tls-tool/

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
