### ISSUE TITLE
not able to access kibana dashboard with search guard

### ISSUE THREAD

**Issue by prabhurs123** [floragunncom/search-guard#599]
Hi Team, Recently I have installed ELK + Searchguard plugin for both Elasticsearch and Kibana.Its worked fine with admin credentials to Kibana Dashboard.So i have created new user "user1" from Kibana Searchguard console and allowed only one indices and when I tried to login with the new user am getting below error from browser,

{"message":"no permissions for [indices:data/read/search] and User [name=venus, roles=[venus], requestedTenant=null]: [security_exception] no permissions for [indices:data/read/search] and User [name=venus, roles=[venus], requestedTenant=null]","statusCode":403,"error":"Forbidden"}

So I have given permission for "[indices:data/read/search]" for the particular roles, but still it is not working and giving same above error.Below are my details.

Elasticsearch Version - 6.5.1
Kibana Version - 6.5.1

Elasticsearch-Searchguard plugin version : search-guard-6-6.5.1-23.2
Kibana-Searchguard plugin : search-guard-kibana-plugin-6.5.1-16

And if I assign admin role to the user, i can able to login.but manually created role is not working.

one more thing, When I try to login with admin account for kibana dashboard, webserver is pop up for credentials again, even I have added below line in kibana.yml
elasticsearch.requestHeadersWhitelist: ["Authorization", "sgtenant"]

Could you please help me.

**Comment by floragunncom** [comment]
Can you share a screenshot of the custom role you created? Make sure the role has also the appropriate permissions for the .kibana index (see sg_kibana_user in https://github.com/floragunncom/search-guard/blob/es-6.5.1/sgconfig/sg_roles.yml)

And if you are updating from a version prior 6.5.x then please read https://docs.search-guard.com/latest/upgrading-560
