### ISSUE TITLE
Installation instructions don't verify integrity

### ISSUE THREAD

**Issue by bitmelt** [floragunncom/search-guard#6]
The installation instructions in README.md say to install the plugin using

```
bin/plugin -i com.floragunn/search-guard/0.5
```

However, earlier in the README it says that you must verify the integrity of the plugin, which means you already downloaded the `.zip` and `.zip.asc` files, imported the `KEYS` file into your keychain, and then verified the signature with something like

```
gpg --verify search-guard-0.5.zip.asc
```

To install the downloaded zip file, the command should be

```
bin/plugin -u file:///path/to/downloaded/search-guard-0.5.zip -i search-guard
```

**Comment by floragunncom** [comment]
see https://github.com/floragunncom/search-guard-ssl/wiki/Check-Release-Integrity
