### ISSUE TITLE
we need a SSL/TLS  config  example

### ISSUE THREAD

**Issue by triumph281** [floragunncom/search-guard#60]
I want to implement Searchguard with SSL/TLS, but I can hardly find a successful example, who can share a successful config example so that I can access https://localhost:9200 instead of http://localhost:9200

**Comment by maizels** [comment]
Do you still need help ?

**Comment by triumph281** [comment]
thank you  , l understand it now :

use the script in  directory <example-pki-scripts> to create SSL keystore.jks and config like tis

searchguard.ssl.transport.http.enabled: true
searchguard.ssl.transport.http.keystore_type: JKS
searchguard.ssl.transport.http.keystore_filepath: /root/yinjj/elk/opt/es/example-pki-scripts/node-0-keystore.jks
searchguard.ssl.transport.http.keystore_password: changeit

#searchguard.ssl.transport.http.enforce_clientauth: true

searchguard.ssl.transport.http.truststore_type: JKS
searchguard.ssl.transport.http.truststore_filepath: /root/yinjj/elk/opt/es/example-pki-scripts/truststore.jks
searchguard.ssl.transport.http.truststore_password: changeit

searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.AlwaysSucceedAuthenticationBackend
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.NoRolesAuthorizator
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.HTTPUnauthenticatedAuthenticator
