### ISSUE TITLE
cann't switch user with search guard on ES 6.5.1

### ISSUE THREAD

**Issue by moloch90** [floragunncom/search-guard#600]
hi,

i use to work with search gurad on ES 6.4.2, and it worked perfectly.

when i install ES 6.5.1, i've install with the last version of SG. But i notice that i can't switch user.

when i enter the username/password in the login page of Kibana, it send back pop-up the enter again the information (" Authorization Required")
once i'm connected to kibana, i can logout and go to the login page. or if i enter a new user/password, it will connect with the old one.

did anyone else encounter this situation??
thanks.

**Comment by mgustafsson1** [comment]
Hi there,

could you please check if you've disabled Kibana Spaces in your kibana.yml file?
Like so:
`xpack.spaces.enabled: false`

The authorization required dialog shouldn't come up. When you use it, your login credentials will be "cached" in the browser headers, which is probably the reason you get logged in with your first user.

More details here: https://docs.search-guard.com/latest/upgrading-560

**Comment by moloch90** [comment]
Indeed, it's my fault. It work now, thank you very much.
