### ISSUE TITLE
Plugin installation was unsuccessful due to error - JavaScript heap out of memory

### ISSUE THREAD

**Issue by josephbleroy** [floragunncom/search-guard#601]
* Search Guard version: com.floragunn:search-guard-6:6.5.1-23.2
* Elasticsearch version: 6.5.1
* JVM version: openjdk version "1.8.0_191"
* Operating system: RHEL 7.6 (2 vCPU / 8 GB RAM)
* Number of nodes in cluster: 1

I'm currently experiencing an issue when installing the Search Guard Kibana plugin. Here are the steps I've used to install:

```
[root@localhost src]# /usr/share/kibana/bin/kibana-plugin install file:///usr/src/kibana-plugin.zip
Found previous install attempt. Deleting...
Attempting to transfer from file:///usr/src/kibana-plugin.zip
Transferring 2059943 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
```

After that, I'm presented with the following errors:

```
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false
(node:27595) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/share/kibana/node/bin/node]
 2: 0x8c21ec [/usr/share/kibana/node/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/share/kibana/node/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/share/kibana/node/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/share/kibana/node/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/share/kibana/node/bin/node]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [/usr/share/kibana/node/bin/node]
 8: v8::internal::String::LastIndexOf(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/share/kibana/node/bin/node]
 9: v8::internal::Builtin_StringPrototypeLastIndexOf(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/share/kibana/node/bin/node]
10: 0x3c4a18c0697d

{"type":"log","@timestamp":"2018-12-06T02:13:40Z","tags":["info","optimize"],"pid":27595,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, space_selector, login, logout, dashboardViewer, apm, canvas, infra, searchguard-login, searchguard-customerror, searchguard-multitenancy, searchguard-accountinfo, searchguard-configuration and kibana. This may take a few minutes"}

<--- Last few GCs --->

[27595:0x4169bc0]   699742 ms: Mark-sweep 1319.7 (1473.1) -> 1319.6 (1474.6) MB, 984.5 / 0.0 ms  allocation failure GC in old space requested
[27595:0x4169bc0]   700905 ms: Mark-sweep 1319.6 (1474.6) -> 1319.6 (1443.6) MB, 1163.7 / 0.0 ms  last resort GC in old space requested
[27595:0x4169bc0]   701710 ms: Mark-sweep 1319.6 (1443.6) -> 1319.6 (1443.6) MB, 805.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x29a1d6525879 <JSObject>
    0: builtin exit frame: lastIndexOf(this=0x6ce937cc691 <Very long string[1106662]>,0x16144750ca51 <String[1]\: \n>)

    1: has_nlb(aka has_nlb) [0xc0e40e022d1 <undefined>:5970] [bytecode=0x7ac0a8ffec1 offset=15](this=0xc0e40e022d1 <undefined>)
    2: /* anonymous */(aka /* anonymous */) [0xc0e40e022d1 <undefined>:6070] [bytecode=0x358d5ed518b1 offset=60](this=0xc0e40e022d1 <undefined>,c=0x17...

"
```

To me it looks like the optimization process is using all of the memory allocated to Kibana (NodeJS). I'm wondering if this is a known issue with Search Guard or an issue with Kibana 6.5.1? 

Any thoughts on how to remedy this issue, or should I consult with the Elastic team?

Thanks for your time.

**Comment by josephbleroy** [comment]
Seems that I was able to fix my problem by issuing the following command:

```
NODE_OPTIONS="--max-old-space-size=4096" /usr/share/kibana/bin/kibana-plugin install file:///usr/src/kibana-plugin.zip
```

**Comment by floragunncom** [comment]
thx, will add this to our docs

**Comment by hackery** [comment]
We've often seen plugin installation hang (for hours) until killed before - the OP here actually saw an OOM failure, but could the situation result in a stuck "Optimizing and caching browser bundles..." with **no** error? Maybe Node gets stuck in some GC loop?

On an upgrade last week, we had several hangups like this, and discovered that settings NODE_OPTIONS as above worked for us. There are also many other reports of such hangs on discussion groups, perhaps some of them can be resolved this way.

**Comment by jochenkressin** [comment]
Yes, absolutely. We have seen both behaviors (OOM and the process just being stuck), and you are right, in the latter case node (webpack to be more precise) seems to be stuck in a GC loop. This is an issue with all Kibana plugins, unfortunately. Elastic finally decided to do something about it, so since 6.5 there is the --no-optimize flag which defers optimization:

https://www.elastic.co/guide/en/kibana/current/install-plugin.html

This is especially useful when running KI on docker or K8s and we were able to bring down the startup time for KI in our own Docker-based integration tests to ~3 minutes. But since Elastic never backports anything, you need to upgrade to >= 6.5.x.

We've also already added the max-old-space-size option to our docs.
