### ISSUE TITLE
Feature request:  ability to change 'audit_utc_timestamp' field name in audit logging

### ISSUE THREAD

**Issue by packetrevolt** [floragunncom/search-guard#609]
When enabling Search Guard audit logging using Elasticsearch as the data type, is there a way to change the name of the 'audit_utc_timestamp' field name to '@timestamp' or perhaps even copy the field so both are populated?  The reason I ask due to Kibana, we create index patterns in Kibana of aliases that then contain many other indexes.  If the created Search Guard audit index is added to an alias with other security audit related logs then in Kibana only a single field is supported as the timefield.

**Comment by floragunncom** [comment]
We will include this in the next release (v24) expected next week. Thx for this feature request.
