### ISSUE TITLE
Incorrect permissions for operation: write operation being evaluated as bulk

### ISSUE THREAD

**Issue by HT154** [floragunncom/search-guard#610]
ES Version: 6.5.2
SG Version: 23.2
JRE Version: 8.181.0
JVM Version: 25.181-b13
Cluster size: 11 nodes (3 master, 3 controller, 5 data)

The user has `INDICES_ALL` permission on all `metadata-*` indices. The client is doing a write directly to the index, not using the bulk API. The error shows that permission for a bulk write is being denied.

Client logs:
```
POST https://172.16.12.138:9200/metadata-build/doc [status:403 request:0.005s]
> {"created":"2018-12-18T02:22:12.906924+00:00"}
< {"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [indices:data/write/bulk] and User [name=<REDACTED>, roles=[], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [indices:data/write/bulk] and User [name=<REDACTED>, roles=[], requestedTenant=null]"},"status":403}
```

ES logs from controller node:
```
[2018-12-18T01:01:53,067Z][INFO ][c.f.s.p.PrivilegesEvaluator] [elasticsearch-controller-2]No cluster-level perm match for User [name=<REDACTED>, roles=[], requestedTenant=null] Resolved [aliases=[], indices=[metadata-build], allIndices=[metadata-build], types=[doc], isAll()=false, isEmpty()=false] [Action [indices:data/write/bulk]] [RolesChecked [pipeline_metadata]]
[2018-12-18T01:01:53,067Z][INFO ][c.f.s.p.PrivilegesEvaluator] [elasticsearch-controller-2]No permissions for [indices:data/write/bulk]
```

**Comment by floragunncom** [comment]
Elasticsearch converts all writes internally to bulk, so you need to allow "indices:data/write/bulk" on cluster level.

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support. See CLUSTER_COMPOSITE_OPS in https://github.com/floragunncom/search-guard/blob/master/sgconfig/sg_action_groups.yml

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by HT154** [comment]
Can you point me to where in the docs this is explained? It's quite confusing to grant permissions on an index and have to separately define that a role can perform any writes in the cluster. Is there documentation on the full range of permissions as well?
