### ISSUE TITLE
sg_tenant query param missing in kibana share search (discovery)

### ISSUE THREAD

**Issue by faxm0dem** [floragunncom/search-guard#612]
In Kibana (multitenant) sharing visualizations or dashboards using the "share" button conveniently sets the `sg_tenant` query parameter in the link.

Unfortunately, this is not the case when sharing searches in the discovery tab.

**Comment by floragunncom** [comment]
@faxm0dem we look into it, thx for reporting this

**Comment by mgustafsson1** [comment]
@faxm0dem which version of Kibana are you using? The share panel has changed a lot in the later versions of Kibana so I need to look into a few different solutions here, I'm afraid.

**Comment by faxm0dem** [comment]
we're using 6.3.2 for the moment

**Comment by mgustafsson1** [comment]
@faxm0dem Sorry about the delay - I'm having a bit of trouble reproducing this issue.
Testing with 6.3.2 I do get the sg_tenant query parameter in the discover tab, both for long and short URLs
![image](https://user-images.githubusercontent.com/393558/52572303-d1c53a80-2e17-11e9-84cb-5e490424d1ae.png)

Do you see any JavaScript errors in the browser's console?
What browser are you using?

**Comment by faxm0dem** [comment]
I just tried with firefox and chromium with the same result.
I don't see any erros in the console.
Thanks for trying to reproduce. I'll upgrade ES+kibana+SG soon, and report back. In the meantime either we leave the issue open, or I'll reopen it if still present.

**Comment by faxm0dem** [comment]
Using 6.6.0, the situation seems worse: no tenant in any "share" link

**Comment by mgustafsson1** [comment]
@faxm0dem I'm afraid you are right. Kibana has changed the share panel completely, but I'm working on a solution. Let's leave this issue open and I'll post back here as soon as I have more information.

**Comment by faxm0dem** [comment]
wat? you mean elastic devs changed *everything* *again*? I don't believe you 😂

**Comment by mgustafsson1** [comment]
I think we have a solution for this now.
PR: https://github.com/floragunncom/search-guard-kibana-plugin/pull/177

**Comment by jochenkressin** [comment]
@mgustafsson1 this fix has been released now, right?

**Comment by mgustafsson1** [comment]
@jochenkressin Yes! Sorry, I should have closed this!
