### ISSUE TITLE
How to create a client with the protect of SearchGuard By Class RestHighLevelClient

### ISSUE THREAD

**Issue by AveiShriety** [floragunncom/search-guard#622]
Sry! I have wanted to ask my queston in the [https://groups.google.com/forum/#!forum/search-guard](https://groups.google.com/forum/#!forum/search-guard), but my network can't establish with it, so I have to ask here!!

Search Guard and Elasticsearch version:6.5.4:24
JVM version and operating system version:1.8  win10
Number of nodes in your cluster:2
Description of the bug: sry sry , it's not a bug!

Now, I use SearchGuard to secure my elasticsearch cluster.

And in the search-guard official website, I found the Transport Clients to create A client. But, due to the Elasticsearch official website's declare:

> We plan on deprecating the TransportClient in Elasticsearch 7.0 and removing it completely in 8.0. Instead, you should be using the Java High Level REST Client, which executes HTTP requests rather than serialized Java requests.

So I prefer to use Class RestHighLevelClient to create the elasticsearch client!
But in this way, how could I write the code? Could someone provide the demo?
Thanks!

**Comment by AveiShriety** [comment]
hello~hello~ anybody?

**Comment by qiumingben** [comment]
I also encountered the same problem,Maybe you can try my code, but I will report an error in my local area,If you can solve it, please reply me or email me.

email: qiumingben@gmail.com

    private static RestHighLevelClient client = null;
    private static String user = "admin";
    private static String password = "change it";
    private static String ip = "change it";
    private static Integer port = 9200;

    @Bean
    public static RestHighLevelClient getInstance() {
        if(client == null){
            synchronized (RestHighLevelClient.class){
                if(client == null){
                    try {
                        String esAuth = "Basic " + Base64.encode(user + ":" + password);
                        Header[] defaultHeaders = new Header[]{new BasicHeader("Authorization", esAuth)};
                        client = new RestHighLevelClient(
                                RestClient.builder(new HttpHost(ip, port, "https"))
                                        .setDefaultHeaders(defaultHeaders)
                                        .setMaxRetryTimeoutMillis(30*3600*1000)
                                        .setRequestConfigCallback(requestConfigBuilder -> requestConfigBuilder
                                                .setConnectTimeout(150000)
                                                .setSocketTimeout(150000)
                                                .setAuthenticationEnabled(true)));
                    }catch (Exception e){
                        e.printStackTrace();
                    }
                }
            }
        }
        return client;
    }

**Comment by kasinaat** [comment]
> I also encountered the same problem,Maybe you can try my code, but I will report an error in my local area,If you can solve it, please reply me or email me.
> 
> email: [qiumingben@gmail.com](mailto:qiumingben@gmail.com)
> 
> ```
> private static RestHighLevelClient client = null;
> private static String user = "admin";
> private static String password = "change it";
> private static String ip = "change it";
> private static Integer port = 9200;
> 
> @Bean
> public static RestHighLevelClient getInstance() {
>     if(client == null){
>         synchronized (RestHighLevelClient.class){
>             if(client == null){
>                 try {
>                     String esAuth = "Basic " + Base64.encode(user + ":" + password);
>                     Header[] defaultHeaders = new Header[]{new BasicHeader("Authorization", esAuth)};
>                     client = new RestHighLevelClient(
>                             RestClient.builder(new HttpHost(ip, port, "https"))
>                                     .setDefaultHeaders(defaultHeaders)
>                                     .setMaxRetryTimeoutMillis(30*3600*1000)
>                                     .setRequestConfigCallback(requestConfigBuilder -> requestConfigBuilder
>                                             .setConnectTimeout(150000)
>                                             .setSocketTimeout(150000)
>                                             .setAuthenticationEnabled(true)));
>                 }catch (Exception e){
>                     e.printStackTrace();
>                 }
>             }
>         }
>     }
>     return client;
> }
> ```

I assume you are using HTTP authentication in your case.Can you please help me how to use client certificate authentication in this case??

**Comment by AveiShriety** [comment]
> > I also encountered the same problem,Maybe you can try my code, but I will report an error in my local area,If you can solve it, please reply me or email me.
> > email: [qiumingben@gmail.com](mailto:qiumingben@gmail.com)
> > ```
> > private static RestHighLevelClient client = null;
> > private static String user = "admin";
> > private static String password = "change it";
> > private static String ip = "change it";
> > private static Integer port = 9200;
> > 
> > @Bean
> > public static RestHighLevelClient getInstance() {
> >     if(client == null){
> >         synchronized (RestHighLevelClient.class){
> >             if(client == null){
> >                 try {
> >                     String esAuth = "Basic " + Base64.encode(user + ":" + password);
> >                     Header[] defaultHeaders = new Header[]{new BasicHeader("Authorization", esAuth)};
> >                     client = new RestHighLevelClient(
> >                             RestClient.builder(new HttpHost(ip, port, "https"))
> >                                     .setDefaultHeaders(defaultHeaders)
> >                                     .setMaxRetryTimeoutMillis(30*3600*1000)
> >                                     .setRequestConfigCallback(requestConfigBuilder -> requestConfigBuilder
> >                                             .setConnectTimeout(150000)
> >                                             .setSocketTimeout(150000)
> >                                             .setAuthenticationEnabled(true)));
> >                 }catch (Exception e){
> >                     e.printStackTrace();
> >                 }
> >             }
> >         }
> >     }
> >     return client;
> > }
> > ```
> 
> I assume you are using HTTP authentication in your case.Can you please help me how to use client certificate authentication in this case??

+1, what your said is what I want to ask! How~~ Anybody???

**Comment by qiumingben** [comment]
> I assume you are using HTTP authentication in your case.Can you please help me how to use client certificate authentication in this case??

My goal is not to use certificate verification, just use the account number and password, it seems that I have encountered the same problem with you.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
