### ISSUE TITLE
doc website v2 redirects to v5

### ISSUE THREAD

**Issue by scampi** [floragunncom/search-guard#632]
https://docs.search-guard.com/v2/index goes to https://docs.search-guard.com/v5/index

**Comment by floragunncom** [comment]
That's intended. v2 and v5 docs live in the same "space". That is why the docs are headlined "Search Guard 5 and Search Guard 2 Documentation".

Do you look for anything specific? If so pls refer to https://groups.google.com/forum/#!forum/search-guard

**Comment by scampi** [comment]
I thought that wasn't intentional, nothing specific to lookup
