### ISSUE TITLE
Incorrect curl statement in docs

### ISSUE THREAD

**Issue by philenius** [floragunncom/search-guard#637]
The docs at [Admin certificate access control](https://docs.search-guard.com/latest/rest-api-access-control#admin-certificate-access-control) give an example curl command for testing the authentication per admin TLS certificate:
```bash
curl --insecure --cert chain.pem --key kirk.key.pem "<API Endpoint>"
```
The stated command doesn't work as expected because I received a HTTP 401 unauthorized response no matter what I did (reinstalled Search Guard, regenerated my TLS certs, etc.). I lost quite some time to solve this. Later, I found out that curl prints a warning, if you activate verbose mode and read carefully:
```bash
curl --insecure --cert chain.pem --key kirk.key.pem "<API Endpoint>" -vvv
# ...
# certificate file name "xxxxxxx.cer" handled as nickname; please use "./xxxxxxx.cer" to force file name.
# ...
```
Curl requires you to specify a path starting with `./` (for relative file paths) or an absolute path starting with `/` like this way:
```bash
curl --insecure --cert ./chain.pem --key ./kirk.key.pem "<API Endpoint>"
```
I'll highly appreciate it, if you update your docs on behalf of this curl command. This issue might depend on the version of curl itself. I used curl in version 7.29.0 on Ubuntu 18.04.

SearchGuard deployment environment:
* Search Guard: 6.5.4-33.0
* Elasticsearch: 6.5.4-1
* OS: RHEL 7.4 (Maipo)
* JVM: OpenJDK 1.8.0_161-b14
* Number of nodes: 2 (test cluster)

**Comment by floragunncom** [comment]
Fixed with https://github.com/floragunncom/search-guard-docs/commit/56bc783e9d4039dca2d9fef259d3f7489a40c4a3

Thanks for reporting
