### ISSUE TITLE
Wrong content-type in HTTP responses

### ISSUE THREAD

**Issue by philenius** [floragunncom/search-guard#638]
I observed some inconsistencies on behalf of the content type of HTTP responses. For example, the endpoint  `GET _searchguard/api/rolesmapping` returns an HTTP response with content type `application/json`.
But, the endpoint `GET searchguard/api/rolesmapping/{rolename}` returns `text/plain` as content-type even though the response contains valid JSON data. I observed the same behavior using curl and Postman. This might apply to other endpoints as well.

SearchGuard deployment environment:
* Search Guard: 6.5.4-33.0
* Elasticsearch: 6.5.4-1
* OS: RHEL 7.4 (Maipo)
* JVM: OpenJDK 1.8.0_161-b14
* Number of nodes: 2 (test cluster)

**Comment by floragunncom** [comment]
Yes, there are a few inconsistencies. Thx for pointing this out. We are on it.

**Comment by jochenkressin** [comment]
@floragunncom I think we released this fix now, right?

**Comment by floragunncom** [comment]
@jochenkressin only for SG >= 7

**Comment by jochenkressin** [comment]
Please also backport for the last 6.x release

**Comment by philenius** [comment]
Yesterday, I've installed Search Guard 35.0.0. 
I can confirm that the HTTP response is of content-type `application/json`.
Keep up the good work! Thanks.

**Comment by floragunncom** [comment]
Fixed with v25.3 released last week
