### ISSUE TITLE
Getting "TimeOut"error while making  kibana to work with SearchGuard  

### ISSUE THREAD

**Issue by balubollam** [floragunncom/search-guard#64]
Hi Everyone

 I Have Implemented  “search-guard” Elasticsearch
-->
*First i have created a “SearchGuard” Index
*Then I have Installed and Configured it in logging.yml and Elasticsearch.yml 
*In elasticsearch.yml i have given a user name:admin and password:admin
note:I have given all permissions to admin user in “searchguard” index
**HERE is my index

curl -XPUT 'http://localhost:9200/searchguard/ac/ac' -d '{
    "acl": [
    {    
        "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
        "filters_bypass": [],
        "filters_execute": []
     },
     {
           "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
           "roles": [
               "admin"
           ],
           "filters_bypass": [],
           "filters_execute": [“actionrequestfilter.kibanaUser”]
     }
     ]
}'

**Here is my elasticsearch.yml
searchguard.enabled: true
searchguard.rewrite_get_as_search: true
searchguard.allow_all_from_loopback: true
searchguard.config_index_name: searchguard
searchguard.key_path: /var/lib/elasticsearch/searchguard_node.key
##User settings
searchguard.authentication.settingsdb.user.admin: admin
searchguard.actionrequestfilter.names: ["kibanaUser","admincopy"]
searchguard.actionrequestfilter.kibanaUser.allowed_actions:["indices:admin/get","indices:data/read/*", "*monitor*"]

--->Here iam getting “timeout” Error.
As i am new to this concept.Not getting.Please someone help me out in this??  

Thanks And Regards
Balaji

**Comment by jayeshdhamechai** [comment]
Try with 
searchguard.allow_all_from_loopback: false

**Comment by balubollam** [comment]
If i do that then i can’t change the config index and kibana also not working.
Please see this 2cases
Case1: 
KIbana giving “RuntimeException” due to no default bypass and execute filters becuase the default configiration is 
                                         "filters_bypass": [],
                                          filters_execute": []
Now by replacing this to 
                             "filters_bypass": ["actionrequestfilter.readonlyuser"],
                           "filters_execute": []
and giving same  usernames and password in elasticsearch.yml and kibana.yml
Kibana is working fine For Admin role and Readonly users…
But not working for the  readonly specific indices when i replace the default configuration…

Here is my updated config index:
curl -XPOST -u admin:admin  'http://localhost:9200/searchguard/ac/ac' -d '
{
    "acl": [
     {    
        "__Comment__":Default”,
        "filters_bypass": ["actionrequestfilter.readonlyuser"],
        "filters_execute": []
     },

{
           "__Comment__": "For user *agent1* only “ind” index operations should be performed",
           "users": [
               "agent1"
           ],
           "indices": [
               "Ind"
           ],
           "filters_bypass": [],
           "filters_execute":["actionrequestfilter.readonlyuser"]
     },
}


*Now here comes the problem is that the user “agent1” actually should only read the index “ind” but reading and writing all the  indices
 *BUT when we replace the “ind” with “*” then it is reading the all indices but not writing the indices..
Please help me How to perform read only on particular index without keeping default empty(Because kibana is giving exception if default is empty)...

*here is My elasticsearch.yml file
searchguard.authentication.settingsdb.user.agent2:pswd
searchguard.actionrequestfilter.readonlyuser.allowed_actions:["indices:admin/get","indices:data/read/*", "*monitor*"]

*here is my kibana.yml
searchguard.enabled: true
kibana_elasticsearch_username: agent2
kibana_elasticsearch_password: pswd


Case2:
Here if i give default configuration "filters_execute": [“*”]
THen kibana is giving “internal server error”

**Comment by jayeshdhamechai** [comment]
For the timeout issue,

rewrite get as search: false

Probably there's some issue with being able to run Kibana with this setting as true. I'm looking at the issue, meanwhile try this workaround if it helps you.

For the default Acls, I have 
  {
			"__Comment__": "By default, bypass nothing, execute read only filter",
			"filters_bypass": [],
			"filters_execute": [
			  "actionrequestfilter.readonlyfilter"
			]
  }

and if you want to restrict access, you could have something like:

  {
			"__Comment__": "Role Nurse has no access to patients data",
			"roles": [
			  "nurse"
			],
			"indices": [
			  "patients"
			],
			"filters_bypass": [],
			"filters_execute": [
			  "actionrequestfilter.noaccess"
			]
		  }

and in config file:
searchguard.actionrequestfilter.readonlyfilter.forbidden_actions: ["indices:data/write*"]
searchguard.actionrequestfilter.readonlyfilter.allowed_actions: ["indices:data/read*"]
searchguard.actionrequestfilter.noaccess.forbidden_actions: ["indices:data/*"]

**Comment by balubollam** [comment]
HI 
Thank You.Please Help me when the issue is solved.
*I  tried  in that above way as u said 
I am unable to access even the index  "patients" i mean specified index and no other index.

case1
*When iam trying to access "patients" index giving me error “RuntimeException[Action 'indices:admin/get' is forbidden due to DEFAULT]”
 so



Then i added the 'indices:admin/get’ to the “searchguard.actionrequestfilter.readonlyfilter.allowed_actions”
 Now i can read all the indices.. 
 But our requirement is “specific role should  access only one indices” and kibana also should work

Case 2:
I added ‘indices:admin/get’ to the “searchguard.actionrequestfilter.noaccess.forbidden_actions:”
Now i Our requirement (“specific role should  access only one indices”) reaching but kibana is giving error”Runtime error” due to “indices:data/read/search” is forbidden in default
Then i added that “indices:data/read/search” to the “actionrequestfilter.readonlyfilter.allowed_actions” But now kibana is giving “internal server exception”

Is their any idea about searchguard index such that  “specific role should  access only one indices?? and kibana to be connected without errors”..
Please Suggest me

Thanks and regards
Balaji

**Comment by jayeshdhamechai** [comment]
what are the rules you have configured for kibana index in your search guard acl?

**Comment by balubollam** [comment]
Same as U given in the above comment
{
"Comment": "By default, bypass nothing, execute read only filter",
"filters_bypass": [],
"filters_execute": [
"actionrequestfilter.readonlyfilter"

}
{
"Comment": "Role Nurse has no access to patients data",
"roles": [
"nurse"
],
"indices": [
"patients"
],
"filters_bypass": [],
"filters_execute": [
"actionrequestfilter.noaccess"
]
}

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
