### ISSUE TITLE
cannot restart es after removing indice searchguard

### ISSUE THREAD

**Issue by Zuckonit** [floragunncom/search-guard#640]
bug of searchguard:

es version: 5.3.0
search guard version: search-guard-5-5.3.0-11

steps:
1. prepare a cluster with searchguard installed and initialized, and there hold 10T data
2. uninstall the searchguard and then remove indice ```searchguard```
3. reinstall searchguard, then we could see:

```
[WARN ][c.f.s.c.IndexBaseConfigurationRepository] index 'searchguard' not healthy yet, we try again ... (Reason: timeout)
```

many hour passed, we can still see this error

**Comment by floragunncom** [comment]
ES 5.3.0 and SG for 5.3.0 is EOL (End of Life), see https://docs.search-guard.com/latest/eol-policy

You need to upgrade and if the issue remains pls. file a new issue
