### ISSUE TITLE
Need help for configuring kibana-curator-plugin "cleaner"

### ISSUE THREAD

**Issue by CodeFreezr** [floragunncom/search-guard#643]
Hello together,

thanks for offering this awesome elastic search security solution for all! We try this on ELK v6.4.1 within this smart docker-compose solutions: https://github.com/deviantony/docker-elk.

For curating indexes we fall in love with "cleaner" a very smart and simple kibana plugin which works fine ootb without any security setting (also 6.4.1). See: https://github.com/TrumanDu/cleaner

But now we have problems to get cleaner up and running inside the searchguarded environment. Installation of the plugin works fine, but after clicking on the plugin item inside kibana, the start page of "cleaner" hangs. After sniffing a bit around we found an "unauthorized" response on their REST-API-Calls. We hope this is only a configuration issue, we can't figure out. 

Did you have an idea how and where to configure stuff, so we can use a kibana plugin with their REST-API Call inside a searchguard setup?

BR

**Comment by CodeFreezr** [comment]
Because we are not sure where to solve this, we have also post this question here https://github.com/deviantony/docker-elk/issues/364 and there https://github.com/TrumanDu/cleaner

**Comment by CodeFreezr** [comment]
Here are the Get-Request which creates the "403" Response: 
https://[kibana-url]/api/cleaner/list

**Comment by floragunncom** [comment]
Can you please configure  debug mode for Search Guard (https://docs.search-guard.com/latest/troubleshooting-setting-log-level#turn-on-debug-logging-temporarily), reproduce the error and send the logs (they should detailed point  out which permission is exactly missing)

**Comment by CodeFreezr** [comment]
Thanks for your attention. Starting with ES 6.6+ there is a buildin Index Lifecycle Management, so we don't the cleaner plugin anymore.
