### ISSUE TITLE
How to give access read only for "Discover","Log UI" and "Dashboard"?

### ISSUE THREAD

**Issue by balamelangi** [floragunncom/search-guard#644]
Hi,

Please help me how to create role give read only access to **Dashboards** , **Logs UI** and **Discover** tabs in kibana.

I'm running V6.6.1 of ELK and search-guard plugin as well.

Please some one help me.

Thanks.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
