### ISSUE TITLE
Is there a plan to release or branch sg for es 1.7.3?

### ISSUE THREAD

**Issue by xied5531** [floragunncom/search-guard#65]
@floragunncom Is there a plan to release or branch sg for es 1.7.3?

**Comment by jmaitrehenry** [comment]
Hi,
I made a fork of this project for support 1.7, and merge other PR like returning 403 instead of 500.
You can install it via bin/plugin -i com.petalmd/armor/1.7.0 or find it on github: https://github.com/petaldevelopment/armor

@floragunncom do you have a build for 1.7?

**Comment by floragunncom** [comment]
just released: https://github.com/floragunncom/search-guard/tree/es1.7

<pre>
bin/plugin -i com.floragunn/search-guard/1.7.3.0
</pre>
