### ISSUE TITLE
sgadmin Done with failures

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [floragunncom/search-guard#651]
When doing initialization with sgadmin.sh, the previous prompt was successful, but the last one did show Done with failures.

Will connect to 192.168.43.129:9300 ... done
Elasticsearch Version: 6.5.4
Search Guard Version: 6.5.4-24.1
Connected as CN=admin,OU=client,O=client,L=Test,C=DE
Contacting elasticsearch cluster 'es-cluster' and wait for YELLOW clusterstate ...
Clustername: es-cluster
Clusterstate: GREEN
Number of nodes: 2
Number of data nodes: 2
searchguard index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/
Will update 'sg/config' with /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_config.yml 
   SUCC: Configuration for 'config' created or updated
Will update 'sg/roles' with /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_roles.yml 
   FAIL: Configuration for 'roles' failed because of SettingsException[Failed to load settings from [dummy.json]]; nested: IllegalStateException[only value lists are allowed in serialized settings];
Will update 'sg/rolesmapping' with /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'sg/internalusers' with /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update 'sg/actiongroups' with /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
FAIL: Expected 2 nodes to return response, but got only 0
Done with failures

**Comment by floragunncom** [comment]
Anything in the log files of the data nodes?

**Comment by floragunncom** [comment]
Please also check if sg_roles.yml contains valid yml

**Comment by FANGXIANGQUAN** [comment]
> Please also check if sg_roles.yml contains valid yml

Yes, your suggestion is right.I later used -f instead of -cd, which I found was due to a configuration problem with sg_roles.yml.Thank you very much!
But what I don't understand is why using -cd does prompt success?

**Comment by pablolescotti** [comment]
According to [sgadmin documentation ](https://docs.search-guard.com/latest/sgadmin):
> The following switches define which configuration file(s) you want to push to Search Guard. You can either push a single file or specify a directory containing one or more configuration files.
>- -cd Directory containing multiple Search Guard configuration files.
>- -f Single config file (cannot be used together with -cd).

That is the difference between -f and -cd. If You use -cd all config files need to be valid. When running with -f, only the file passed as argument needs to be valid.
