### ISSUE TITLE
add roles, roles_mapping ,indices on kibana can't synchronize to configuration file of sgconfig

### ISSUE THREAD

**Issue by HLLavender** [floragunncom/search-guard#658]
I found that these new configurations could not be synchronized to the relevant configuration files on sgconfig,When I add a roles,role_mapping,internal user to the kibana page.and when
i upload the changes via sgadmin ,configuration files is gone on kibana page . I wonder why settings isn't synchronous.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
