### ISSUE TITLE
Unexpected exception cluster:admin/snapshot/restore

### ISSUE THREAD

**Issue by djsowa** [floragunncom/search-guard#663]
We was using ELK stack in version 6.4.2 with SG enabled.
I created a snapshot using this version and now try to restore it on ELK version 6.6.2 with SG Enabled.
On new cluster SG is in version: 6:6.6.2-24.2
We have 3 master and 3 data nodes in cluster.

In elasticsearch.yml I alredy set:
`searchguard.enable_snapshot_restore_privilege: true`
And in roles/user I have:
sg_roles:

```
sg_snapshot_restore:
  cluster:
    - cluster:admin/repository/put
    - cluster:admin/repository/get
    - cluster:admin/snapshot/status
    - cluster:admin/snapshot/get
    - cluster:admin/snapshot/create
    - cluster:admin/snapshot/restore
    - cluster:admin/snapshot/delete
  indices:
    '*':
      '*':
        - indices:data/write/index
        - indices:admin/create
```

In sg_internal_users I have:
```
admin:
  readonly: true
  hash: fsfsdfsdf
  roles:
    - admin
    - manage_snapshots
    - snapshot_restore
```

When sending this request:

> curl -k -X POST "https://admin:PASSWD@DATA_NODE_IP:9200/_snapshot/ondemand/version_update/_restore" -H 'Content-Type: application/json' -d'
> {
>   "indices": "logstash*,logaudit*",
>   "include_global_state": false,
>   "rename_pattern": "*2019.03.26(.+)",
>   "rename_replacement": "restored_2019.03.26"
> }
> '

I'm receiving:

> {"error":{"root_cause":[{"type":"security_exception","reason":"Unexpected exception cluster:admin/snapshot/restore"}],"type":"security_exception","reason":"Unexpected exception cluster:admin/snapshot/restore"},"status":500}

In Data node logs I see this:

> [2019-03-26T15:19:42,321][WARN ][r.suppressed             ] [datanode-vm1] path: /_snapshot/ondemand/version_update/_restore, params: {repository=ondemand, snapshot=version_update}
> org.elasticsearch.transport.RemoteTransportException: [masternode-vm0][masternodeip:9300][cluster:admin/snapshot/restore]
> Caused by: org.elasticsearch.ElasticsearchSecurityException: Unexpected exception cluster:admin/snapshot/restore
> 	at com.floragunn.searchguard.filter.SearchGuardFilter.apply0(SearchGuardFilter.java:263) ~[?:?]
> 	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:107) ~[?:?]
> 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:83) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:73) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:169) ~[?:?]
> 	at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:260) ~[?:?]
> 	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:141) ~[?:?]
> 	at com.floragunn.searchguard.SearchGuardPlugin$7$1.messageReceived(SearchGuardPlugin.java:645) ~[?:?]
> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1289) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:140) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1247) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1111) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:914) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) [transport-netty4-client-6.6.2.jar:6.6.2]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by djsowa** [comment]
Update. In master node logs I see why this error occur.

> [2019-03-26T15:19:42,319][ERROR][c.f.s.f.SearchGuardFilter] [masternode-vm0] Unexpected exception java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
> *2019.03.26(.+)
> ^
> java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
> *2019.03.26(.+)
> ^
> 	at java.util.regex.Pattern.error(Pattern.java:1957) ~[?:1.8.0_201]
> 	at java.util.regex.Pattern.sequence(Pattern.java:2125) ~[?:1.8.0_201]
> 	at java.util.regex.Pattern.expr(Pattern.java:1998) ~[?:1.8.0_201]
> 	at java.util.regex.Pattern.compile(Pattern.java:1698) ~[?:1.8.0_201]
> 	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_201]
> 	at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_201]
> 	at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_201]
> 	at com.floragunn.searchguard.resolver.IndexResolverReplacer.renamedIndices(IndexResolverReplacer.java:666) ~[search-guard-6-6.6.2-24.2.jar:6.6.2-24.2]
> 	at com.floragunn.searchguard.resolver.IndexResolverReplacer.getOrReplaceAllIndices(IndexResolverReplacer.java:795) ~[search-guard-6-6.6.2-24.2.jar:6.6.2-24.2]
> 	at com.floragunn.searchguard.resolver.IndexResolverReplacer.resolveRequest(IndexResolverReplacer.java:381) ~[search-guard-6-6.6.2-24.2.jar:6.6.2-24.2]
> 	at com.floragunn.searchguard.privileges.PrivilegesEvaluator.evaluate(PrivilegesEvaluator.java:413) ~[search-guard-6-6.6.2-24.2.jar:6.6.2-24.2]
> 	at com.floragunn.searchguard.filter.SearchGuardFilter.apply0(SearchGuardFilter.java:242) [search-guard-6-6.6.2-24.2.jar:6.6.2-24.2]
> 	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:107) [search-guard-6-6.6.2-24.2.jar:6.6.2-24.2]
> 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:83) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:73) [elasticsearch-6.6.2.jar:6.6.2]
> 	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:169) [search-guard-ssl-6.6.2-25.6.jar:6.6.2-25.6]
> 	at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:260) [search-guard-6-6.6.2-24.2.jar:6.6.2-24.2]
> 	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:141) [search-guard-ssl-6.6.2-25.6.jar:6.6.2-25.6]
> 	at com.floragunn.searchguard.SearchGuardPlugin$7$1.messageReceived(SearchGuardPlugin.java:645) [search-guard-6-6.6.2-24.2.jar:6.6.2-24.2]
> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1289) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:140) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1247) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1111) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:914) [elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) [transport-netty4-client-6.6.2.jar:6.6.2]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by floragunncom** [comment]
Your rename_pattern is not a valid regular expression.

But I have to admit we need a better error message here.

**Comment by djsowa** [comment]
Yes, when use correct pattern restore started.
So no error here. But it seems just error message can be improved.
I send https request to data node, but proper error message appear on master node only.

**Comment by floragunncom** [comment]
That's because ES route all restore actions to the master node. Nothing we can do here.
But will improve the error message in the next release. Pls do not close this issue.

**Comment by floragunncom** [comment]
v25.0 released with improved error message
