### ISSUE TITLE
Priority of "filters_bypass": []"

### ISSUE THREAD

**Issue by balubollam** [floragunncom/search-guard#67]
Hi everyone 

As i am new to Searchguard elasticsearch i am unable to grap the priority or execution of "filters_bypass": []". Is it for default or for the existing

Please see this index for clear understanding

My index:
curl -XPUT 'http://localhost:9200/searchguard/ac/ac?pretty' -d '
{"acl": [
    {
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": [],
      "filters_execute": []
    },
{
      "__Comment__": "This means any user with the role starfleet or command can do anything with the starfleetinfos index",
      "roles" : ["starfleet", "command"],
      "indices": ["starfleetinfos"],
      "filters_bypass": ["actionrequest.write"],
      "filters_execute": ["actionrequestfilter.read"]
    },

Now which one of  ""filters_bypass": []," will execute ??.......or the "filters_bypass":["actionrequest.write"], ?.,,,,,,please help me out in this??...

And my elasticsearch,yml is here

searchguard.actionrequestfilter.names: ["read","write"]
searchguard.actionrequestfilter.read.allowed_actions: ["indices:data/read/*", "*monitor*"]
searchguard.actionrequestfilter.read.forbidden_actions: ["cluster:*", "indices:admin*"]
searchguard.actionrequestfilter.write.allowed_actions: ["indices:data/write/*", "*monitor*"]

and actually what this "searchguard.actionrequestfilter.read.forbidden_actions: ["cluster:*", "indices:admin*"]" will do?

Thanks and Regards
Balaji

**Comment by gugansankar** [comment]
What you are expecting here ?. Its so hard to explain without knowing your expectation. Even, your elasticsearch.yml file is not configured perfectly.

For understanding the configuration settings, please refer the Readme file , that give some example configuration and explanations.

**Comment by balubollam** [comment]
Hi Thank u for quick reply..
Actually i am expecting is "readonly functionality to the user for the particular index"..
That working fine without kibana...
But when i add Kibana

Case1:
KIbana giving “RuntimeException” due to no default bypass and execute filters becuase the default configiration is
"filters_bypass": [],
filters_execute": []
Now by replacing this to
"filters_bypass": ["actionrequestfilter.readonlyuser"],
"filters_execute": []
and giving same usernames and password in elasticsearch.yml and kibana.yml
Kibana is working fine For Admin role and Readonly users…
But not working for the readonly specific indices when i replace the default configuration…

Here is my updated config index:
curl -XPOST -u admin:admin 'http://localhost:9200/searchguard/ac/ac' -d '
{
"acl": [
{

"Comment":Default”,
"filters_bypass": ["actionrequestfilter.readonlyuser"],
"filters_execute": []
},

{
"Comment": "For user agent1 only “ind” index operations should be performed",
"users": [
"agent1"
],
"indices": [
"Ind"
],
"filters_bypass": [],
"filters_execute":["actionrequestfilter.readonlyuser"]
},
}

Now here comes the problem is that the user “agent1” actually should only read the index “ind” but reading and writing all the indices
*BUT when we replace the “ind” with “” then it is reading the all indices but not writing the indices..
Please help me How to perform read only on particular index without keeping default empty(Because kibana is giving exception if default is empty)...

here is My elasticsearch.yml file
searchguard.authentication.settingsdb.user.agent2:pswd
searchguard.actionrequestfilter.readonlyuser.allowed_actions:["indices:admin/get","indices:data/read/", "monitor"]

*here is my kibana.yml
searchguard.enabled: true
kibana_elasticsearch_username: agent2
kibana_elasticsearch_password: pswd

Case2:
Here if i give default configuration "filters_execute": [“*”]
THen kibana is giving “internal server error”

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
