### ISSUE TITLE
Logstash indexes always empty in Travis CI

### ISSUE THREAD

**Issue by antoineco** [floragunncom/search-guard#670]
#### Environment

* **Search Guard and Elasticsearch version**: 24.3 / 6.7.0 (but affected since at least since 6.0.0)
* **JVM version and operating system version**: OpenJDK  11.0.1 / CentOS 7 (official [image](https://github.com/elastic/elasticsearch-docker/blob/master/.tedi/tedi.yml))
* **Number of nodes in your cluster**: 1

#### Description of the bug

As part of our automated tests, over at [deviantony/docker-elk](https://github.com/deviantony/docker-elk/tree/searchguard), we execute a series of HTTP requests in order to assert that a document can get created properly all the way from Logstash to Elasticsearch after running `init_sg`:

_1. send something to Logstash over the TCP input_
```console
$ echo 'dockerelk' | nc localhost 5000
```
_2. refresh all indexes_
```console
$ curl -s -XPOST 'http://localhost:9200/_refresh' -u admin:admin
{"_shards":{"total":12,"successful":7,"failed":0}}
```
_3. search for the document_
```console
$ curl -s 'http://localhost:9200/_count?q=message:dockerelk' -u kibanaro:kibanaro
{"count":1,"_shards":{"total":7,"successful":7,"skipped":0,"failed":0}}
```

While everything works locally (also in Docker), this last command doesn't return any result inside the Ubuntu Trusty environment provided by [Travis CI](https://travis-ci.org) (see [job 285](https://travis-ci.org/deviantony/docker-elk/builds/515634008), and especially the [line 602](https://travis-ci.org/deviantony/docker-elk/builds/515634008#L602)).

The reason why I report this here is that the exact same test works fine 100% of the time when Search Guard is not installed, with both the OSS and X-Pack flavours of the Elastic stack (see the [expected output](https://travis-ci.org/deviantony/docker-elk/builds/515637647#L492)).

Any gut feeling regarding that issue and how Search Guard in particular may affect the indexes in that particular environment?

**Comment by floragunncom** [comment]
Can you change 
```curl -s -XPOST 'http://localhost:9200/_refresh' -u admin:admin```
to something like
```curl -s -XPOST 'http://localhost:9200/_refresh' -u admin:admin -vvv --fail``` followed by
```curl -s 'http://localhost:9200/_count?q=message:dockerelk' -u kibanaro:kibanaro -vvv --fail```
and display the result (not swallowing it) so that we can see what is really happening? Maybe a permissions issue? But its strange that its only happening on travis and not local.

**Comment by antoineco** [comment]
Sure, here is the full result: [job 288](https://travis-ci.org/deviantony/docker-elk/builds/515692892)
The test script can be seen here: [.travis.yml](https://github.com/deviantony/docker-elk/blob/troubleshoot-sg-test/.travis.yml#L22-L38)

**Comment by floragunncom** [comment]
To be honest i have no idea right now. The only thing i can think of is a timing issue so that ```echo 'dockerelk' | nc localhost 5000``` is executed in a stage where SG is not yet initialized. Maybe we narrow down the issue my issuing a normal index request via curl directly to elastic instead. If that works then at least its clear that the issue is somehow logstash related.

**Comment by antoineco** [comment]
I added the following steps to the test suite as suggested: https://github.com/deviantony/docker-elk/commit/aba8646de84f02980b1dd775d7b6f641485c0d35
I indeed get a hit in Travis ([job 290](https://travis-ci.org/deviantony/docker-elk/jobs/516362453#L637)) so you were right, something's fishy with Logstash.

I raised the log level of Logstash's Elasticsearch output but the last messages I see do not provide any valuable information: [job 292](https://travis-ci.org/deviantony/docker-elk/builds/516371206#L988-L999)

Thanks for your time and pointers so far! I'll keep digging on my side 👍
