### ISSUE TITLE
Non-resolvable parent POM for com.floragunn:search-guard-6:6.2.4-22.3: Could not transfer artifact com.floragunn:search-guard-parent:pom:6.20.0 from/to central 

### ISSUE THREAD

**Issue by yongge666** [floragunncom/search-guard#671]
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/com/floragunn/search-guard-parent/6.20.0/search-guard-parent-6.20.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.floragunn:search-guard-6:6.2.4-22.3: Could not transfer artifact com.floragunn:search-guard-parent:pom:6.20.0 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and 'parent.relativePath' points at wrong local POM @ line 13, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.floragunn:search-guard-6:6.2.4-22.3 (E:\Java\project\esPlugin\search-guard\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.floragunn:search-guard-6:6.2.4-22.3: Could not transfer artifact com.floragunn:search-guard-parent:pom:6.20.0 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and 'parent.relativePath' points at wrong local POM @ line 13, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Process finished with exit code 1

**Comment by jochenkressin** [comment]
@salyh this does not look like an error on our side, does it?

**Comment by floragunncom** [comment]
No, this looks like a maven central issue or a misconfigured proxy. The pom is there: https://repo.maven.apache.org/maven2/com/floragunn/search-guard-parent/6.20.0/search-guard-parent-6.20.0.pom

@yongge666 Please just try again
