### ISSUE TITLE
URL Parsing issue with multi-tenancy

### ISSUE THREAD

**Issue by Guruhbk** [floragunncom/search-guard#672]
I have a tenant name **$kedler&_#test**. A new index is created without special character(**kedletest**) and index is working fine. But the problem is when i tried to hit a visualization with **sgtenant=$kedler&_#test**, it is not working. I tried removing special characters, and it still doesn't work. 

URL:http://localhost:5601/app/kibana?sgtenant=$kedler&_#test#/visualize/edit/919f5810-55ff-11e7-a198-5f6d82ac1c15?_g=()

**Comment by floragunncom** [comment]
@jochenkressin @mgustafsson1 canyou have a look pls?

**Comment by Guruhbk** [comment]
@floragunncom @jochenkressin  Any update?

**Comment by mgustafsson1** [comment]
@Guruhbk I've tested this and the problem is that the characters are not great for URLs, especially & and #. Kibana interprets those as parts of the URL.
If you replace **$kedler&_#test** with **%24kedler%26_%23test**, it should work.

I'll investigate if we can add this to the share panel, so that tenant names are always URL safe.

**Comment by Guruhbk** [comment]
@mgustafsson1 I tried that. It is working on one case. If the kibana is already authenticated, it is working fine. If the kibana is not authenticated, It didn't work. 
1. This is my URL - **http://localhost:5601/app/kibana?sgtenant=%24kedler%26_%23test#/dashboard/2b9d8150-5c37-11e9-bb49-65b8efeda32a?_g=(time:(from:%272019-04-03T05:44:40.000Z%27,mode:absolute,to:%272019-04-23T05:44:40.000Z%27))&_a=(filters:!(),query:(language:lucene,query:%27*%27))**
2. I'm hitting the URL in incognito. The URL changed like this. **http://localhost:5601/login?nextUrl=%2Fapp%2Fkibana%3Fsgtenant%3D%2524kedler%2526_%2523test#/dashboard/2b9d8150-5c37-11e9-bb49-65b8efeda32a?_g=(time:(from:%272019-04-03T05:44:40.000Z%27,mode:absolute,to:%272019-04-23T05:44:40.000Z%27))&_a=(filters:!(),query:(language:lucene,query:%27*%27))**
 3. I'm using my credentials and logging in. It somehow changed like this. - **http://localhost:5601/app/kibana?sgtenant=$kedler#/home?_g=()#%2Fdashboard%2F2b9d8150-5c37-11e9-bb49-65b8efeda32a%3F_g=(time:(from:'2019-04-03T05:44:40.000Z',mode:absolute,to:'2019-04-23T05:44:40.000Z'))&_a=(filters:!(),query:(language:lucene,query:'*'))**

Instead of showing the dashboard page, it shows me the home page.

**Comment by mgustafsson1** [comment]
@Guruhbk Good catch! There's a lot of encoding/decoding going on there... I'll look into that too. Thanks!

**Comment by Guruhbk** [comment]
@mgustafsson1 Can you please let me know the ETA for this fix?

**Comment by mgustafsson1** [comment]
@Guruhbk Sorry for the delay on this, it was a bit more complicated than expected. I'll try to give you an update in the next couple of days.

**Comment by mgustafsson1** [comment]
This fix has been released for versions 6 and 7. Here are the release notes:
https://docs.search-guard.com/latest/changelog-kibana-7.x-35_1_0
https://docs.search-guard.com/6.x-25/changelog-kibana-6.x-18.4

**Comment by Guruhbk** [comment]
@mgustafsson1 Thank you for the update. Will check it.
