### ISSUE TITLE
"Runtime Exception" and "internal server Exception" while using searchguard with kibana

### ISSUE THREAD

**Issue by balubollam** [floragunncom/search-guard#68]
Hi all
When i am using searchguard elasticsearch with kibana getting errors
[Actually what iam tring to do is "readonly functionality to the particular user on the particular index"]

Please have a look on below 2cases
Case1:
KIbana giving “RuntimeException” due to no default bypass and execute filters becuase 
The default configiration is
"filters_bypass": [],
filters_execute": []
Now by replacing this to
"filters_bypass": ["actionrequestfilter.readonlyuser"],
"filters_execute": []
and giving same usernames and password in elasticsearch.yml and kibana.yml
Kibana is working fine For Admin role and Readonly users…
But not working for the readonly specific indices when i replace the default configuration…

Here is my updated config index:
curl -XPOST -u admin:admin 'http://localhost:9200/searchguard/ac/ac' -d '
{
"acl": [
{

"Comment":Default”,
"filters_bypass": ["actionrequestfilter.readonlyuser"],
"filters_execute": []
},

{
"Comment": "For user agent1 only “ind” index operations should be performed",
"users": [
"agent1"
],
"indices": [
"Ind"
],
"filters_bypass": [],
"filters_execute":["actionrequestfilter.readonlyuser"]
},
}

Now here comes the problem is that the user “agent1” actually should only read the index “ind” but reading and writing all the indices
*BUT when we replace the “ind” with “” then it is reading the all indices but not writing the indices..
Please help me How to perform read only on particular index without keeping default empty(Because kibana is giving exception if default is empty)...

here is My elasticsearch.yml file
searchguard.authentication.settingsdb.user.agent2:pswd
searchguard.actionrequestfilter.readonlyuser.allowed_actions:["indices:admin/get","indices:data/read/", "monitor"]

*here is my kibana.yml
searchguard.enabled: true
kibana_elasticsearch_username: agent2
kibana_elasticsearch_password: pswd

Case2:
Here if i give default configuration "filters_execute": [“*”]
THen kibana is giving “internal server error”

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
