### ISSUE TITLE
${user.roles}: "Unrecognized token '$'"

### ISSUE THREAD

**Issue by theuppercase** [floragunncom/search-guard#688]
## Version
* ES: 6.3.2
* SG: 24.0
* JAVA: 1.8.0_51
* OS: debian 8.11

Nodes in cluster: 1

## Description
I'm using Proxy Authentication to gather user and roles via the 'x-proxy-user' and 'x-proxy-roles' header fields. 
Then I tried to filter my search results via the Document-Level-Security (DLS) query (from your website):

    _dls_: '{"term" : {"manager" : "${user.name}"}}'

which worked as expected.

### The Error:

As I need to match results to a user's role rather than to it's name, I tried to use the ${user.roles} variable as you described in your Documentation:

    _dls_: '{"terms" : { "role" : [${user.roles}]}}'

With applied configuration, every query (using this role) now returns this error:

    {
      "error": {
        "root_cause": [
          {
            "type": "exception",
            "reason": "failed to wrap searcher"
          }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
          {
            "shard": 0,
            "index": "humanresources",
            "node": "innioX6hQXuZd0J-BjMB0w",
            "reason": {
              "type": "exception",
              "reason": "failed to wrap searcher",
              "caused_by": {
                "type": "i_o_exception",
                "reason": "java.util.concurrent.ExecutionException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token '$': was expecting ('true', 'false' or 'null')\n at [Source: java.io.StringReader@779d77ae; line: 1, column: 29]",
                "caused_by": {
                  "type": "execution_exception",
                  "reason": "com.fasterxml.jackson.core.JsonParseException: Unrecognized token '$': was expecting ('true', 'false' or 'null')\n at [Source: java.io.StringReader@779d77ae; line: 1, column: 29]",
                  "caused_by": {
                    "type": "json_parse_exception",
                    "reason": "Unrecognized token '$': was expecting ('true', 'false' or 'null')\n at [Source: java.io.StringReader@779d77ae; line: 1, column: 29]"
                  }
                }
              }
            }
          }
        ]
      },
      "status": 500
    }

"Unrecognized token '$'" seems like SG does not translate the variable "${user.roles}".
I am not completely sure, if this is a bug, or I just missed something here.

**Comment by floragunncom** [comment]
Are you really sure you run SG v24.0 or later? This error message is expected for versions before v24.0 because the feature was introduced with v24.0.

**Comment by theuppercase** [comment]
I'm sorry! 
Was so sure using v24 that I did not check it again before writing.
After upgrading it now works perfectly!

Thanks for your quick response.
