### ISSUE TITLE
Links incorrect in latest versions for SG6

### ISSUE THREAD

**Issue by cheald** [floragunncom/search-guard#693]
The docs with the latest versions matrix at https://docs.search-guard.com/6.x-25/search-guard-versions use incorrect URLs for the SG6 packages.

The 6.7.2 release, for example, links to:

* https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-7/6.7.2-25.0/search-guard-7-6.7.2-25.0.zip

but this URL is a 404. The correct URL for it should be:

* https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-6/6.7.2-25.0/search-guard-6-6.7.2-25.0.zip

(search-guard-6 vs search-guard-7)

The artifact name likewise specifies `com.floragunn:search-guard-7` which results in a 404 when attempting to install via normal install procedures, unless you correct the artifact name to search-guard-6.

**Comment by jochenkressin** [comment]
Thanks much for pointing this out. Seems like a merge error while preparing SG7 GA. Links have been corrected.
