### ISSUE TITLE
Kibana Discover: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Alsheh** [floragunncom/search-guard#695]
After session expires, Kibana throws this error:
![Screen Shot 2019-05-08 at 3 25 30 PM](https://user-images.githubusercontent.com/16920445/57412602-0c840800-71a6-11e9-9f96-398e25692829.png)

ES: `6.7.1`
Kibana: `6.7.1`
SG: `25.0`
SG Kibana plugin: `18.3`

***Steps to reproduce:***
1. Leave a browser open on an idle Kibana Discover page until session expires.
2. When session expires and without refreshing the page, click any element that would redirect to a different page.

**Comment by jochenkressin** [comment]
@mgustafsson1 can you investigate please?

**Comment by mgustafsson1** [comment]
@jochenkressin Will do!
