### ISSUE TITLE
Kibana Did Not Load Properly

### ISSUE THREAD

**Issue by Alsheh** [floragunncom/search-guard#698]
This error started to come up a lot recently:
![Screen Shot 2019-05-10 at 11 25 40 AM](https://user-images.githubusercontent.com/16920445/57548995-39a3f800-7317-11e9-865b-b09a84ff4b60.png)

Kibana server logs show 300 status code for `GET` requests with the following path patterns:
1. `GET /built_assets/<resource-path> 304`
2. `GET /bundles/<resource-path> 304`
3. `GET /translations/<resource-path> 304`
4. `GET /ui/fonts/<resource-path> 304`

NOTE: SG is used with basic license and Kibana Spaces is enabled. Also, there is a load balancer between Kibana and the browser with 5 min idle timeout.

ES: `6.7.1`
Kibana: `6.7.1`
SG: `25.0`
SG Kibana plugin: `18.3`

**Comment by floragunncom** [comment]
@jochenkressin @mgustafsson1 can you have a look?

**Comment by jochenkressin** [comment]
To me, this does not seem to be related to Search Guard.

In the screenshot, the error is related to loading Kibana internal assets, like a CSS file from the tiles map plugin. A gateway timeout usually means that the load balancer is not configured correctly.

@Alsheh : Can you please check that the assets that cannot be loaded (the index.css of the tiles map plugin in the screenshot above) are accessible when requesting them via the load balancer?

**Comment by Alsheh** [comment]
@jochenkressin thanks the follow up! Yes, this issue seems be related to the load balancer as it can be observed with large idle timeout and less frequently with a small idle timeout.
