### ISSUE TITLE
Kibana Redirect To Wrong Page After Re-login

### ISSUE THREAD

**Issue by Alsheh** [floragunncom/search-guard#699]
When a user session expires in a non-default Kibana Space, the user refreshes the page and re-logins but the user doesn't get redirected to the original Kibana Space; instead, the user gets redirected to the default Kibana Space where the user may not have access and, as a result, security exceptions are thrown. It may take the user some time before realizing that s/he was redirected to a different Kibana Space. Ideally, when a session expires and a user re-logins, the user should be redirected to the same Kibana Space before the expired session while preserving previous search settings.

**Comment by mgustafsson1** [comment]
@Alsheh Thanks for reporting this! Will investigate!
