### ISSUE TITLE
Failed To Upload Config On Busy Node

### ISSUE THREAD

**Issue by Alsheh** [floragunncom/search-guard#701]
Failed to upload `sgconfig` because SG primary shard happened to be on a busy node:
```
   FAIL: Configuration for 'config' failed because of org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of processing of [34088901][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[searchguard][0]] containing [index {[searchguard][sg][config], source[n/a, actual length: [3.2kb], max length: 2kb]}] and a refresh, target allocation id: awbX-tSpQG6Tymfly0UqvA, primary term: 1 on EsThreadPoolExecutor[name = es-busy-node/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@33053b81[Running, pool size = 1, active threads = 1, queued tasks = 201, completed tasks = 12481003]]
```
I tried to move the SG primary shard to a less busy node using the ES API but I get this error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "no permissions for [] and User [name=admin, roles=[admin], requestedTenant=null]"
      }
    ],
    "type": "security_exception",
    "reason": "no permissions for [] and User [name=admin, roles=[admin], requestedTenant=null]"
  },
  "status": 403
}
```

and the `sgadmin` tool does not seem to allow for a culster-level shard allocation filtering. I think it is necessary to have the ability to apply shard allocation filtering to the SG index either by the ES API or by the `sgadmin` tool.

**Comment by floragunncom** [comment]
You always can use curl with the same certificates you use for sgadmin to allow any operation. Should then look like `curl -Ss https://eshost:9200/<api> --cert /path/to/admincert.epm --key /path/to/adminkey.pem --cacert /path/to/root-ca.pem`

See also 

* https://docs.search-guard.com/latest/troubleshooting-tls#fixing-curl
* https://github.com/floragunncom/search-guard/issues/272
* https://search-guard.com/elasticsearch-client-certificate-authentication/

**Comment by Alsheh** [comment]
@floragunncom thanks! That's what I was looking for.
