### ISSUE TITLE
Hiding indexes to which user does not have access.

### ISSUE THREAD

**Issue by serhik** [floragunncom/search-guard#702]
I think it would be nice to hide indexes to which user does not have access. Now when the user is authorized in the kibana -> Discover, he sees all the indexes, but when he selects the index to which there is no access, he receives a warning Discover: no permissions for [indices:data/read/search] and User [name=my_user, roles=[], requestedTenant=null]

**Comment by floragunncom** [comment]
Set `do_not_fail_on_forbidden: true` in sg_config.yml like described here: https://docs.search-guard.com/latest/kibana-plugin-installation#configuring-elasticsearch-enable-do-not-fail-on-forbidden
