### ISSUE TITLE
Unable to install SG 6.6.0-25.3

### ISSUE THREAD

**Issue by AnisHAIL** [floragunncom/search-guard#720]
Hi,
I have some diffculty to install SG 6-6.6.0-25.3, the command line **/usr/share/elasticsearch/bin/elasticsearch-plugin install -b com.floragunn:search-guard-6:6.6.0-25.3** returns the error : 

Downloading com.floragunn:search-guard-6:6.6.0-25.3 from maven central
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/floragunn/search-guard-6/6.6.0-25.3/search-guard-6-6.6.0-25.3.zip....

When I try to download the zip from : https://docs.search-guard.com/6.x-25/search-guard-versions , I have also an 404 not found 

thanks you for the feedback
ES 6.6.0

**Comment by floragunncom** [comment]
Thanks for letting us know. The download links have been corrected: https://docs.search-guard.com/6.x-25/search-guard-versions
