### ISSUE TITLE
Need help for configuring indices & Document (DLS) level security on ELK

### ISSUE THREAD

**Issue by SaketKum** [floragunncom/search-guard#73]
Pushing all logs in single ES index; each log distinguish each other by a field name "Project". On Kibana I have created a Dashboard; which contains visualizations. I wish to restrict Kibana users to view only their project related data on dashboard. 

Also in some cases i will have users to restrict only for particular indices. I read the READ ME and tried to configure my own but didn't get success. Any help in this regard is much appreciated.

Please guide me experts!

**Comment by jayeshdhamechai** [comment]
Document level filters work on fields which are explicitly marked as not_analyzed. You might want to check your field mappings and update them if you want to use DLF.

Dashboards are stored in .kibana index. If you want to filter out kibana dashboards on the basis of its title, you will have to first update the dashboard mapping ( before creating your any dashboards). Then you can set up document level filters.

For restricting access to indices, action filters will work.. i think kibana does msearch/mget and not get/search to get the data for the visualizations/dashboards. So your filters need to be written accordingly

**Comment by SaketKum** [comment]
Thanks Jayesh!

I have following config:

elasticsearch.yml:
#############################################################################################
#                                       SEARCH GUARD                                        #
#                                       Configuration                                       #
#############################################################################################
searchguard.enabled: true
searchguard.check_for_root: false
searchguard.key_path: /etc/elasticsearch/
#searchguard.allow_all_from_loopback: true
searchguard.http.xforwardedfor.header: DUMMY

searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend
searchguard.authentication.authentication_backend.cache.enable: false
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator
searchguard.authentication.authorizer.cache.enable: false
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator

searchguard.authentication.settingsdb.user.root: passwd111
searchguard.authentication.settingsdb.user.kibana: passwd222
searchguard.authentication.settingsdb.user.logstash: passwd333
searchguard.authentication.settingsdb.user.admin: passwd444
searchguard.authentication.settingsdb.user.user: passwd555

searchguard.authentication.authorization.settingsdb.roles.root: ["root"]
searchguard.authentication.authorization.settingsdb.roles.kibana: ["kibana"]
searchguard.authentication.authorization.settingsdb.roles.logstash: ["logstash"]
searchguard.authentication.authorization.settingsdb.roles.admin: ["admin"]
searchguard.authentication.authorization.settingsdb.roles.user: ["user"]

searchguard.actionrequestfilter.names: ["kibana-server", "kibana-user", "kibana-admin", "logstash-server", "logstash-user"]
searchguard.actionrequestfilter.kibana-server.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/create*",
  "indices:admin/exists*",
  "indices:admin/mapping/put*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/refresh*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*",
  "indices:data/write/delete*",
  "indices:data/write/index*",
  "indices:data/write/update*"
]
searchguard.actionrequestfilter.kibana-user.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/exists*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*"
]
searchguard.actionrequestfilter.kibana-admin.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/exists*",
  "indices:admin/mapping/put*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/refresh*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*",
  "indices:data/write/delete*",
  "indices:data/write/index*",
  "indices:data/write/update*",
  "indices:admin/create*"
]
searchguard.actionrequestfilter.logstash-server.allowed_actions: [
  "indices:admin/template/get*",
  "indices:admin/template/put*",
  "indices:admin/create*",
  "indices:data/write/bulk*",
  "indices:data/write/index*",
  "indices:data/write/delete*",
  "indices:data/write/update*",
  "indices:data/read/search*",
  "indices:data/read/scroll*"
]
searchguard.actionrequestfilter.logstash-user.allowed_actions: [
  "indices:admin/mappings/fields/get*",
  "indices:admin/validate/query*",
  "indices:data/read/search*",
  "indices:data/read/msearch*",
  "indices:admin/get*"
]

searchguard.dlsfilter.names: ["logstash-user","index-pattern"]
searchguard.dlsfilter.dashboard: ["term", "Project","Amway", "false"]
searchguard.dlsfilter.index_pattern: ["term", "index-pattern","logstash-*", "false"] 

ACL: 

curl -XPUT "http://localhost:9200/searchguard/ac/ac" -d '{
    "acl": [
    {
        "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
        "filters_bypass": [],
        "filters_execute": []
    },
    {
        "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
        "roles": ["root"],
        "filters_bypass": ["*"],
        "filters_execute": []
    },
    {
        "__Comment__": "For role *kibana* executed filter *kibana-server*.",
        "users": ["kibana"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-server"]
    },
    {
        "__Comment__": "For role *logstash* executed filter *logstash-server*.",
        "users": ["logstash"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-server"]
    },
    {
        "__Comment__": "For role *admin* executed filter *kibana-admin*.",
        "roles": ["admin"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-admin"]
    },
    {
        "__Comment__": "For role *user* executed filter *kibana-user*.",
        "roles": ["user"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-user", "dls.dashboard"]
    },
    {
        "__Comment__": "For role *admin* executed filter *logstash-user*.",
        "roles": ["admin"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-user","dlsfilter.dashboard","dlsfilter.index_pattern"]
    },
    {
        "__Comment__": "For role *user* executed filter *logstash-user*.",
        "roles": ["user"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-user", "dlsfilter.dashboard","dlsfilter.index_pattern"]
    }
    ]
}'


####
Above config seems not working.

**Comment by SaketKum** [comment]
Using above config when I try with "user" getting exception...
Courier Fetch Error: unhandled error Error: RuntimeException[java.lang.RuntimeException: Action 'indices:data/read/msearch' is forbidden due to DEFAULT]; nested: RuntimeException[Action 'indices:data/read/msearch' is forbidden due to DEFAULT];

**Comment by jayeshdhamechai** [comment]
add data/read/msearch as allowed action for user. update your kibana-user filter

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
