### ISSUE TITLE
security configuration reloaded one time per second, is it expected?

### ISSUE THREAD

**Issue by timesgarden** [floragunncom/search-guard#74]
Hi fg,

As titled, is it normal?
![image](https://cloud.githubusercontent.com/assets/3774872/12047252/904cdec8-af03-11e5-829e-424b43de661d.png)

**Comment by timesgarden** [comment]
![snapshot](https://cloud.githubusercontent.com/assets/3774872/12047270/c5136d02-af03-11e5-8db9-fc7d59f69049.png)

**Comment by ersushantsood** [comment]
As per the design of the module and code written in the plugin , it is scheduled to refresh after every second.

**Comment by timesgarden** [comment]
ok, i know that, thank you:)
