### ISSUE TITLE
after install search-guard plugin, how can i use head plugin?

### ISSUE THREAD

**Issue by timesgarden** [floragunncom/search-guard#75]
when i visit head plugin via browser, it just shows:502 Read from server failed: Timeout.

so, how can i use head plugin when search-guard installed?

**Comment by ersushantsood** [comment]
Are you able to install search guard without plugin-descriptor.properties?

**Comment by timesgarden** [comment]
sorry, i didn't get your point. 
i just install search guard using command: bin/plugin --url file:///home/installs/elasticsearch-1.7.1/search-guard-1.7.3.1-SNAPSHOT.zip --install search-guard

**Comment by timesgarden** [comment]
when i visit http://<host>:<port>/_plugin/head/, the browser popup a login window, and i fill it with admin account, but still failed to open head page. error msg:
{"error":"ClassCastException[com.floragunn.searchguard.http.netty.SessionAwareNettyHttpChannel cannot be cast to org.elasticsearch.http.HttpChannel]","status":500}

**Comment by ersushantsood** [comment]
I thought you were trying to install alpha version of search guard 2.1 .

**Comment by timesgarden** [comment]
i download source code from branch es1.7

**Comment by whateverblake** [comment]
i got the  same error   
{"error":"ClassCastException[com.floragunn.searchguard.http.netty.SessionAwareNettyHttpChannel cannot be cast to org.elasticsearch.http.HttpChannel]","status":500}

**Comment by whateverblake** [comment]
if i set searchguard.http.enable_sessions: false  , then  no errors anymore   ,but   i  can not  see  any audit logs   and the ACL RULE   does not  work  .  ( es1.7.3     searchguard1.7.3.1)

**Comment by pmoosh** [comment]
I have it working with 1.7.3, so that the good news. After I login I get to the kopf gui.
Maybe you can turn on debugging for search guard and check the elasticsearch logs.

Did you setup ssl as well?

**Comment by tzakrajs** [comment]
@pmoosh You didn't have searchguard.http.enable_sessions enabled. This is still a bug that breaks interoperability with virtually all elasticsearch plugins.

While having searchguard.http.enable_sessions disabled can be viewed as a work-around, search-guard will authenticate and authorize users repeatedly using the backend plugin you have configured. In my case, this means hundreds-thousands of LDAP requests per second.

Please fix this bug by inspecting the channel type of the destination plugin before attempting to cast the existing channel or by failing back to non-session http.

**Comment by floragunncom** [comment]
will fix this for SG 2

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
