### ISSUE TITLE
search-guard authorization   error  when use java scroll api

### ISSUE THREAD

**Issue by whateverblake** [floragunncom/search-guard#78]
when i  use Client.prepareSearchScroll api   i    get a authorization error even  though i  have permissions to this index,   when i  check  the log info  i find that   Actionrequestfilter  deny  client request because client try to request index *  ,actually * is not the index i want to search, where is * come from ? i found that prepareSearchScroll  can not specify indexname ,  when  searchguard can not get index name from client request  then index name will be * , so  i have to modify source code add scroll_index to specify the index name that i want to search  like this 'client.prepareSearchScroll(scrollid).putHeader("scroll_index","myIndex")' , does this is a search-guard bug

**Comment by whateverblake** [comment]
if(request instanceof SearchScrollRequest){
        	
         	log.debug("-----index is a  scrollrequest---");
        	SearchScrollRequest sr = (SearchScrollRequest)  request ;
            String scrollIndex = sr.getHeader("scroll_index") ;
            if(scrollIndex != null ){
            	log.debug("scroll index is -------------{}---------", scrollIndex);
            	ci.add(scrollIndex);
            }
        }

**Comment by XDestination** [comment]
Having a similar issue. Only possibility to solve it was to allow access to all indexes.

**Comment by floragunncom** [comment]
good catch, will investigate that for Search Guard 2

**Comment by floragunncom** [comment]
``indices:data/read/scroll`` is now a cluster permission

<pre>
sg_role_starfleet:
  cluster:
    - 'cluster:monitor*'
    - indices:data/read/scroll
  indices:
    ...
</pre>

But yes, its just another way of expressing that this is needed for all indices. But thats not a problem cause you need to know the scrollid.
