### ISSUE TITLE
Dose the search-guard is available for ES 2.1.1 

### ISSUE THREAD

**Issue by tianzongqi** [floragunncom/search-guard#84]
My ES version is 2.1.1, when i settled the search-guard plugin  by the "bin/plugin install com.floragunn/search-guard-ssl/2.1.0.2" , the result tell me can not successfully DONE. 

the result information is:
ERROR: Plugin [search-guard-ssl] is incompatible with Elasticsearch [2.1.1]. Was designed for version [2.1.0]

this means there is not right version of search-guard for ES 2.1.1 ???

**Comment by floragunncom** [comment]
There is also a version for 2.1.1, pls see https://github.com/floragunncom/search-guard-ssl/tree/2.1.1
<pre>
sudo bin/plugin install com.floragunn/search-guard-ssl/2.1.1.4
</pre>

**Comment by tianzongqi** [comment]
ok thank you !  i will try this for testing.

**Comment by athuljayaraj** [comment]
@floragunncom Will search-guard-2(currently alpha) plugin be ES 2.1.1 compliant(currently not)?

**Comment by tianzongqi** [comment]
@floragunncom  is there right version of search-guard for ES 2.1.1 ?  My above question only means search-guard-ssl, but i also want to use the search-guard for my ES 2.1.1.  thank you

**Comment by floragunncom** [comment]
Search Guard 2 Alpha-2 is now also available for ES 2.1.1
https://github.com/floragunncom/search-guard/tree/2.1.1

**Comment by floragunncom** [comment]
Pls. look also on our new Twitter account for updates or send us a tweet/DM if you have questions: https://twitter.com/searchguard
