### ISSUE TITLE
SSO Authentication

### ISSUE THREAD

**Issue by athuljayaraj** [floragunncom/search-guard#88]
Does searchguard support SSO authentication?

**Comment by djtecha** [comment]
I believe you have to run nginx in the front of it. I'm in the process of trying to figure out how to get it to pass the authorization.

**Comment by floragunncom** [comment]
A dedicated Backend for CAS or similar is not yet planned (we appreciate contributions here) but with the upcoming ProxyAuthentication Backend this should be possible. See https://github.com/floragunncom/search-guard/issues/100

**Comment by floragunncom** [comment]
closed as duplicate of #100
