### ISSUE TITLE
AD functionality broken?

### ISSUE THREAD

**Issue by fancyman7** [floragunncom/search-guard#9]
Based on the configs provided for LDAP/AD auth, it appears the functionality doesn't work properly.  I keep on getting an error that [No {username] found]. If i'm wrong, it would be great to add additional debug information to help diagnose the issue or better documentation (maybe a sample config).  

I've also tried to use a demo LDAP server to test (http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/) just to confirm there were no issue on my side.  I've had no luck with this one either.

**Comment by floragunncom** [comment]
Can you pls. post (or mail) the elasticsearch.log file on debug level?

The LDAP stuff is know to be working with AD and OpenLDAP.
Pls try the following configuration for AD:

```
searchguard.authentication.ldap.usersearch: "(sAMAccountName={0})"
searchguard.authentication.authorization.ldap.rolesearch: "(member={0})" 
searchguard.authentication.authorization.ldap.rolename: "cn"
```

**Comment by fancyman7** [comment]
False alarm. These configurations for AD helped alot.  I've got it working now.  Thanks!
