### ISSUE TITLE
How do you pass credentials in java clinet

### ISSUE THREAD

**Issue by gem360** [floragunncom/search-guard#91]
Hi,

How do you pass the user credentials in a java client. 

for Shield it is something like

TransportClient client = TransportClient.builder()
    .settings(Settings.builder()
        .put("cluster.name", "yourcluster")
        .put("shield.user", "youruser:yourpassword")
        .put("plugin.types", "org.elasticsearch.shield.ShieldPlugin")
        ...
        .build())

But what is the equivalent in searchguard ?

**Comment by maximus2situation** [comment]
Hey @g1ylb did you find a way to do it? I have the same issue

**Comment by g1ylb** [comment]
Hi,
No never did find out. I ended up using the read only plugin with a white list of IPs that could write. Adequate for my purposes.

**Comment by floragunncom** [comment]
For Search Guard 2 look here https://github.com/floragunncom/search-guard/blob/2.2/src/test/java/com/floragunn/searchguard/SGTests.java#L540 - docs will follow soon

Regading Search Guard 1 (for ES 1.x) pls read https://groups.google.com/d/msg/search-guard/_rfXnjijE3M/pRkgchGiBQAJ

**Comment by paul58914080** [comment]
Isn't there an interceptor which can add this information. If you have a lot of repository calls then adding putHeader would be a pain.

**Comment by floragunncom** [comment]
This is answered here: https://github.com/floragunncom/search-guard/issues/53#issuecomment-217019746

There is no username:password login possible with transport client. Authentication is done via mutual SSL and optionally impersonation as an other user is possible. IMHO it makes no sense to logon with a plaintext password here.
