### ISSUE TITLE
OID value question

### ISSUE THREAD

**Issue by vroomvroomvroom** [floragunncom/search-guard#92]
Hey floragunn et al:

Do I HAVE to use your OID value, or can I generate my own?
eg, so long as they all agree (eg certs used for search-guard-ssl and for search-guard, I can use any OID value (1.9.3.1.3.2 or any other arbitrary unassigned OID should work), right?  or am I always tied to :  oid:1.2.3.4.5.5  and that's it?  I don't see anything in the code other than a check for the OID, so I would presume that I can use any value, wanted a confirmation.
I figured I'd ask before I gave it a go, if it won't work I won't waste any time.

Thanks!

**Comment by floragunncom** [comment]
OID is currently hardcoded here: https://github.com/floragunncom/search-guard/blob/2.2/src/main/java/com/floragunn/searchguard/transport/SearchGuardTransportService.java

**Comment by vroomvroomvroom** [comment]
great thank you!
