### ISSUE TITLE
search-guard will reduce es search performance sharply

### ISSUE THREAD

**Issue by whateverblake** [floragunncom/search-guard#94]
hey guys,  i found search-guard will  reduce es search performance sharply, without search-guard es will  return search results within 5ms ,but with search-guard es need 30ms or even more time to return search results to client. does anybody encounter this issue

**Comment by tzakrajs** [comment]
What do your ACLs look like? (curl http://127.0.0.1/searchguard/ac/ac)
How many indexes do you have? (curl http://127.0.0.1/_status?pretty=yes)
What actionrequestfilters, dlsfilters and flsfilters do you have defined in your elasticsearch.yml? (cat /etc/elasticsearch/elasticsearch.yml)

**Comment by whateverblake** [comment]
acl  is very simple  like this   
    "acl": [



{
"filters_bypass": [ ],
"filters_execute": [
"actionrequestfilter.forbidall"
]
}
,
{
"roles": [
"root"
],
"filters_bypass": [
"*"
],
"filters_execute": [ ]
}
,
{
"aliases": [
"*"
],
"indices": [
"dianping*"
],
"users": [
"lxh08677"
],
"roles": [
"write"
],
"filters_bypass": [
"actionrequestfilter.forbidall"
],
"filters_execute": [
"actionrequestfilter.write"
]
}

**Comment by whateverblake** [comment]
there are 8 indices in es cluster and the biggest index just has 42805 docs ,most of indices just have docs less then 6000

**Comment by whateverblake** [comment]
here is the elasticsearch.yml config about search-guard

searchguard.enabled: true
searchguard.key_path: /home/dpdcadmin/elasticsearcher/elasticsearch17/elasticsearch-1.7.3/config
searchguard.http.enable_sessions: false
searchguard.config_index_name: searchguard
searchguard.allow_all_from_loopback: false
searchguard.transport_auth.enabled: true
searchguard.auditlog.enabled: false
#############################for ldap settings#############################
searchguard.http.enable_sessions: false
searchguard.config_index_name: searchguard
searchguard.allow_all_from_loopback: false
searchguard.transport_auth.enabled: true
searchguard.auditlog.enabled: false
#############################for ldap settings#############################
searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.ldap.LDAPAuthenticationBackend
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.ldap.LDAPAuthorizator
searchguard.authentication.ldap.host: ["10.14.84.130:389"]
searchguard.authentication.ldap.bind_dn:  "cn=Manager,dc=ly,dc=com"
searchguard.authentication.ldap.password: "123456"
searchguard.authentication.ldap.userbase: "ou=users,dc=ly,dc=com"
searchguard.authentication.ldap.usersearch: "(uid={0})"
searchguard.authentication.ldap.username_attribute: "cn"

searchguard.authentication.authorizer.cache.enable: true
searchguard.authentication.authorization.ldap.rolebase: "ou=roles,dc=ly,dc=com"
searchguard.authentication.authorization.ldap.rolesearch: "(cn={0})"
searchguard.authentication.authorization.ldap.userrolename: "carLicense"
searchguard.authentication.authorization.ldap.rolename: "cn"

searchguard.actionrequestfilter.names: ["read"]
searchguard.actionrequestfilter.read.allowed_actions: ["indices:data/read/*"]
searchguard.actionrequestfilter.read.forbidden_actions: ["cluster:*", "indices:admin*"]

searchguard.actionrequestfilter.names: ["write"]
searchguard.actionrequestfilter.write.allowed_actions: ["indices:data/write/*","indices:data/read/*","indices:admin/*"]
searchguard.actionrequestfilter.write.forbidden_actions: ["cluster:*"]

searchguard.actionrequestfilter.names: ["forbidall"]
searchguard.actionrequestfilter.forbidall.allowed_actions: ["indices:monitor/status"]

**Comment by whateverblake** [comment]
@tzakrajs  thanks

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
