### ISSUE TITLE
Permissions are not working

### ISSUE THREAD

**Issue by merito** [floragunncom/search-guard#96]
Hi,

I run ES 2.2.0, SG-ssl 2.2.0.6 and SG 2.2.0.0-alpha2. SG-ssl transport works well, there is an encrypted connection between two nodes. Next I've enabled ssl.http. My sg_internal_users.yml
```
testt:  
  hash: <<hash>>  
  roles:  
    - myadmin  
```
sg_roles.yml
```
my_role:
  cluster:
    - CLUSTER_ALL
  indices:
    '*':
      '*':
        - indices:admin/get
        - indices:data/read/search 
```
sg_roles_mapping.yml
```
my_role:
  backendroles:
    - myadmin
```
sg_config.yml is default from repository. When I try to run (index test1 exists and contains one document)
`curl -XGET 'https://192.168.1.10:9200/test1/_search?pretty=true&q=*:*' -u testt -Ss -k`
I receive
```json
{
  "error" : {
    "root_cause" : [ {
      "type" : "security_exception",
      "reason" : "no permissions for indices:data/read/search"
    } ],
    "type" : "security_exception",
    "reason" : "no permissions for indices:data/read/search"
  },
  "status" : 403
}
```

but as you can see above the indices:data/read/search property is set for this role for all indices. For example this works
`curl -XGET 'https://192.168.1.10:9200/_cluster/health?pretty=true' -u testt -Ss -k`
```json
{
  "cluster_name" : "elasticsearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 46,
  "active_shards" : 87,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```
I'm out of ideas why this doesn't work.

**Comment by floragunncom** [comment]
Weird, can you post the logs (on debug level) and post the output of 

<pre>
curl -XGET 'https://192.168.1.10:9200/_searchguard/authinfo' -u testt -Ss -k
</pre>

**Comment by merito** [comment]
The answer is
```json
{"user":"User [name=testt, roles=[myadmin]]","sg_roles":null,"principal":null,"peer_certificates":"0"}
```

**Comment by floragunncom** [comment]
seems the roles get not mapped properly
<pre>
"sg_roles":null
</pre>

Beside this you have a lot of Exceptions in your logs. Please make sure you have disabled security on both nodes (`security.manager.enabled: false`). Seem also you like to talk plaintext (non ssl) to your first node. Whats missing in the logs is the part where you login in via basic authentication and where roles and permissions are evaluated.

**Comment by merito** [comment]
OK, I've cleaned up my configuration. Now there are no exceptions when transport is enabled, SG-ssl works and SG2 too. Running
`curl -XGET 'https://192.168.1.10:9200/_searchguard/authinfo' -u testt -Ss -k`
response is
```json
{
  "user" : "User [name=testt, roles=[myadmin]]",
  "sg_roles" : null,
  "principal" : null,
  "peer_certificates" : "0"
}
```
so the sg_roles are null but permissions are working, I can refuse access to the selected indices. They are still some problems with indices:admin/... permissions, even if they are granted I've got an exception.
`curl -XGET 'https://192.168.1.10:9200/_aliases?pretty=true' -u testt -Ss -k`
```json
{
  "error" : {
    "root_cause" : [ {
      "type" : "security_exception",
      "reason" : "no permissions for indices:admin/get"
    } ],
    "type" : "security_exception",
    "reason" : "no permissions for indices:admin/get"
  },
  "status" : 403
}
```
the sg_roles.yml
```
my_role:
  cluster:
    - CLUSTER_ALL
  indices:
    '*':
      '*':
        - ALL
```

**Comment by beardedlinuxgeek** [comment]
I'm also having issues with the roles not mapping properly. I'm use all stock config files, except I also added sg_admin to kirk's roles in sg_internal_users.yml

`curl -XGET 'https://localhost:9200/_searchguard/authinfo' -u kirk -Ss -k`

```
{"user":"User [name=kirk, roles=[captains, starfleet, sg_admin]]","sg_roles":null,"principal":null,"peer_certificates":"0"}
```

Here are the logs generated when I make that request:
```
[2016-03-10 12:40:20,355][DEBUG][com.floragunn.searchguard.http.XFFResolver] xff resolve /0:0:0:0:0:0:0:1:57770
[2016-03-10 12:40:20,355][DEBUG][com.floragunn.searchguard.http.XFFResolver] no xff done true,false,class org.elasticsearch.http.netty.NettyHttpRequest,{}
[2016-03-10 12:40:20,356][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] Try to authenticate with authDomain 0, authenticatedUser so far is null
[2016-03-10 12:40:20,356][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] Challenge client with class com.floragunn.searchguard.http.HTTPBasicAuthenticator
[2016-03-10 12:40:20,356][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] Authentication token is: AuthCredentials [username=kirk, password empty=false, nativeCredentials empty=true,backendRoles=[]]
[2016-03-10 12:40:20,356][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] Try to authenticate token with class com.floragunn.searchguard.auth.internal.InternalAuthenticationBackend
[2016-03-10 12:40:20,736][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'User [name=kirk, roles=[captains, starfleet, sg_admin]]' is authenticated
```

When I run

`curl -XGET 'https://localhost:9200/_aliases?pretty=true' -u kirk -Ss -k`

the output is

```json
{
  "error" : {
    "root_cause" : [ {
      "type" : "security_exception",
      "reason" : "no permissions for indices:admin/get"
    } ],
    "type" : "security_exception",
    "reason" : "no permissions for indices:admin/get"
  },
  "status" : 403
}
```

[Here at the logs](https://gist.github.com/beardedlinuxgeek/5c86cccdd710f6ecc13b).

One thing I don't understand is that if I connect to "https://localhost:9200/_searchguard/sslinfo" then I get a response. I assume this means there is an index called _searchguard? But I do:

`https://localhost:9200/_searchguard/_mapping?pretty`

and the output is

```json
{
  "error" : {
    "root_cause" : [ {
      "type" : "index_not_found_exception",
      "reason" : "no such index",
      "resource.type" : "index_or_alias",
      "resource.id" : "sf",
      "index" : "sf"
    } ],
    "type" : "index_not_found_exception",
    "reason" : "no such index",
    "resource.type" : "index_or_alias",
    "resource.id" : "sf",
    "index" : "sf"
  },
  "status" : 404
}
```

[the logs](https://gist.github.com/beardedlinuxgeek/95a6d4bbd21fbbfdacee)

I get that "index_not_found_exception" for every index I try, even when I know it exists. The only time i don't get that error is when I check "_all" because then I get the permissions error instead. I assume this comes down to the roles not mapping properly, but how do I fix it?

**Comment by floragunncom** [comment]
There is now (and basic) vagrant demo available, see https://github.com/floragunncom/search-guard/tree/2.2

**Comment by floragunncom** [comment]
Regarding the issue: Would be great if we can get some logoutput on DEBUG or TRACE level which shows how the PrivilegeEvaluator evaluate the permissions. This should look like https://gist.github.com/floragunncom/317b79309ead63d651d6

**Comment by floragunncom** [comment]
issue still valid with Search Guard 2 Beta 1? https://github.com/floragunncom/search-guard

**Comment by floragunncom** [comment]
fixed with https://github.com/floragunncom/search-guard/commit/ed39bbb242b36701839ec46f64b313b1979d9d04
