### ISSUE TITLE
ES 2.0 Logstash not allowing bulk insert

### ISSUE THREAD

**Issue by djtecha** [floragunncom/search-guard#97]
So, I'm unable to get logstash to add events. I see the following error in the logstash log though:

error"=>{"type"=>"security_exception", "reason"=>"no permissions for indices:data/write/bulk[s]"}}

**sg_roles.yml:
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    'logstash-*':
      '*':
        - indices:data/write/bulk
        - indices:data/write/bulks
        - indices:data/write/delete
        - indices:data/write/update
        - indices:data/read/search
        - indices:data/read/scroll
        - CREATE_INDEX

**sg_internal_users.yml:
logstash:
  hash: $2a$12$94WQ0q
  roles:
    - logstash

**sg_roles_mapping.yml
sg_logstash:
  backendroles:
    - logstash
  users:
    - logstash

I also see the indices being created, just no content is ever added to them.

**Comment by djtecha** [comment]
logstash output:

output {
        elasticsearch {
            hosts => ["127.0.0.1:9200"]
            user => logstash
            password => "test"
            index => "logstash-%{+YYYY.MM.dd}"
        }
}

**Comment by djtecha** [comment]
Figured it out, it was a permissions issue. You need to have `- indices:data/write/bulk\[s\]` in addition to the logstash user.

**Comment by floragunncom** [comment]
see https://github.com/floragunncom/search-guard/blob/2.2/sgconfig/sg_roles.yml#L134  `indices:data/write/bulk` should be sufficient enough.

**Comment by djtecha** [comment]
interesting... maybe I have some odd setup, but without adding that I keep seeing an error in the ES logs and it refused to commit. I'll post the exact log tomorrow.

**Comment by djtecha** [comment]
So it actually shows up in logstash logs:

> @data={"message"=>" Registered Authentication Agent for unix-process:4542:226014155 (system bus name :1.14327 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)", "path"=>"/var/log/secure", "type"=>"system", "@timestamp"=>"2016-03-06T22:37:42.144Z", "program"=>"polkitd", "@Host"=>"corp-estest-2"}, @metadata_accessors=#<LogStash::Util::Accessors:0x1327c7b2 @store={}, @lut={}>, @cancelled=false>], :response=>{"create"=>{"_index"=>"logstash-2016.03.06", "_type"=>"system", "_id"=>"AVNSy2WIXCaQo2xm2EpB", "status"=>403, "error"=>{"type"=>"security_exception", "reason"=>"**no permissions for indices:data/write/bulk[s]**"}}}, :level=>:warn

#Versions 
elasticsearch-2.2.0-1.noarch
logstash-2.1.3-1.noarch

**Comment by EMACz** [comment]
Hi ,

I have configured SearchGuard with Logstash after restarting the elasticsearch service i'll be getting following error continuously,

{:timestamp=>"2017-01-17T11:06:53.090000+0000", :message=>"Failed action. ", :status=>500, :action=>["index", {:_id=>nil, :_index=>"test-2017.01.17", :_type=>"ApacheAccessLog", :_routing=>nil}, #<LogStash::Event:0x62e98428 @metadata_accessors=#<LogStash::Util::Accessors:0x1f94d538 @store={}, @lut={}>, @cancelled=false, @data={"message"=>"10.72.132.161 - \"\" [16/Jan/2017:03:31:24 +0000] \"GET /cdn/sureroute/akamai-sureroute-test-object.htm HTTP/1.0\" 200 8302 \"-\" \"-\"", "@version"=>"1", "@timestamp"=>"2017-01-17T03:41:10.582Z", "type"=>"ApacheAccessLog", "host"=>"web.tack.com", "path"=>"/usr/local/pmc/var/log/httpd/access.log", "tags"=>["_grokparsefailure", "test"], "bubble_name"=>"app1", "application_name"=>"app1"}, @metadata={}, @accessors=#<LogStash::Util::Accessors:0xc842faa @store={"message"=>"10.72.132.161 - \"\" [16/Jan/2017:03:31:24 +0000] \"GET /cdn/sureroute/akamai-sureroute-test-object.htm HTTP/1.0\" 200 8302 \"-\" \"-\"", "@version"=>"1", "@timestamp"=>"2017-01-17T03:41:10.582Z", "type"=>"ApacheAccessLog", "host"=>"webtack.com", "path"=>"/usr/local/pmc/var/log/httpd/access.log", "tags"=>["_grokparsefailure", "test"], "bubble_name"=>"app1", "application_name"=>"app1"}, @lut={"type"=>[{"message"=>"10.72.132.161 - \"\" [16/Jan/2017:03:31:24 +0000] \"GET /cdn/sureroute/akamai-sureroute-test-object.htm HTTP/1.0\" 200 8302 \"-\" \"-\"", "@version"=>"1", "@timestamp"=>"2017-01-17T03:41:10.582Z", "type"=>"ApacheAccessLog", "host"=>"web.tack.com", "path"=>"/usr/local/pmc/var/log/httpd/access.log", "tags"=>["_grokparsefailure", "test"], "bubble_name"=>"app1", "application_name"=>"app1"}, "type"], "[tags][0]"=>[["_grokparsefailure", "test"], "0"], "[tags][1]"=>[["_grokparsefailure", "test"], "1"]}>>], :response=>{"create"=>{"_index"=>"test-2017.01.17", "_type"=>"ApacheAccessLog", "_id"=>"AVmsG7EhzipYH7TS-eHK", "status"=>500, "error"=>{"type"=>"exception", "reason"=>"Search Guard not initialized (SG11) for indices:data/write/bulk[s]"}}}, :level=>:warn}

any idea why this is happened?

**Comment by floragunncom** [comment]
@EMACz Search Guard is not initialized, you need to run sgadmin https://github.com/floragunncom/search-guard-docs/blob/master/sgadmin.md

**Comment by EMACz** [comment]
Hi I have already run sgadmin and all ES nodes are connected and even i can login with particular user credentials. This issue is happening on logstash side.

**Comment by floragunncom** [comment]
Can you please share your logstash config and tell us which ES and Logstash and which Search Guard version you are using?

**Comment by EMACz** [comment]
Hi ,

Please find the requested info below,

Logstash config
------------------------

input {

redis{
        host => "10.10.12.2"
        port => 6369
        data_type => "list"
        key => "logstash"
        type => "redis"

	}
}




output {

if [tags][0] == "mcp"

 {

       elasticsearch {
       user => abc
       password => abc
       ssl => true
       ssl_certificate_verification => true
       truststore => "/opt/logstash/truststore.jks"
       truststore_password => it
       hosts => ["10.10.10.98:9200","10.10.10.99:9200","10.10.10.100:9200","10.10.10.101:9200"]
       index => "mcp-%{+YYYY.MM.dd}"
       }
 }


elseif [tags][1] == "mcp"

 {

       elasticsearch {
       user => abc
       password => abc
       ssl => true
       ssl_certificate_verification => true
       truststore => "/opt/logstash/truststore.jks"
       truststore_password => it
       hosts => ["10.10.10.98:9200","10.10.10.99:9200","10.10.10.100:9200","10.10.10.101:9200"]
       index => "mcp-%{+YYYY.MM.dd}"
       }
 }

}

ES - 2.2.1
logstash 2.1.3
bin/plugin install com.floragunn/search-guard-ssl/2.2.1.7
bin/plugin install com.floragunn/search-guard-2/2.2.1.0-alpha3

**Comment by floragunncom** [comment]
You are using a very very old and outdated (and unsupported) alpha version of search guard. Please upgrade to elasticsearch 2.3.x or 2.4.x or 5 and install v10 of the Search Guard plugin. See here for more details: https://github.com/floragunncom/search-guard/wiki

Please do not report bugs for old versions because its very likely there are already fixed in the most recent version.
